### ISSUE TITLE
[Bug]: Expectation is marked as internal class

### ISSUE THREAD

**Issue by allanmcarvalho** [pestphp/pest#1018]
### What Happened

It's provide a false IDE errors

### How to Reproduce

When we use the method each() a 
closure is passed as param and a Expectation is provided on this closure as param, so if we want type the closure, a IDE error is printed as below.

<img width="407" alt="Captura de Tela 2023-11-22 às 17 01 46" src="https://github.com/pestphp/pest/assets/12012197/c02590f9-1c09-4ce0-bc24-6263c153bf8f">

### Pest Version

2.25

### PHP Version

8.2.0

### Operation System

macOS

**Comment by owenvoke** [comment]
I think it's correctly marked as internal, and the IDE notice is just a warning that it might change without notice (which is true). As far as I know, PhpStorm's notice doesn't stop you from using the class at all.

I guess this is a little bit confusing though, as it's showing up on a built-in method.

@nunomaduro, what are your thoughts on this?

**Comment by nunomaduro** [comment]
Lets remove the internal thing for now. Please make a pull request.
