### ISSUE TITLE
Missing Pull Request Template

### ISSUE THREAD

**Issue by AlexMartinFR** [pestphp/pest#102]
## Problem:
Every Pest repository has a **CONTRIBUTING.md** file, which links to a missing [PULL_REQUEST_TEMPLATE.md](https://github.com/pestphp/pest-plugin-template/blob/master/.github/PULL_REQUEST_TEMPLATE.md) file.

_Cf._ _https://help.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository_

**Comment by nunomaduro** [comment]
@AlexMartinFR This kind of stuff, don't hesitate on making tweets like this: https://twitter.com/enunomaduro/status/1019981092336660480?s=20

**Comment by AlexMartinFR** [comment]
Good idea!
