### ISSUE TITLE
[Bug]: vendor/autoload.php loaded twice when Pest is used with Laravel

### ISSUE THREAD

**Issue by aldemeery** [pestphp/pest#1027]
### What Happened

When using Pest with Laravel, the `vendor/autoload.php` file is loaded two times

The first time being in the `artisan` file
https://github.com/laravel/laravel/blob/e57d15ac8f71ac65eb974b7a535804b6552bf4f1/artisan#L18
```php
require __DIR__.'/vendor/autoload.php';
```

And the second time being in the `bin/pest` file
https://github.com/pestphp/pest/blob/9a8f6e64149592b2555a2519237abb39e9e4f1fe/bin/pest#L60

This causes Fatal Errors with other packages that declare functions/classes ...etc without checking for their existence first (e.g. [azjezz/psl](https://github.com/azjezz/psl)) as they cannot be re-declared.

### How to Reproduce

1. Install a fresh Laravel application
2. Require `pestphp/pest`
3. Require `azjezz/psl`
4. In a controller, write some code that uses any Psl function (e.g. `Psl\Str\format('Hello %s', 'World')`)
5. Write a Pest test that tests the code
6. When you run the test, you should get `PHP Fatal error:  Cannot redeclare Psl\Str\format() (previously declared in vendor/azjezz/psl/src/Psl/Str/format.php:26) in vendor/azjezz/psl/src/Psl/Str/format.php on line 26`

### Pest Version

2.27

### PHP Version

8.3

### Operation System

Linux

**Comment by aldemeery** [comment]
Well, it looks like `azjezz/psl` does check for functions' existence, yet somehow Pest loads it twice

**Comment by nunomaduro** [comment]
Unable to reproduce this...
