### ISSUE TITLE
[Bug]: toBeBetween not work

### ISSUE THREAD

**Issue by Fadonougbo** [pestphp/pest#1029]
### What Happened

When i use expect(2)->toBeBetween(1,3); i have an error  **'Call to a member function toBeBetween() on int'**

### How to Reproduce

test('number between', function (){

    expect(2)->toBeBetween(1,3);
    
});
    

### Pest Version

1.23

### PHP Version

8.2

### Operation System

Windows

**Comment by fabio-ivona** [comment]
`toBeBetween()` was introduced in v2, it is not available for v1
