### ISSUE TITLE
[Feature]: Black/White List on architecture tests

### ISSUE THREAD

**Issue by DhavalGondaliya9** [pestphp/pest#1033]
### What Happened

First of all, I am sorry this is not a bug. This is a feature request. I checked there is no way to create a feature request. Sorry if I am misleading.

I have figured out while implementing the model extend architecture test.

We are using our custom model and I want to add a test that no one will extend the Laravel Model directly. But I want to exclude some of the files.
I checked the whole documentation and code. I haven't found it anyway.

Thanks.

### How to Reproduce

```
test('models should extend base model')
    ->expect('App\Models')
	->exclude(['App\Models\User', 'App\Models\Post'])
    ->toExtend('App\Models\Model');
```

### Pest Version

2.0

### PHP Version

8.2.12

### Operation System

Linux

**Comment by henryavila** [comment]
Same problem here.
Can't use this feature because it can't "exclude" some folder.

**Comment by morrislaptop** [comment]
@DhavalGondaliya9 did you find a solution?
