### ISSUE TITLE
[Bug]: Incorrect $this Binding In Test

### ISSUE THREAD

**Issue by darrencoutts118** [pestphp/pest#1039]
### What Happened

I expected that the `$this` variable in the test closure would be bound to the class specified in `uses(...)`, however this is not happening.

### How to Reproduce

Example Test Code

```php
<?php

uses(AppKit\UI\Tests\TestCase::class);

it('can be integrated into a component', function () {
    dd(get_class($this));
});
```

When this is run, I get the following output

```bash
./vendor/bin/pest --filter Component

WARN  No code coverage driver available
"P\Tests\ComponentIntegratrionTest" // /workspaces/ui/tests/ComponentIntegratrionTest.php:6
```

### Pest Version

2.28

### PHP Version

8.2.9

### Operation System

Linux (Github Codespaces)

**Comment by darrencoutts118** [comment]
I should also add that this is based on my understanding, and from the examples, on this page https://pestphp.com/docs/configuring-tests

**Comment by aerni** [comment]
I'm running into the same issue on Pest `v2.32.0` and PHP `8.2.15`.

**Comment by nunomaduro** [comment]
The class `P\Tests\ComponentIntegratrionTest` extends `AppKit\UI\Tests\TestCase`.
