### ISSUE TITLE
Get Started button triggers a download on the website

### ISSUE THREAD

**Issue by nunomaduro** [pestphp/pest#104]
Not sure why, but from time to time, the "Get Started" button triggers a download on the website. 

@octoper can you take a look? 

<img width="767" alt="Screenshot 2020-06-19 at 21 13 09" src="https://user-images.githubusercontent.com/5457236/85172777-0d74dd80-b272-11ea-9ac1-246d09c74e53.png">

**Comment by nunomaduro** [comment]
<img width="370" alt="Screenshot 2020-06-19 at 21 25 12" src="https://user-images.githubusercontent.com/5457236/85173382-6f821280-b273-11ea-8eb4-73dc33da67cd.png">

**Comment by octoper** [comment]
@nunomaduro Yeah I'm on it!

**Comment by nunomaduro** [comment]
safari

**Comment by octoper** [comment]
I can't repopulate that error @nunomaduro 😪

**Comment by nunomaduro** [comment]
It happens rarely.

**Comment by octoper** [comment]
If it happens again send me a screenshot of your browser.

**Comment by PieterO** [comment]
@nunomaduro what version of safari are you running? (might make this easier to reproduce)

**Comment by nunomaduro** [comment]
`Version 13.1.1 (15609.2.9.1.2)`

**Comment by nunomaduro** [comment]
Didn't happen again.
