### ISSUE TITLE
[Bug]: toHaveMethod expectation does not work correctly

### ISSUE THREAD

**Issue by marepilc** [pestphp/pest#1043]
### What Happened

The test
```php
it('has isAdmin method', function () {
    $user = User::factory()->admin()->make();
    expect($user)->toHaveMethod('isAdmin');
});
```
returns AssertionError:
`AssertionError: assert(is_string($expectation->value) || is_array($expectation->value))`

When changed to `expect($user)->toHaveMethods(['isAdmin']);` the test passes.

### How to Reproduce

Add `$table->boolean('is_admin')->default(false);` to the default users table and `isAdmin` method to the User model
```php
public function isAdmin()
    {
        return $this->is_admin;
    }
```

### Pest Version

2.28.1

### PHP Version

8.2.7

### Operation System

Windows

**Comment by nunomaduro** [comment]
expect(User::class)->toHaveMethod(...);
