### ISSUE TITLE
[Bug]: --process-isolation in "--help" shown

### ISSUE THREAD

**Issue by schonhoff** [pestphp/pest#1047]
### What Happened

If you want to know the `./vendor/bin/pest` options you can go to the web page for cli-api-reference or you type `--help`. If you type `--help` you get a list of all cli options. But there is an option shown that isn't support currently.
`--process-isolation`.

### How to Reproduce

1. Go to a bash
2. type `./vendor/bin/pest --help`
3. go to `EXECUTION OPTIONS`
4. the 3rd options shown is `--process-isolation`

### Pest Version

2.28.1

### PHP Version

8.2.10

### Operation System

Windows

### Notes

Thanks for the great tool!

**Comment by nunomaduro** [comment]
Fixed in `2.33.0`
