### ISSUE TITLE
cant run code in terminal

### ISSUE THREAD

**Issue by binarys12** [pestphp/pest#105]
I can't run any code in vs code terminal how to fix this problem
![Capture](https://user-images.githubusercontent.com/67180608/85195139-bf9dbb00-b2ed-11ea-9b9b-1e46f01317cd.PNG)

**Comment by astha-29** [comment]
u can use ecllipe for the following

**Comment by owenvoke** [comment]
Hi @binarys12, from your screenshot this doesn't seem to be related to Pest. Is there an error you are getting with Pest?
