### ISSUE TITLE
[Bug]: CLI argument --cache-directory is always overrided by Cache plugin

### ISSUE THREAD

**Issue by krencl** [pestphp/pest#1050]
### What Happened

Commands 
- `./vendor/bin/pest --cache-directory="./tmp"` 
 - `./vendor/bin/pest --cache-directory "./tmp"` 

are not using defined directory, but always is used default directory `vendor/pestphp/pest/.temp/`.

Expected: use `./tmp` directory

### How to Reproduce

Run 
```
./vendor/bin/pest --cache-directory="./tmp"
ls ./tmp/
ls ./vendor/pestphp/pest/.temp/
```

### Pest Version

2.30.0

### PHP Version

8.1.27

### Operation System

Linux

**Comment by pizzot** [comment]
Still getting this on Pest **3.8.2.**. Steps to reproduce are the same.
