### ISSUE TITLE
[Bug]: Profile cold start can create false positives

### ISSUE THREAD

**Issue by SanderCokart** [pestphp/pest#1057]
### What Happened

# Issue
`--profile` can produce **false positives**. The first test has a cold start time of about **60ms**.

![image](https://github.com/pestphp/pest/assets/45256817/495e6d89-21dc-4122-924d-da6191006a41)

You can test this out by using a simple `get` to `/` and asserting status code `200`.
Create 2 such tests and swap their order to see that on both occasions the top one is always the slowest.

# Workaround for now
Make an empty test or simple `get` test to `/` or other routes to startup phpunit and make sure this one runs **first**.
By ensuring the cold start it spend on a test that is lightweight we can be sure there won't be cold start durations added to possible actual slow tests.

### How to Reproduce

You can test this out by using a simple `get` to `/` and asserting status code `200`.
Create 2 such tests and swap their order to see that on both occasions the top one is always the slowest.

### Pest Version

2.30.0

### PHP Version

8.2.11

### Operation System

Windows

**Comment by nunomaduro** [comment]
I think there is a real solution for this... PHP's autoloading simply takes more time on the very first time it loads certain classe..
