### ISSUE TITLE
[Improvement] Scoped helper functions

### ISSUE THREAD

**Issue by jakubtobiasz** [pestphp/pest#1064]
> **Note:** I've looked for a way how to achieve the expected result, but it seems to not be possible or I am missing something.

## Description

My idea is to allow creating helper functions (just like you do it in the `Pest.php` file) inside `*Test.php`, but scoped. What I mean:

```php
// SomeTest.php
<?php

test('example', function () {
    expect(true)->toBeTrue();
});

function random(): void
{
    echo "test1";
}

// AnotherTest.php
<?php

test('example', function () {
    expect(true)->toBeTrue();
});

function random(): void
{
    echo "test1";
}

```

Result: `ERROR Fatal error: Cannot redeclare random() (previously declared in /app/tests/Feature/ExampleTest.php:9) in /app/tests/Unit/ExampleTest.php on line 9.`

Expected result: No error thrown. Each file uses the function declared in it.

## Motivation

I personally do like to create `createTestSubject` methods inside regular PHPUnit tests. In Pest it's harder to achieve it, as I had to create functions with different names, and I could by accident use a function from another test file.

**Comment by fabio-ivona** [comment]
Wouldn't using a namespace solve your issue?

**Comment by jakubtobiasz** [comment]
Hi @fabio-ivona 👋🏼,

Considering I want to declare `createTestSubject` function in every test file, it wouldn't as multiple classes under the same namespace will have that function. Maybe my problem is not common, but I miss more ways to create scoped functions/helpers/custom expectations.

**Comment by nunomaduro** [comment]
You can simply namespace your test file.

**Comment by SachinAgarwal1337** [comment]
@nunomaduro Having test files in same namespace (which is a common usecase) does not solve this.

P.S I am having same issue. My use case:  I usually add `getUrl` method in each Feature Test case as a convenience.

**Comment by jakubtobiasz** [comment]
> @nunomaduro Having test files in same namespace (which is a common usecase) does not solve this.
> 
> P.S I am having same issue. My use case: I usually add `getUrl` method in each Feature Test case as a convenience.

I solved it partially by anonymous functions assigned to variables. 
![CleanShot 2025-01-07 at 18 44 27@2x](https://github.com/user-attachments/assets/5e7792a6-872d-4383-837f-11affc390524)

So, in your case:
```php
$getUrl = function () { };

it('test', function () use ($getUrl) {
    $url = $getUrl();
});
```

should do the job. Unfortunately, there's no simple way to force PhpStorm to add a namespace to the pest file on a creation.

**Comment by SachinAgarwal1337** [comment]
@jakubtobiasz Thank you for the solution. 
I solved it a bit differently. 
I just added File name in the namespace as well. 

```php
// file Feature/CreateUserTest.php
namespace Tests\Feature\CreateUserTest

function getUrl()
{
    // return route
}
```

This way it is not conflicting as namespace if each file is different
