### ISSUE TITLE
[Bug]: Adding the --parallel option breaks testdox options 

### ISSUE THREAD

**Issue by raf-lv** [pestphp/pest#1066]
### What Happened

When I run pest with the `--parallel `option and `--testdox-text` I get an error message: `The "--testdox-text" option does not exist.  `

### How to Reproduce

Install a fresh Laravel app; add Pest then run:

`./vendor/bin/pest --parallel --testdox-text /tmp/testdox.txt  `

### Error message:
                                               
 

>  The "--testdox-text" option does not exist.  
>                                                
> 
> paratest [--functional] [-m|--max-batch-size MAX-BATCH-SIZE] [--no-test-tokens] [--passthru-php PASSTHRU-PHP] [-p|--processes PROCESSES] [--runner RUNNER] [--tmp-dir TMP-DIR] [-v|--verbose] [--bootstrap BOOTSTRAP] [-c|--configuration CONFIGURATION] [--no-configuration] [--cache-directory CACHE-DIRECTORY] [--testsuite TESTSUITE] [--exclude-testsuite EXCLUDE-TESTSUITE] [--group GROUP] [--exclude-group EXCLUDE-GROUP] [--filter FILTER] [--process-isolation] [--strict-coverage] [--strict-global-state] [--disallow-test-output] [--dont-report-useless-tests] [--stop-on-defect] [--stop-on-error] [--stop-on-failure] [--stop-on-warning] [--stop-on-risky] [--stop-on-skipped] [--stop-on-incomplete] [--fail-on-incomplete] [--fail-on-risky] [--fail-on-skipped] [--fail-on-warning] [--order-by ORDER-BY] [--random-order-seed RANDOM-ORDER-SEED] [--colors [COLORS]] [--no-progress] [--display-incomplete] [--display-skipped] [--display-deprecations] [--display-errors] [--display-notices] [--display-warnings] [--teamcity] [--testdox] [--log-junit LOG-JUNIT] [--log-teamcity LOG-TEAMCITY] [--coverage-clover COVERAGE-CLOVER] [--coverage-cobertura COVERAGE-COBERTURA] [--coverage-crap4j COVERAGE-CRAP4J] [--coverage-html COVERAGE-HTML] [--coverage-php COVERAGE-PHP] [--coverage-text [COVERAGE-TEXT]] [--coverage-xml COVERAGE-XML] [--coverage-filter COVERAGE-FILTER] [--no-coverage] [--] [<path>]
> 

### Pest Version

2.28.0

### PHP Version

8.2.14

### Operation System

Linux

### Notes

Removing --parallel gets the test running without errors.
_No response_

**Comment by nunomaduro** [comment]
The `--testdox-text` is not supported by Paratest.

**Comment by raf-lv** [comment]
Perhaps mention that here https://pestphp.com/docs/cli-api-reference ?
