### ISSUE TITLE
Test file not discovering for architecture tests

### ISSUE THREAD

**Issue by abdullah-ctl** [pestphp/pest#1071]
I created a folder inside the tests, as the image shows
![image](https://github.com/pestphp/pest/assets/45127367/a3578e69-5341-49b6-8dbf-cdaa20448c57)

When I run the tests then it only runs the Unit folders tests. not architecture folder tests. How can I fix this?
Note: I didn't change anything on `Pest.php` or `TestCase.php`

**Comment by faissaloux** [comment]
I think you didn't add it to your testsuites!

**Comment by JonPurvis** [comment]
In your `phpunit.xml` file, you should see a section that looks like:

```xml
<testsuites>
    <testsuite name="Unit">
        <directory>tests/Unit</directory>
    </testsuite>
    <testsuite name="Feature">
        <directory>tests/Feature</directory>
    </testsuite>
</testsuites>
```

You'll need to add something in for your Architecture tests:

```xml
<testsuite name="Architecture">
    <directory>tests/Architecture</directory>
</testsuite>
```
