### ISSUE TITLE
DOMDocument::schemaValidate(): Invalid Schema

### ISSUE THREAD

**Issue by michelmelo** [pestphp/pest#110]
I'm trying to use the package but I have the following error:
```
$ ./vendor/bin/pest
DOMDocument::schemaValidate(): Invalid Schema

```

**Comment by owenvoke** [comment]
That sounds like your `phpunit.xml` file might not be matching the schema. 🤔 Could you post the contents of that here?

**Comment by michelmelo** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="./vendor/phpunit/phpunit/phpunit.xsd"
         bootstrap="vendor/autoload.php"
         colors="true"
>
    <testsuites>
        <testsuite name="Test Suite">
            <directory suffix="Test.php">./tests</directory>
        </testsuite>
    </testsuites>
    <filter>
        <whitelist processUncoveredFilesFromWhitelist="true">
            <directory suffix=".php">./app</directory>
            <directory suffix=".php">./src</directory>
        </whitelist>
    </filter>
</phpunit>

```

**Comment by michelmelo** [comment]
![image](https://user-images.githubusercontent.com/159223/85433794-e1f93800-b57c-11ea-8b71-24dfbe6b1bec.png)

**Comment by owenvoke** [comment]
So I ran a quick XML schema validation on your config and it returns:
> cvc-complex-type.2.4.a: Invalid content was found starting with element 'filter'. One of '{"":groups, "":testdoxGroups, "":coverage, "":logging, "":extensions, "":listeners, "":php}' is expected.

I don't think I've ever included the schema reference in my PHPUnit config. Just noticed that my config gets the same issue when I add the schema reference.

**Comment by michelmelo** [comment]
@owenvoke how do you have the file? phpunit.xml

**Comment by owenvoke** [comment]
Here's my default, if that's what you meant?
https://github.com/owenvoke/skeleton-php/blob/master/phpunit.xml.dist

**Comment by michelmelo** [comment]
tks done.
