### ISSUE TITLE
Lastest nunomaduro/collision requires Laravel 8

### ISSUE THREAD

**Issue by ekandreas** [pestphp/pest#111]
Latest version 5.0.0-BETA3 of nunomaduro/collision requires Laravel 8. Perhaps it is a bit too forward right now as Laravel 8 isn't released yet?

**Comment by ekandreas** [comment]
My workaround to get pest to work in L7:
```
        "nunomaduro/collision": "5.0.0-BETA2",
        "pestphp/pest": "0.2.1",
        "pestphp/pest-plugin-livewire": "*",
```

**Comment by owenvoke** [comment]
Isn't that just for testing as it's in `require-dev`? 🤔

**Comment by ekandreas** [comment]
https://github.com/nunomaduro/collision/blob/v5.0.0-BETA3/composer.json

**Comment by nunomaduro** [comment]
That's is `require-dev` ...

**Comment by owenvoke** [comment]
@ekandreas, that's a `require-dev` entry. It's only for the development and unit testing, Collision 5 still works with Laravel 7 (I just did a test install to check). 👍

I guess `laravel: [7.0, 8.0]` could be added to the CI matrix to test both if really necessary? 🤷

**Comment by ekandreas** [comment]
Yest, pest is placed in require-dev and therefore getting the lastest update 0.2.2 that requires beta3 and laravel 8.

**Comment by ekandreas** [comment]
So where do you want me to put pest to get this to work again?

**Comment by ekandreas** [comment]
Never mind, just forcing pest to use beta2 solves the issue for now:
```
        "nunomaduro/collision": "5.0.0-BETA2",
        "pestphp/pest": "0.2.2",
        "pestphp/pest-plugin-livewire": "*"
```
As you have "nunomaduro/collision": "^5.0.0-BETA2" with the ^-sign it will grab beta3 and force it to Laravel 8.
Your composer should perhaps say: "nunomaduro/collision": "5.0.0-BETA2" ?

**Comment by owenvoke** [comment]
It won't force to Laravel 8 🤔

Just ran through an install with a fresh Laravel 7 app. It stays on Laravel 7 because `require-dev` in a package has no effect on projects/packages that require it.
https://asciinema.org/a/jqYTxyualIilRwrDuNZ39PexY

**Comment by ekandreas** [comment]
Ohh, yes, as long as you have ^ in the version numbering it will take the latest package and install beta3.
Working around this with a more declarative setting for the collision package for now.

**Comment by ekandreas** [comment]
But if it's only me that have this issue we can close it and hope that no one else stumbles on it as they upgrade to the latest pest package.

**Comment by owenvoke** [comment]
Mine did install `v5.0.0-BETA3` and it was fine. I'm not sure what the issue is, Collision `v5.0.0-BETA3` is compatible with Laravel 7 and 8, and does not force either to be installed. 🤔

**Comment by ekandreas** [comment]
I still argue that beta 3 forces L8: https://github.com/nunomaduro/collision/blob/stable/composer.json

**Comment by nunomaduro** [comment]
lol, it doesn't.

**Comment by adalessa** [comment]
After a fresh install I found the following as was mentioned here that required dev does not generates a conflict for installation on composer, but trying to run php artisan test is throwing an error from this line https://github.com/nunomaduro/collision/blob/stable/src/Adapters/Laravel/Commands/TestCommand.php#L71
running pest command from the vendor directory great.

**Comment by ratacibernetica** [comment]
I'm with @adalessa here, tried a new Laravel app from scratch, then installing Livewire and finally Pest:

```bash
~> composer require phpunit/phpunit:"^9.0" --dev --update-with-dependencies
~> composer require nunomaduro/collision:"^5.0" --dev --update-with-dependencies
~> composer require pestphp/pest --dev
~> composer require pestphp/pest-plugin-laravel --dev && php artisan pest:install
~> ./vendor/bin/pest 


   PASS  Tests\Unit\ExampleTest
  ✓ basic test

   PASS  Tests\Feature\ExampleTest
  ✓ basic test

  Tests:  2 passed
  Time:   0.15s

~> php artisan test                                                                                  

   RuntimeException 

  Running Collision ^5.0 artisan test command requires Laravel ^8.0.

  at vendor/nunomaduro/collision/src/Adapters/Laravel/Commands/TestCommand.php:71
     67▕         }
     68▕ 
     69▕         // @phpstan-ignore-next-line
     70▕         if ((int) \Illuminate\Foundation\Application::VERSION[0] < 8) {
  ➜  71▕             throw new RuntimeException('Running Collision ^5.0 artisan test command requires Laravel ^8.0.');
     72▕         }
     73▕ 
     74▕         $options = array_slice($_SERVER['argv'], $this->option('without-tty') ? 3 : 2);
     75▕ 

      +14 vendor frames 
  15  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

**Comment by owenvoke** [comment]
Yeah, using the Artisan command does require Laravel 8. I've never used the test command as it just calls Pest behind the scenes.

It looks like this is due to the `dotenv` package which released a new version. https://github.com/nunomaduro/collision/issues/132

**Comment by nunomaduro** [comment]
```
~> php artisan test                                                                                  

   RuntimeException 

  Running Collision ^5.0 artisan test command requires Laravel ^8.0.
```

Maybe we should support both dotenv versions on  nunomaduro/collision. Basicly have two functions that does different jobs up to the dotenv version.

Someone wants to work on this?

**Comment by owenvoke** [comment]
@nunomaduro I'd be happy to take a look tomorrow if I have time. If anyone else wants to take this before though, I'm fine with that. 👍

**Comment by nunomaduro** [comment]
thanks, the goal is try to support both dotenv 4 and 5 at the same time.

**Comment by ekandreas** [comment]
This is still a problem for us. Pest requires Laravel 8. Perhaps we have to wait for September before we can accelerate Pest testing?
