### ISSUE TITLE
[META-ISSUE] Progress with PHPUnit 11 and Pest 3.0

### ISSUE THREAD

**Issue by shakaran** [pestphp/pest#1120]
Since [3.x branch](https://github.com/pestphp/pest/tree/3.x) is started with PHPUnit 11 support. I would like to create a meta-issue to see the progress for the work remaining todo until be released, so others members with knowledge can help with pull request and accelerate the progress hopefully.

Feel free here to add the points needed to finish.

**Comment by nunomaduro** [comment]
No plans for keeping a public todo list at the moment.
