### ISSUE TITLE
RFC: add `expect` function

### ISSUE THREAD

**Issue by nunomaduro** [pestphp/pest#113]
When we are writing tests, we often need to check that values meet certain conditions. And for that, at the time of this writing, we are using PHPUnit syntax using the global helpers: `assertEquals`, `assertTrue`, `assertFalse`, etc.

The problem with this is the number of global helpers that are injected in the global namespace: **One function per assertion**.

This RFC introduces the global helper `expect`, that would offer the same number of assertions of PHPUnit, but using a **single global function** and a **fluent syntax** like so:

```php
// old
assertTrue($variable);
// new
expect($variable)->toBe(true);

// --

// old
assertGreaterThan(0, $variable);
// new
expect($variable)->toBeGreaterThan(0);

// --

// old
assertContains('nuno', $array);
// new
expect($array)->toContain('nuno');
```

Of course, the RFC is inspired in Jest: **[jestjs.io/docs/en/expect](https://jestjs.io/docs/en/expect)**.

**Comment by ssmusoke** [comment]
@nunomaduro for easier migration and reduce cognitive load, can the default expectations be consistent with the asserts then add aliases to better sounding or user friendly names

**Comment by ecreeth** [comment]
hhvm has some good libraries that can inspire: [FBExpect](https://github.com/hhvm/fbexpect) and [HackTest](https://github.com/hhvm/hacktest)

**Comment by DavertMik** [comment]
Just plug this in and you are ready! 🎯 
https://github.com/Codeception/Verify

**Comment by nunomaduro** [comment]
In progress...

**Comment by tpaksu** [comment]
Will they be chained? For example: 

```php
expect($array)->toContain('nuno')->toHaveMinElements(5)->toIncludeElementsFrom($array2);
```

Like Laravel's Validation system. And maybe have clauses like `toContainWhen('nuno', count($array) > 0)`.

**Comment by nunomaduro** [comment]
I've just bootstrapped this work of adding the full-featured `expect` API.

Check out the pull request: https://github.com/pestphp/pest/pull/123. Fell free to help me with this. 👍🏻

**Comment by nunomaduro** [comment]
@tpaksu Yes: https://github.com/pestphp/pest/pull/123/files#diff-a644964bd3325a15734d76efdaabd137R52.
