### ISSUE TITLE
feat: `--thanks` option

### ISSUE THREAD

**Issue by nunomaduro** [pestphp/pest#116]
Would be cool if we had a `--thanks` command that shows all the options on how people can support the project: github stars, sponsors, etc.

**Comment by owenvoke** [comment]
Kind of like the `composer fund` command? Or would it just be another core-flag thing like the `--version` flag? I can add this later today.

**Comment by nunomaduro** [comment]
> Or would it just be another core-flag thing like the --version flag?

Yeah like the `--version`.

The idea would be add some GitHub stars on our github projects, open a browser to make a tweet about pest, propose funding options, etc.

**Comment by owenvoke** [comment]
I'll add that later. Sounds good. :+1:

**Comment by owenvoke** [comment]
Implemented in PR https://github.com/pestphp/pest/pull/118 👍
