### ISSUE TITLE
docs: add possibility for translations

### ISSUE THREAD

**Issue by nunomaduro** [pestphp/pest#117]
I would like to explore if we can have our website in multiple languages.

**Comment by raphaelts3** [comment]
Hey @nunomaduro I stumbled on this https://obsproject.com/forum/threads/how-to-contribute-translations-for-obs.16327/ other day and I  think could be handy for it =) [Crowdin](http://crowdin.net/) is free for open source projects.

**Comment by octoper** [comment]
@raphaelts3 I will take a look. Thank you!!

**Comment by nunomaduro** [comment]
I've no plans on working on this. Feel free to submit a pull request.
