### ISSUE TITLE
[Bug]: --update-snapshots deletes all snapshots

### ISSUE THREAD

**Issue by fedeisas** [pestphp/pest#1191]
### What Happened

When running tests with --update-snapshots it deletes all the snapshots and recreates from scratch even if I'm running a single test. I went through docs and issues but couldn't find any flag to correct this and operate only on the _affected_ snapshots. Is this by design? Thanks!

### How to Reproduce

Run tests with --update-snapshots 

### Pest Version

latest

### PHP Version

8.2

### Operation System

macOS

**Comment by nunomaduro** [comment]
yeah, feel free to contribute with something that changes this behavior. It's just the default behavior at the moment.
