### ISSUE TITLE
[Bug]: Support PHP 8.4

### ISSUE THREAD

**Issue by withinboredom** [pestphp/pest#1199]
### What Happened

Attempting to run tests an 8.4-alpha results in the following error:

```
 brianium/paratest v7.3.1 requires php ~8.1.0 || ~8.2.0 || ~8.3.0 -> your php version (8.4.0alpha2) does not satisfy that requirement.
    - brianium/paratest[v7.4.0, ..., v7.5.0] require php ~8.2.0 || ~8.3.0 -> your php version (8.4.0alpha2) does not satisfy that requirement.
    - pestphp/pest[v2.34.7, ..., v2.34.9] require brianium/paratest ^7.3.1 -> satisfiable by brianium/paratest[v7.3.1, ..., v7.5.0].
    - Root composer.json requires pestphp/pest ^2.34.7 -> satisfiable by pestphp/pest[v2.34.7, v2.34.8, v2.34.9].
```

### How to Reproduce

Install php 8.4, run `composer install`

### Pest Version

2.34.x

### PHP Version

8.4

### Operation System

Linux

### Notes

Attempting to run project unit tests to assist in testing 8.4 compatibility before release.

**Comment by joanhey** [comment]
It's holidays
We'll wait !!!

**Comment by faissaloux** [comment]
You should report this to [paratest](https://github.com/paratestphp/paratest) which doesn't support `php8.4` yet.

**Comment by Slamdunk** [comment]
PHP 8.4 support has been released in ParaTest for both PHPUnit 10 and PHPUnit 11.

**Comment by joanhey** [comment]
Thank you @Slamdunk 
It's working !!
