### ISSUE TITLE
ShouldNotHappen Exception when testing with --coverage

### ISSUE THREAD

**Issue by liorchamla** [pestphp/pest#12]
Hi all ! Just found this when I launches `vendor/bin/pest tests --coverage` for the first time :(

- Issue: Coverage not found in path: /Users/liorchamla/code/angsym8/_php/07-csv-tests/vendor/pestphp/pest/.temp/coverage.php.
- PHP version: 7.4.3
- Operating system: Darwin

To notice : I have **pecl.php.net/xdebug-2.9.2**

**Comment by nunomaduro** [comment]
Can you try `vendor/bin/pest --coverage`?

**Comment by liorchamla** [comment]
Not a bug Nuno, i'm just bad at testing and forgot about the whitelist.

Sorry for this. Closing the issue :)

**Comment by nunomaduro** [comment]
Maybe you can open an new one so we can improve the exception on the console in this cases?

**Comment by mattlake** [comment]
Hi All,
I am encountering the same issue.

Issue:
` ./vendor/bin/pest --coverage`

returns:
```
Pest\Exceptions\ShouldNotHappen

This should not happen - please create an new issue here: https://github.com/pestphp/pest.

- Issue: Coverage not found in path: /var/www/vtiger-sdk/vendor/pestphp/.temp/coverage.php.
- PHP version: 8.0.0
- Operating system: Linux
```

My source code is located in ./src and the phpunit.xml includes:
```xml
    <coverage processUncoveredFiles="true">
        <include>
            <directory suffix=".php">./app</directory>
            <directory suffix=".php">./src</directory>
        </include>
    </coverage>
```

I get this exception with PHP versions 7.3, 7.4, & 8.0. My environment is Ubuntu 20.04 via WSL
My PestPHP version is v1.0.2

Any help would be appreciated.

Thanks

**Comment by riwiki** [comment]
Just ran into this, and I had to enable XDebug's coverage mode. It's pointed out in the docs: https://pestphp.com/docs/coverage
