### ISSUE TITLE
feat: parallel testing

### ISSUE THREAD

**Issue by nunomaduro** [pestphp/pest#120]
Today, all the testing is closure based. Therefore, we should be able to [serialiaze closures ](https://github.com/opis/closure) and run them ( somehow ) run them in parallel.

**Comment by royduin** [comment]
Maybe this can help: https://github.com/paratestphp/paratest

**Comment by nunomaduro** [comment]
cc @owenvoke

**Comment by mennorenkens** [comment]
Is this somethings that's on the planning in the near future or probably not? I really love to use Pest, but now the tests are growing I'm missing something like paratest.

**Comment by nunomaduro** [comment]
@mennorenkens I would like to have something native about this, not planning on developing this myself on the near future tho. Waiting for someone to contribute to this.

**Comment by nunomaduro** [comment]
This is in progress.

**Comment by lakuapik** [comment]
> Maybe this can help: https://github.com/paratestphp/paratest

any clue how to integrate it with pest ?

**Comment by nunomaduro** [comment]
I am working on it.

**Comment by Krato** [comment]
Any updates? We look forward to testing it. Thanks @nunomaduro!

**Comment by deevus** [comment]
Also keen on an update.

Meta: why close the issue when a solution is in progress?

**Comment by nunomaduro** [comment]
Because there is no "issue". This is an feature request.
