### ISSUE TITLE
laravel: execute test dataset closure in app context

### ISSUE THREAD

**Issue by Gummibeer** [pestphp/pest#122]
Hey,

right now I have a loop in my test closure which is okay but leads to the problem that the whole test fails if one entry of the loop fails. Instead I would like to use the `with()` method and define a closure that returns the elements of my current loop.
My problem is that the closure is executed outside of the Laravel app context.
Do you see any way to run the closure in Laravel app context and pass the result to the phpunit dataset?

I would like to be able to do this:
```php
it('can render route', function(string $url) {
    get($url)->assertStatus(200);
})->with(function() {
    return [
        'home' => [route('home')],
        'about' => [route('about')],
    ];
});
```

**Comment by nunomaduro** [comment]
No plans for tackling this at the moment.
