### ISSUE TITLE
[Bug]:  XDEBUG_MODE=coverage no longer works correctly on Pest 3 without the --parallel mode

### ISSUE THREAD

**Issue by pascalchevrel** [pestphp/pest#1223]
### What Happened

Upgrade project from pest 2.2 to 3.0, ran the `XDEBUG_MODE=coverage vendor/bin/pest --coverage` command in the terminal. Got an Xdebug error..

### How to Reproduce

**Works in Pest 2.2.0:**
`XDEBUG_MODE=coverage vendor/bin/pest --coverage`

**Same command gives this error with Pest 3.0:**
`WARN  Unable to get coverage using Xdebug. Did you set Xdebug's coverage mode?`

**But it does work if I also pass the  `--parallel` flag:**
`XDEBUG_MODE=coverage vendor/bin/pest --coverage --parallel`

### Pest Version

3.0

### PHP Version

8.3.6

### Operation System

Linux

### Notes

Ubuntu 24.04

**Comment by JonPurvis** [comment]
Ah, was just about to open an issue for this! Glad it's not just me 😄

**Comment by nunomaduro** [comment]
yeah, i was able to reproduce it; working on a fix.

**Comment by nunomaduro** [comment]
fixed on `v3.0.1`.
