### ISSUE TITLE
[Docs] Continuous Integration article doesn't explain what the --ci flag actually does

### ISSUE THREAD

**Issue by Jamesking56** [pestphp/pest#1225]
The Continuous Integration article doesn't explain what the `--ci` flag actually does:

https://pestphp.com/docs/continuous-integration

It talks about using it in various CI provider but doesn't actually explain why you need to add `--ci`

**Comment by nunomaduro** [comment]
Can you make a pull request to add what it does?

At the moment, i think the only thing it does is disabling the `->only()` method option.
