### ISSUE TITLE
[Bug]: Using `--mutate --parallel --processes=X` ignores num processes

### ISSUE THREAD

**Issue by rabrowne85** [pestphp/pest#1228]
### What Happened

When you run Pest 3 with the following options:
```bash
./vendor/bin/pest --mutate --parallel --processes=x
```
it should limit the processes to the value specified. However, it ignores the option entirely.

### How to Reproduce

Running the above command.

### Pest Version

3.0.1

### PHP Version

8.3.10

### Operation System

macOS

### Notes

Looking at the source for the plugin, the `ProcessesOption@match()` function seems to be a bit greedy. Locally adjusting the function to the following seems to resolve the issue:
```php
    public static function match(string $argument): bool
    {
        return $argument === str_starts_with($argument, sprintf('--%s=', self::ARGUMENT));
    }
```

**Comment by gehrisandro** [comment]
Thanks, @rabrowne85, for reporting the issue.

Fixed here https://github.com/pestphp/pest-plugin-mutate/pull/14
