### ISSUE TITLE
Improvements for TeamCity output format

### ISSUE THREAD

**Issue by smirok** [pestphp/pest#1236]
Hi, PhpStorm is here! I'm working on improving Pest support in PhpStorm and would like to suggest some improvements for TeamCity output format.

1. A single prefix for `locationHint` 

Pest uses different prefixes for `testSuiteStarted` and `testStarted` TeamCity events: 

`file://` for `testSuiteStarted`:

```php
    public static function testSuiteStarted(string $name, ?string $location): self
    {
        return new self('testSuiteStarted', [
            'name' => $name,
            'locationHint' => $location === null ? null : "file://$location",
        ]);
    }
 ```
 
 and `pest_qn://` for `testStarted`:
 
 ```php
    public static function testStarted(string $name, string $location): self
    {
        return new self('testStarted', [
            'name' => $name,
            'locationHint' => "pest_qn://$location",
        ]);
    }
 ```
 
 It would be easier to process the single prefix `pest_qn://` for both cases like it's done in PHPUnit with the `php_qn://` prefix ([link](https://github.com/sebastianbergmann/phpunit/blob/f226e683a06e18608ee94408fdfbe4aa5db4fb5a/src/Logging/TeamCity/TeamCityLogger.php#L85))
 
 2. The exact `locationHint` for tests with datasets & real method name.
 
 The following test execution
 ```php
 test('foo', function (int $a) {
    expect($a)->toBe(0);
})->with([[0]]);
```
from `tests/MyTest.php` with the `--teamcity` flag produce the following output: 
```
##teamcity[testSuiteStarted name='Tests\MyTest' locationHint='file://tests/MyTest.php' flowId='49586']
##teamcity[testCount count='1' flowId='49586']
##teamcity[testSuiteStarted name='Tests\MyTest::__pest_evaluable_foo' locationHint='file://tests/MyTest.php' flowId='49586']
##teamcity[testStarted name='foo with data set "(0)"' locationHint='pest_qn://tests/MyTest.php::foo with data set "(0)"' flowId='49586']
##teamcity[testFinished name='foo with data set "(0)"' duration='2' flowId='49586']
##teamcity[testSuiteFinished name='Tests\MyTest::__pest_evaluable_foo' flowId='49586']
##teamcity[testSuiteFinished name='Tests\MyTest' flowId='49586']
```

We can improve the output for the line 
```
##teamcity[testSuiteStarted name='Tests\MyTest::__pest_evaluable_foo' locationHint='file://tests/MyTest.php' flowId='49586']
```
by 
* providing the real method name instead "pest evaluable" one
* clarifying the `locationHint` and provide there the method, not the file.

The result will be:
```
##teamcity[testSuiteStarted name='foo' locationHint='file://tests/MyTest.php::foo' flowId='49586']
```

Impact:

- It will help PhpStorm team to develop new features in the Pest plugin and adapting the existing ones for tests with dataset.
- Test results will look better in the `Test Tool Window`:
<img width="350" alt="Screenshot 2024-09-11 at 15 24 51" src="https://github.com/user-attachments/assets/ab374a85-33c1-4146-abe1-9c223377867b">
instead of
<img width="350" alt="Screenshot 2024-09-11 at 15 25 32" src="https://github.com/user-attachments/assets/a19e95f6-6bbc-4ebd-be24-a0b240b36a62">

**Comment by nunomaduro** [comment]
done: https://github.com/pestphp/pest/releases/tag/v3.0.6.

Would be cool to also ensure that works on "--parallel".

**Comment by smirok** [comment]
> Would be cool to also ensure that works on "--parallel".

Totally agree, but for now, tests executed with both `--teamcity` and `--parallel` completely ignore `--teamcity` ([relevant issue](https://github.com/pestphp/pest/issues/811))

I'll try to contribute by supporting `--parallel` and `--teamcity` flags to work together after the Pest 3.0 support on our side

**Comment by CamKem** [comment]
@smirok is there any progress on this? Can I be of any assistance?

It would be nice to have the output of the --parallel flag to display the individual results as you would expect in the run panel. The tests still run, but it looks more like a terminal output rather than a individual result.

<img width="1265" alt="Screenshot 2024-10-24 at 1 17 55 PM" src="https://github.com/user-attachments/assets/3318c23f-b424-4442-b883-fdacfbf57dad">

<img width="981" alt="Screenshot 2024-10-24 at 1 18 40 PM" src="https://github.com/user-attachments/assets/0d141112-4525-4a5a-88a7-4a67ef504947">
