### ISSUE TITLE
Idea: allow test closure to be passed after the fact

### ISSUE THREAD

**Issue by BinaryKitten** [pestphp/pest#124]
Coming from Live Stream, it seemed to be a good idea to have an alternative syntax for readability

currently:
```php
it('does a thing', function($data) { assertTrue(true);})
    ->with(['data`,'data2']);
```

here the passed function is small and easy to see what is going on

The proposal here is to allow the second argument to 'it' to be passed later in the chain so we get something like 
```php
it('does a thing')
    ->with(['data`,'data2'])
    ->test(function($data) { 
          assertTrue(true); 
    });
```

**Comment by nunomaduro** [comment]
No plans for this. Thank you!
