### ISSUE TITLE
[Bug]: Laravel preset not accounting for static middleware function in controller

### ISSUE THREAD

**Issue by danielh-official** [pestphp/pest#1252]
### What Happened

Laravel 11 allows you to specify middleware in a controller using a public static middleware function: https://laravel.com/docs/11.x/controllers#controller-middleware

However, the Laravel preset says that the only functions allowed to exist on a controller are the following:

<img width="724" alt="Screenshot 2024-09-13 at 9 43 16 AM" src="https://github.com/user-attachments/assets/7b9cb678-1854-4447-a112-b81b9cacc04c">

### How to Reproduce

1. Create a new Laravel repo
2. Create an `ArchitectureTest.php` file in the Unit folder
3. Add `arch()->preset()->laravel();` to it
4. Create a `DummyController.php` in the `App/Http/Controllers` folder and add the following code:

```php
    public static function middleware(): array
    {
        return [];
    }
```

### Pest Version

3.0.1

### PHP Version

8.2

### Operation System

macOS

**Comment by danielh-official** [comment]
Would it be possible to implement preset overriding functionality?

So, you still have the preset, but if there's something in the latest Laravel release that doesn't match convention, rather than waiting for the package to be updated, a developer can write:

```php
arch()->preset()->laravel()
    ->setExpectation('App\Http\Controllers')
    ->not->toHavePublicMethodsBesides(['__construct', '__invoke', 'index', 'show', 'create', 'store', 'edit', 'update', 'destroy', 'middleware']);
```

And it would override the previous expectation that tackles that part of the Controller architecture.

**Comment by CamKem** [comment]
I mean is it more than 1 controller? An easy fix would just be to ignore it for now?
```php
arch()->preset()->laravel()->ignoring(FeedController::class);
```
A better fix would be to fork the Pest repo & submit a PR to add the middleware method in the array, IMO given it's a framework convention, it should be added unless laravel removes this functionality.
