### ISSUE TITLE
[Bug]: Unable to install Pest 3.x along with Psalm 5.26

### ISSUE THREAD

**Issue by Lukasss93** [pestphp/pest#1262]
### What Happened

I tried to install Pest 3.x along with Psalm 5.26, but I got the following error:

```bash
Your requirements could not be resolved to an installable set of packages.

Problem 1
- vimeo/psalm[5.26.1, ..., 5.x-dev] require nikic/php-parser ^4.17 -> satisfiable by nikic/php-parser[v4.17.0, ..., 4.x-dev].
- You can only install one version of a package, so only one of these can be installed: nikic/php-parser[v4.10.0, ..., 4.x-dev, v5.0.0alpha1, ..., v5.2.0].
- pestphp/pest-plugin-mutate[v3.0.3, ..., 3.x-dev] require nikic/php-parser ^5.1.0 -> satisfiable by nikic/php-parser[v5.1.0, v5.2.0].
- pestphp/pest[v3.0.5, ..., 3.x-dev] require pestphp/pest-plugin-mutate ^3.0.3 -> satisfiable by pestphp/pest-plugin-mutate[v3.0.3, 3.x-dev].
- Root composer.json requires pestphp/pest ^3.0.5 -> satisfiable by pestphp/pest[v3.0.5, v3.0.6, 3.x-dev].
- Root composer.json requires vimeo/psalm ^5.26.1 -> satisfiable by vimeo/psalm[5.26.1, 5.x-dev].
```

### How to Reproduce

Add "pestphp/pest": "^3.0.5" and "vimeo/psalm": "^5.26.1" to composer.json

### Pest Version

3.0.5

### PHP Version

8.2

### Operation System

Windows, Linux

### Notes

<img width="1091" alt="phpstorm64_yFL03RcWuM" src="https://github.com/user-attachments/assets/7c99e51b-ff9b-431f-a6b5-59ae664eb41a">

**Comment by Lukasss93** [comment]
2 possible solutions in my opinion:
- Lower the version of "php-parser" to 4.17 in "pest-plugin-mutate".
- Wait for the merge and release of this PR: https://github.com/vimeo/psalm/pull/11035

**Comment by nunomaduro** [comment]
This is a problem with psalm that is using an outdated version of `nikic/php-parser`.
