### ISSUE TITLE
[Bug]: Adding covers() reduces test coverage

### ISSUE THREAD

**Issue by princejohnsantillan** [pestphp/pest#1264]
### What Happened

I have a test coverage of 100% but when I add `covers(CreatePost::class);` it drops to 91.7%.

Why does adding a `covers()` for mutation testing drop the coverage? I'm guessing it's a bug but I could be wrong. Help me understand 🙏

### How to Reproduce

- gh repo clone [princejohnsantillan/pesttest](https://github.com/princejohnsantillan/pesttest)
- composer install
- php artisan test --coverage (This will result in 100% coverage)
- uncomment line 11 in `CreatePostTest.php` 
- php artisan test --coverage (This will result in 91.7% coverage)

### Sample Repository

https://github.com/princejohnsantillan/pesttest

### Pest Version

3.0.6

### PHP Version

8.3

### Operation System

macOS

### Notes

I am using Herd's PHP8.3 with XDebug

![CleanShot 2024-09-19 at 09 11 27@2x](https://github.com/user-attachments/assets/bacfef73-ad31-450b-a7d1-b7458f088e73)

![CleanShot 2024-09-19 at 09 13 04@2x](https://github.com/user-attachments/assets/950907fc-5363-40c5-b078-39fd2ec28711)

**Comment by gehrisandro** [comment]
This is because `covers()` uses the @covers function of PHPUnit behind the scenes: https://docs.phpunit.de/en/10.5/annotations.html#covers

With the latest release of the mutation testing plugin, you can now use `mutate()` instead of `covers()` to mitigate the issue: https://pestphp.com/docs/mutation-testing#get-started

**Comment by princejohnsantillan** [comment]
> This is because `covers()` uses the @Covers function of PHPUnit behind the scenes: https://docs.phpunit.de/en/10.5/annotations.html#covers
> 
> With the latest release of the mutation testing plugin, you can now use `mutate()` instead of `covers()` to mitigate the issue: https://pestphp.com/docs/mutation-testing#get-started

How do I do this though?  `mutate` or `mutates` are functions that don't exist even after requiring `pestphp/pest-plugin-mutate`

**Comment by princejohnsantillan** [comment]
> > This is because `covers()` uses the @Covers function of PHPUnit behind the scenes: https://docs.phpunit.de/en/10.5/annotations.html#covers
> > With the latest release of the mutation testing plugin, you can now use `mutate()` instead of `covers()` to mitigate the issue: https://pestphp.com/docs/mutation-testing#get-started
> 
> How do I do this though? `mutate` or `mutates` are functions that don't exist even after requiring `pestphp/pest-plugin-mutate`

Nevermind. I installed the version `3.1.0` and see the `mutates` function now and it works perfectly!! Thank you @gehrisandro !!
