### ISSUE TITLE
[Bug]: Pest\Mutate\MutationTest::calculateTimeout(): Return value must be of type int, float returned

### ISSUE THREAD

**Issue by wietsewarendorff** [pestphp/pest#1268]
### What Happened

Running mutation test and expected no errors (since I always write perfect code) but I ran into an error:

```
TypeError

  Pest\Mutate\MutationTest::calculateTimeout(): Return value must be of type int, float returned

  at vendor/pestphp/pest-plugin-mutate/src/MutationTest.php:110
    106▕         $initialTestSuiteDuration = Container::getInstance()->get(TelemetryRepository::class) // @phpstan-ignore-line
    107▕             ->getInitialTestSuiteDuration()
    108▕             ->seconds();
    109▕
  ➜ 110▕         return $initialTestSuiteDuration + max(5, $initialTestSuiteDuration * 0.2);
    111▕     }
    112▕
    113▕     public function hasFinished(): bool
    114▕     {
```

### How to Reproduce

`php artisan test --mutate --everything --path=app/`

### Pest Version

3.1.0

### PHP Version

8.3.11

### Operation System

Linux

### Notes

setting the return type to float fixes the problem for me

**Comment by gehrisandro** [comment]
Thanks @wietsewarendorff for raising the issue.

Has been fixed in https://github.com/pestphp/pest-plugin-mutate/pull/16 (release is pending)

**Comment by wietsewarendorff** [comment]
Thanks for the quick reply and fix!
