### ISSUE TITLE
chore: missing tests against PHP 8

### ISSUE THREAD

**Issue by nunomaduro** [pestphp/pest#127]
Currently, the test suite is testing against PHP 7.3, and PHP 7.4. To fix this issue, you should make sure our test suite is testing also against PHP 8. So we can be prepared for PHP 8 before it gets released. 👍🏻

To get started you should update https://github.com/pestphp/pest/blob/3eb0a95955750e4a83749d24462076e5aa1e9a33/.github/workflows/tests.yml#L12.

Finally, and if tests are failing, you should update the source code until the tests are passing.

**Comment by nunomaduro** [comment]
@driesvints is also trying to test the Laravel Core against PHP 8: https://github.com/laravel/framework/compare/php-8-builds. His work may help us here.

**Comment by GrahamCampbell** [comment]
Laravel 8 is coming along well now. A big blocker was Mockery, but I fixed up all that: https://github.com/mockery/mockery/pull/1072. It looks like you are facing a similar issue to mockery.

**Comment by GrahamCampbell** [comment]
I think you can just delete these lines entirely. They are never hit:

<img width="1016" alt="image" src="https://user-images.githubusercontent.com/2829600/87592056-204bc800-c6e1-11ea-89b2-e3283de7c570.png">

**Comment by GrahamCampbell** [comment]
Ish. I'll PR.
