### ISSUE TITLE
[Bug]: --mutate does not work with --parallel

### ISSUE THREAD

**Issue by princejohnsantillan** [pestphp/pest#1270]
### What Happened

Adding `--parallel` breaks mutation testing.

![CleanShot 2024-09-21 at 09 17 39@2x](https://github.com/user-attachments/assets/07b610f5-7dbf-4411-8ff3-e40e07032253)

### How to Reproduce

gh repo clone [princejohnsantillan/pesttest](https://github.com/princejohnsantillan/pesttest)
composer install
./vendor/bin/pest --mutate `this works`
./vendor/bin/pest --mutate --parallel `this does not work`

### Sample Repository

https://github.com/princejohnsantillan/pesttest

### Pest Version

3.1.0

### PHP Version

8.3

### Operation System

macOS

### Notes

Using Herd's PHP 8.3 with XDebug

**Comment by gehrisandro** [comment]
Hi @princejohnsantillan 

Thanks for raising the issue.

This has been fixed now in the latest release of the mutation testing plugin (v3.0.5).

**Comment by princejohnsantillan** [comment]
> Hi @princejohnsantillan
> 
> Thanks for raising the issue.
> 
> This has been fixed now in the latest release of the mutation testing plugin (v3.0.5).

Confirmed that this is fixed.

![CleanShot 2024-09-22 at 18 40 43@2x](https://github.com/user-attachments/assets/6057dc07-751b-4dbd-a1d6-54bcc0b88526)

Thanks @gehrisandro! 🎉
