### ISSUE TITLE
PHPUnit Environment variables not respected

### ISSUE THREAD

**Issue by aniljaiswal** [pestphp/pest#131]
While running `vendor/bin/pest` in a Laravel 7.x project via Docker, the environment variables defined in the phpunit.xml are not being used, instead, it is using the values defined in the .env file.

Is this a bug or an expected behavior at this point?

**Comment by nunomaduro** [comment]
That's very weird. Can you somehow make a project or a test that reproduces that bug?

**Comment by owenvoke** [comment]
I wonder if this is related in any way to the issue we were having with adding back DotEnv 4 support to Collision 5? 🤔

**Comment by nunomaduro** [comment]
@owenvoke He said that've runned `vendor/bin/pest`, and not `php artisan test`.

**Comment by owenvoke** [comment]
Ah, no worries. :+1: I missed that.

**Comment by aniljaiswal** [comment]
> That's very weird. Can you somehow make a project or a test that reproduces that bug?

Sure, I'll try to take out some time to detail the steps.

**Comment by nunomaduro** [comment]
I'm closing this issue because it has been inactive for a few months.
