### ISSUE TITLE
Coverage line numbers not quite in numeric order

### ISSUE THREAD

**Issue by Synchro** [pestphp/pest#132]
I just noticed this slightly odd output:

    Validator 108..111, 296..299, 424..427, 447..446, 456, 480, 520, 539, 542, 597, 657, 661..663, 665..667, 671..680, 700, 705 . 87.7 %

Notice amongst those: `447..446` – looks like line number ranges are not always sorted correctly.

**Comment by nunomaduro** [comment]
That sounds a bug to me. Can you try to make a pull request to fix it?

**Comment by Synchro** [comment]
I made a PR [over here](https://github.com/pestphp/pest-plugin-coverage/pull/5) – is that the right place? The tests are failing, but that doesn't seem to be anything to do with my code!

**Comment by nunomaduro** [comment]
Thank you!
