### ISSUE TITLE
Coverage line numbers not quite in numeric order

### ISSUE THREAD

**Issue by Synchro** [pestphp/pest#133]
I just saw this slightly odd output:

    Validator 108..111, 296..299, 424..427, 447..446, 456, 480, 520, 539, 542, 597, 657, 661..663, 665..667, 671..680, 700, 705 . 87.7 %

Notice amongst those: `447..446` – looks like line number ranges are not always sorted correctly.

Running with PHPUnit 9.2.6 and PHP 7.4.8.

**Comment by nunomaduro** [comment]
Duplicated of https://github.com/pestphp/pest/issues/132.
