### ISSUE TITLE
[Website] Twitter preview image is broken on the website installation docs

### ISSUE THREAD

**Issue by nunomaduro** [pestphp/pest#137]
Looking at this tweet: https://twitter.com/enunomaduro/status/1285990743832694785?s=20. Looks like the twitter preview is broken. 

cc @octoper @AlexMartinFR

**Comment by AlexMartinFR** [comment]
Broken, as in it always displays the same image?

**Comment by nunomaduro** [comment]
Is good now. It wasn't deploying nothing.
