### ISSUE TITLE
Overriding base testcase methods

### ISSUE THREAD

**Issue by nmokkenstorm** [pestphp/pest#143]
[Linked tweet as requested ](https://twitter.com/enunomaduro/status/1288962431209869313)

As mentioned in the above conversation, there's a relatively common usecase for (abstract) base testcases giving extension points for the actual testcases. I ran into this when using Pest and [orchestral/testbench](https://github.com/orchestral/testbench#setup-environment) in conjunction, but it's also something I anticipate having trouble with in Laravel applications where I usually set up some generic API resource testing class.

I'd like to propose having the option to override protected methods/properties using the Pest syntax we've all grown to love, in a similar manner as the [uses option](https://pestphp.com/docs/underlying-test-case/). Although I'm not sure on what a good name would be, I _think_ it should be possible to implement using Reflection if nothing else.

**Comment by nunomaduro** [comment]
`uses(['foo' => function () {}])`. What do you think?

**Comment by nmokkenstorm** [comment]
```
abstract class BaseTestCase
{
    protected function getCacheDriver() : string
    {
        return 'database';
    }
}
```
and
```
uses(BaseTestCase::class)
uses(['getCacheDriver' => function() : string { return 'redis'; }]);
```

Should work I think, although that does relax the function signature of both the [uses global](https://github.com/pestphp/pest/blob/master/src/globals.php#L50) and the [backing Pending Object](https://github.com/pestphp/pest/blob/master/src/PendingObjects/UsesCall.php#L48), so maybe a new global function would be better. I'm not familiar with the internals of Pest yet but I think I'm able to take a stab at this over the weekend.

**Comment by nunomaduro** [comment]
@nmokkenstorm Good luck!

**Comment by nunomaduro** [comment]
As discussed, we are going to keep your proposals on this topic in mind.
