### ISSUE TITLE
Higher order assertDatabase{x} functions

### ISSUE THREAD

**Issue by wardy484** [pestphp/pest#144]
It kind of felt like this issue should have lived in the laravel plugin but I couldn't seem to create issues there, let me know if this is the wrong place. Also let me know if I've missed something glaringly obvious and this is either super easy to do or is already implemented. 

Anyway, I found the higher order functions enable you to right fairly clean tests, for example I'd written the following:

```
beforeEach(function () {
    factory(MenuItem::class)->create([
        'name' => 'Pepperoni Pizza'
    ]);
});

deleteJson('/api/menu-items/pepperoni-pizza')
    ->assertNoContent();
```

However I find it looks a bit less expressive and messy when mixing higher order tests and it() calls. I propose it would be nice to be able to chain `assertDatabaseHas` and the associated laravel database methods onto `getJson`, `postJson`, etc. Which could take the following code:

```
it('deletes menu item when provided a valid menu item', function() {
    deleteJson('/api/menu-items/pepperoni-pizza');

    assertDatabaseMissing('menu_items', [
        'name' => 'Pepperoni Pizza'
    ]);
});
```
and make it : 
```
deleteJson('/api/menu-items/pepperoni-pizza')
    ->assertDatabaseMissing('menu_items', [
        'name' => 'Pepperoni Pizza'
    ]);
}
```

Thanks for reading :smile:

**Comment by wardy484** [comment]
For anyone curious I've solved this in my project for the mean-time with macros: 
```
TestResponse::macro('assertDatabaseHas', function(string $table, array $data) {
    return test()->assertDatabaseHas($table, $data);
});

TestResponse::macro('assertDatabaseMissing', function(string $table, array $data) {
    return test()->assertDatabaseMissing($table, $data);
});
``` 

I'm not convinced its a good solution but it certainly makes my tests quite tidy.

**Comment by nunomaduro** [comment]
lol, seems a good solution for me.

Another option is using your own `deleteJson` function, that returns the test case instead of the test response.
