### ISSUE TITLE
Better exception assertions

### ISSUE THREAD

**Issue by GrahamCampbell** [pestphp/pest#152]
It'd be nice if throws provided a callback so someone can write assertions against the thrown exception. The current way of doing things could be slicker. Currently one must do something like (some real test code from StyleCI here):

```php
    public function testMakeInvalidFinderOption(): void
    {
        $this->expectException(InvalidFinderOptionException::class);
        $this->expectExceptionMessage('The finder option \'foo\' is not valid.');

        try {
            ConfigFactory::make(['finder' => ['foo' => 'bar']]);
        } catch (Exception $e) {
            $this->assertSame('foo', $e->getOption());

            throw $e;
        }
    }
```

In pest world, the try-catch would still be there:

```php
it('forbids using invalid finder option', function () {
    try {
        ConfigFactory::make(['finder' => ['foo' => 'bar']]);
    } catch (Exception $e) {
        $this->assertSame('foo', $e->getOption());

        throw $e;
    }
})->throws(InvalidFinderOptionException::class, 'The finder option \'foo\' is not valid.');
```

Can we do better, maybe by allowing throws to have a callback to allow a developer to make assertions about the caught exception.

**Comment by owenvoke** [comment]
So would this just be a 3rd parameter in the `throws()` call? That would be neat! So something like:
```php
it('throws', fn () => throw new Exception())
  ->throws(Exception::class, 'error', function (Exception $exception) {
    expect($exception->getFile())
      ->toBe('path/to/file.php');
  });
```

**Comment by GrahamCampbell** [comment]
Yeh, exactly. That's pretty much what I had in mind, and possibly allowing param 2 to be a callable too, in the case that someone doesn't wanna check the message.

Another approach would be to have `->throws(...)->then(function...)` or something, but then we'd have to change the return value of throws to something else, which could be annoying.

**Comment by owenvoke** [comment]
Yeah, I had thought about a different return type but couldn't think of a good name. `then()` would be quite simple and consistent.

I agree that sometimes people won't want to check the message, or for example they want to check it in the callback instead. 🤷🏻 👍🏻

**Comment by GrahamCampbell** [comment]
> then() would be quite simple and consistent.

Yeh, that was @nunomaduro's idea actually, after I suggested `andThen`. ;)

**Comment by nunomaduro** [comment]
I've no plans on working on this. Feel free to submit a pull request.
