### ISSUE TITLE
Add Pest plugin to documentation

### ISSUE THREAD

**Issue by olivernybroe** [pestphp/pest#157]
The plugin is now getting a stable release and I think it is time for us to actually add it to the website for user's to easily find it.

JetBrains has support for two different iframes which might be useful in docs
![image](https://user-images.githubusercontent.com/5870441/89391704-d6b33380-d708-11ea-8da9-7bcbd389885f.png)
```
<iframe frameborder="none" width="230px" height="110px" src="https://plugins.jetbrains.com/embeddable/card/14636"></iframe>
```
![image](https://user-images.githubusercontent.com/5870441/89391745-e468b900-d708-11ea-9b33-5c0cb45461f8.png)
```
<iframe frameborder="none" width="245px" height="48px" src="https://plugins.jetbrains.com/embeddable/install/14636"
````

ofc. we don't have to use them 👍

**Comment by owenvoke** [comment]
I feel like it would be nice to create our own component that fits with the rest of the site. But either of those embeds would probably be fine, although that's loading another thing from a remote endpoint. :shrug:

**Comment by olivernybroe** [comment]
@owenvoke Yeah, I think our own component would prob. be better 👍 Just wanted to show the option if somebody found them a better fit.

**Comment by nunomaduro** [comment]
cc @AlexMartinFR

**Comment by octoper** [comment]
I might be able to make a component later today.

**Comment by AlexMartinFR** [comment]
Now that we have an official PHPStorm plugin, can we assume [all issues listed here](https://github.com/pestphp/pest/issues/86) are solved?

If so, we could turn the **PHPStorm guide** into a broader **IDE integration** guide.
We could also link @m1guelpf's https://github.com/m1guelpf/better-pest for VSCode users.

**Comment by olivernybroe** [comment]
@AlexMartinFR We can also use shield.io for the downloads part, they support intellij plugins

**Comment by AlexMartinFR** [comment]
Can we extract only the downloads number from the JetBrains website?

If so, we could have a custom design like so:
(I would write a text introduction on top of the page, before throwing the cards).

![image](https://user-images.githubusercontent.com/19224681/89660655-ee89e380-d8d1-11ea-855e-91129654056b.png)

I've reused a "dome badge" CSS class I'm using on my projects to make different logos fit better together.
Also, the card is inspired by some TailwindUI components, and the download SVG is from Heroicons 👍

**Comment by owenvoke** [comment]
@AlexMartinFR, that looks great! You could probably use their API and just extract the relevant XML attribute?
https://plugins.jetbrains.com/plugins/list?pluginId=14636

It's under the following XML XPath selector:
```
/plugin-repository/category/idea-plugin[1]@downloads
```

**Comment by olivernybroe** [comment]
@owenvoke that is also how shields.io does it 👍

**Comment by AlexMartinFR** [comment]
Shootout to @octoper who is working in the dark to bring this to life! 👍

**Comment by octoper** [comment]
This is gonna be included in the new Pest Documentation

**Comment by olivernybroe** [comment]
@octoper looking sooo forward to that 👍

**Comment by octoper** [comment]
@olivernybroe I think that you can close that issue because the page has been added to the new website!
