### ISSUE TITLE
Pest broken with PHPUnit 9.3

### ISSUE THREAD

**Issue by adamthehutt** [pestphp/pest#158]
PHPUnit 9.3 made some changes to the class/directory structure that seem to have broken Pest.

In particular, there are no longer any classed in the PHPUnit/TextUI/Configuration namespace. Pest's Pest\Actions\ValidatesConfiguration class relies on two classes that used to be in that namespace (Configuration and Registry). This results in a fatal error any time you run Pest with PHPUnit 9.3.

**Comment by owenvoke** [comment]
Looks like this should be resolved going forward by #128 👍🏻

**Comment by GrahamCampbell** [comment]
You need to upgrade to the latest tag of pest, to stop this happening. :)
