### ISSUE TITLE
Plans for `only` modifier?

### ISSUE THREAD

**Issue by mikeerickson** [pestphp/pest#16]
Along the lines of `describe` blocks, curious of the thought process for using `only` modifier

Example

```php
test('do something here', function(){
  assertTrue(true);
})->only();
```

**Comment by nunomaduro** [comment]
It’s already there no?

**Comment by nunomaduro** [comment]
<img width="849" alt="Screenshot 2020-05-23 at 03 15 59" src="https://user-images.githubusercontent.com/5457236/82718606-ba742e80-9ca3-11ea-841d-02a4f22a0d65.png">

**Comment by mikeerickson** [comment]
Ah, my bad. I missed this one 🤓
