### ISSUE TITLE
How override uses() in a single file in Suite? [Q / Feature request]

### ISSUE THREAD

**Issue by ajthinking** [pestphp/pest#167]
How can I use a different `uses` statement for a single file in my Feature suite?

In `Pest.php`

    // All tests in Feature folder should use TestCase
    uses(Tests\TestCase::class)->in('Feature');
    // Except this one 
    uses(Tests\IseedTestCase::class)->in('Feature/Ifrs/BulkTest');

It seems I cant override `uses` in that specific file:
> Test case `Tests\TestCase` can not be used. The folder `/...../tests/Feature/Ifrs/BulkTest.php` already uses the test case `Tests\IseedTestCase

Leaving me with options to move that specific test to its own folder or keeping all uses() statement in each test. Any remedy for this situation?

**Comment by nunomaduro** [comment]
I've no plans on working on this. Feel free to submit a pull request.
