### ISSUE TITLE
Laravel .env not picked up in test

### ISSUE THREAD

**Issue by JacobBennett** [pestphp/pest#168]
When running my test, if I `dd(config('services'));` Nothing will be set in the array that is defined in my `.env` and loaded into the config.

Not sure if I am missing something in my `TestCase` that needs to be added or what might be causing these `.env` values to be ignored.

**Comment by nunomaduro** [comment]
@owenvoke Can you test this in a fresh laravel app very quickly? I am almost 100% sure this works.

**Comment by owenvoke** [comment]
Seems to be working as expected when I tested. 🤔

https://asciinema.org/a/lVxc1Wwi8txmihEEhBHvqJg9z

<details>
<summary>Preview screenshot</summary>

![image](https://user-images.githubusercontent.com/1899334/91155777-345cef00-e6bb-11ea-803b-1c8d8b0ca6ae.png)

</details>

**Comment by michaeldyrynda** [comment]
Make sure you don’t have cached config. That’ll wreak havoc on your expectations!

**Comment by JacobBennett** [comment]
Hey guys. Had an .env.testing I didn’t realize was taking precedence! My bad 😅

**Comment by owenvoke** [comment]
No problem @JacobBennett, easy mistake to make. Going to close this issue if that's alright? 👍🏻

**Comment by JacobBennett** [comment]
Yes, please! Was going to close myself but couldn't find the option on Github Mobile :)
