### ISSUE TITLE
Document pest cli

### ISSUE THREAD

**Issue by JoshMoreno** [pestphp/pest#17]
A simple page for this should suffice. I'm thinking

- Document that pest forwards all arguments to PHPUnit. For example, I often use `--filter` to cut down on test time when I'm working on a specific feature.
- Document pest specific arguments (`--coverage` and `--min`). This would be in addition to the coverage page.

**Comment by nunomaduro** [comment]
Can you sync with @AlexMartinFR ? I think he can help you making a pull request on docs about this.

**Comment by AlexMartinFR** [comment]
Hi @JoshMoreno , I have a few other docs improvement & additions waiting, but if you can make a draft for this I'll be happy to review and improve upon it if you want.

A list of the other PHPunit options you find the most useful and a small description for each, just like you did here would be perfect.

**Comment by JoshMoreno** [comment]
@AlexMartinFR Sure, no problem! How would you like the draft? Markdown, just some notes like I did below, etc...? It's going to be really simple, since all I really use is `--filter` and `--group`, but pest already has it's own api for grouping tests. So I'm thinking:

- A note about pest forwarding args to PHPUnit with an example using `--filter` to get the point across.
- A section to list pest cli args - `--coverage`, `--min`, and `--group`.

**Comment by AlexMartinFR** [comment]
Markdown is great, it's what the other documentation pages are written in 🙂
Yeah I would go with two sections too:

- Pest's own CLI first, each command detailed with a code/output example
- Then PHPUnit's other useful CLI options (it's worth polling the other Pest users on the Discord for their favorite ones)

**Comment by nunomaduro** [comment]
It's in progress by @owenvoke.
