### ISSUE TITLE
Call to undefined function assert*

### ISSUE THREAD

**Issue by Synchro** [pestphp/pest#175]
Just a pointer issue for searchers. If you start getting these "undefined function" errors after upgrading to pest 0.3, it means you need to read [the upgrade guide](https://pestphp.com/docs/upgrade-guide/), and switch your assertions to [the expectation API](https://pestphp.com/docs/expectations/) or instance methods instead of the old global `assert*` functions.

**Comment by AlexMartinFR** [comment]
Thanks for that!

**Comment by erikaheidi** [comment]
Thank you for this, helped me a lot :)
