### ISSUE TITLE
Website: Move from Jigsaw to a Laravel App

### ISSUE THREAD

**Issue by octoper** [pestphp/pest#176]
I think it would be a good idea if we move from Jigsaw to a Laravel App like [laravel.com](https://github.com/laravel/laravel.com-next) or [blade-ui-kit.com](https://github.com/blade-ui-kit/blade-ui-kit.com) and also seperate the docs mardown files to a seperate reporitory. This will add some easier maintaining for the website development in my opinion.

**Comment by owenvoke** [comment]
Hmm, interesting idea. I quite like the static ability of Jigsaw personally (I use it for my site as well). I'm open to using a Laravel app if there are many benefits over the current way.

**Comment by octoper** [comment]
I think we will have more flexsibility for development and we can easily add table of contents for our docs pages with Blade UI Kit ToC Component 😅

**Comment by AlexMartinFR** [comment]
Long documentation pages would greatly benefit from a clickable **Table of Contents**.
See **Idea 1** in #90

This idea came back to the surface while re-reading the Expectation API page.
It lacks an easy to browse overview of all available methods:

[Pest Documentation - Expectations](https://pestphp.com/docs/expectations/)
VS
[Laravel Documentation - Eloquent Collections - List of available methods](https://laravel.com/docs/7.x/eloquent-collections#available-methods)

**Comment by AlexMartinFR** [comment]
I can't remember if I already said that, but I feel it's important to keep an easy way for people to contribute to the documentation!

The fact that it's currently as easy as submitting a GitHub PR is a huge plus.
That's how I got involved in Pest in the first place. 🙂

**Comment by octoper** [comment]
@AlexMartinFR I have this in mind so don't worry!

**Comment by octoper** [comment]
Closing this as it's done! [pestphp/pestphp.com-next](https://github.com/pestphp/pestphp.com-next)
