### ISSUE TITLE
Add toThrow expect assertion

### ISSUE THREAD

**Issue by khalyomede** [pestphp/pest#177]
## Motivation

Expect is a great way to make my test more readable. À la Jest, I would like to be able to use expect to assert that some code should throw a particular exception instance.

## Expected behavior

A new `->toThrow(Exception::class)` method to assert that a class will be thrown in the expect callback.

```php
it("should throw an exception if the HTTP protocol is not valid", function() {
  expect(function() {
    new Route("FOO", "/about-us");
  })->toThrow(InvalidArgumentException::class);
});
```
 
## Actual Behavior

The method do not exist yet.

## Current working alternatives

I use this working code for the moment:

```php
it("should throw an exception if the HTTP protocol is not valid", function() {
  $this->expectException(InvalidArgumentException::class);
  
  new Route("FOO", "/about-us");
});
```

## Notes

I found [the source code location](https://github.com/sebastianbergmann/phpunit/blob/9.3.8/src/Framework/TestCase.php#L574) for the original `$this->expectException()` method, but as I understand the source code of Pest, this is not part of the `Assert` class.

If you don't want to extends from TestCase, this means we will probably need to make it on our own?

**Comment by owenvoke** [comment]
You could use the top level `throws` method, which is a bit cleaner.
```php
it("should throw an exception if the HTTP protocol is not valid", function() {
  new Route("FOO", "/about-us");
})->throws(InvalidArgumentException::class);
```

But that does look interesting. 🤔 So if you were using `toThrow()` it would need to catch everything inside the expectation.

**Comment by nunomaduro** [comment]
No plans for having this. Thanks for the suggestion tho.
