### ISSUE TITLE
Unknown formatter "name" (when using with factories in Laravel)

### ISSUE THREAD

**Issue by lexdubyna** [pestphp/pest#181]
I am trying to write Pest test for a Laravel 8 project.
Pest.php:
```
<?php

use Tests\TestCase;
use Illuminate\Foundation\Testing\RefreshDatabase;

uses(TestCase::class, RefreshDatabase::class)->in('Feature', 'Unit');
```
Feature/LoginTest.php
```
<?php

use App\Models\User;

$user = User::factory()->create();

it('logins a valid user')->postJson('api/login', [
    'email' => $user->email,
    'password' => 'password'
])
    ->assertStatus(200)
    ->assertJsonStructure([
        'data' => [
            'user',
            'token'
        ]
    ]);
```
It gives me this issue:
``` InvalidArgumentException 

  Unknown formatter "name"

  at C:\OpenServer\domains\eight\vendor\fzaninotto\faker\src\Faker\Generator.php:248
    244▕ 
    245▕                 return $this->formatters[$formatter];
    246▕             }
    247▕         }
  ➜ 248▕         throw new \InvalidArgumentException(sprintf('Unknown formatter "%s"', $formatter));
    249▕     }
    250▕
    251▕     /**
    252▕      * Replaces tokens ('{{ tokenName }}') with the result from the token method call

  1   C:\OpenServer\domains\eight\vendor\fzaninotto\faker\src\Faker\Generator.php:228
      Faker\Generator::getFormatter()

  2   C:\OpenServer\domains\eight\vendor\fzaninotto\faker\src\Faker\Generator.php:274
      Faker\Generator::format()
```

I can "fix" it with `User::create(...some data...)`, but then I get this
```
Call to a member function connection() on null

  at C:\OpenServer\domains\eight\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php:1336
    1332▕      * @return \Illuminate\Database\Connection
    1333▕      */
    1334▕     public static function resolveConnection($connection = null)
    1335▕     {
  ➜ 1336▕         return static::$resolver->connection($connection);
    1337▕     }
    1338▕ 
    1339▕     /**
    1340▕      * Get the connection resolver instance.

  1   C:\OpenServer\domains\eight\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php:1302
      Illuminate\Database\Eloquent\Model::resolveConnection()

  2   C:\OpenServer\domains\eight\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php:1108
      Illuminate\Database\Eloquent\Model::getConnection()
```

Please help.

**Comment by owenvoke** [comment]
What's the content of the factory class? 🤔

**Comment by lexdubyna** [comment]
@owenvoke 
```
<?php

namespace Database\Factories;

use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

class UserFactory extends Factory
{
    /**
     * The name of the factory's corresponding model.
     *
     * @var string
     */
    protected $model = User::class;

    /**
     * Define the model's default state.
     *
     * @return array
     */
    public function definition()
    {
        return [
            'name' => $this->faker->name,
            'email' => $this->faker->unique()->safeEmail,
            'email_verified_at' => now(),
            'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', // password
        ];
    }
}
```

**Comment by owenvoke** [comment]
So I've had a look into this, it seems that in the base [`Illuminate\Database\Eloquent\Factories\Factory` class](https://github.com/laravel/framework/blob/75b796d9220233ac9c232ed5db32a9d5dbdc0d7d/src/Illuminate/Database/Eloquent/Factories/Factory.php#L669) it doesn't take locale into account as it just uses `return Container::getInstance()->make(Generator::class);` to get the generator from the container. Which seems to create a generator instance with no providers. 🤨

This can be resolved by updating the `withFaker()` method there to match the existing [`WithFaker`](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Foundation/Testing/WithFaker.php#L44) trait. Therefore, you'd end up with something like the following (although this still doesn't take the config locale into account).
```php
protected function withFaker()
{
    $locale = \Faker\Factory::DEFAULT_LOCALE;

    if (Container::getInstance()->bound(Generator::class)) {
        return Container::getInstance()->make(Generator::class);
    }

    return \Faker\Factory::create($locale);
}
```

This also appears to be a problem in PHPUnit, so I'd assume it's a Laravel issue. 🤔

**Comment by nunomaduro** [comment]
You need to place the `$user = User::factory()->create();` inside a closure.

**Comment by owenvoke** [comment]
🤦🏻 I should have spotted that as well.

**Comment by pramanikriju** [comment]
I have a weird issue when using setup functions inside a test case. 
This works flawlessly
```
beforeEach(function () {
    $user = User::factory()->create([
        'is_subscribed' => true,
    ]);
    return actingAs($user);
});
```
But this doesn't. And unknown formatter 'name' error is thrown.
```
beforeAll(function () {
    $user = User::factory()->create([
        'is_subscribed' => true,
    ]);
    return actingAs($user);
});
```
Not sure what changes between the two. 
The test is a simple 
`test('can view dashboard')->get('/dashboard')->assertStatus(200);`
Any hints as to why this might be caused?

**Comment by ZeroGodForce** [comment]
> I have a weird issue when using setup functions inside a test case. This works flawlessly
> 
> ```
> beforeEach(function () {
>     $user = User::factory()->create([
>         'is_subscribed' => true,
>     ]);
>     return actingAs($user);
> });
> ```
> 
> But this doesn't. And unknown formatter 'name' error is thrown.
> 
> ```
> beforeAll(function () {
>     $user = User::factory()->create([
>         'is_subscribed' => true,
>     ]);
>     return actingAs($user);
> });
> ```
> 
> Not sure what changes between the two. The test is a simple `test('can view dashboard')->get('/dashboard')->assertStatus(200);` Any hints as to why this might be caused?

I have exactly this same issue.  Worked fine when I was using `beforeEach` but not for `beforeAll`.  Did you ever find a resolution?
