### ISSUE TITLE
only() modifier is only limited to file scope

### ISSUE THREAD

**Issue by DannyvdSluijs** [pestphp/pest#183]
The `only` modifier is only limited to file scope. It will run tests in other files as well when running the command `./vendor/bin/pest` and only skip the ones that are in the current file.
It's current behaviour doesn't match the expectations from the Pest website where it mentions:

> ## Running a single test
> If you’d like to run a single test to debug a problem, just use the following syntax:
> 
> ```php
> it('has home', function () {
>     // ..
> })->only();
> ```

The way I see it there are two ways about this:
1.) Update the docs to reflect the `only()` is limited to the file scope
2.) Update pest to only run the tests (yes, plural) that are marked with the `only()` modifier.

Given I don't know what the opinion is of the core team it think it is best to have a decision before any fix.

**Comment by olivernybroe** [comment]
Given that `only` is more of a debug solution than something you would have in your codebase, I think I would prefer the second option here.

**Comment by nunomaduro** [comment]
This is not true. 

The `only` modified doesn't work tho if you have tests in PHPUnit classes.

**Comment by DannyvdSluijs** [comment]
I've double checked this and indeed from a new laravel application the `Feature` test was still as a PHPUnit Testcase. Moving this over to Pest format using `it('description', callback)` it resolved my issues. Perhaps worth adding this to the site to inform people moving from PHPUnit to Pest?

**Comment by nunomaduro** [comment]
Sure, can you make a pull request?
