### ISSUE TITLE
Add collision output to teamcity printer

### ISSUE THREAD

**Issue by olivernybroe** [pestphp/pest#188]
Right now when an exception happens when using the teamcity printer, it is not using the nice collision output.

By adding support for that, when running test inside phpstorm, we will see our favorite output format.

**Comment by roni-estein** [comment]
Super excited for this!!

**Comment by olivernybroe** [comment]
So we updated the exception output, however it is still not using collision.

@roni-estein This still might make it just a bit easier to read the exception outpu.
https://github.com/pestphp/pest/pull/215

New result:
![image](https://user-images.githubusercontent.com/5870441/98089385-ef0b2980-1e82-11eb-9f72-2c9673028111.png)
Old result:
![image](https://user-images.githubusercontent.com/5870441/98089524-1feb5e80-1e83-11eb-8465-a7774112fa8b.png)

**Comment by olivernybroe** [comment]
Before we can get collision output, I think Collision might need some changes so we can call the different methods for rendering exceptions in their nice output.

**Comment by nunomaduro** [comment]
This is done?

**Comment by olivernybroe** [comment]
Nope.

So we changed the output in the teamcity printer to a much nicer looking one.

However I don't think I see the need for collision exception output when running in phpstorm, as you can press the file for seeing the code.

I think we should close this one as a "not right now" state. And if more users show interest we should reopen it.
