### ISSUE TITLE
Idea: get easy access to an faker instance in pest

### ISSUE THREAD

**Issue by LarsWiegers** [pestphp/pest#19]
We could have an $this->faker instance or something like that or an trait that we can implement using uses(), love to know your ideas on this

**Comment by canvural** [comment]
You can create a [custom helper](https://pestphp.com/docs/helpers/) function called `faker` that returns a Faker instance. And use it like `faker()->text` in your tests. I think that's pretty easy.

**Comment by nunomaduro** [comment]
Ideally this would be also a plugin. 🥰

**Comment by owenvoke** [comment]
I guess this is solved by the Faker plugin now. :+1:

- [Documentation](https://pestphp.com/docs/plugins/faker/)
- [Source code](https://github.com/pestphp/pest-plugin-faker)

**Comment by LarsWiegers** [comment]
Looks good!
