### ISSUE TITLE
Bug: `$this when not in object context` for datasets

### ISSUE THREAD

**Issue by nmokkenstorm** [pestphp/pest#192]
Hey all,

Currently trying to access the current test scope `$this` does not work for datasets. This is annoying but pretty easily fixable for the `Callable`& named cases, I don't know from the top of my head how I'd tackle the array case.

Happy to work on a PR for the former cases, would love some thoughts on the latter. Probably related to #122

**Comment by nunomaduro** [comment]
Sure - curious to see your PR on this.

**Comment by nunomaduro** [comment]
I've no plans on working on this. Feel free to submit a pull request.
