### ISSUE TITLE
Tests outside of `tests` directory won't load/run

### ISSUE THREAD

**Issue by faustbrian** [pestphp/pest#194]
On larger projects with Laravel I keep tests in the same directory as the source but this seems to cause issues with Pest, PHPUnit works fine.

```php
<?php

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

uses(TestCase::class, RefreshDatabase::class)->in(realpath(__DIR__.'/../app'));
```

This results in the following.

```
  Undefined index: file

      +2 vendor frames
  3   [internal]:0
      Composer\Autoload\ClassLoader::loadClass("App\Console\Commands\SomeCommand")

  4   [internal]:0
      spl_autoload_call("App\Console\Commands\SomeCommand")
```

Should this just work out of the box or is there something I am overlooking that needs to be adjusted?

**Comment by owenvoke** [comment]
Yeah, Pest currently expects a `tests` directory and this isn't configurable at the moment. 🤔

**Comment by nunomaduro** [comment]
Yeah - no plans for having this.

**Comment by faustbrian** [comment]
Any specific reason for not making this configurable? It's not uncommon to keep the source and tests in the same directory when working on large projects.

**Comment by nunomaduro** [comment]
I think the vast majority of Pest users do put their tests in the `tests` folder.

**Comment by georgeboot** [comment]
@nunomaduro I maintain a mono repo (both php and javascript packages in same repo) and have my php tests in `/php-tests`.

Would you accept a PR for adding this as a configurable option?

**Comment by nunomaduro** [comment]
Yes.

**Comment by lcdss** [comment]
I'm using laravel-modules in a project and there are a test directory for each module created, so would be great if pest could run test from multiple directories as phpunit do.

**Comment by faustbrian** [comment]
https://github.com/pestphp/pest/pull/283

**Comment by binaryfire** [comment]
Hi. I’m also using laravel-modules (which has a separate tests folder in each module).

So just to clarify- there’s no way of using Pest in this scenario?

**Comment by lcdss** [comment]
@binaryfire Unfortunately no. I switched projects and haven't worked with Pest/PHP anymore.

**Comment by shijunti19** [comment]
```
packages\a031\comm
 "repositories": [
        {
            "type": "path",
            "url": "./packages/a031/comm"
        }
    ]
packages\a031\comm\tests
Now I want to execute in the root directory \Vendor bin pest -- test directory packages a031 comm tests
```
How to achieve it

**Comment by chrispage1** [comment]
Just for when I google this next time... you can add your modules into phpunit.xml and they'll run when you make your call to pest from the root of the product. Example:

```xml
    <testsuites>
        <testsuite name="Unit">
            <directory>tests/Unit</directory>
        </testsuite>
        <testsuite name="Feature">
            <directory>tests/Feature</directory>
            <directory>modules/Auth/tests</directory>
            <directory>modules/CampaignMonitor/tests</directory>
            <directory>modules/Countries/tests</directory>
            <directory>modules/Folders/tests</directory>
            <directory>modules/Posts/tests</directory>
            <directory>modules/Reporting/tests</directory>
            <directory>modules/Translator/tests</directory>
            <directory>modules/VideoTranscoding/tests</directory>
        </testsuite>
    </testsuites>
```
