### ISSUE TITLE
Can't use empty array as one of dataset values

### ISSUE THREAD

**Issue by rihardssceredins** [pestphp/pest#195]
Hey,

Just started using datasets (great feature 💯) and noticed this:

```
it('test empty user input processing', function ($param){
    expect(true)->toBeTrue();
})->with([
    null,
    []
]);
```

<img width="771" alt="Screenshot 2020-09-29 at 19 23 58" src="https://user-images.githubusercontent.com/23099574/94585948-584abc00-0289-11eb-9e0a-87ac979ec7c2.png">

**Comment by nunomaduro** [comment]
Your closure requires an `$param`. Update the code to:

```
it('foo', function ($param = null) { ..
```

**Comment by rihardssceredins** [comment]
@nunomaduro hmmm, it now received null in both cases but in the second one it should've received an empty array:

```
it('test empty user input processing', function ($param = null){
    dump($param);
    expect(true)->toBeTrue();
})->with([
    null,
    []
]);
```

<img width="592" alt="Screenshot 2020-09-30 at 09 57 17" src="https://user-images.githubusercontent.com/23099574/94652884-62a99c00-0303-11eb-8720-a95a336fd3c5.png">

**Comment by owenvoke** [comment]
I'd assume that's because the array is interpreted as a subset of parameters.
```php
it('test empty user input processing', function ($param = null) {
    expect(true)->toBeTrue();
})->with([
    [null],
    [[]]
]);
```

**Comment by rihardssceredins** [comment]
@owenvoke oh, nice, thanks! I saw it but it didn't seem applicable because it was indended for _multiple arguments_. :D

**Comment by owenvoke** [comment]
Perhaps we could update the docs to clarify that a bit more in the case of an empty array. 👍🏻 Cheers.
