### ISSUE TITLE
Output when run via PHPStorm looks like phpunit, not pest

### ISSUE THREAD

**Issue by Synchro** [pestphp/pest#198]
I originally assumed that this issue was in pest-intellij and reported it [here](https://github.com/pestphp/pest-intellij/issues/71), but @olivernybroe tells me it's not, so reposting it here.

I have set up a pest test running as per the docs, and when it runs inside PHPStorm it looks like "regular" phpunit:

![image](https://user-images.githubusercontent.com/81561/94270267-1693db80-ff40-11ea-84fd-d41f298e9cb4.png)

But when I run it on a command line it produces pretty pest output:

![image](https://user-images.githubusercontent.com/81561/94270409-44792000-ff40-11ea-8ec9-a51c82587555.png)

I assume the difference is in the `--teamcity` output option, but can I get the pretty pest output in PHPStorm? Or is the teamcity format output needed to provide source links?

I also noticed that when phpunit is run via pest, it reports zero assertions – I don't know if that's a symptom of the same problem or a separate thing.

**Comment by owenvoke** [comment]
Check out issue https://github.com/pestphp/pest/issues/188 regarding adding Collision output to the TeamCity adapter. 👍🏻  Hopefully we're able to get this working soon (although I have no idea what's involved). 🤔

That zero assertions issue seems odd though...

**Comment by olivernybroe** [comment]
Thanks for posting it here 👍  

So the [`TeamCity` printer](https://github.com/pestphp/pest/blob/master/src/TeamCity.php) has a `printResult` method. This one has to be updated to use the same logic pest uses for it's printer. 

@owenvoke The collision output is also related to this printer, however I think solving this one is much easier.

**Comment by olivernybroe** [comment]
I guess we don't have to solve the zero assertion issue if we change the output to the same as pest is using, as pest don't show the amount of assertions 🤣

**Comment by nunomaduro** [comment]
@olivernybroe Now that TeamPrinter is merged - does it solve this issue?

**Comment by olivernybroe** [comment]
Unfortunately not. We only added the printer, we did not change to output so it looks like the normal pest output. 

As mentioned earlier, we have to update the `printResult` method, so the output is the same as in normal run with pest.

**Comment by dcblogdev** [comment]
I'm also getting PHPUnit output when running PEST 

The test:
![image](https://user-images.githubusercontent.com/1018170/118458574-d19cff00-b6f2-11eb-8965-ba3a5fdbd8f4.png)


The Output in storm:
![image](https://user-images.githubusercontent.com/1018170/118458504-bcc06b80-b6f2-11eb-9d31-661a9e71281e.png)

In CLI works perfectly:
![image](https://user-images.githubusercontent.com/1018170/118458675-e9748300-b6f2-11eb-9643-3181a51b5f1a.png)

**Comment by olivernybroe** [comment]
@dcblogdev Yeah, so this one is still waiting for someone to take on the task and actually change the output to pest looking output when using the TeamCity printer.

**Comment by nunomaduro** [comment]
@olivernybroe Is this fixed?

**Comment by olivernybroe** [comment]
@nunomaduro nope, it still hasn't been done. 

The biggest reason why I don't work on this myself if because it's not really a problem for me, I don't read the console output phpstorm to see the amount of tests, as that is available in phpstorms interface
