### ISSUE TITLE
test() does not return the same instance with `beforeEach()`

### ISSUE THREAD

**Issue by mnapoli** [pestphp/pest#202]
The `test()` function should return the `TestCase` instance. However, it does not return the same object in `beforeEach()` and in the test. That means that using this to store a global variable (for example the application) doesn't work.

## Reproducing

```php
beforeEach(function () {
    echo spl_object_id(test()) . PHP_EOL;
    ob_flush();
});

test('foo', function () {
    echo spl_object_id(test()) . PHP_EOL;
    ob_flush();
});
```

This will show 2 different object IDs, meaning 2 different instances of `TestCase`.

**Comment by octoper** [comment]
Hmm that's weird @mnapoli  it's shows the same object ID for both of them for me

**Comment by mnapoli** [comment]
Maybe it has been fixed since then?

**Comment by owenvoke** [comment]
Yeah, this appears to be working. Feel free to reopen this issue if you experience it again. 🤔 I can't see much that would have changed this behaviour though.
