### ISSUE TITLE
Coverage results lines sometimes exceeds compared to the other lines

### ISSUE THREAD

**Issue by khalyomede** [pestphp/pest#204]
## Description

Sometimes the results exceeds in length compared to other results, resulting in visual overflow.

![overflowing-result-pest-php](https://user-images.githubusercontent.com/15908747/95652840-56d48b80-0af4-11eb-9951-6b0fd72fd8bc.png)

## Reproduce the issue

I can't systematically reproduce this, but my guess is that big file path combined with a lot of missing covered line facilitate the bug to appear, but nothing sure as I did not dived into the source code.

## Expected behavior

All the lines allign without overflowing results.

**Comment by owenvoke** [comment]
Hi @khalyomede, thanks for flagging this up.

Looks like this is caused by the way the "dotted line" is generated in the Coverage plugin:
https://github.com/pestphp/pest-plugin-coverage/blob/master/src/Coverage.php#L57

So I guess we'd need to allow lengths of more than 70, although that could be an issue as I'm assuming the width of 70 is based on a standard old terminal width of 80.

**Comment by khalyomede** [comment]
I know that in Javascript, when using nyc for displaying the coverage in the terminal, as the involved lines cells are quite short, the author have used a technique to use ellipsis in the case there is too much lines to cover.

![nyc coverage on terminal](https://www.thetopsites.net/images/53249858-2.png)

Do you think this could be a possible solution, to use ellipsis to avoid the line to go over 70 characters?

**Comment by owenvoke** [comment]
We probably could, although due to the existing dotted lines I'm not sure if that may cause it to look confusing. @nunomaduro, what is your thought on this?

**Comment by nunomaduro** [comment]
I think we could add a line bellow?

**Comment by owenvoke** [comment]
Hmm, what do you mean? Like... split the line numbers into multiple lines?

```text
| --------------------------  72 characters  ------------------------- |
QueueDrivers/FileQueueDriver.php ..... 42, 51, 57, 91, 103, 194 . 90.2%
                                 ................ 209, 220, 232
```

**Comment by nunomaduro** [comment]
```
| --------------------------  72 characters  ------------------------- |
QueueDrivers/FileQueueDriver.php 42, 51, 57, 91, 103, 194 ......
                                                             209, 220, 232 .................... 90.2%

```

**Comment by nunomaduro** [comment]
I've no plans on working on this. Feel free to submit a pull request.
