### ISSUE TITLE
Allow usage of static closures

### ISSUE THREAD

**Issue by olivernybroe** [pestphp/pest#206]
When writing a test which contains no `$this` keyword, it would be awesome if we could define them as static.

```php
it('can contain work', static function () {
    expect(Str::containsWord('test & word', 'test'))->toBeTrue();
});
```

**Comment by nunomaduro** [comment]
What would be the benefit from it?

**Comment by owenvoke** [comment]
Micro-op? 🤔 PhpStorm always is complaining to me about this.

**Comment by olivernybroe** [comment]
Yeah so the reason is basically that static functions are faster, which means static analysis would always recommend you to write it as a static function when possible.

With the usage of `expect` and so on we are actually not depending on `$this`, so it can be static 👍

**Comment by owenvoke** [comment]
Realistically, how much faster are them (genuinely interested if there's a good blog)? 🙂

**Comment by olivernybroe** [comment]
@owenvoke Read about it awhile ago, so can't remember the blog I found about it 🙂

However I don't think the performance difference is of any significance. This is mostly about satisfying static analysis, else all of the static analysis tools have to get a condition in for not checking for static functions in pest tests

**Comment by owenvoke** [comment]
Sounds good. 👍🏻 Thanks for the info.

**Comment by nunomaduro** [comment]
I've no plans on working on this. Feel free to submit a pull request.
