### ISSUE TITLE
How to go about using Laravel Models

### ISSUE THREAD

**Issue by mikeerickson** [pestphp/pest#21]
Just trying to do something like

```php
<?php

it("should retrieve model data", function () {
    $data = \App\User::all();
    assertTrue($data);
});
```

Throws the following

```
1) /Users/mikee/Documents/code/xxx/tests/Unit/PestTest.php::it test model
  Error: Call to a member function connection() on null
```

**Comment by nunomaduro** [comment]
As specified on the guide: https://pestphp.com/docs/guides/laravel/.

If you want to use your Laravel applications within your unit tests, you will need to adapt your `Pest.php` file with something like this:

```php
uses(Tests\TestCase::class)->in('Feature', 'Unit');

```
