### ISSUE TITLE
Add CI flag for disallowing ->only()

### ISSUE THREAD

**Issue by nmokkenstorm** [pestphp/pest#210]
Hello all,

I've run into an issue where I'm working on an application using TDD with PestPHP one test at a time using `only()`, and then forget to take out the `only()` before commit & push. It'd be nice if there would be a flag like `--ci` that disallows using this option to use during CI.

I'd love to hear any thoughts on the matter.

**Comment by nunomaduro** [comment]
No plans for this. Thank you for the proposal.
