### ISSUE TITLE
Dusk environment handling is not supported

### ISSUE THREAD

**Issue by clmntgr** [pestphp/pest#212]
When running dusk test with pest the [environment handling](https://laravel.com/docs/8.x/dusk#environment-handling) feature of dusk is not supported.

This is a problem because the dev server still run with the `.env` file and not with env values from `phpunit.xml` or `.env.dusk.XXX`.

I've created a repo [here](https://github.com/clmntgr/pest-with-dusk) where I reproduce the issue, you can follow the commit but I'm just following the docs.

I don't know how to fix this, maybe moving the environment handle feature from the dusk command to the `DuskTestCase` class (not even sure it's possible), or allowing dusk to execute `pest` instead of `phpunit` [here](https://github.com/laravel/dusk/blob/6.x/src/Console/DuskCommand.php#L97)

**Comment by nunomaduro** [comment]
Can you make a pull request into Pest that adds a DuskCommand that overrides the binary protected method: https://github.com/laravel/dusk/blob/97910000b4cd9cce6b3887791ede0cf78108f971/src/Console/DuskCommand.php#L91?

**Comment by clmntgr** [comment]
Yes but I will have to add dusk as a dependency, is it ok?

**Comment by nunomaduro** [comment]
It doesn't have too. You can add that command only if class exists.

**Comment by clmntgr** [comment]
Ok didn't know that. I will try something this week so

**Comment by nunomaduro** [comment]
I've no plans on working on this. Feel free to submit the pull request you were talking about.
