### ISSUE TITLE
Support for Phpunit 9.4.0

### ISSUE THREAD

**Issue by marvinhosea** [pestphp/pest#214]
```pestphp/pest v0.3.9 requires phpunit/phpunit >= 9.3.7 <= 9.4.1 -> found phpunit/phpunit[9.3.7, ..., 9.4.1] but the package is fixed to 9.4.2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command```

**Comment by nunomaduro** [comment]
Fixed.
