### ISSUE TITLE
Problem with phpunit 9.4.3

### ISSUE THREAD

**Issue by KuenzelIT** [pestphp/pest#218]
Just tried to install pest:

Problem 1
    - Installation request for pestphp/pest ^0.3.11 -> satisfiable by pestphp/pest[v0.3.11].
    - Conclusion: remove phpunit/phpunit 9.4.3
    - Conclusion: don't install phpunit/phpunit 9.4.3
    - pestphp/pest v0.3.11 requires phpunit/phpunit >= 9.3.7 <= 9.4.2 -> satisfiable by phpunit/phpunit[9.3.10, 9.3.11, 9.4.0, 9.4.1, 9.4.2].

Is there a reason why pest is limited to 9.4.2?

Thanks!

**Comment by owenvoke** [comment]
Yeah, the reasoning is that it uses internal PHPUnit classes that don't have a backwards compatibility guarantee. I've opened a PR for this and then we can release a new patch version.

**Comment by owenvoke** [comment]
You should now be able to use v0.3.12, let me know if you have any issues. 👍🏻
