### ISSUE TITLE
"The class `Tests\TestCase` was not found." - on CI (Docker)

### ISSUE THREAD

**Issue by Enaah** [pestphp/pest#220]
Hi there,

so here's my situation:

* I wanted to convert my PHPUnit Tests to Pest
* I'm on a fresh laravel/breeze Installation 
* On **my Mac** everything runs correctly, but **on CI** (GitLab Runner, with Docker Executor (image: `edbizarro/gitlab-ci-pipeline-php:7.4`)), it fails

### What I did to debug:

1. Used `php artisan test` instead of `./vendor/bin/pest`
2. I did all the commands to debug:
    ```
    php artisan clear
    php artisan cache:clear
    php artisan config:clear
    composer dump-autoload
    ```
    even did a fresh cloning of the repo.  
3. removed all test but one example test

### Screenshots/Errors

_CI with `./vendor/bin/pest`_
![Bildschirmfoto 2020-11-18 um 12 38 32](https://user-images.githubusercontent.com/10073766/99532180-2b22ac00-29a4-11eb-845c-b5acffc865b9.png)

_local with `./vendor/bin/pest`_
![Bildschirmfoto 2020-11-18 um 12 43 53](https://user-images.githubusercontent.com/10073766/99532295-5a391d80-29a4-11eb-9441-265344e10483.png)

_CI with `php artisan test`_
![Bildschirmfoto 2020-11-18 um 12 55 26](https://user-images.githubusercontent.com/10073766/99532247-4988a780-29a4-11eb-95a2-d6404a730309.png)

_local with `php artisan test`_
![Bildschirmfoto 2020-11-18 um 12 43 38](https://user-images.githubusercontent.com/10073766/99532304-5c02e100-29a4-11eb-9b7e-4c73a5998bd0.png)

_CI with **PHPUnit**_ (before Pest was used)
![Bildschirmfoto 2020-11-18 um 13 10 38](https://user-images.githubusercontent.com/10073766/99532472-a6845d80-29a4-11eb-985a-578ec3873344.png)

_local with **PHPUnit**_ (before Pest was used)
![Bildschirmfoto 2020-11-18 um 13 03 09](https://user-images.githubusercontent.com/10073766/99532427-953b5100-29a4-11eb-819f-e0a2b6ccbbfa.png)

### File-contents

**`tests\Pest.php`**
```php
<?php

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

// Uses the given test case and trait in the current folder recursively
uses(TestCase::class, RefreshDatabase::class)->in(__DIR__);
```

**`tests\TestCase.php`**
```php
<?php

namespace Tests;

use Illuminate\Foundation\Testing\TestCase as BaseTestCase;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;
}
```

**`tests\Helpers.php`**
```php
<?php

namespace Tests;

use Illuminate\Contracts\Auth\Authenticatable;

/**
 * A basic assert example.
 */
function assertExample(): void
{
    test()->assertTrue(true);
}


function actingAs(Authenticatable $user, string $driver = null)
{
    return test()->actingAs($user, $driver);
}
```

**`tests\CreateApplication.php`**
```php
<?php

namespace Tests;

use Illuminate\Contracts\Console\Kernel;

trait CreatesApplication
{
    /**
     * Creates the application.
     *
     * @return \Illuminate\Foundation\Application
     */
    public function createApplication()
    {
        $app = require __DIR__.'/../bootstrap/app.php';

        $app->make(Kernel::class)->bootstrap();

        return $app;
    }
}
```

**`tests\Unit\ExampleTest.php`**
```php
<?php

test('basic', function () {
    assertTrue(true);
});
```

**`tests\CreateApplication.php`**
```php
<?php

namespace Tests;

use Illuminate\Contracts\Console\Kernel;

trait CreatesApplication
{
    /**
     * Creates the application.
     *
     * @return \Illuminate\Foundation\Application
     */
    public function createApplication()
    {
        $app = require __DIR__.'/../bootstrap/app.php';

        $app->make(Kernel::class)->bootstrap();

        return $app;
    }
}
```

**`tests\Unit\ExceptionTest.php`**
```php
<?php

it('throws exception', function () {
    throw new Exception('Something happened.');
})->throws(Exception::class, 'Something happened.');

```

Do I miss anything?

Went through the docs 2 times and couldn't find anything.

Thanks in advance!

**Comment by octoper** [comment]
@Enaah Have you installed Pest for Laravel correctly?

**Comment by Enaah** [comment]
I hope so.

Pulled it via composer and did `php artisan pest:install`.
It was working on my computer, but CI did not want to work. 

Will try it again, later.

**Comment by Enaah** [comment]
Found the error... it was me. As usual.

Sorry for disturbance and thanks for this project 💐
