### ISSUE TITLE
Abstract Test Cases

### ISSUE THREAD

**Issue by ksassnowski** [pestphp/pest#222]
Related to [this](https://twitter.com/warsh33p/status/1330757668449947649) Twitter thread.

## What am I trying to do?

I'm looking for a way to implement contract tests in pest. In a contract test, all common test cases are defined in either an abstract class or a trait. This class/trait then defines a few abstract methods that you need to implement in the test file of your implementation.

Then, in the test file for your implementation, you would either `extend` or `use` this contract tests trait/class.

Here's how I would do it in PHPUnit.

```php
/** @mixin TestCase */
trait WorkflowManagerContractTests
{
    abstract protected function getManagerInstance(): WorkflowManagerInterface;

    /** @test */
    public function it_calls_the_before_create_hook_if_it_exists(): void
    {
        $manager = $this->getManagerInstance();

        $actual = $manager->doTheThing();

        $this->assertEquals('::result::', $actual);
    }
}
```

Then in the test file for my implementation I would include this trait and implement the abstract method.

```php
class WorkflowManagerTest extends TestCase
{
    use WorkflowManagerContractTest;

    protected function getManagerInstance(): WorkflowManagerInterface
    {
        return new WorkflowManager(Bus::fake());
    }
}
```

So the problem is that I have a trait that defines both abstract methods _and_ PHPUnit style tests. I can't seem to get this combination to work in Pest.

**Comment by nunomaduro** [comment]
@ksassnowski Did you manage to solve this problem?

**Comment by nunomaduro** [comment]
Please re-open this issue, if you didn't found a solution for this issue.
