### ISSUE TITLE
Missing PHPStan extension

### ISSUE THREAD

**Issue by olivernybroe** [pestphp/pest#225]
Right now Pest and PHPStan does not work well together.

For making PHPStan understand Pest I think we would have to create a custom PHPStan extension.
https://phpstan.org/developing-extensions/extension-types

**Comment by canvural** [comment]
I'd like to help with this one. What kind of code is not understood by PHPStan currently?

**Comment by olivernybroe** [comment]
@canvural Awesome! Our larastan master!

The first error I get, which will prob. yield a bunch of other errors afterwards is that phpstan does not understand `$this` inside the test closure.
![image](https://user-images.githubusercontent.com/5870441/100993682-00188a80-3556-11eb-8abb-e95eb0942f04.png)

**Comment by olivernybroe** [comment]
Oh, so we might have to open an issue in PHPStan so we can extend that part also?

**Comment by canvural** [comment]
There are already open issues in PHPStan for this. But this kind of code is really hard for static analysis tools to understand. So I don't think it'll be solved.

Yeah, we can add `Undefined variable: $this` to the `ignoreErrors` to ignore it.

Also, can you share the whole code snippet for this?

**Comment by olivernybroe** [comment]
Yeah, we are also having some problems with some of this in Phpstorm.

Sure. 

```php
test('example', function() {
    $this->assertEquals("yes", "yes");
});
```

**Comment by canvural** [comment]
Oh, I realized my previous solution (with `@var`) also does not work: https://phpstan.org/r/12bb6ed2-f253-48e6-9016-fb51e48ac1e4 I guess it needs to be in class scope or in `Closure::bind` for PHPStan to understand.

[This](https://phpstan.org/r/8b590bdc-b6ff-4830-b933-e137533cff8c) works. But this way all the `$this` usages in this file will be bound to `TestCase` I don't know if this is good or not.

So the best way, for now, is to advise users to ignore this error or tell to use the solution above 😕

**Comment by olivernybroe** [comment]
damn :( 

Yeah, the problem is we also have support for `uses` to include other class methods into `this`. so binding it to `TestCase` won't work in all scenarios
https://pestphp.com/docs/underlying-test-case#overview


So sounds like the only thing we can do for now is ignore the error 😢

**Comment by nunomaduro** [comment]
Well, I guess we will have to wait until someone wants to put some work on this. But it's not a priority I think.

**Comment by olivernybroe** [comment]
@nunomaduro Agreed. For now adding a line into `ignoreErrors` is the best we can do. 

No reason to have an issue open which we can't work on as long as phpstan does not have support for it correctly.

**Comment by tlaverdure** [comment]
Is this a hack, or is this a possible solution? 🤔 

```php
test('example', function () {
    test()->assertEquals("yes", "yes");
});
```
