### ISSUE TITLE
Coverage not found on Linux/Mac with Xdebug on PHP 7.3/7.4

### ISSUE THREAD

**Issue by owenvoke** [pestphp/pest#226]
This issue was flagged up by @Awilum on Discord.

I had originally thought it was to do with #180 or #13, however the coverage whitelist is correct (and it works correctly with PCov, and Xdebug on Linux).

I think it's related to using Xdebug in Windows/Mac :thinking: 

With PCov it works correctly:
https://github.com/owenvoke/pest-coverage-test/actions/runs/384962899

With Xdebug it fails on Mac and Windows:
https://github.com/owenvoke/pest-coverage-test/actions/runs/384976791

I've never actually used Xdebug on CI because I've found it to be a lot slower, so probably why I've never noticed this. :thinking:

---

For reference, my Xdebug versions are as follows:
- Local Windows dev environment: Xdebug v2.9.2
- CI Linux environment: Xdebug v3.0.0RC2-dev (selected by Ubuntu on GitHub Actions)
- CI macOS environment: Xdebug v3.0.0
- CI Windows environment: Xdebug v3.0.0

~~I haven't tested on macOS locally with Xdebug as I don't want to have to set it up~~, but if anyone has this issue on local macOS, let us know.

I've now tested with Xdebug v3.0.0 on macOS local (in exactly the same setup), and it works fine. 😕

It also does not appear to be a problem when running Pest with coverage against the [Code Coverage plugin](https://github.com/owenvoke/pest-plugin-coverage/actions/runs/385289715).

---

Just noticed, it may also be failing on Linux, just can't tell because it's correctly installing Xdebug 2. I think that this whole issue should (in theory) be resolved by using https://github.com/owenvoke/setup-php/commit/e18908477c27fede95b85898d79168f09ae136a1. 🤔 This is demonstrated by [the passing test suite here](https://github.com/owenvoke/pest-coverage-test/actions/runs/385538259), however I'm not sure if this has any negative effects on older PHP versions.

**Comment by owenvoke** [comment]
This should be resolved with the next release of Setup PHP. 👍🏻 https://github.com/shivammathur/setup-php/commit/fce77afe731878e3b29f245b23a49bca0c3c245c

**Comment by nunomaduro** [comment]
Seems be related to: https://github.com/sebastianbergmann/phpunit/issues/4526.

**Comment by nunomaduro** [comment]
Confirmed. Seems to be related with the issue above. Let's wait.

**Comment by owenvoke** [comment]
This issue is now resolved on GitHub Actions after v2.9.0 of Setup PHP. 👍🏻 I guess that env variable issue is separate, but might be worth tracking in the upstream issue.

**Comment by owenvoke** [comment]
Looks like that upstream issue is now resolved. 👍🏻
