### ISSUE TITLE
Depends breaks test class inheritance

### ISSUE THREAD

**Issue by avrahamappel** [pestphp/pest#230]
Hi guys, I'm really enjoying Pest so far!

I'm not sure if this is related to #213 and #216 or not, but I'm having an issue with Eloquent model factories. When I use a factory in a normal test, it works fine. However, if there are any tests in the file which depend on other tests, every test fails with an `InvalidArgumentException : Unable to locate factory for [App\User].`

Here's an example:
```php
<?php

use App\User;

it('is the first test', function () {
    $this->user = factory(User::class)->make();
    $this->assertTrue(true);

    return true;
});

// If I remove this test, it works fine.
it('depends on the first test', function ($arg) {
    $this->assertTrue($arg);
})->depends('it is the first test');
```

I've also noticed that if I add `dump(get_parent_class($this))` in one of the tests, it prints `"PHPUnit\Framework\TestCase"`, whereas if I remove the depends test, it prints `"Tests\TestCase"`.

I didn't have an issue until I upgraded from 0.2 to 0.3.

PS I'm still on Laravel 7, so I'm still using file-based factories. I haven't tested with Laravel 8 class-based factories.

**Comment by nunomaduro** [comment]
cc @nuernbergerA

**Comment by nuernbergerA** [comment]
Will take a look at it today.

**Comment by nuernbergerA** [comment]
@nunomaduro thats what i found after some research:
`TestCaseFactory::makeClassFromFilename()` runs before `TestRepository::build()` therefor the generated class hasn't the proper `$baseClass` set

**Comment by nunomaduro** [comment]
@avrahamappel Can you make a pull request that adds a failing test? So we can work from there.

**Comment by avrahamappel** [comment]
Will do. Thanks for looking into this.
