### ISSUE TITLE
PhpStorm throws expression result is not used anywhere when using test() instead of it()

### ISSUE THREAD

**Issue by dingo-d** [pestphp/pest#235]
Not sure if this is a pest issue, PhpStorm issue, or what but when I use `test()` instead of `it()` my entire test gets underlined

![Screenshot 2020-12-05 at 10 47 57](https://user-images.githubusercontent.com/8638515/101239363-5cf77a80-36e7-11eb-9737-bc0156845bd2.png)

When I use `it()` everything is fine.

![Screenshot 2020-12-05 at 10 48 36](https://user-images.githubusercontent.com/8638515/101239381-726ca480-36e7-11eb-8e08-7b8b89fb8b45.png)

The test passes in both cases, either with `it()` or with `test()` used. The difference is only in the prepended `it`, which looks a bit odd in my case, which is why I opt for using the `test()` instead.

![Screenshot 2020-12-05 at 10 50 00](https://user-images.githubusercontent.com/8638515/101239413-a8aa2400-36e7-11eb-912f-91033fa44e17.png)

Any idea why this would happen? When I hover over `it()` it correctly picks up the signature and docblock from vendor file, but not for `test()` function 🤷🏼‍♂️ . Bizzare thing is that `it()` is just a wrapper around the `test()` function.

I'm on macOS 11.0.1 (BigSur), using PHP 7.4.13, and on PhpStorm 2020.3. Also, I have the pest plugin installed.

Dependency versions

```bash
pestphp/pest                                   v0.3.15            An elegant PHP Testing Framework.
pestphp/pest-plugin                            v0.3.0             The Pest plugin manager
pestphp/pest-plugin-coverage                   v0.3.0             The Pest Coverage Plugin
pestphp/pest-plugin-init                       v0.3.1             The Pest Init plugin

phpunit/php-code-coverage                      9.2.5              Library that provides collection, processing, and rendering functionality for PHP code ...
phpunit/php-file-iterator                      3.0.5              FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-invoker                            3.1.1              Invoke callables with a timeout
phpunit/php-text-template                      2.0.4              Simple template engine.
phpunit/php-timer                              5.0.3              Utility class for timing
phpunit/phpunit                                9.5.0              The PHP Unit Testing framework.
```

### EDIT

Ok, bizarre but if I use the `test` when testing exceptions, everything is fine.

![Screenshot 2020-12-05 at 11 02 18](https://user-images.githubusercontent.com/8638515/101239629-5bc74d00-36e9-11eb-9862-f4457d1b4a1d.png)

### EDIT 2

Ok, when I pass the dataset to the `test()` function it doesn't report the error. But without it shows the "not used anywhere" warning.

**Comment by nunomaduro** [comment]
cc @olivernybroe

**Comment by olivernybroe** [comment]
@dingo-d Just for future reference, this should have been posted on https://github.com/pestphp/pest-intellij/ instead, as it is related to our phpstorm integration.

What you are experiencing is an inspection in phpstorm telling you that the result is not used, so your code is doing nothing, which is not true.

If you press the 3 dots you should be able to edit the inspection, hence getting the name of it. If you could give me this, then we should be able to add in a condition to disable the inspection when in a pest test.

**Comment by dingo-d** [comment]
Sorry, wasn't aware it was related to a different project.

The inspection gives me this

```
Expression result is not used anywhere 
Inspection info: Reports expressions that are calculated, but the calculation result is not used anywhere.
Such errors can be caused, for example, by misspelling the = operator as ==.
```

**Comment by olivernybroe** [comment]
That would be great! 👍 Then we can keep this repo's issues more clean. 

So this is something we can fix in the plugin, just checked 👍 However as a temporary fix until someone actually fixes it in the plugin you can do the following.
![expression_disable](https://user-images.githubusercontent.com/5870441/101453694-09c43880-3930-11eb-92ea-aaf7b7376d8e.gif)

**Comment by owenvoke** [comment]
Was just going to say we could transfer the issue, but that's ok. 👍🏻

**Comment by olivernybroe** [comment]
@owenvoke Oh yeah, totally forgot that we can do that 👍
