### ISSUE TITLE
How can I run a seeder in beforeAll?

### ISSUE THREAD

**Issue by rishpandey** [pestphp/pest#237]
I have to seed some basic information that will be used by all tests in my test class.

Right now, I do something like this:
```
beforeEach(function () {
    $this->seed(FeedSeeder::class);
});
```

But doing this beforeEach test is slow. So it'd be great if I can something like this in beforeAll, but using $this or app() does not work here.

Any ideas?

**Comment by nunomaduro** [comment]
That's not possible at the moment.

**Comment by ilyavaiser** [comment]
Why is it closed? It is currently impossible to do setup tests in Laravel with Pest.  And this is a huge problem. I can't run common code for all tests in the context of a laravel application.

**Comment by SimonMacIntyre** [comment]
This is a major bummer, it seems like a fair ask and standard test flow to want to seed something before all tests, once, in this manner.

**Comment by netdjw** [comment]
+1

**Comment by booni3** [comment]
Shame about this. I was excited to start using pest but this is a deal breaker.

**Comment by booni3** [comment]
> This is a major bummer, it seems like a fair ask and standard test flow to want to seed something before all tests, once, in this manner. I cannot even use `beforeEach` for this without copying and pasting it into every single file that wants the same seed.

You can use before each, as persetup in Pest.php

```php
uses(
    Tests\TestCase::class,
    // Illuminate\Foundation\Testing\RefreshDatabase::class,
)
    ->beforeEach(fn() => $this->seed(\Database\Seeders\DatabaseSeeder::class))
    ->in('Feature');
```

But cannot use before all here, for seeing at least.

**Comment by husskade** [comment]
I don't think I'll be using Pest next time if this is not fixed. Not having one time setup is absurd.

**Comment by russellgalpin** [comment]
I ran into this problem today, and while not ideal, you can work around it by booting the application itself within the beforeAll() function. E.g. this is what I have for Laravel:

```php
uses(DuskTestCase::class)
    ->beforeAll(function () {
        $app = require_once __DIR__.'../../bootstrap/app.php';
        $kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
        $kernel->bootstrap();
        Artisan::call('db:seed');
    });
```

**Comment by theutz** [comment]
And, to make it even easier, you can wrap this in a helper function in your `tests/Pest.php` file:

```php
function bootstrapApp()
{
    $app = require_once __DIR__.'/../bootstrap/app.php';
    $kernel = $app->make(Kernel::class);
    $kernel->bootstrap();
}
```

Once there, you can call `bootstrapApp()` inside a dataset declaration, beforeAll, or whatever.

**Comment by giusepetroso** [comment]
I don't know if this could be a good workaround but I manage to seed using the `protected $seed` property.

First i created a new class file near `TestCase.php` class, I called it `TestCaseWithSeed.php`:

```php
<?php

namespace Tests;

use Illuminate\Foundation\Testing\RefreshDatabase;

abstract class TestCaseWithSeed extends TestCase
{
    use RefreshDatabase;

    protected $seed = true;
}
```

Then into `Pest.php` file instead of using `TestCase` class I used the newly created one.
```php
uses(
    Tests\TestCaseWithSeed::class,
    // Tests\TestCase::class,
    // Illuminate\Foundation\Testing\RefreshDatabase::class,
)->in('Feature');
```

You can actually edit `TestCase.php` but I preferred to extend it instead of changing it.

Hope it helps.

**Comment by michabbb** [comment]
hi everyone in this thread. i want to ask: what is the "state of the art" way of:

- doing a "one-time migration" including seeding "before" running all tests 

this approach (https://github.com/pestphp/pest/issues/237#issuecomment-1424197814) is working, but not really pretty.

thanks.

**Comment by espenlg** [comment]
I'm afraid this is a deal-breaker for me as well ;( I would love to be able to seed the DB once, instead of before every test. At the moment I'm dropping 19 tables and import a new SQL in addition to creating entries with factory for every test. Even though it works it's bad for performance.

**Comment by ivaralink0407** [comment]
u can do in Pest.php

```
uses(TestCase::class)->beforeAll(function () {
    shell_exec('php artisan migrate:fresh --seed');
})->in('Feature');
```

or any artisan command you need

**Comment by abrahamgreyson** [comment]
@ivaralink0407 In many systems, exec is disabled

**Comment by kavanbsf** [comment]
If you want to prepare data or execute code before running the test suite, you can use this simple technique:

`Custom Technique:`
Create a test file named `AA00.php` inside `tests/Feature`. The alphabetical naming ensures this file runs first, before any other test executes.

You can write any global setup logic inside this file, such as seeding data, initializing configurations, or running necessary commands.

**Comment by netdjw** [comment]
It seems to me a little dirty and hard-to-maintain way.

With this solution you build in your project a very unpredictable working path what every developer should to know, but nobody knows this way. I think this is the opposite of Laravel's nice, clean and smooth coding style.

**Comment by michabbb** [comment]
"dirty" is the situation we are forced into to find a way for something that should exist in the first place and is a crucial part when it comes to testing. The fact that nuno ignored that completely in the first place is some kind of crazy 🙈 we should be thankful for every tip that finds its way to this thread 😏

**Comment by netdjw** [comment]
> "dirty" is the situation we are forced into to find a way for something that should exist in the first place and is a crucial part when it comes to testing. The fact that nuno ignored that completely in the first place is some kind of crazy 🙈 we should be thankful for every tip that finds its way to this thread 😏

You're right about that this isn't a clean situation, but the idea of database filling up with test data (actually they're real data) with seeder isn't sounding so stupid thing. We create datas in many cases with factories. This is the same just in different color of grey.

**Comment by charlesgetup** [comment]
I am using `"pestphp/pest": "^3.8"` and today I found the `beforeAll` and `afterAll` are still not working in `Pest.php` file, only `beforeEach` and `afterEach` work. I have set them up according to the document. In `beforeAll` function, I want to start the Swoole server, and this could not be done in `beforeEach` and shut it down in `afterEach`. If I do that, the tests will run super slow. I am still looking for a solution.

`UnitTestCase.php` file

```
<?php

namespace Tests;

use PHPUnit\Framework\TestCase as BaseTestCase;

abstract class UnitTestCase extends BaseTestCase
{
}
```

`Pest.php` file

```
pest()->extend(Tests\UnitTestCase::class)->beforeAll(function () {
    error_log('Not working');
})->beforeEach(function () {
    error_log('Working');
})->afterEach(function () {
    error_log('Working');
})->afterAll(function () {
    error_log('Not working');
})->in('Unit');
```

**Comment by inglucifer83** [comment]
I also had the need to start from the same point before all tests, meaning a database in a certain state to perform tests on and thus assert results. After a little thinking I realised that a simple workaround would be a basic shell script and that worked pretty good for me. Don't know how dirty this is, it seems fine to me and surely does its job. The simple script could looks something like this:

```
#!/bin/bash

set -e

echo "Dumping main DB..."
mysqldump -u {user} -p{}password {original-db} > {dump-name}.sql
mysql -h localhost --port {port} -u{user} -p{password} -e "CREATE DATABASE IF NOT EXISTS \`{dump-name}\`"
mysql -h localhost --port {port} -u {user} -p{pasword} {dump-name} < {dump-name}.sql
echo "Removing main sql dump..."
rm {dump-name}.sql
echo "Running tests..."
./vendor/bin/pest
```

I obviously do this on my local machine and always dump the current database, but the same thing can be done without dumping each time and using always the same sql dump... just run ./test.sh and everything works as expected...
