### ISSUE TITLE
Is it necessary to display the dataset it self?

### ISSUE THREAD

**Issue by Ilyes512** [pestphp/pest#238]
So I going to use this as an example:

```php
<?php

declare(strict_types=1);

it('uses data from a dataset', function ($name) {
    expect($name)->toBeString();
})->with([
    'set1' => ['name' => 'hello'],
    'set2' => ['name' => 'bye'],
    'set3' => ['name' => ['oeps' => 'a array']],
]);
```

When you run this `./vendor/bin/pest` without any arguments... I get the following output:

```
> pest 'tests/FoobarTest.php'

   FAIL  Tests\FoobarTest
  ✓ it uses data from a dataset with data set "set1" ('hello')
  ✓ it uses data from a dataset with data set "set2" ('bye')
  ⨯ it uses data from a dataset with data set "set3" (array('a array'))
```

For simple datasets this might not be a problem, but with a larger set it gets rather messy really quick ie

`✓ it accepts eloquent models with data set "with_keyname_id" (array(1, 'a', 'b'), 'id', 'int', true, array('1', array('a', 'b')))`

I also notice that the message is malformed when setting `testdox="true"` in phpunit.xml:

```
PHPUnit 9.5.0 by Sebastian Bergmann and contributors.

Foobar (P\Tests\Foobar)
 ✔ It uses data from a dataset with data set "set 1" ('hello') with 
 ✔ It uses data from a dataset with data set "set 2" ('bye') with 
 ```
 
 Notice that it say `with` twice.

**Comment by nunomaduro** [comment]
You can do something like this:

```php
foreach($dataset as $data) {
    test('...', ...)
};
```

**Comment by Ilyes512** [comment]
Hmm, I was hoping for another way of "fixing" this. I found the line responsible for outputting it: https://github.com/pestphp/pest/blob/master/src/Datasets.php#L116 But no easy way of overwriting it... do I really need to fork it :/

Anyway, thanks for you time.

**Comment by nunomaduro** [comment]
You can propose something about this. 👍🏻

**Comment by Ilyes512** [comment]
Well the easiest would be to update `getDataSetDescription` to something like:

```php
   /**
     * @param int|string        $key
     * @param array<int, mixed> $data
     */
    private static function getDataSetDescription($key, array $data): string
    {
        $nameInsert = is_string($key) ? \sprintf('data set "%s" ', $key) : '';

        return \sprintf(' with %s', $nameInsert);
    }
    ```

I just don't see the point of displaying the data it self in the report. But that is just my opinion of course.

**Comment by owenvoke** [comment]
If you change it to that, it ends up without any description of the dataset. So it'd just be `with `, I think it's good to show the dataset, but I wonder if for anything with more than `x` number of entries, it'd just show `array(...) #1`, `array(...) #2` or something. 🤷🏻

**Comment by Ilyes512** [comment]
You could only show the structure when the dataset has not description:

```php
    private static function getDataSetDescription($key, array $data): string
    {
        if (is_int($key)) {
            return \sprintf(' with (%s)', (new Exporter())->shortenedRecursiveExport($data));
        }

        return \sprintf(' with data set "%s"', $key);
    }
```

Output:

```
  ✓ it uses data from a dataset with a description with data set "set1"
  ✓ it uses data from a dataset with a description with data set "set2"
  ⨯ it uses data from a dataset with a description with data set "set3"
  ✓ it uses data from a dataset witout a description with ('hello')
  ✓ it uses data from a dataset witout a description with ('bye')
  ⨯ it uses data from a dataset witout a description with (array('a array'))
```

Or create a "description" based on the numeric index:

```php
    private static function getDataSetDescription($key, array $data): string
    {
        $key = is_int($key) ? \sprintf("#%s", $key + 1) : $key;
        $nameInsert = \sprintf('data set "%s" ', $key);

        return \sprintf(' with %s', $nameInsert);
    }
```

Output:

```
   FAIL  Tests\FoobarTest
  ✓ it uses data from a dataset with a description with data set "set1" 
  ✓ it uses data from a dataset with a description with data set "set2" 
  ⨯ it uses data from a dataset with a description with data set "set3" 
  ✓ it uses data from a dataset witout a description with data set "#1" 
  ✓ it uses data from a dataset witout a description with data set "#2" 
  ⨯ it uses data from a dataset witout a description with data set "#3" 
```

Of a combination:

```php
    private static function getDataSetDescription($key, array $data): string
    {
        if (is_int($key)) {
            return \sprintf(' with data set "#%u" (%s)', $key + 1, (new Exporter())->shortenedRecursiveExport($data));
        }

        return \sprintf(' with data set "%s"', $key);
    }
```

Ouput:

```
   FAIL  Tests\FoobarTest
  ✓ it uses data from a dataset with a description with data set "set1"
  ✓ it uses data from a dataset with a description with data set "set2"
  ⨯ it uses data from a dataset with a description with data set "set3"
  ✓ it uses data from a dataset witout a description with data set "#1" ('hello')
  ✓ it uses data from a dataset witout a description with data set "#2" ('bye')
  ⨯ it uses data from a dataset witout a description with data set "#3" (array('a array'))
```

I used the below tests for the outputs:

```php
it('uses data from a dataset with a description', function ($name) {
    expect($name)->toBeString();
})->with([
    'set1' => ['name' => 'hello'],
    'set2' => ['name' => 'bye'],
    'set3' => ['name' => ['oeps' => 'a array']],
]);

it('uses data from a dataset witout a description', function ($name) {
    expect($name)->toBeString();
})->with([
    ['name' => 'hello'],
    ['name' => 'bye'],
    ['name' => ['oeps' => 'a array']],
]);
```

**Comment by owenvoke** [comment]
That's true, I think when there is a description, that should definitely be used over the dataset structure. 👍🏻

**Comment by Ilyes512** [comment]
So... how to continue? Want me to create a PR?

(BTW, Closing a non-resolved (at least for me) issue also doesn't really help)

**Comment by nunomaduro** [comment]
@owenvoke I didn't follow this discussion, should I re-open this? There is an issue here?

**Comment by AlexMartinFR** [comment]
It's an enhancement more than an actual issue imho.

Good to have but not blocking for 1.0 👍

**Comment by benswinburne** [comment]
I use datasets to get copies of valid data etc for a test mostly and use faker to generate it. I also often augment the dataset with perhaps the field i'm testing,

i.e. let's say a campaign requires a name and a description and then there are optional fields, if use `->with('campaign')` i know I'm going to get a name and a description, but I'm testing another field like `start_date` for example, so my payload is `$dataset + ['start_date' => $start_date]`

```
when updating a campaign, I cannot change the team with (array('e-enable distributed infomediaries', 'Qui eos quia quibusdam sit cu...ribus.'))
```

My test runs are full of useless information as a result of not being able to turn this off.

 - You'll notice the description is truncated (so i wouldn't be able to utilise this data to recreate a failed test)
 - The data i'm actually changing/that i care about comes from within the test and is therefore absent in the test description. (The dataset is just so i know i've got a set of passing fields for this model to lean on while I test something relevant)

Whilst it is pretty inconsequential and doesn't harm my test runs, during my search I discovered this issue and thought I'd share my use case in the hope that an option to disable it may come about at some point.

**Comment by fabio-ivona** [comment]
@nunomaduro and @AlexMartinFR  I'd like to propose a pull request to implement this enhancement, but it is closed since January

is there any issue about this? or can I PR to change 

```
private static function getDataSetDescription($key, array $data): string    {        
    $exporter = new Exporter();
    $nameInsert = is_string($key) ? \sprintf('data set "%s" ', $key) : '';
    return \sprintf(' with %s(%s)', $nameInsert, $exporter-&gt;shortenedRecursiveExport($data));    
}
```

to 

```
 private static function getDataSetDescription($key, array $data): string
  {
      if (is_int($key)) {
          return \sprintf(' with (%s)', (new Exporter())->shortenedRecursiveExport($data));
      }

       return \sprintf(' with data set "%s"', $key);
}
```

?

if I've read well this @owenvoke 's  answer 

> That's true, I think when there is a description, that should definitely be used over the dataset structure. 👍🏻

it seem to be a good enhancement (It will surely be for my tests)
