### ISSUE TITLE
Docs 404 hit => https://pestphp.com/docs/guides/pest-from-scratch#installation

### ISSUE THREAD

**Issue by authanram** [pestphp/pest#242]
Hey buddy, i've hit a 404 while browsing the docs.

**It can be reproduced this way:**
1. open https://pestphp.com/docs/installation (or any other docs route)
2. search for "helpers"
3. click the docs search hit title "a  tests/Helpers.php file"
4. hit

![Screenshot 2020-12-28 at 01 50 54](https://user-images.githubusercontent.com/1874088/103182925-62dc1800-48af-11eb-9bf4-13a4fc6a9972.png)

Hope it helps. Just reported it, because i couldn't found a matching issue.

_PS: PEST ❤️ ❤️ ❤️  ... x1000 times 😄  👍_

**Comment by owenvoke** [comment]
Yeah, the guides no longer exist and it looks like Algolia hasn't refreshed properly. 🤔 I'm not sure how long it usually takes.

**Comment by authanram** [comment]
> Yeah, the guides no longer exist and it looks like Algolia hasn't refreshed properly. 🤔 I'm not sure how long it usually takes.

Actually, I just wanted to confess my love. 🤪 

Should i close it? What do you think? For me it sounds like the issue is not necessary, in this case.

**Comment by nunomaduro** [comment]
Algolia will refresh the search eventually. Yesterday we made some work on the docs.
