### ISSUE TITLE
InvalidUsesPath exception in every command

### ISSUE THREAD

**Issue by R4c00n** [pestphp/pest#243]
Hi, I would love to play around with Pest a little bit, but unfortunately I get a `InvalidUsesPath` exception with every command, even with `./vendor/bin/pest --init`.
```
Pest\Exceptions\InvalidUsesPath

The path `/path/to/my/project/tests` is not valid.
```

I tried to install it into an existing project with existing PHPUnit tests.

Am I missing some step or configuration?

**Steps to reproduce:**
```
$ composer require pestphp/pest --dev
$ ./vendor/bin/pest --init
```

**Environment:**
- OS: macOS Mojave
- PHP version: 7.4.13
- Composer version: 1.10.19

**Comment by owenvoke** [comment]
What is your directory structure, and do you have any `uses()` calls in your `tests/Pest.php`? 🤔 Usually this happens when the `tests/` directory can't be found, or when you have a `uses(Foo::class)->in('dir')` with a non-existant directory.

**Comment by R4c00n** [comment]
Hi @owenvoke, thanks for the fast response :)
I don't have the Pest config yet, because the documentation says that this should be created by `./vendor/bin/pest --init`, which also fails with the same exception.
https://pestphp.com/docs/installation

**Comment by R4c00n** [comment]
Ah never mind, I just saw that I mixed up the installation docs and https://pestphp.com/docs/cli-options. In the CLI options docs it reads like it would create the tests directory with the --init option. The Installation docs say that I need to create it manually. 
As soon as I create the tests directory, the --init command works :)

**Comment by owenvoke** [comment]
Ah, no problem. 👍🏻 We could probably do with updating the docs to make it clearer that the `tests/` directory won't be automatically created, or update it to create the `tests/` directory automatically.
