### ISSUE TITLE
[Feature] Command create Dusk test

### ISSUE THREAD

**Issue by gpibarra** [pestphp/pest#244]
There is a `--unit` parameter to create a test in testSuite Unit.
Can you add a `--dusk` parameter to create a test in folder Browser?
It would be a stub like this.
```php
<?php

use Laravel\Dusk\Browser;

it('has {name} page', function () {
    $this->browse(function (Browser $browser) {
        $browser->visit('/{name}')
            ->assertSee({name});
    });
});
```
Instead of the parameters `--unit` and` --dusk` it could be called as `--testSuite unit` and `--testSuite browser`.
Additionally, if new testSuites are defined in "phpunit.xml", tests cannot be created directly. I understand that this already escapes Pest and if you want to create tests in those TestSuites they must be created manually.

**Comment by owenvoke** [comment]
I quite like the simplicity of the `--unit` / `--dusk` flags over the `--testSuite x` format. 👍🏻

This would be a neat feature to have (in my opinion). Feel free to open a PR with it if @nunomaduro agrees. 🥳
