### ISSUE TITLE
[Bug] Github actions are not working properly for plugins

### ISSUE THREAD

**Issue by karol-dabrowski** [pestphp/pest#248]
The issue affects pull requests and branches with names other than 'master'. [This pull request](https://github.com/pestphp/pest-plugin-expectations/pull/2) can serve as an example. This is due to the dependency requirements of the core Pest library towards version of plugins. Version generated by GitHub actions for pull requests don't satisfy requirement.
![obraz](https://user-images.githubusercontent.com/34897174/103462580-7dd2e000-4d26-11eb-9136-5f0376252193.png)

The solution I come with is to specify explicitly the version of the module in composer.json file. It solves the problem. I created [this pull request](https://github.com/pestphp/pest-plugin-expectations/pull/3) few minutes ago with added version and it passed all checks.

The very same issue will probably show up in _pestphp/pest-plugin_, _pestphp/pest-plugin-coverage_, _pestphp/pest-plugin-expectations_ and _pestphp/pest-plugin-init_ plugins. I can also create pull requests for them if the solution is accepted.

**Comment by owenvoke** [comment]
Using the `version` key in the `composer.json` isn't recommended by the Composer devs if using VCS as far as I can tell. It's probably easier to use the `COMPOSER_ROOT_VERSION` env in CI. :+1: This is what I was using while testing the Coverage plugin using:
https://github.com/marketplace/actions/composer-root-version-action

**Comment by nunomaduro** [comment]
@owenvoke Can you make a pull request on that?

**Comment by karol-dabrowski** [comment]
Thank you for answers. I closed my pull requests. Also I checked the solution linked by @owenvoke and it works perfectly fine for linux instances, but not for MacOs and Windows ones. I googled a bit and it's a common issue.
![obraz](https://user-images.githubusercontent.com/34897174/103479483-3738c080-4dce-11eb-9336-ffdb1df7d344.png)
Then I created a branch with tests on linux instances only ([this branch](https://github.com/karol-dabrowski/pest-plugin-expectations/tree/linux_ci)) and it works.

I also tested hardcoding env variable in workflow YAMLs like @owenvoke did [here](https://github.com/owenvoke/pest-plugin-coverage/commit/20f9cead064a168c984a6e6461308691ced305ff) and it also works ([this branch](https://github.com/karol-dabrowski/pest-plugin-expectations/tree/hardcoded_composer_root_version)).

If the last solution is ok for you @nunomaduro and @owenvoke I can create a new pull request.

**Comment by owenvoke** [comment]
Ah, that's a fair point. I think I removed that as I was hoping to not need to update them in every repository (using the action is automatic), however if it only works on Linux then that's an issue. 😬 We'd only have to update it on major version bumps anyway (if we set it to `0.3.x-dev`, or `1.x-dev` when stable).

**Comment by karol-dabrowski** [comment]
Thank you. I am gonna open PRs soon :)

**Comment by karol-dabrowski** [comment]
@owenvoke you were faster. I was going to do it today after work.

**Comment by owenvoke** [comment]
@karol-dabrowski, apologies, I needed the change for another PR I was going to submit and ended up doing it for those 3 affected repositories.
