### ISSUE TITLE
Idea: set the minimum code coverage target value in a config file

### ISSUE THREAD

**Issue by AlexMartinFR** [pestphp/pest#25]
**Problem:**
Every time you want to check your code coverage, you have to repeat the `--min=70` command line option.

**Suggestion:**
This target value should be set once per project in a config file:
- It would save a few keystrokes / lighten the cognitive load of remembering the syntax
- Every collaborator would be on the same page
- It wouldn't prevent revising the target later on

It could be set in a configuration file in the project, and then read every time we run `pest --coverage`.
Candidate for hosting this value:
- phpunit.xml
- pest.php

**Comment by nunomaduro** [comment]
No plans to have this.
