### ISSUE TITLE
Incorrect `Pest\Expectation` phpDoc

### ISSUE THREAD

**Issue by MatanYadaev** [pestphp/pest#250]
If I'm not mistaken, the correct type should be `Pest\Expectations\Expectation`.

It does not lead to any issue in the code, but my IDE is confused:

```php
// PHPStorm: Method 'toBe' not found in Pest\Expectation 
it('asserts true to be true')->expect(true)->toBe(true);
```

https://github.com/pestphp/pest/blob/b0f03c278db30bfe9a146827c651b719acf6f02b/src/PendingObjects/TestCall.php#L15

**Comment by nunomaduro** [comment]
Can you make a pull request to fix this? Thanks!
