### ISSUE TITLE
Access level to Pest\Concerns\TestCase::setUp() must be public (as in class Tests\TestCase)

### ISSUE THREAD

**Issue by imran-itmajlis** [pestphp/pest#254]
When I am adding setUp function in base TestCase.php below error is showing

and without setUp function it is working fine

![image](https://user-images.githubusercontent.com/68069779/104089328-21c30b00-5294-11eb-80f2-9d1a1a9f9b80.png)

**Comment by owenvoke** [comment]
`setUp()` should be a protected function rather than public. 👍🏻

**Comment by imran-itmajlis** [comment]
> `setUp()` should be a protected function rather than public. 👍🏻

Thanks Now Working

**Comment by owenvoke** [comment]
That's great @imran-itmajlis. 👍🏻
