### ISSUE TITLE
Conflicting functions with same name in different test file

### ISSUE THREAD

**Issue by albertpratomo** [pestphp/pest#257]
I have 2 helper functions with the same name in 2 different test files. When running the tests, I got:
```
Cannot redeclare [helper]() (previously declared in /var/www/html/...)
```

A possible solution to this is by namespacing the test file. But I think the idea of Pest is that we don't have to namespace our tests.

Perhaps we can add functions to the underlying test case? I don't mind having to call `$this->helper()`..

**Comment by danilopolani** [comment]
You can try putting them in the `beforeAll()` I guess, but you won't have the autocomplete and it could be a "dirty" solution, something like

```php
beforeAll(function () {
  $this->helper = function ($arg) { ... }
});

test('my test', function () {
  $this->helper(...);
});
```

**Comment by nunomaduro** [comment]
@albertpratomo Maybe use a "specific" name that describes what the helper using doing?
