### ISSUE TITLE
"Plugin initialization failed" on installation

### ISSUE THREAD

**Issue by Johnathan** [pestphp/pest#258]
Having issues just getting pest installed, `composer require...` output below.

**Composer version 2.0.8 2020-12-03 17:20:38
PHP 7.4.10 (cli) (built: Sep  9 2020 06:36:14) ( NTS )**

```
 php -d memory_limit=-1 $(which composer) require pestphp/pest --dev --with-all-dependencies
Using version ^1.0 for pestphp/pest
./composer.json has been updated
Running composer update pestphp/pest --with-all-dependencies
Loading composer repositories with package information
Updating dependencies
Lock file operations: 5 installs, 12 updates, 8 removals
...
  - Locking pestphp/pest (v1.0.0)
  - Locking pestphp/pest-plugin (v1.0.0)
  - Locking pestphp/pest-plugin-coverage (v1.0.0)
  - Locking pestphp/pest-plugin-expectations (v1.0.1)
  - Locking pestphp/pest-plugin-init (v1.0.0)
...
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 5 installs, 12 updates, 0 removals
  - Installing pestphp/pest-plugin (v1.0.0): Extracting archive
Plugin initialization failed (include(/home/vagrant/code/PROJECTNAME/backend/vendor/pestphp/pest-plugin/src/Manager.php): failed to open stream: No such file or directory), uninstalling plugin
  - Removing pestphp/pest-plugin (v1.0.0)
    Install of pestphp/pest-plugin failed

Installation failed, reverting ./composer.json and ./composer.lock to their original content.


  [RuntimeException]
  Could not delete /home/vagrant/code/PROJECTNAME/backend/vendor/pestphp/pest-plugin/.temp:


require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--no-scripts] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>]...
```

**Comment by octoper** [comment]
Hmm this is weird... cc @owenvoke

**Comment by owenvoke** [comment]
Are you installing this on a project that already had Pest (less than 1.x) installed? Or would you be able to provide an example of the repository?

I should be able to test this later, but I can't think of any reason that `.temp` would be created inside the `pest-plugin` package (I thought it was only used in the coverage plugin).

**Comment by Johnathan** [comment]
Hey, nope, haven't installed pest before. My project is based on this repository https://github.com/1707-Industries/greenfield-backend

Trying to install pest there results in the same problem.

**Comment by octoper** [comment]
@Johnathan I tried to reproduce the issue but it's working just fine for me.

**Comment by owenvoke** [comment]
I wasn't able to replicate this either. 🤔 https://asciinema.org/a/2bNcyYNvYJZlm2P0uOAGxzqxg

Could you try just removing the entire `vendor` directory, and re-running the install?

**Comment by Johnathan** [comment]
Hmm that's odd. I tried removing `vendor` and installing again. Obviously seems to be something up with my homestead setup.

Thanks both for looking into it so quickly. I'll update the issue if I get anywhere.

**Comment by Johnathan** [comment]
No further trying to get it installed from inside the homestead container but I was able to install it ok from the host machine, so that'll do for now until I work out what's wrong with homestead.

Thanks again for the help @octoper and @owenvoke

**Comment by owenvoke** [comment]
I'll have a look into this as well, I personally don't use Homestead. But it would definitely be good to resolve this if it's an issue with Pest in Vagrant or something.
