### ISSUE TITLE
Phar version?

### ISSUE THREAD

**Issue by Pierstoval** [pestphp/pest#26]
I wish there could be a scoped-phar version of Pest, to allow downloading in a blink of an eye without having to check anything on the current project, and without pest having compatibility issues with PHPUnit, nor the need for PHPUnit by the way.

PHPUnit has a scoped phar since version 8.1, and it has a special list of scripts to generate this scoped phar: https://github.com/sebastianbergmann/phpunit/tree/master/build/scripts

There's more documentation on how to achieve this there:

- https://github.com/sebastianbergmann/phpunit/issues/2015
- https://github.com/sebastianbergmann/phpunit/pull/3086
- https://github.com/sebastianbergmann/phpunit/pull/3575

I hope this helps :)

I really wanted to contribute on this specific point, but I'm sadly completely overwhelmed by work and really tough personal issues, and I don't want to work on something I might not have time to do 😞

**Comment by nunomaduro** [comment]
No plans to have this.

**Comment by owenvoke** [comment]
I started working on this the other day, and it's kind of complicated due to the way the test generation is done. 👍🏻 I've pushed up what I had so far to this branch if you're interested.

https://github.com/owenvoke/pest/tree/feature/phar

**Comment by agarzon** [comment]
Most useful PHP tools in the world comes with PHAR files: composer, codeception, phpmd, deployer, robo, phpcpd, phpcs, phpunit, psysh, php-cs-fixer, and a long etc.... just saying.

**Comment by owenvoke** [comment]
I'm going to try and take another look at this, as I too think it would be beneficial. 👍🏻

**Comment by leocavalcante** [comment]
Pest is now the only one tool without a corresponding PHAR at https://github.com/opencodeco/phpctl

**Comment by owenvoke** [comment]
@leocavalcante, feel free to open a PR with support for building a PHAR. 👍🏻

**Comment by KorvinSzanto** [comment]
Can this be reopened since it's something that would be accepted?
