### ISSUE TITLE
Use Models inside tests

### ISSUE THREAD

**Issue by mgarcia96** [pestphp/pest#260]
Hi there!

Can I use foreach inside tests? Like this:

```
foreach (Role::all() as $role) {

    test("{$role->name} can login", function () use($role) {

        $user = factory(User::class)->create([
            'name' => $role->name,
            'email' => Str::slug($role->name) . "@example.com",
            'password' => Hash::make('secret'),
        ]);
        $user->assignRole($role->name);

        $this->actingAs($user);

        $response = $this->post('/login', [
            'email' => $user->email,
            'password' => Hash::make('secret'),
        ]);

        $response->assertStatus(200);
    });

}
```

It throws me error:

![image](https://user-images.githubusercontent.com/6561770/104894561-2747e180-5975-11eb-972a-d874f8c2f858.png)

**Comment by octoper** [comment]
Hey!
No but you can take a look at Datasets here [https://pestphp.com/docs/datasets](https://pestphp.com/docs/datasets), create a dataset for your roles and you will be fine!

**Comment by mgarcia96** [comment]
Hi @octoper ! I made a dataset, but still getting the same error:

```
dataset('users', function() {
    $users = [];
    foreach (Role::all() as $role) {

        $user = factory(User::class)->create([
            'name' => $role->name,
            'email' => Str::slug($role->name) . "@example.com",
            'password' => Hash::make('secret'),
        ]);
        $user->assignRole($role->name);

        $this->actingAs($user);

        $users[] = $user;
    }

    return $users;
});
```

**Comment by octoper** [comment]
Oh don't need a return in datasets remove the return with `yield`

**Comment by mgarcia96** [comment]
@octoper  Same, the problem is when I use the "Role" or other model:

```
dataset('users', function() {
    foreach (Role::all() as $role) {

        $user = factory(User::class)->create([
            'name' => $role->name,
            'email' => Str::slug($role->name) . "@example.com",
            'password' => Hash::make('secret'),
        ]);
        $user->assignRole($role->name);

        $this->actingAs($user);

        yield $user;
    }
});
```

**Line 9 is the   foreach (Role::all() as $role) line**
 
![image](https://user-images.githubusercontent.com/6561770/104898161-8a3b7780-5979-11eb-9072-eccffc9fa00e.png)

**Comment by owenvoke** [comment]
Is `Role` a model? If so, it can't be used in a dataset or before a test has been instantiated as the framework hasn't been booted.

**Comment by mgarcia96** [comment]
@octoper Yep, it's **Spatie\Permission\Models\Role**.

So how can I do this? I can't get items from DB via Models?

**Comment by mgarcia96** [comment]
Okay, I solved this adding these lines in **Pest.php**. Perhaps there is a better solution, but this works for me:

```
$app = require __DIR__.'/../bootstrap/app.php';
$app->make('Illuminate\Contracts\Console\Kernel')->bootstrap();
```
