### ISSUE TITLE
Add support for PHPUnit 10

### ISSUE THREAD

**Issue by owenvoke** [pestphp/pest#262]
There is an upcoming major version bump for PHPUnit. This seems to contain some breaking changes that affect Pest.

- [Docs for v10](https://phpunit.readthedocs.io/en/latest)
- [Branch for v10](https://github.com/sebastianbergmann/phpunit/tree/master)
- [Changelog for v10](https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-10.0.md)
- [Diff for v10](https://github.com/sebastianbergmann/phpunit/compare/9.5...master)

----

### Current issues

- **[Custom `TestSuiteLoader` deprecation](https://github.com/sebastianbergmann/phpunit/pull/4531)**
   I think that this is now indirectly causing issues as it now seems to expect any selected file in the testsuite directory to contain a PHP class. So if the testsuite directory is set to `tests/` and `suffix=".php"` (as per our current suite), it tries loading all files that are pascal case as a class. This means that `tests/Autoload.php` is loaded as a class, as are all the datasets, etc.
   
   This basically means that all Pest-syntax tests will fail, as they don't contain a class in the files. 😬

**Comment by nunomaduro** [comment]
Closing in favour of #263
