### ISSUE TITLE
How we can define faker locale globally for test cases instead of writing in every function

### ISSUE THREAD

**Issue by imran-itmajlis** [pestphp/pest#264]
![image](https://user-images.githubusercontent.com/68069779/106390035-7168a280-640c-11eb-8546-1399b11a8808.png)

**Comment by nunomaduro** [comment]
You will need to create an issue on the faker repository.

**Comment by owenvoke** [comment]
@nunomaduro, not really sure if this is a Faker issue. It's an issue with the Pest Faker plugin. We don't have issues enabled on any of our plugin repos though.

I think we could maybe include an empty class that has a static variable and we'd just do something like:
```php
Pest\Faker\Faker::setDefaultLocale('en_GB');
```
