### ISSUE TITLE
Idea: loading pest.php, helpers and datasets from another directory

### ISSUE THREAD

**Issue by jeroenf-avg** [pestphp/pest#27]
Hi! Right now, it looks like the Pest.php & Helpers.php have to be in the "/tests" directory for them to load. What if my projects tests are not in "/tests", but in another directory, configured through the phpunit.xml file? 

Ideally, I would like to have the Pest.php, Helpers.php, Datasets, etc in the root of my own tests directory. Because they feel (especially the helpers & datasets) as part of my test files.

Is there a clean way to do this?

**Comment by nunomaduro** [comment]
Yeah - Pest assumes that your Test suite haves a certain structure. Today, I am not sure you can have something like that.

**Comment by nunomaduro** [comment]
No plans on working on this at the moment.
