### ISSUE TITLE
Coverage not found in path: ...\vendor\pestphp\.temp\coverage.php

### ISSUE THREAD

**Issue by jonorozcoc** [pestphp/pest#272]
- Issue: Coverage not found in path: D:\projects\sani\sani-media-service\vendor\pestphp\.temp\coverage.php.
- PHP version: 8.0.1
- Operating system: WINNT

  at D:\projects\sani\sani-media-service\vendor\pestphp\pest\src\Exceptions\ShouldNotHappen.php:38
     34▕      * Creates a new instance of should not happen without a specific exception.
     35▕      */
     36▕     public static function fromMessage(string $message): ShouldNotHappen
     37▕     {
  ➜  38▕         return new ShouldNotHappen(new Exception($message));
     39▕     }
     40▕ }
     41▕

  1   D:\projects\sani\sani-media-service\vendor\pestphp\pest-plugin-coverage\src\Coverage.php:48
      Pest\Exceptions\ShouldNotHappen::fromMessage("Coverage not found in path: D:\projects\sani\sani-media-service\vendor\pestphp\.temp\coverage.php.")

  2   D:\projects\sani\sani-media-service\vendor\pestphp\pest-plugin-coverage\src\Plugin.php:104
      Pest\PluginCoverage\Coverage::report(Object(Symfony\Component\Console\Output\ConsoleOutput))

I'm using Lumen

**Comment by nunomaduro** [comment]
What coverage driver are you using?

**Comment by jonorozcoc** [comment]
XDebug

**Comment by nunomaduro** [comment]
I guess you need to pass the `XDEBUG_MODE=coverage` option before the command itself.

**Comment by jonorozcoc** [comment]
I have Coverage mode on php.ini

![image](https://user-images.githubusercontent.com/8442497/108008190-ccce8f00-6fcd-11eb-9279-43e39ab214a9.png)

**Comment by nunomaduro** [comment]
@jonorozcoc You will need to debug this.

**Comment by jonorozcoc** [comment]
@nunomaduro seems to be something related with Lumen. I tried with a blank Laravel project and it worked as expected. I'll research about it
