### ISSUE TITLE
Pest output duplicated per test, except for filter with exact match

### ISSUE THREAD

**Issue by odinns** [pestphp/pest#273]
I am seeing a weird output in a project where I am using pest, and which has a mixture of normal phpunit as well as pest tests.

Example output: (these are both phpunit tests)

![image](https://user-images.githubusercontent.com/10807424/108518446-dc4d2100-72c8-11eb-87e1-976398cfa6f9.png)

I have verified (using a line of logging), that the test is in fact only run once.

If I filter and there is only one match, then the test shows output only once.

![image](https://user-images.githubusercontent.com/10807424/108518692-20402600-72c9-11eb-8451-20c35da87771.png)

I don't know where to look for a cause of this phenomena, so I hope you can help with directions where the cause might be. 

Unfortunately I am not able to create a simple reproducible case, as this is in a very large project with hundreds of tests and a complicated test setup.

Pest version: 1.x, but this has been an issue in every version I used almost since it came out.

**Comment by danilopolani** [comment]
I cannot reproduce that, but maybe posting your `Pest.php`, `TestCase.php` (if used) and `phpunit.xml` could help (?)

**Comment by nunomaduro** [comment]
@odinns Please create a OSS repository where we can reproduce the issue first.
