### ISSUE TITLE
error when running pest

### ISSUE THREAD

**Issue by nivpenso** [pestphp/pest#274]
Hi I use PEST but I encounter a weird error when trying to run the tests

```
# input
php ./vendor/bin/pest

# ouptut
   PASS  Tests\ExampleTest
  ✓ example

  Tests:  1 passed
  Time:   0.04s


   TypeError 

  Return value of Pest\Console\Command::run() must be of the type int, none returned

  at vendor/pestphp/pest/src/Console/Command.php:143
    139▕             $result = $plugin->addOutput($result);
    140▕         }
    141▕ 
    142▕         exit($result);
  ➜ 143▕     }
    144▕ 
    145▕     protected function showHelp(): void
    146▕     {
    147▕         /** @var Version $version */
```

Looking into the code there is an `exit($result)` command on line 142, when changing the exit command to `return $result` everything works fine. Is there something I do wrong?

**Comment by owenvoke** [comment]
Please could you give some details about your environment? PHP version, Pest version, OS, etc? 👍🏻 I'm unable to replicate this issue on PHP 7.4 or PHP 8 on macOS Big Sur.

**Comment by nivpenso** [comment]
sure!
OS: Linux Ubuntu 20.04.2 LTS (Focal Fossa)
Pest version: 1.0.2
phpunit version: 9.5.2
PHP Version: 7.4.3

**Comment by nivpenso** [comment]
According to the 2nd scenario described [here](https://www.php.net/manual/en/class.typeerror.php) it seems you must return value of the correct type when declaring a function return type

> There are three scenarios where a TypeError may be thrown. The first is where the argument type being passed to a function does not match its corresponding declared parameter type. The second is where a value being returned from a function does not match the declared function return type. The third is where an invalid number of arguments are passed to a built-in PHP function (strict mode only).

**Comment by owenvoke** [comment]
Hmm. It looks like the same thing is used in PHPUnit core: https://github.com/sebastianbergmann/phpunit/blob/9.5/src/TextUI/Command.php#L156 However, they also have a return below.

I wouldn't have thought this would cause any issues in Pest because nothing is ever returned due to the `exit()` call. 🤔

**Comment by nivpenso** [comment]
Agree that this is strange behavior.

I created this script on my local
```php
<?php
function foo() : int {
        $result = 1;
        echo "before exit". PHP_EOL;
        exit($result);
        echo "after exit";
        return $result;
}

foo();
```

this is the output:
```
before exit
after exit
```

when I commented out the `return $result` it throws the TypeError 
```php
<?php
function foo() : int {
        $result = 1;
        echo "before exit" . PHP_EOL;
        exit($result);
        echo "after exit";
//      return $result;
}

foo();
```

output:
`Uncaught TypeError: Return value of foo() must be of the type int, none returned in ...`

When I'm checking both scripts online using [PHP sandbox](https://sandbox.onlinephpfunctions.com/) the output is
```
before exit
```
and no exception is being thrown for both cases

**Comment by owenvoke** [comment]
That's really weird, sounds like it's not actually exiting (and is continuing the process) when `exit()` is called. 🤔 Which shouldn't be possible.

I copied the exact code you used, and my output is `before exit` in both scenarios.

**Comment by nivpenso** [comment]
Ok after trying to reproduce it with docker I found that the problem is caused by `ext-uopz`. I assume it affects the `exit()` function and therefore, the exception thrown

**Comment by owenvoke** [comment]
Ah, interesting. Looking at the [docs for that extension](https://www.php.net/manual/en/function.uopz-allow-exit.php) it says the following:
>  By default uopz disables the exit opcode, so exit() calls are practically ignored. uopz_allow_exit() allows to control this behavior.
