### ISSUE TITLE
Does tests dir required?

### ISSUE THREAD

**Issue by antonmedv** [pestphp/pest#276]
Upgraded to v0.3.19 and got this message:
```
composer test
> pest

   Pest\Exceptions\InvalidUsesPath

  The path `/Users/anton/dev/deployer/tests` is not valid.
Script pest handling the test event returned with error code 1
```

My tests in `test` dir, adding empty `tests` helps. Is it a bug?

**Comment by owenvoke** [comment]
Currently Pest only supports a `tests` directory. Just a quick note as well, the latest Pest version is 1.x so you may want to update from 0.3. 👍🏻

**Comment by antonmedv** [comment]
Got it. For better DX more meaningful error message is preferable. Without issue I was not able to understand it.

**Comment by antonmedv** [comment]
v0.3 was working with "test" dir.  It's a bummer not any more(. And it's painful to rename dir in deployer as project quite big. =(

**Comment by owenvoke** [comment]
I'm surprised that the `test` directory worked in `v0.3` 🤔 I didn't think we supported that ever.

**Comment by antonmedv** [comment]
It worked for sure 😄
