### ISSUE TITLE
Running with --coverage throws ShouldNotHappen exception

### ISSUE THREAD

**Issue by GeeH** [pestphp/pest#277]
Pest\Exceptions\ShouldNotHappen

This should not happen - please create an new issue here: https://github.com/pestphp/pest.

- Issue: Coverage not found in path: /Users/ghockin/www/twilio-wrapper/vendor/pestphp/.temp/coverage.php.
- PHP version: 8.0.2
- Operating system: Darwin

  at vendor/pestphp/pest/src/Exceptions/ShouldNotHappen.php:38
     34▕      * Creates a new instance of should not happen without a specific exception.
     35▕      */
     36▕     public static function fromMessage(string $message): ShouldNotHappen
     37▕     {
  ➜  38▕         return new ShouldNotHappen(new Exception($message));
     39▕     }
     40▕ }
     41▕

**Comment by GeeH** [comment]
The `.temp` folder doesn't exist in the location mentioned above. I'm running
 - PHP 8.0.2
 - Pest 1.19.0
 - Xdebug 3.1.0-dev

My Xdebug seems to be the dev build, I can run again against 3.0.3 latest release if you think it might help?

**Comment by nunomaduro** [comment]
You need to activate the XDEBUG coverage mode.

Try this: `XDEBUG_MODE=coverage ./vendor/bin/pest`.

**Comment by GeeH** [comment]
Awesome, thanks @nunomaduro -- would you like a PR to the docs to include this potential gotcha?

**Comment by nunomaduro** [comment]
@GeeH Yes please. 👍🏻

cc @owenvoke Did we made any progress on having this detected on the code actually?

**Comment by owenvoke** [comment]
Not yet, but I was going to have a look into it later if I can.
