### ISSUE TITLE
Idea: Higher Order Tests - handle null returns

### ISSUE THREAD

**Issue by fetzi** [pestphp/pest#28]
When chaining multiple higher order methods it can happen, that one assertion does not return the target instance and simply returns null or nothing.

For example

```php
it('exposes the plugin class via composer.json')
    ->assertArrayHasKey('extra', $data)
    ->assertArrayHasKey('pest', $data['extra']);
```

does not work because `assertArrayHasKey` returns null. So the second assertion breaks.

The idea would be to keep the initial target and reuse it when a chain method does not return a value.

```php
    public function chain(object $target): void
    {
        $originalTarget = $target;

        foreach ($this->messages as $message) {
            $target = $message->call($target);

            if ($target === null) {
                $target = $originalTarget;
            }
        }
    }
```

What do you think?

**Comment by nunomaduro** [comment]
@fetzi that would cause troubles in implementations like this:

```php
it('has a welcome page'))->get('/')->assertSee('Laravel');
```

**Comment by nunomaduro** [comment]
Haaaaaaa. Just when `target` === null ?

**Comment by nunomaduro** [comment]
Sounds good, can you make a pull request with tests on that?
