### ISSUE TITLE
Laravel 6 (LTS) Support

### ISSUE THREAD

**Issue by tpetry** [pestphp/pest#286]
The `pest-plugin-laravel` laravel plugin in its current form only supports Laravel versions `^7.0 || ^8.0` due to the specifications in the `composer.json`. However, until 6 months from now (September 2021) Laravel 6 will be the latest LTS version. The exclusion of an LTS version is quite questionable, because in some companies the rule is to use only LTS releases.

**Comment by owenvoke** [comment]
Feel free to PR this, I've done a test to see how quick this would be to implement.

Commit with necessary changes: https://github.com/owenvoke/pest-plugin-laravel/commit/2259b5feba7e8ee48fef5cbdbc2e2762e62b2a3d
Workflow run: https://github.com/owenvoke/pest-plugin-laravel/runs/2276896113

---

It looks like there is currently a conflict with our use of the `symfony/var-dumper` package at 5.x for dev tools, whereas Laravel 6 requires 4.x, I'm not sure what specifically we use from 5.x though. We could probably add 4.x to the [`pestphp/pest-dev-tools`](https://github.com/pestphp/pest-dev-tools/blob/master/composer.json#L24) package, but I'll leave this for @nunomaduro to decide whether he wants to maintain additional compatibility.

**Comment by nunomaduro** [comment]
No plans to support the LTS version, sorry.

**Comment by tpetry** [comment]
Ok, so i will keep PHPUnit 🤷‍♂️
