### ISSUE TITLE
Forwarding to global functions might not work

### ISSUE THREAD

**Issue by felixdorn** [pestphp/pest#298]
Hey!

I've commited those 3 lines https://github.com/pestphp/pest/commit/278af4b8354f8209cc258823bb155cadf8ea195d which made possible to forward an undefined method in the test suite to a global function with the same name.

I've noticed a while ago that `tests/Helpers.php` was created with a Helpers namespace which would break this neat feature.
However, it seems like the `tests/Helpers.php` file is no longer included in neither of the `pest:install` command or `pest --init`. 

I could PR a fix that also checks if the function exists in the `Helpers` namespace and/or any namespace but I'm not sure this is even a bug considering the file has been removed.

Let me know if there is something I can do.

**Comment by nunomaduro** [comment]
We no longer have a `Helpers.php`.
