### ISSUE TITLE
Should `toHaveKey()` use AssertSame by default?

### ISSUE THREAD

**Issue by stancl** [pestphp/pest#299]
Right now, `->toBe()` uses `AssertEquals` and `->toHaveKey()` uses `AssertSame`.

I see why one might want to use `AssertEquals` here, but maybe for consistency they should be the same? If a "to be" assertion is strict, then the "to have a key that **is** ..." should also be strict IMO.

Maybe there should be a third argument, `$strict = true`.

https://github.com/pestphp/pest-plugin-expectations/blob/master/src/Expectation.php#L457-L472

**Comment by nunomaduro** [comment]
Sure - can you make a PR?

**Comment by nunomaduro** [comment]
No plans to make a `strict` assertion there at this time.
