### ISSUE TITLE
RefreshDatabase not working as expected

### ISSUE THREAD

**Issue by martin-ro** [pestphp/pest#301]
Hi all,

I `use(RefreshDatabase::class)->('Feature')` in `Pest.php` but data persist between different tests. Did I set it up wrong? For example `Feature/FirstTest.php` I create a few models and they still exist in the DB in `Feature/SecondTest.php` while I was expecting the database to be wiped in between!?

**Comment by alexgarrett** [comment]
Is this the actual code you're using?

`use(RefreshDatabase::class)->('Feature');` should be `uses(RefreshDatabase::class)->in('Feature');`

**Comment by martin-ro** [comment]
Hi,

no, must been a copy paste error. Here is the actual code:

```php
uses(
    TestCase::class,
    RefreshDatabase::class,
    NovaResourceTest::class,
    NovaAssertions::class,
    InteractsWithViews::class
)->in('Feature');

uses(DuskTestCase::class)->in('Browser');
```

**Comment by nunomaduro** [comment]
I am sorry - but this must be something related to your environment/setup. I've used this trait in hundreds of **Pest** projects. And I've seen this issue before.
