### ISSUE TITLE
Facade validator class has not been set.

### ISSUE THREAD

**Issue by amrography** [pestphp/pest#304]
I am getting an error : `A facade root has not been set.` while trying to create new Validator from Facade. Also, creating new instance using `app('validator)` didn't work.

![Screenshot 2021-05-31 at 20 44 04](https://user-images.githubusercontent.com/9614340/120231185-2b540c00-c251-11eb-8332-fc5ebb66c361.png)

![Screenshot 2021-05-31 at 20 44 30](https://user-images.githubusercontent.com/9614340/120231189-2db66600-c251-11eb-9d4d-6d5b68c05255.png)

**Comment by nunomaduro** [comment]
You test need to `uses(TestCase::class)` being this class a test case from LaraveL.

**Comment by amrography** [comment]
@nunomaduro Thanks for your quick reply. I updated my `Pest.php` file to be like following and it's running! Thank you.

```php
uses(Tests\TestCase::class)->in('Unit');
uses(Tests\TestCase::class)->in('Feature');
```
