### ISSUE TITLE
Requirements unsatisfied for PHPUnit 9.5.5

### ISSUE THREAD

**Issue by bigint** [pestphp/pest#309]
<img width="1037" alt="Screenshot 2021-06-05 at 6 51 32 PM" src="https://user-images.githubusercontent.com/69431456/120893126-1ef3f880-c62f-11eb-98f4-924472ca6941.png">

/cc @nunomaduro

**Comment by owenvoke** [comment]
Thanks for this, feel free to open a PR updating the Composer constraints and I'll merge it. 👍🏻
https://github.com/pestphp/pest/blob/master/composer.json#L26

**Comment by bigint** [comment]
Done @owenvoke https://github.com/pestphp/pest/pull/310
