### ISSUE TITLE
Getting Unknown option "--init"

### ISSUE THREAD

**Issue by marufmax** [pestphp/pest#311]
Hi, 
I am very new to PEST. Not sure if this is an issue or not. I am getting _Unknown option "init"_  when I am trying to initialize pest to my project. 
NB: I am not using Laravel. 

From my console:
```
root@4c4d13c45483:/public_html/tests# ./vendor/bin/pest --init
PHPUnit 9.5.5 by Sebastian Bergmann and contributors.

Unknown option "--init"
root@4c4d13c45483:/public_html/tests# 
```

**PHP version:** 7.4
**PEST version:** 1.3
Composer version: 2.1.1

Thanks

**Comment by thinkverse** [comment]
Seems it's calling `phpunit` instead of `pest`, make sure the path to the `pest` bin is correct. If you're doing `./vendor/bin/pest` then that should be done from the root folder where `/vendor` lives, i.e.

```bash
/src
/tests
/vendor
composer.json
```

**Comment by marufmax** [comment]
yea, I think so. But I'd tried executing  `/public_html/vendor/bin/pest` too but no luck. Getting same Unknown option "--init"

**Comment by nunomaduro** [comment]
This doesn't seems a code issue.
