### ISSUE TITLE
Re-merge `pest-plugin-coverage`, `pest-plugin-expectations`, `pest-plugin-init`

### ISSUE THREAD

**Issue by nunomaduro** [pestphp/pest#316]
I don't think we've made a good decision on splitting `pest-plugin-coverage`, `pest-plugin-expectations`, `pest-plugin-init` to its own package. The goal of this issue, is merge the code again in this repository.

**Comment by owenvoke** [comment]
I kind of think `expectations` is quite nice as a separate plugin. That means you can use it with PHPUnit as well if you wanted. The others I think would be good to merge. 👍🏻

I'm happy to help merge all 3 though.

**Comment by nunomaduro** [comment]
@owenvoke I think is quite nice - but we don't need it personally.

**Comment by owenvoke** [comment]
Cool, that's fine. 👍🏻 I've opened a PR for the init plugin part of this issue: https://github.com/pestphp/pest/pull/317

**Comment by nunomaduro** [comment]
Feel free to merge everything if you are confident on those pull requests... We will run a test when everything is ready.

**Comment by Ilyes512** [comment]
Wow... really don't like this move. I really liked `pestphp/pest-plugin-expectations` as a separate package. I guess I will just add `pestphp/pest` instead and only use the expectations as I do now.

(Above is just a personal "preference" :) just needed to get it out.)
