### ISSUE TITLE
Significantly slower than PHPUnit?

### ISSUE THREAD

**Issue by davidrans** [pestphp/pest#327]
PHPUnit (2 seconds)
---
```
▶  XDEBUG_MODE=off ./vendor/bin/phpunit Tests/Unit
PHPUnit 9.5.5 by Sebastian Bergmann and contributors.

.............................................................   61 / 1043 (  5%)
.............................................................  122 / 1043 ( 11%)
.............................................................  183 / 1043 ( 17%)
.............................................................  244 / 1043 ( 23%)
.............................................................  305 / 1043 ( 29%)
.............................................................  366 / 1043 ( 35%)
.............................................................  427 / 1043 ( 40%)
.............................................................  488 / 1043 ( 46%)
.............................................................  549 / 1043 ( 52%)
.............................................................  610 / 1043 ( 58%)
.............................................................  671 / 1043 ( 64%)
.............................................................  732 / 1043 ( 70%)
.............................................................  793 / 1043 ( 76%)
.............................................................  854 / 1043 ( 81%)
.............................................................  915 / 1043 ( 87%)
.............................................................  976 / 1043 ( 93%)
............................................................. 1037 / 1043 ( 99%)
......                                                        1043 / 1043 (100%)

Time: 00:02.078, Memory: 80.50 MB

OK (1043 tests, 22036 assertions)

```

Pest (58 seconds)
---
```
▶  XDEBUG_MODE=off ./vendor/bin/pest --test-directory=Tests Tests/Unit
                                                                            
... (lots of pretty output) ...

 Tests:  1043 passed
 Time:   58.35s
```

I was considering using pest as our default test runner for our PHPUnit test suite, because of the much improved output, but when running a series of fast unit tests, using vanilla PHPUnit seems to be an order of magnitude faster.

Is this a known tradeoff of using Pest vs. PHPUnit, or am I doing something wrong?

**Comment by owenvoke** [comment]
I think this is probably due to the use of `usleep()` in Collision (https://github.com/nunomaduro/collision/issues/160).

**Comment by nunomaduro** [comment]
We should create a printer that is not that verbose.

**Comment by davidrans** [comment]
Is there an option to provide our own printer to Pest?

**Comment by owenvoke** [comment]
@davidrans, yes. You can use the `--printer [PrinterClassName]` option. 👍🏻

**Comment by jj-meyer** [comment]
You're able to use the default PHPUnit ResultPrinter `--printer "PHPUnit\TextUI\DefaultResultPrinter" --testdox` as a workaround. It speeds up test runs significantly while providing feedback in the `testdox` format, which is somewhat similar, though not a pretty as `NunoMaduro\Collision\Adapters\Phpunit\Style`.

**Comment by tpetry** [comment]
> We should create a printer that is not that verbose.

Wouldn‘t batching the output do the same? The problem with many outputs is not the amount of text but the amount of (system) calls.

**Comment by jordanbrauer** [comment]
I also noticed this on a suite with thousands of tests. Doesn't really bother me though because I don't run full things locally.

What does `time` refer to? Is it the time it took to execute all tests, or the time it took to execute and print everything? If the former, wouldn't that mean that something else is also causing the slow down – such as how Pest loads things. What is memory usage difference?

**Comment by nunomaduro** [comment]
Try now.

**Comment by davidrans** [comment]
I tested on `v1.12.0` and it's faster than before:
![image](https://user-images.githubusercontent.com/806152/127414203-ef56a4dc-ead0-449b-adaf-52a0621a46dd.png)

But still 10x as slow as `phpunit`:
![image](https://user-images.githubusercontent.com/806152/127414225-315dc9ca-afa7-41b3-95f7-f2a38e85ec19.png)
