### ISSUE TITLE
Coverage not found in path ...

### ISSUE THREAD

**Issue by felipenaf** [pestphp/pest#334]
- Issue: Coverage not found in path: /var/www/html/vam/API/composer/vendor/pestphp/pest/.temp/coverage.php.
- PHP version: 7.4.20
- Operating system: Linux Mint 20
- environment variable: XDEBUG_MODE=coverage

![image](https://user-images.githubusercontent.com/31565912/123636457-446dbf80-d7f3-11eb-9d4c-d3977e0a8952.png)

**Comment by nunomaduro** [comment]
https://github.com/pestphp/pest/issues/277
