### ISSUE TITLE
Error: Using $this when not in object context

### ISSUE THREAD

**Issue by damms005** [pestphp/pest#347]
Pest    1.0.5
PHPUnit 9.5.4
PHP 8.0.8

I am getting the error:

```

  Using $this when not in object context

  at tests/Feature/HomepageRequestTest.php:7
      3  ▕ use App\Models\BookPublisher;
      4  ▕ 
      5  ▕ 
      6  ▕ beforeAll(function () {
    ➜ 7  ▕     $app = $this->createApplication();
      8  ▕     $app->seed();
      9  ▕ });
     10  ▕   
     11  ▕ it('loads homepage', function () {
```

The complete code for the test class is:
```
<?php

beforeAll(function () {
    $app = $this->createApplication();
    $app->seed();
});

it('loads homepage', function () {

    $response = $this->get('/');

    $response->assertStatus(200);
});
```

Content of Pest.php:
```

uses(Tests\TestCase::class, RefreshDatabase::class)->in('Feature');

uses(\Tests\DuskTestCase::class)->in('Browser');

uses()->group('unit')->in('Unit');
uses()->group('feature')->in('Feature');
uses()->group('browser')->in('Browser');
```

**Comment by damms005** [comment]
My aim is to be able to run migrations once for all the tests in `tests/Feature` and also seed the database once for all the tests in  `tests/Feature` folder. 

I tried below in `Pest.php`:
```
uses()
    ->beforeAll(function () {
        uses(RefreshDatabase::class);
    })
    ->in('Feature');
```
but got error `Call to undefined method Pest\PendingObjects\UsesCall::beforeAll()`.

It did not matter if I did `uses()->in(...)->beforeAll(...)` or `uses()->beforeAll(...)->in(...)`

**Comment by owenvoke** [comment]
You need to use `beforeEach()` rather than `beforeAll()` as `beforeAll()` is run before the class is instantiated.

**Comment by damms005** [comment]
> You need to use `beforeEach()` rather than `beforeAll()` as `beforeAll()` is run before the class is instantiated.

Using `beforeEach()` in `Pest.php` resulted in error: `Undefined method 'beforeEach'`.
Using `beforeEach()` in `HomepageRequestTest.php` is not my aim. I aim to run migrations and seed the database *once* for all the tests in `tests/Feature`

**Comment by damms005** [comment]
> Pest 1.0.5
> PHPUnit 9.5.4
> PHP 8.0.8
> 
> I am getting the error:
> 
> ```
> 
>   Using $this when not in object context
> 
>   at tests/Feature/HomepageRequestTest.php:7
>       3  ▕ use App\Models\BookPublisher;
>       4  ▕ 
>       5  ▕ 
>       6  ▕ beforeAll(function () {
>     ➜ 7  ▕     $app = $this->createApplication();
>       8  ▕     $app->seed();
>       9  ▕ });
>      10  ▕   
>      11  ▕ it('loads homepage', function () {
> ```
> 
> The complete code for the test class is:
> 
> ```
> <?php
> 
> beforeAll(function () {
>     $app = $this->createApplication();
>     $app->seed();
> });
> 
> it('loads homepage', function () {
> 
>     $response = $this->get('/');
> 
>     $response->assertStatus(200);
> });
> ```
> 
> Content of Pest.php:
> 
> ```
> 
> uses(Tests\TestCase::class, RefreshDatabase::class)->in('Feature');
> 
> uses(\Tests\DuskTestCase::class)->in('Browser');
> 
> uses()->group('unit')->in('Unit');
> uses()->group('feature')->in('Feature');
> uses()->group('browser')->in('Browser');
> ```

This was caused because `$this` is not bound in `beforeAll` call, but rather in `beforeEach` call. [Hopefully, this will be made clearer in the docs](https://github.com/pestphp/docs/pull/83)

**Comment by damms005** [comment]
> uses()
> 	->beforeEach(function () {
> 		uses(RefreshDatabase::class);
> 	})
> 	->in('Feature');

Well, this is what you get when you don't upgrade your composer dependencies. I was running this against:

> Pest 1.0.5
> PHPUnit 9.5.4
> PHP 8.0.8
