### ISSUE TITLE
Missing the team on the website

### ISSUE THREAD

**Issue by nunomaduro** [pestphp/pest#35]
At long term, I wanna pest to run on its own. Would be cool an page on the website ( like https://vuejs.org/v2/guide/team.html or better ) where people understand the different concerns of the project and the people involved on those concerns.

**Comment by nunomaduro** [comment]
The idea here is also see open positions. Example: Discord moderator, issue triage, etc.

**Comment by Kristories** [comment]
@nunomaduro I tried to make it, but I'm not sure if it fits?
![Screen Shot 2020-05-29 at 02 19 29](https://user-images.githubusercontent.com/774338/83184050-0d8e2b80-a153-11ea-8e48-bbf527db517d.png)

**Comment by nunomaduro** [comment]
I think you may need to sync with @AlexMartinFR and @octoper on this.

I think the most important I would just before that having the open positions.

**Comment by octoper** [comment]
@Kristories Can you make a make a fork and push what you made so far so I can help you

**Comment by Kristories** [comment]
@octoper hi, yes. Please check my [branch](https://github.com/Kristories/website/tree/feature/team)

**Comment by octoper** [comment]
Nice, I will check it as soon as possible @Kristories !

**Comment by octoper** [comment]
I have made some changes on @Kristories design.
Let me know what you think.

![image](https://user-images.githubusercontent.com/6823226/83217645-e6e0ec80-a174-11ea-8cbb-cb3ad642ca7c.png)

**Comment by nunomaduro** [comment]
@octoper I would replace the `CORE FOCUS` (and the links bellows )just by: Founder, UX Architect, Translator, and those.

**Comment by nunomaduro** [comment]
Ps, I am very fan of those page: https://elementary.io/team. But I trust you for the best decision on this one.

**Comment by owenvoke** [comment]
This is looking neat! Nice job.

**Comment by AlexMartinFR** [comment]
I like the idea of an horizontal list, showing multiple people per line on desktop, it brings a cooperation vibe 👍
(A vertical list evokes hierarchy imho)

Elementary.io keeps that vibe even on the smallest mobile: 

<img width="355" alt="Capture d’écran 2020-05-29 à 13 16 38" src="https://user-images.githubusercontent.com/19224681/83254256-c9c90f80-a1ae-11ea-9702-60f4506f3046.png">

So, for me, @Kristories 's grid layout, with @octoper 's design refactor and @nunomaduro 's idea regarding the role label would be dope 🔥

**Comment by nunomaduro** [comment]
Open positions must be on the top of the list. The idea is people know exactly how they can help.

**Comment by octoper** [comment]
@nunomaduro  Yeah I thought that too I will make some changes throughout the day

**Comment by octoper** [comment]
I think maybe I should make it more simple to and remove the work, city, and languages.
I will just put, the name, role and social links
@AlexMartinFR you think that good idea?

**Comment by nunomaduro** [comment]
the name, role and social links ✅

**Comment by AlexMartinFR** [comment]
Good call, no need to clutter the page with too much info.
If people want to know more they'll click on social stuff, that's what it's for 👍

**Comment by octoper** [comment]
Hey!
I want to ask you guys how we should name the roles like
@nunomaduro will be Creator.
But I have been thinking how to label to others like @AlexMartinFR, @owenvoke, @olivernybroe etc.
And how label the open positions.

**Comment by nunomaduro** [comment]
You can pull request what do you have. And the rest of the team will commit what they think they are here.

**Comment by octoper** [comment]
OK! @nunomaduro

**Comment by AlexMartinFR** [comment]
I think labelling positions is almost as hard as naming things in code 😋

**Comment by octoper** [comment]
@AlexMartinFR definitely! 😪
