### ISSUE TITLE
 enhancement suggestion for additional dsl 

### ISSUE THREAD

**Issue by SerjoA** [pestphp/pest#356]
hi, first of all thank you for a great tool, excellent work 

i do have a dsl suggestion, i write test in couple of languages, what i miss most in php is something like the similar

specs
```
describe("math library", {
  describe("addition()", {
    it("can add two numbers", {
      expect_equal(1 + 1, addition(1, 1))
    })
  })
  describe("division()", {
    it("can divide two numbers", {
      expect_equal(10 / 2, division(10, 2))
    })
    it("can handle division by 0") #not yet implemented
  })
})
```
basically a grouping of tests to describe a spec/feature
i  think it will also look nicely in the output format i saw pest does

would it be something of interest or pest is only about unit/feature tests, without spec in mind

**Comment by jordanbrauer** [comment]
@SerjoA, see #15. If I am not mistaking, we might see them sometime, but is not a priority at the moment it seems (unfortunately).

**Comment by SerjoA** [comment]
thank you i read the comments there 👍

**Comment by AndyWendt** [comment]
Also would like to see context though a little lower in priority than describe
