### ISSUE TITLE
toMatchObject

### ISSUE THREAD

**Issue by roni-estein** [pestphp/pest#358]
Hopefully I'm not misreading the docs, but, noticed this after struggling with object matching:

```php
//DOESNT WORK
expect(LoggedIp::first())->toMatchObject([
    'ip' => request()->getIp(),
    'blocked' => true,
]);

//WORKS
expect(LoggedIp::first()->toArray())->toMatchArray([
    'ip' => request()->getIp(),
    'blocked' => true,
]);
```

LoggedIp is a just a standard Laravel model.

Using Laravel 8.51.0 and Pest 1.10

**Comment by nunomaduro** [comment]
That's because those attributes are not "real" PHP properties.

**Comment by roni-estein** [comment]
Thanks for the respsonse, would you could you clarifying that a bit? Are you able to use this with eloquent models? Is there a better way? Is this something I have to extend to make it work. Any suggestions and clarifications would be appreciated.

**Comment by samir-araujo** [comment]
Sorry for posting in a closed issue, but since I couldn't find the answer nor a thread discussing it, I thought it would be good to share what I did to get it working in my project.

Looks like if you use `toHaveKey` or `toHaveKeys` instead of `toMatchObject` works just fine.

```php
//DOESNT WORK
expect(LoggedIp::first())->toMatchObject([
    'ip' => request()->getIp(),
    'blocked' => true,
]);

//WORKS
expect(LoggedIp::first())->toHaveKeys([
    'ip' => request()->getIp(),
    'blocked' => true,
]);```

**Comment by samir-araujo** [comment]
Thought it would be something like this, but I still don't know if it is/not the best way to test the existence of an attribute.
