### ISSUE TITLE
Builds failing on windows

### ISSUE THREAD

**Issue by nunomaduro** [pestphp/pest#36]
Currently builds are failing on windows: https://github.com/pestphp/pest/runs/704328906?check_suite_focus=true.

<img width="699" alt="Screenshot 2020-05-28 at 01 37 22" src="https://user-images.githubusercontent.com/5457236/83082434-c84ef880-a083-11ea-8dba-e4c5d1d19f83.png">

Some help would be appreciated here.

**Comment by Maxim-Mazurok** [comment]
That's how we do this in NodeJS:
`eslint` for Unix:
```
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*|*MINGW*|*MSYS*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  "$basedir/node"  "$basedir/../eslint/bin/eslint.js" "$@"
  ret=$?
else 
  node  "$basedir/../eslint/bin/eslint.js" "$@"
  ret=$?
fi
exit $ret
```

and `eslint.cmd` for Windows:
```
@ECHO off
SETLOCAL
CALL :find_dp0

IF EXIST "%dp0%\node.exe" (
  SET "_prog=%dp0%\node.exe"
) ELSE (
  SET "_prog=node"
  SET PATHEXT=%PATHEXT:;.JS;=;%
)

"%_prog%"  "%dp0%\..\eslint\bin\eslint.js" %*
ENDLOCAL
EXIT /b %errorlevel%
:find_dp0
SET dp0=%~dp0
EXIT /b
```

Hopefully, that may help

**Comment by fetzi** [comment]
I think the problem with the failing unit tests lies somewhere in https://github.com/pestphp/pest/blob/master/src/PendingObjects/UsesCall.php#L59. Can you reproduce the failing tests on Windows?

**Comment by Pierstoval** [comment]
I tried it locally, I've got something else:

```
$ php bin/pest --colors=always --exclude-group=integration --verbose
Pest\Exceptions\InvalidUsesPath

The path `E:\dev\www\pest\src\e:\dev\www\pest\tests` is not valid.
```

Seems like there's some work to do, I'll investigate on this

**Comment by Pierstoval** [comment]
Check out #41 🙂
