### ISSUE TITLE
Coverage not found in path: vendor\pestphp\pest\.temp\coverage.php

### ISSUE THREAD

**Issue by Bilge** [pestphp/pest#373]
```
> pest -c tests --colors --coverage
<!--
This should not happen - please create an new issue here: https://github.com/pestphp/pest.

- Issue: Coverage not found in path: vendor\pestphp\pest\.temp\coverage.php.
- PHP version: 7.4.21
- Operating system: WINNT (500 Internal Server Error) -->
```

**Comment by owenvoke** [comment]
See #277, this is probably related. But let us know if not.

**Comment by Bilge** [comment]
Yes, specifying `XDEBUG_MODE=coverage` fixes it. Being as that's the case, probably the error message should be improved. Rather than saying _this should not happen_, why not suggest setting the correct `XDEBUG_MODE`?

**Comment by owenvoke** [comment]
Feel free to open a PR. 👍🏻 It probably would be pretty easy to add a better message, however it then has to check which coverage driver is as well. I'm happy to have a look sometime soon.

**Comment by nunomaduro** [comment]
@Bilge That's a good suggestion - please pull request a better error message.

**Comment by jrmajor** [comment]
Hi, I don't know how to check what value of `XDEBUG_MODE` is used, but when I set it to `coverage` in `xdebug.ini`, the tests run noticeably longer, so I'm pretty sure it's enabled. However, I still get this error. Is there something else I should check?
