### ISSUE TITLE
Pest output should match PHPUnit parity

### ISSUE THREAD

**Issue by Bilge** [pestphp/pest#375]
Although Pest output is objectively better than the PHPUnit standard printer, it shouldn't remove features present in the underlying software. In particular, the following aspects are missing:

* Total memory consumption in summary output
* Total number of assertions run in summary output
* Software version in printer preamble (i.e. Pest version number plus PHPUnit version number)
* Random seed when `executionOrder="random"` (this is important to reproduce the same results using the same seed)

**Comment by nunomaduro** [comment]
I think output the memory is a good idea - fell free to pull request that feature as an option like `--memory` or something. Regarding the Pest version + the PHPUnit version, you don't get that feature by using the `--version` option?

**Comment by Bilge** [comment]
Passing `--version` shows the version information but doesn't run the tests. This is contrary to the behaviour of PHPUnit, which emits version information when running tests, without specifying any command line switches.

**Comment by nunomaduro** [comment]
Regarding the `--version` no plans to change it's behavior. 

Regarding the `--memory` option no plans to add that information by default, still open for having that information, as opt-in using the `--memory` option. Fell free to pull request that.

**Comment by Bilge** [comment]
Sad!

**Comment by Bilge** [comment]
Sad!

And in prematurely closing this, not only do you fail to address the issues we discussed, but you completely fail to address the missing random seed and assertion counter (which actually does appear in the TeamCity output, just not the CLI).

I thought Pest was a good project, but you're an awful maintainer.
