### ISSUE TITLE
Immediate feedback with unbuffered output

### ISSUE THREAD

**Issue by Bilge** [pestphp/pest#376]
Unlike PHPUnit, and most PHPUnit printers, Pest does not emit output after each test in a test case, but rather, it buffers the entire collection of tests in a test case until the whole test file has completed. This is presumably because it wants to emit PASS/FAIL on the header line for the test case, which it can't know until all sub-tests have finished, but the upshot of this is there is no output for some time, especially for long-running tests, which is not a good user experience.

We should like to know, as soon as the test runner knows, what the result of running each test is. If that means reformatting the output so it is less pretty, and the PASS/FAIL summary appears at the foot of each test case rather than in the head, then so be it: I strongly support functionality over form when the two are otherwise in conflict.

The following is just a suggestion of an alternative layout that would permit immediate feedback for each test case.

![image](https://user-images.githubusercontent.com/470626/129459008-e4b3a827-da3c-456b-8902-60f97f92ffd6.png)

**Comment by lukeraymonddowning** [comment]
Howdy @Bilge!

This is actually an issue to be posted in the Collision package, not here, as all output is handled by the Collision printer. Are you okay to move it and close this one?

**Comment by Bilge** [comment]
Yes.
