### ISSUE TITLE
Show run time for each test

### ISSUE THREAD

**Issue by Bilge** [pestphp/pest#377]
For test suites with slow tests, that want to crack down on performance bottlenecks, showing the execution time for each test is paramount. As someone who [once dabbled](https://github.com/ScriptFUSION/PHPUnit-Immediate-Exception-Printer) in PHPUnit printers, I happen to know this information is already available to printers, so it is just a matter of formatting it in a readable way. 

It can be a good idea to colour the test times according to the duration. The [thresholds I went with](https://github.com/ScriptFUSION/PHPUnit-Immediate-Exception-Printer/blob/de2f8a0987ff1c0d835e3ee36db0e86920f68ee1/src/Printer.php#L45-L49) were t < 200ms = green, t < 1s = yellow, otherwise red, but I am sure you can come up with a better scheme.

**Comment by nunomaduro** [comment]
I think this feature would be a nice to have. Fell free to pull request that option to this printer: https://github.com/nunomaduro/collision/tree/stable/src/Adapters/Phpunit.

**Comment by Bilge** [comment]
@nunomaduro Do you just close issues once you've read them? Or otherwise, what is the reason for closing this now?

**Comment by nunomaduro** [comment]
Well, I've told you that is a good idea - and you are free to contribute with a pull request. Do you see a reason to have this issue open?

**Comment by Bilge** [comment]
To keep track of unresolved ideas and implementations.

**Comment by nunomaduro** [comment]
@Bilge We only use the issues tab for bugs. Regarding your idea, you are free to create a pull request.
