### ISSUE TITLE
PEST with Laravel Modules and Laravel Livewire plugin

### ISSUE THREAD

**Issue by dcblogdev** [pestphp/pest#382]
I would really like to use PEST with Laravel Modules package. (https://github.com/nWidart/laravel-modules)

PEST runs with modules by itself but where the problem lies is the plugins for example I have a fresh Laravel install with a contacts module which has this test file

ContactTest.php

```php
<?php

use App\Http\Livewire\Counter;
use function Pest\Livewire\livewire;

it('can be incremented', function () {
    livewire(Counter::class)
        ->call('increment')
        ->assertSee(1);
});
```

When I run the test I get:

> Call to undefined method PHPUnit\Framework\TestCase::livewire()

I have these installed:

```bash 
"pestphp/pest": "^1.16",
"pestphp/pest-plugin-faker": "^1.0",
"pestphp/pest-plugin-global-assertions": "^1.0",
"pestphp/pest-plugin-laravel": "^1.1",
"pestphp/pest-plugin-livewire": "^1.0",
```

I've uploaded a demo project to show this.

https://github.com/dcblogdev/laravel-module-pest-demo/blob/master/Modules/Contacts/Tests/Feature/ContactTest.php

Are there any steps I need to complete?

**Comment by nunomaduro** [comment]
No plans to investigate this issue. Fell free to submit a pull request that addresses this issue.

**Comment by garbinmarcelo** [comment]
Hi @dcblogdev , are you still using PESTPHP with Laravel Modules? I currently use Laravel Modules and am learning PESTPHP.

Could you tell us a little about your experience so far? 

I'm thinking about getting started using Inertia.js in my projects too, so I'm still studying about that.

Thanks

**Comment by dcblogdev** [comment]
@garbinmarcelo pest works fine with modules now. 

most of the time you only need to import:

```php
uses(Tests\TestCase::class);
```

for example:

```php
<?php

use Modules\Contacts\Models\Contact;

uses(Tests\TestCase::class);

test('can see contact list', function() {
    $this->authenticate();
   $this->get(route('app.contacts.index'))->assertOk();
});
```

**Comment by KuzminDima** [comment]
It seems to me that the best option is to specify the full path to the module
Example:
```php
// Pest.php
uses(Tests\TestCase::class)->in(
    'Feature',
    __DIR__ . '/../Modules/TestModule/Tests/Feature',
);

uses(Illuminate\Foundation\Testing\RefreshDatabase::class)->in(
    'Feature',
    __DIR__ . '/../Modules/TestModule/Tests/Feature',
);
```

**Comment by andresilvagomez** [comment]
@dcblogdev did you have some update with parallel testing?

It's working fine for me, but I need coverage in parallel mode

**Comment by back2Lobby** [comment]
For me, nothing worked except following what's mentioned in the [documentation](https://pestphp.com/docs/configuring-tests#:~:text=Another%20more%20complex%20example%20would%20be%20using%20a%20pattern%20to%20match%20multiple%20directories%20in%20different%20modules%20while%20applying%20multiple%20test%20case%20classes%20and%20traits%3A) lol.

I tried the method specified above like this but it didn't work:
```php
uses(
    DuskTestCase::class,
    DatabaseMigrations::class
)->in(__DIR__ . '/../Modules/TestModule/Tests/Feature');
```
But adding the module pattern like this worked like a charm:
```php
uses(
    DuskTestCase::class,
    DatabaseMigrations::class
)->in('../Modules/*/Tests/Feature');
```

Plus we don't need to mention it for every single module 🥳.

**Comment by solomon-ochepa** [comment]
Add the modules' tests path to the root `tests/Pest.php` file.
```php
pest()->extend(Tests\TestCase::class)
    ->use(Illuminate\Foundation\Testing\RefreshDatabase::class)
    ->in('Feature', '../modules/*/tests/Feature');
```

How it works!
- `.../` - move one directory outside - the `Pest.php` file is inside the `tests/` folder..
- `modules/` - my modules' path is lowercase.
- `*/` - include all modules (`glob`)
- `tests/Feature` - the targeted tests directory inside the module.
