### ISSUE TITLE
Parallel testing does not work with teamcity printer

### ISSUE THREAD

**Issue by mertasan** [pestphp/pest#383]
Parallel test fails because of this line.

https://github.com/pestphp/pest-intellij/blob/4469b6bfd75097536ae555bac828b2c5797858be/src/main/kotlin/com/pestphp/pest/configuration/PestRunConfigurationHandler.kt#L20

<img width="1179" alt="screenshot 158" src="https://user-images.githubusercontent.com/13007665/130990236-6a669242-8851-4629-88b4-2a3178480784.png">

**Comment by nunomaduro** [comment]
@mertasan Can you pull request a fix for this?
