### ISSUE TITLE
Calling DB Facade inside afterAll() throws an error

### ISSUE THREAD

**Issue by jeytii** [pestphp/pest#388]
**tests/Feature/Auth/LoginTest.php**
```php
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\DB;

uses(RefreshDatabase::class);

afterAll(function() {
    DB::table('users')->truncate();
});

// ...
```

**_Error message:_**
> Exception in P\Tests\Feature\Auth\LoginTest::tearDownAfterClass
> Target class [db] does not exist.

**Comment by nunomaduro** [comment]
That's expected. Maybe you meant "afterEach"?

**Comment by jeytii** [comment]
@nunomaduro I only want to fire `DB::table('users')->truncate()` after all tests since only a few tests create fake data
