### ISSUE TITLE
Accessibility: epilepsy & animated logo?

### ISSUE THREAD

**Issue by AlexMartinFR** [pestphp/pest#39]
Something interesting came up during our Laracon break talk, regarding the Pest logo.

**Concerns:**
We wonder if people suffering from **epilepsy** would be affected by the **animated logo** on Pest's home page.

**Resources:**
- An actual academic testing tool: [Photosensitive Epilepsy Analysis Tool (PEAT)](https://trace.umd.edu/peat)
- A [Guide to use this tool](https://www.useragentman.com/blog/2017/04/02/using-peat-to-create-seizureless-web-animations/)
- MDN's [accessibility recommendations](https://developer.mozilla.org/en-US/docs/Web/Accessibility/Seizure_disorders)

**Workaround:**
I tried a slowed down version of the current logo:
https://ezgif.com/speed/ezgif-1-325dcc77bf08.gif

I find 10% seems whimsical enough, still convey the intended vibe and shouldn't be as dangerous?

I will take some time to dig through that, and would love to hear from people competent on the matter about this topic!

**Comment by nunomaduro** [comment]
cc @caneco

**Comment by nunomaduro** [comment]
Thanks for creating this issue.

**Comment by caneco** [comment]
@AlexLombry thanks for pointing this out 😅

Really need to check this, we don't want to injure someone 😶

**Comment by AlexMartinFR** [comment]
I'm not sure I'm him, but thanks 😅

If someone find something interesting about this topic it would be cool to share it here, it would be good knowledge to spread around if we encounter that problem in the future!

**Comment by AlexLombry** [comment]
Since I saw the comment yes i wasn’t aware of that kind of problem. It’s very interesting to know

**Comment by caneco** [comment]
Finally managed to get the thing running on a Windows, and made a test with the following clip:

> [pest-logo-homepage.avi.zip](https://github.com/pestphp/pest/files/4719845/pest-logo-homepage.avi.zip)

And according to the analysis tool this was the result:

> ![image](https://user-images.githubusercontent.com/502041/83573135-cb823280-a522-11ea-8655-acd1c7ab8ba5.png)

### We got **0️⃣ warnings**. 

I think it's safe to say that the logo will not cause any harm `:phew:`

**Comment by AlexMartinFR** [comment]
Awesome!

Better safe than sorry, and we get to keep the whimsical stuff 🔥

**Comment by m1guelpf** [comment]
Could we disable the animation when the prefers-reduced-motion media query is enabled?

**Comment by AlexMartinFR** [comment]
Very good idea @m1guelpf !

cc @octoper 😉
