### ISSUE TITLE
Display output on test run

### ISSUE THREAD

**Issue by midnite81** [pestphp/pest#393]
Minor issue I'm having. I have my normal application tests and then a couple of internal projects within the main application which have their own tests. When I run the test suite all the tests are run (both application tests and the internal project ones) however when it outputs it misses the first letter off the directory when printing. Like I say not a massive issue but just making you aware.

Missing the first P
<img width="173" alt="image" src="https://user-images.githubusercontent.com/254850/132109028-7d2a1fb4-b61e-43a3-b91e-e6f95927cc5c.png">

However doesn't miss the first letter from the application's Test folder
<img width="127" alt="image" src="https://user-images.githubusercontent.com/254850/132109042-0970367a-53a0-4402-b283-8222e5a10eba.png">

Versions:
```
pestphp/pest                          v1.18.0    An elegant PHP Testing Framework.
pestphp/pest-plugin                   v1.0.0     The Pest plugin manager
pestphp/pest-plugin-laravel           v1.1.0     The Pest Laravel Plugin
```

**Comment by nunomaduro** [comment]
@midnite81 Can you pull request a fix here? https://github.com/nunomaduro/collision/.
