### ISSUE TITLE
`sequence()` can generate false positives

### ISSUE THREAD

**Issue by mertasan** [pestphp/pest#398]
I think this test should fail.

https://github.com/pestphp/pest/blob/2f0cd7a4e3a36ac51367ea45d65fc09403ec32c7/tests/Features/Expect/sequence.php#L29-L38

Useful when working with static data. Even so, why test more than the actual data?

But it generates false positives in a use case like the one below.

```php
expect(new Model())
    ->all()
    ->toHaveCount(2) // << Assuming this isn't added
    ->sequence(
        fn ($model) => $model->title->toEqual('foo'),
        fn ($model) => $model->title->toEqual('bar'),
        fn ($model) => $model->title->toEqual('baz'), // << There is no such item.
    );
```

my solution:

```php
Assert::assertLessThanOrEqual(count($value), count($callbacks));
```

https://github.com/pestphp/pest/blob/2f0cd7a4e3a36ac51367ea45d65fc09403ec32c7/src/Expectation.php#L167

This assertion should be added to this line.

Do you support this idea?

Thanks.

**Comment by nunomaduro** [comment]
Good idea, can you make a pull request?
