### ISSUE TITLE
Idea: uses could default in the current directory

### ISSUE THREAD

**Issue by felixdorn** [pestphp/pest#40]
Hey!

I'm playing around with Pest (awesome!) and wondering why the `uses` method don't default to the current directory.

I briefly saw how the magic is made and I think this could be possible.

However, I just noticed that `uses(TestCase::class)->in('.)` was working.

But the version without `in` seems more intuitive.

I can definitely submit a PR, if that can helps.

**Comment by nunomaduro** [comment]
`uses` method defaults to the current directory.

**Comment by felixdorn** [comment]
Okay, I got it!

That all makes sense now, the `Backtrace::file()` returns the last called file a.k.a. the current file.

I'm just too used to PHPunit.
Thanks for the quick reply!
