### ISSUE TITLE
Laravel Plugin get() causes segmentation fault if server returns 502

### ISSUE THREAD

**Issue by ingageco** [pestphp/pest#400]
Hey Team, 

I was running a test to a url in our system that was returning an Nginx 502 bad gateway using Pest\Laravel\get. Instead of failing the test, Pest (or something underlying) was failing completely with a segmentation fault. 

Maybe there's something i do not understand - but shouldn't this be able to be caught and reported as an assertion?

**Comment by nunomaduro** [comment]
That seems to be related to Laravel itself. We just proxy the `get` function to Laravel is TestCase@get method.

**Comment by ingageco** [comment]
Cool - thanks!
