### ISSUE TITLE
"Can you quickly star our Github repository?" causes InitializeSandbox issue

### ISSUE THREAD

**Issue by dougblackjr** [pestphp/pest#408]
Caught this when trying to install pest on a project.

Was greeted with a question: `Can you quickly star our GitHub repository? 🙏🏻 (yes/no) [yes]:`. Hit enter to signify yes. It opened my browser to the page (and I starred, just so you know 😜). In my terminal, I got the following error:

```
[1045692:1045692:0100/000000.278607:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
```

Hitting Control + C broke out of the process just fine. Rerunning the script with "No" as the answer caused no issues.

![Screenshot from 2021-09-24 07-57-16](https://user-images.githubusercontent.com/6020323/134670440-906d0ba4-08b7-4c0e-bbe3-9f24a8f4f6d4.png)

SPECS:
OS: [PopOS](https://pop.system76.com/) (fork of Ubuntu)
PHP version: 8.0.9
Composer version: 2.1.dev
Laravel version: 8.12

Let me know what other info you may need.

**Comment by nunomaduro** [comment]
Thank you for reporting this one. Fell free to submit a pull request that addresses this issue.
