### ISSUE TITLE
Laravel Plugin seems not to work

### ISSUE THREAD

**Issue by dschiller** [pestphp/pest#415]
Using the example from https://pestphp.com/docs/plugins/laravel seems not to work:

```
<?php

use Pest\Laravel;

it('has home')
    ->get('/admin')
    ->assertSee('Hello World');
```

Error is:

```

   PASS  Tests\Unit\ExampleTest
  ✓ basic test

   PASS  Tests\Feature\ExampleTest
  ✓ basic test

   FAIL  Tests\Unit\HomeTest
  ⨯ it has home

  ---

  • Tests\Unit\HomeTest > it has home
   ReflectionException 

  Call to undefined method PHPUnit\Framework\TestCase::get()



  Tests:  1 failed, 2 passed
  Time:   0.09s
```

**Comment by nunomaduro** [comment]
Please put `uses(YourLaravelTestCase::class)` in your `Pest.php` file.

**Comment by soutorafaelbr** [comment]
this isn't working for me

**Comment by soutorafaelbr** [comment]
So, i figured out the problem for me. 

Apparently Pest.php was being cached and no matter what change i was doing on the file, it was not being updated. I manually removed the cache and run pest again and worked just fine.

Unfortunually i didn't found a more soffisticated solution :/

**Comment by shinycactus** [comment]
How did you remove the cache?

**Comment by mitulgolakiya** [comment]
For me, error fixed by specify `->in` parameter after `uses(Tests\TestCase::class)->in(__DIR__);` in `Pest.php`.

Previously it was just `uses(Tests\TestCase::class)`;

**Comment by marcellopato** [comment]
tests->Feature->AutoRegisterVednor.php

```
<?php

use function Pest\Laravel\post;

it('can auto register vendor', function () {
    post('/api/users/vendor');

    assertStatus(200);
});
```

In `Pest.php`: `uses(Tests\Feature\AutoRegisterVendor::class);`

But the error:

```./vendor/bin/pest

   AssertionError 

  assert(array_key_exists(self::FILE, $trace))

  at vendor/pestphp/pest/src/Support/Backtrace.php:29
     25▕     {
     26▕         $current = null;
     27▕ 
     28▕         foreach (debug_backtrace(self::BACKTRACE_OPTIONS) as $trace) {
  ➜  29▕             assert(array_key_exists(self::FILE, $trace));
     30▕ 
     31▕             $traceFile = str_replace(DIRECTORY_SEPARATOR, '/', $trace[self::FILE]);
     32▕ 
     33▕             if (

      +3 vendor frames 
  4   tests/Feature/AutoRegisterVendor.php:5
      +2 vendor frames 

  7   [internal]:0
      Composer\Autoload\ClassLoader::loadClass("Tests\Feature\AutoRegisterVendor")
```

persists.

**Comment by vishalinfyom** [comment]
I just resolved it by changing ine into `Pest.php`

`uses(TestCase::class, RefreshDatabase::class)->in('Feature', 'Actions');`

Here I added the new folder `Actions` before the it was like : 


`uses(TestCase::class, RefreshDatabase::class)->in('Feature');`

**Comment by JaydeepS-Webmavens** [comment]
mutate()->path('app/Http/Controllers/EventController.php');
use in pest.php 

error: Call to undefined function mutate()
