### ISSUE TITLE
Can't run tests on PHP 8.1

### ISSUE THREAD

**Issue by bpolaszek** [pestphp/pest#416]
Hello there,

PHP 8.1 introduced return types almost everywhere into [PHP's internal code](https://wiki.php.net/rfc/internal_method_return_types). 
This theoretically leads to potential BC break, because any class implementing `IteratorAggregate` with `getIterator()` instead of `getIterator(): Traversable` would break inheritance rules. 
However, it's been decided just to warn the user with a deprecation notice until PHP 9.

To avoid having this deprecation yielded, a `#[\ReturnTypeWillChange]` attribute can be added on top of the method before it's effectively refactored. Fine.

The problem is that Pest currently converts those deprecations to exceptions. For example, my app has a dependency to [lexik/jwt-authentication-bundle](https://github.com/lexik/LexikJWTAuthenticationBundle) (amongst many others), which hasn't started that refactoring or silencing process. Here's what I get when I run my test suite:

```
PHP Fatal error:  During inheritance of IteratorAggregate: Uncaught Whoops\Exception\ErrorException: 
Return type of Lexik\Bundle\JWTAuthenticationBundle\TokenExtractor\ChainTokenExtractor::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /vendor/lexik/jwt-authentication-bundle/TokenExtractor/ChainTokenExtractor.php:91
Stack trace:
#0 /vendor/lexik/jwt-authentication-bundle/TokenExtractor/ChainTokenExtractor.php(16): Whoops\Run->handleError(8192, 'Return type of ...', '/Users/benoit/P...', 91)
#1 /vendor/composer/ClassLoader.php(480): include('/Users/benoit/P...')
#2 /vendor/composer/ClassLoader.php(346): Composer\Autoload\includeFile('/Users/benoit/P...')
```

Since it is a dependency, I simply can't add  the `#[\ReturnTypeWillChange]` attribute by myself. Is it possible to convert it back to a simple deprecation notice (not transforming this to a fatal error), or at least have an option to mute it?

It seems related to Whoops, as running a test with PHPUnit shows the deprecation notice but doesn't prevent the test suite to complete.

Thanks,
Ben

**Comment by nunomaduro** [comment]
@bpolaszek Can you create a simple project where we can reproduce the issue?

**Comment by nunomaduro** [comment]
Your issue does not make sense. The `Lexik\Bundle\JWTAuthenticationBundle` author should add `#[\ReturnTypeWillChange]` to avoid this issue.

**Comment by bpolaszek** [comment]
@nunomaduro it doesn't seem related to Whoops directly since Whoops also keeps the deprecation as is. There's something somewhere which tells PHP to convert deprecation notices into fatal errors but I don't figure out what. Maybe something into nunomaduro/collision?
