### ISSUE TITLE
standard php unit tests not run when using 'groups'

### ISSUE THREAD

**Issue by reed-jones** [pestphp/pest#42]
I'm working on converting my tests over to Pest. (Its awesome, Thanks!), When I run `vendor/bin/pest` I get 50 passed tests, roughly half are in `FolderA`, and the other half are in `FolderB`

in my Pest.php I have something like
```
uses(ProjectATestCase::class)->group('a')->in('FolderA');
uses(ProjectBTestCase::class)->group('b')->in('FolderB');
```

but now when I run a group only my actual pest tests run, which means I'm missing quite a few

```sh
vendor/bin/pest --group=a # 3 passed tests
vendor/bin/pest --group=b # 18 passed tests
```
Not sure if this is a bug, or intended, but it definitely surprised me (although soon it will all be switched over so not a problem)

**Comment by nunomaduro** [comment]
Yeah - that `uses` function only covers pest tests. Sorry about that.

Can you add a note on the docs about this?

**Comment by AlexMartinFR** [comment]
Note added to the docs:
[https://pestphp.com/docs/groups/](https://pestphp.com/docs/groups/)

**Comment by nunomaduro** [comment]
@AlexMartinFR Added a comment on the commit. can you check?

**Comment by AlexMartinFR** [comment]
Corrected my wrong statement. It should now be clearer 👍 

@reed-jones , you could confirm that this would have helped you understand the problem you encountered better, please?

**Comment by reed-jones** [comment]
Totally, that makes perfect sense to me. Thanks!

**Comment by AlexMartinFR** [comment]
Great!
Thanks for sharing your experience, and happy testing 😎
