### ISSUE TITLE
Question: why can't test name contain some symbols?

### ISSUE THREAD

**Issue by ibrunotome** [pestphp/pest#422]
I had my tests running and then renamed one from:

`it('favorite category successfully'`

to:

`it('favorite/unfavorite category successfully'`

and it stopped to work instantly. 

```
Tests:  
Assertions:  0
Time:  0s
```

Also saw that symbols `+, *` are not allowed, but `-` symbol is.

Is there a reason to just this 3 symbols (until now) not being allowed?

**Comment by ibrunotome** [comment]
First observation: I downloaded the pest repo and write a unit test with these symbols and it passes.

**Comment by danilopolani** [comment]
Hey, just found this issue. 
A colleague reported to me that he can't write a test with a "+" inside the name (Pest v1.21.1) but I haven't tried it yet. Will let you know if I found something about it.

**Comment by rshaw5** [comment]
Just spent a few hours wrestling with this until I figured out I can't use `=` in test names, This issue has been closed, is there a fix planned?
