### ISSUE TITLE
Mocks created with helper mock() cannot be passed as argument

### ISSUE THREAD

**Issue by javespi** [pestphp/pest#431]
Hello! Have anyone tried passing mocks as argument for a dependency? I couldn't make it work when they are created with the helper `mock()`.

### Problem explained

When I use `$dependency = mock(Class::class)` PHP throws me a TypeError exception if I have `$serviceToTest = new Service($dependency)`

I can show you the exactly code where it happens:
https://github.com/javespi/test-doubles/pull/6/commits/3ec7b78b7c0acf33aa3d25815444f1786da3b455#diff-04525d282c596c98c5f150bcee6c0b6ea09dca47c0dd2bef3c3a76c23e5f9edbR17-R25

And the pest result with Github action ❌ 
https://github.com/javespi/test-doubles/runs/3713921199?check_suite_focus=true

Didn't find a mock example like this in the doc, I would happy to improve it in case there is something I am missing here 😃 

If I inspect what is the class of each mock created, I get this:

```php
beforeEach(function (): void {
    $this->tenantRepository = mock(TenantRepository::class);
    get_class($this->tenantRepository); // string(14) "Pest\Mock\Mock"

    $this->tenantRepository = \Mockery::mock(TenantRepository::class);
    get_class($this->tenantRepository); // string(52) "Mockery_0_TestDoubles_Domain_Tenant_TenantRepository"
    ...
});
```

So I guess the FCQN of Mock class from Pest is overriding the mockery one.

### Workaround

In the meantime, using directly `\Mockery::mock(Class::class)` works and doesn't throw the \TypeError:

Diff: https://github.com/javespi/test-doubles/pull/6/commits/cbadb1646c1fb2d71fa4d5ed7c5fdb5fece869a9#diff-04525d282c596c98c5f150bcee6c0b6ea09dca47c0dd2bef3c3a76c23e5f9edbL18-L19

Github action ✅ https://github.com/javespi/test-doubles/runs/4070181855?check_suite_focus=true

Thank you!

**Comment by fabio-ivona** [comment]
In order to obtain a mock, you should call its `->expect()` method and define mocked methods

`->expect()` will return a mock, then.

```php
beforeEach(function (): void {
    $this->tenantRepository = \Mockery::mock(TenantRepository::class);
    get_class($this->tenantRepository); // string(52) "Mockery_0_TestDoubles_Domain_Tenant_TenantRepository"

    $this->tenantRepository = mock(TenantRepository::class);
    get_class($this->tenantRepository); // string(14) "Pest\Mock\Mock"

    $this->tenantRepository = \Mockery::mock(TenantRepository::class)->expect(method: fn($args) => $result);
    get_class($this->tenantRepository); // string(52) "Mockery_0_TestDoubles_Domain_Tenant_TenantRepository"
    ...
});

**Comment by javespi** [comment]
Thank you @fabio-ivona! It worked. You can check the PR here if you want https://github.com/javespi/test-doubles/pull/7 

I didn't notice that calling `expect()` the mock of mockery was returned.

I was confused because Mockery library has also a `mock()` helper as well. I was wondering if maybe having both collides somehow:

https://github.com/mockery/mockery/blob/816475d89d82ea968796523de8e56237ac5921a6/library/helpers.php#L25-L30

Thank for the quick response! I'm closing the issue since is resolved.

**Comment by fabio-ivona** [comment]
@javespi just added a little alternative way in your PR for obtaining the same result, using pest's mock() syntax
