### ISSUE TITLE
pest fails with --coverage option 

### ISSUE THREAD

**Issue by grEvenX** [pestphp/pest#437]
I run my tests with `pest --coverage` option, the tests passes but I get the following exception at the end:

```
  Tests:  11 passed
  Time:   0.37s


   Pest\Exceptions\ShouldNotHappen 

  
This should not happen - please create an new issue here: https://github.com/pestphp/pest.

- Issue: Coverage not found in path: /var/www/html/vendor/pestphp/pest/.temp/coverage.php.
- PHP version: 8.0.7
- Operating system: Linux

  at vendor/pestphp/pest/src/Exceptions/ShouldNotHappen.php:38
     34▕      * Creates a new instance of should not happen without a specific exception.
     35▕      */
     36▕     public static function fromMessage(string $message): ShouldNotHappen
     37▕     {
  ➜  38▕         return new ShouldNotHappen(new Exception($message));
     39▕     }
     40▕ }
     41▕ 
```

- Pest-version: 1.20.0

**Comment by canvural** [comment]
Are you using xdebug? If so did you activate the coverage for xdebug? You can do it like `XDEBUG_MODE=coverage pest --coverage` or you can set it with `export XDEBUG_MODE=coverage` then run your command.

**Comment by grEvenX** [comment]
@canvural Thanks, I hoped that was the case too, but I get the same issue both when `XDEBUG_MODE` is set to `debug`, `coverage` and `off`. 

Is there any clue in the issue root case about `Issue: Coverage not found in path: /var/www/html/vendor/pestphp/pest/.temp/coverage.php.` ?
I'm not familiar with the internals, but looks a bit weird that it tries to look in a temp folder in the vendor directory?

**Comment by nunomaduro** [comment]
@grEvenX Try this `XDEBUG_MODE=coverage ./bin/pest --coverage`.

**Comment by grEvenX** [comment]
@nunomaduro Yeah, that's the command I used, only exception is that I added a file at the end to not run my whole test-suite (which has other issues running 100% in pest currently). I see the output varies based on what test I run.

Running with command: `XDEBUG_MODE=coverage ./vendor/bin/pest --coverage tests/Unit/HelpersTest.php` causes output:
```
$ XDEBUG_MODE=coverage ./vendor/bin/pest --coverage tests/Unit/HelpersTest.php 

   PASS  Tests\Unit\HelpersTest
  ✓ mask_email masks emails

  Tests:  1 passed
  Time:   0.26s


   Pest\Exceptions\ShouldNotHappen 

  
This should not happen - please create an new issue here: https://github.com/pestphp/pest.

- Issue: Coverage not found in path: /var/www/html/vendor/pestphp/pest/.temp/coverage.php.
- PHP version: 8.0.7
- Operating system: Linux

  at vendor/pestphp/pest/src/Exceptions/ShouldNotHappen.php:38
     34▕      * Creates a new instance of should not happen without a specific exception.
     35▕      */
     36▕     public static function fromMessage(string $message): ShouldNotHappen
     37▕     {
  ➜  38▕         return new ShouldNotHappen(new Exception($message));
     39▕     }
     40▕ }
```

I can send the content of that test-file, but it's very simple test without using any imports or anything.

**Comment by grEvenX** [comment]
This exception no longer occurs, but I was getting this message instead which could be related to the original error:
> 

The solution, in this case, was to add the `coverage` section to the `phpunit.xml` file as described in the documentation: https://pestphp.com/docs/coverage#filters
After adding that, coverage works as expected.
