### ISSUE TITLE
Can you help to setup a test workflow, please?

### ISSUE THREAD

**Issue by bautrukevich** [pestphp/pest#439]
Hello! I don't understand what I am doing wrong when setup the test workflow:
[https://github.com/zorachka/console/pull/3](https://github.com/zorachka/console/runs/4261720543?check_suite_focus=true)

My PR: [https://github.com/zorachka/console/pull/3](https://github.com/zorachka/console/pull/3)

Can you explain please, maybe Pest doesn't see the tests directory or tests?

Thank you.

**Comment by bautrukevich** [comment]
Locally everything works fine and tests passed.

**Comment by owenvoke** [comment]
I think it's because you don't have a `phpunit.xml` file. Is there one locally that you haven't committed?

**Comment by bautrukevich** [comment]
@owenvoke Yes, you are right! Thank you so much!

Sorry for this stupid issue 🙏

**Comment by owenvoke** [comment]
@bautrukevich, no worries at all. And no need to apologise, it's not a stupid issue. Glad you got it sorted!
