### ISSUE TITLE
beforeAll "Target class [config] does not exist"

### ISSUE THREAD

**Issue by stonkeep** [pestphp/pest#446]
When I use beforeEach all the tests work but when I use beforeAll I get the error "Target class [config] does not exist"
Some idea?

**Comment by owenvoke** [comment]
`beforeAll()` is executed before the test class has been instantiated, so it doesn't have access to things such as the Laravel container. You'll need to use `beforeEach()` instead, which is the equivalent of  `setUp()` in PHPUnit.
