### ISSUE TITLE
[doc] Higher Order Expectations

### ISSUE THREAD

**Issue by oliverpool** [pestphp/pest#447]
According to the last example of https://pestphp.com/docs/expectations#higher-order-expectations :
> Once you perform one or more of Pest's expectations, the expectation's scope will reset to the initial value again:

```php
expect($user)
    ->companies->first()->owner->toBeInstanceOf(User::class)->not->toEqual($user)
    ->name->toEqual('Nuno');
```

So my understanding is that the `->name->toEqual('Nuno')` applies to `expect($user)`, since it is preceded by the expectation `toEqual`.

However this should also be the case for `->not->toEqual($user)` since it is preceded by the expectation `toBeInstanceOf`.

So is the example testing that: `expect($user)->not->toEqual($user)`? (which is probably always false).

Did I misunderstand the documentation? Or is the example falsy?

**Comment by lukeraymonddowning** [comment]
`toBeInstanceOf()`, `not` and `toEqual` are all part of the Expectation API, so this is actually still testing the first companies owner. Once `->name` is accessed on the next line, the scope is then reset to `$user->name`. Hope that makes sense?

**Comment by oliverpool** [comment]
Thanks for the quick reply, I think I get it.

Actually it gets back to the initial value on the first non-expectation call (`->name` is not an expectation, so the scope is reset).

Maybe it could be rephrase :

> You can perform one or more of Pest's expectations, the expectation's scope will reset to the initial value on the first non-expectation call (`->name` in this case):
