### ISSUE TITLE
Proposal: pest-plugin-init

### ISSUE THREAD

**Issue by nunomaduro** [pestphp/pest#45]
After merging @fetzi's work on plugins. Would be cool to develop a `pest-plugin-init` that would work the following way: 

1. In applications without tests: `./vendor/bin/pest --init`
2. Boostraps the tests folder
3. Create a configuration file

**Comment by owenvoke** [comment]
This would be nice. 👍 I'd be happy to take a look when the plugin PR is merged.

**Comment by AlexMartinFR** [comment]
Nice!
Could we get rid of the dashes to provide a cleaner CLI experience `./vendor/bin/pest init` ?

Some more thought about CLI syntax here: [#10](https://github.com/pestphp/pest/issues/10#issuecomment-636305590)

**Comment by nunomaduro** [comment]
Dashes are for options. So you are right

**Comment by fetzi** [comment]
@owenvoke are you still on it?

**Comment by owenvoke** [comment]
I was, but was struggling on a way to implement it with the current plugin API.

If it uses HandlesArguments, then it may be run after other plugins which is not desired as it basically just needs to be a separate command.

**Comment by fetzi** [comment]
Yes, maybe this one shouldn't be a plugin and should be included in the core. @nunomaduro what do you think?

**Comment by nunomaduro** [comment]
Should be a plugin that exists by default on the core. 😊

**Comment by owenvoke** [comment]
Ok, I think we may need to modify the plugin API to allow this then. 👍

**Comment by fetzi** [comment]
@owenvoke I think that `handleArguments` is the right place for that. It won't matter if another plugin gets executed beforehand.

**Comment by owenvoke** [comment]
@fetzi, or afterwards? 🤔 Just seems a bit weird for `init` to also run tests. But if so, I'm happy to just do that.

**Comment by nunomaduro** [comment]
@owenvoke Well, you can `exit(0)` when you are handling the arguments of the init right?

**Comment by fetzi** [comment]
The watch plugin will also not continue to execute the tests directly. So I think `exit(0)` is good for the init plugin.

**Comment by owenvoke** [comment]
Just to check, I assume that if that's at the end of the `handleArguments()` method, then the `addOutput()` wouldn't be called? Because it would just exit.
