### ISSUE TITLE
PHPUnit\Framework\TestCase::$name must be a non-blank string

### ISSUE THREAD

**Issue by ilyavaiser** [pestphp/pest#450]
Pest 1.21.1
PHPUnit 9.5.10 by Sebastian Bergmann and contributors.

  /app/tests/Feature/ChatTest.php

  Tests\Feature\ChatTest 

⨯ has a welcome page

PHPUnit\Framework\TestCase::$name must be a non-blank string.

**Comment by nunomaduro** [comment]
Please elaborate in your issue.
