### ISSUE TITLE
High order expectation fail with json on object

### ISSUE THREAD

**Issue by amenophis** [pestphp/pest#452]
Hi,
I'm trying to work on a symfony plugin.
I am unable to use high order expectation with json on object.

I created a failing test in my fork: https://github.com/amenophis/pest/blob/json-high-order/tests/Features/Expect/HigherOrder/methodsJson.php

The error is:

```
  • Tests\Features\Expect\HigherOrder\methodsJson > it can use json in method high order expectation
  Failed asserting that null is identical to 1.

  at src/Expectation.php:275
    271▕      * @param mixed $expected
    272▕      */
    273▕     public function toBe($expected): Expectation
    274▕     {
  ➜ 275▕         Assert::assertSame($expected, $this->value);
    276▕ 
    277▕         return $this;
    278▕     }
    279▕ 

  1   src/HigherOrderExpectation.php:137
      Pest\Expectation::toBe()

  2   src/HigherOrderExpectation.php:92
      Pest\HigherOrderExpectation::performAssertion()


```

Maybe i'm doing something bad.
Can i have your opinion ?

Thanks

**Comment by amenophis** [comment]
Hello, 
Can you confirm it is a normal behavior or not ?

Thanks

**Comment by nunomaduro** [comment]
cc @dansysanalyst - what were your conclusions on this?

**Comment by dansysanalyst** [comment]
@nunomaduro on 21.12.2021 I had asked on the group regarding arrays and Higher Order and you replied `checking`.

Did I miss any further discussion for this topic?

![IMAGE 2022-01-03 15:00:23](https://user-images.githubusercontent.com/79267265/147939351-f1ba9ed9-eea0-4ea8-a20f-72c4520f52c3.jpg)
 `Failed asserting that null is identical to 'amenophis'.`

**Comment by amenophis** [comment]
@dansysanalyst @nunomaduro Do you have news about this issue ??

**Comment by dansysanalyst** [comment]
Just for investigation, I have returned an array instead of using the `json()` modifier. 

```php
//...
public function getArray(): array
{
    return json_decode($this->content, true);
}
```


```php
it('can access array', function () {
    expect(new Response())
        ->getArray()
        ->id->toBe(1)
        ->username->toBe('amenophis')
        ->email->toBe('amenophis@leherpeur.net');
});
```

Higher Order fails to read further array properties: 
`Failed asserting that null is identical to 'amenophis'.`

**Comment by amenophis** [comment]
Can I help on this topic ?

**Comment by lukeraymonddowning** [comment]
@amenophis 

This will be fixed in v2. Can't fix in v1 due to breaking changes. In the meantime, you can `json_decode` in the `expect` instead as a workaround.
