### ISSUE TITLE
Unable to use translated strings in higher order tests

### ISSUE THREAD

**Issue by bcorcoran** [pestphp/pest#455]
There seems to be an issue with higher order tests. Translated strings (e.g. `__('example.message')` ) cause the following error if used inside a higher order test:

```
Illuminate\Contracts\Container\BindingResolutionException 

  Target class [translator] does not exist.

```

In particular, I tried using translated strings inside `assertSee`. The translated strings work as expected inside a regular test structure.

PHP 8.1, Pest 1.21.1, Laravel 8.77.1

**Comment by nunomaduro** [comment]
@lukeraymonddowning He needs to tap here right?

**Comment by lukeraymonddowning** [comment]
Yes. You can't access features that require the Laravel container in higher order tests without using tap or a closure to expect 👍

**Comment by nunomaduro** [comment]
@bcorcoran Take a look at the function `tap`: https://pestphp.com/docs/higher-order-tests.

**Comment by bcorcoran** [comment]
My apologies- I somehow missed this. Thanks

**Comment by bcorcoran** [comment]
I guess I am missing something, because I tried using `tap()` with `assertSee()` and I can't get it to work.

Can you provide an example?

**Comment by lukeraymonddowning** [comment]
Sorry, my bad. In this case, your only two choices are to override the entire TestResponse object to accept closures in methods that are resolved after setup, or switch to standard test syntax

**Comment by lukeraymonddowning** [comment]
Highly experimental but you might also be able to use this

https://github.com/lukeraymonddowning/pest-plugin-larastrap
