### ISSUE TITLE
Dynamic datasets, Laravel

### ISSUE THREAD

**Issue by khlilturki97** [pestphp/pest#459]
Hi, 

In a Laravel project, I am trying to create a dataset that contains primary keys from my database

what i am trying to do in `Datasets/client.php` is 
```
$result=[];
for($i=0; $i < rand(1,5); $i++}{
    $result[] = Client::inRandomOrder()->first()->id;
}
dataset('clients', $result);
```

when i try to run my tests and include the dataset, i get
```

   Error 

  Call to a member function connection() on null

  at vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1653
    1649▕      * @return \Illuminate\Database\Connection
    1650▕      */
    1651▕     public static function resolveConnection($connection = null)
    1652▕     {
  ➜ 1653▕         return static::$resolver->connection($connection);
    1654▕     }
    1655▕ 
    1656▕     /**
    1657▕      * Get the connection resolver instance.

```

as i understood, the problem is that the application has not been bootstrapped.

Is there any solution? 

Thanks

**Comment by owenvoke** [comment]
@khlilturki97, this should be possible using [bound datasets](https://pestphp.com/docs/datasets#bound-datasets). The following should work afaik.

```php
dataset('clients', function () {
    $max = rand(1, 5);
    for ($i = 0; $i <= $max; $i++) {
        yield Client::inRandomOrder()->first()->id
    }
});
```

> Note: I changed the syntax of the `for` block as it seemed like the `$i = rand(1, 5)` would result in an infinite loop as there's no max-number check.

**Comment by khlilturki97** [comment]
@owenvoke thanks for your quick response

I have corrected the for loop in the issue above

i managed to make this work using the following
```
dataset('clients', function () {
    $result = [];
    for ($i = 0; $i < rand(1,5); $i++) {
        $result[] = yield function () {
            return Client::inRandomOrder()->first()->id;
        };
    }
    return $result;
});

**Comment by eleftrik** [comment]
I have a test case similar to @khlilturki97 one. 

Currently, my dataset is

```
dataset('checks', function () {
    $checks = [];
    $i      = 0;

    while ($i++ < 3) {
        $checks[] = yield function () use (&$i) {
            return Check::find($i - 1);
        };
    }

    return $checks;
});

```

It works (even if I don't understand why $i must be passed by reference), but the value 3 is hardcoded. I would like to make `checks` dataset return as many checks as found in the `checks`table.
Is it possible?

Thank you
