### ISSUE TITLE
Proposal: pest-plugin-memory-leak

### ISSUE THREAD

**Issue by nunomaduro** [pestphp/pest#46]
This plugin would detect memory leaks. I have a prototype of this, but seems that PHP itself leaks memory. I need to take a better look at this.

**Comment by nunomaduro** [comment]
Seems quite impossible. PHP itself leaks memory, and composer also allocates memory while discovering classes.

**Comment by maks-rafalko** [comment]
probably related https://github.com/Roave/no-leaks
