### ISSUE TITLE
refacto: create pest-dev-tools

### ISSUE THREAD

**Issue by nunomaduro** [pestphp/pest#47]
Across all the repositories we are using this as `require-dev`:
```
        "ergebnis/phpstan-rules": "^0.14.4",
        "friendsofphp/php-cs-fixer": "^2.16.3",
        "phpstan/phpstan": "^0.12.25",
        "phpstan/phpstan-strict-rules": "^0.12.2",
        "rector/rector": "^0.7.25",
        "symfony/var-dumper": "^5.0.8",
        "thecodingmachine/phpstan-strict-rules": "^0.12.0"
```

Would be cool to create an repository https://github.com/pestphp/pest-dev-tools that contains all of that.

Fell free to perform a pull request.

**Comment by dsampaolo** [comment]
I submitted a PR to pestphp/pest-dev-tools : https://github.com/pestphp/pest-dev-tools/pull/2

Just let me know if I did something wrong.
