### ISSUE TITLE
Backtrace.php error

### ISSUE THREAD

**Issue by howellmartinez** [pestphp/pest#482]
Followed installation instructions for a Laravel project (running 8.x), ran ./vendor/bin/pest and got a `Class "Pest\Support\Backtrace" not found` error.

Running `composer dumpautoload` gives this message `Class Pest\Support\Backtrace located in ./vendor/pestphp/pest/src/Support/?>,m bvc.php does not comply with psr-4 autoloading standard. Skipping.`

Renaming the `?>,m bvc.php` file to `Backtrace.php` in vendor/pestphp/pest/src/Support fixes the issue.

**Comment by fabio-ivona** [comment]
That file is actually called Backtrace.php in pest code, could you try to run

`composer reinstall pestphp/pest`?

**Comment by nunomaduro** [comment]
This is something related to your vendor directory, can you double check that?

**Comment by howellmartinez** [comment]
`composer reinstall pestphp/pest` did the trick, thanks
