### ISSUE TITLE
Uppercase values in a dataset wrongly displayed in the output

### ISSUE THREAD

**Issue by gulien** [pestphp/pest#50]
Hello 👋 

I've encountered a weird "issue" while using a dataset with uppercase values:

```php
->with([
  ['Foo', 'Bar', 'foo.bar@baz.com', LocaleEnum::EN, RoleEnum::ADMINISTRATOR]
])
```

Test output:

![Capture d’écran 2020-05-30 à 16 45 47](https://user-images.githubusercontent.com/8983173/83331220-040cdc80-a295-11ea-8479-eb55e2b7649d.png)

If `'Foo'` is given, I'm expecting it to be displayed as `'Foo'` not `' foo'` 🤔 

Thanks for your time! 😄

**Comment by nunomaduro** [comment]
You can follow that issue here: https://github.com/pestphp/pest/issues/9.

**Comment by gulien** [comment]
@nunomaduro my bad did not find it (should have used 'capitalized' instead of 'uppercase' in my search...).

**Comment by AlexMartinFR** [comment]
I added the keyword to one of my comment.
Other might search for it that way too. Thanks for explaining that 👍
