### ISSUE TITLE
[2.x] Laravel is not detected when using Domain Oriented architecture

### ISSUE THREAD

**Issue by bastien-phi** [pestphp/pest#501]
# How it started

I was running `php artisan test --parallel --recreate-databases` and it appeared that the databases were not recreated.

# What I found

`Illuminate\Testing\ParallelTesting::callSetUpProcessCallbacks` was never called, causing the databases not to be dropped (via the callback defined in `Illuminate\Testing\Concers\TestDatabases::bootTestDatabase`)

This was caused by the fact that the runner used by paratest was `Pest\Parallel\Paratest\Runner` instead of `Illuminate\Testing\ParallelRunner`.

The parallel plugin does not register the correct runner in `Pest\Parallel\Arguments\Laravel::editArguments` because `Pest\Parallel\Support\Environment::isALaravelApplication` does not detect the fact that it is a Laravel application.

# Why 

```php
final class Environment
{
    public static function isALaravelApplication(): bool
    {
        return class_exists('\App\Http\Kernel') && class_exists(ParallelRunner::class);
    }
}
```
The environment detects it is a Laravel application based on the fact that the `App\Http\Kernel` class exists. Unfortunately, using a Domain Oriented approach in Laravel, the `App\Http\Kernel` could be missing and the environment does not detect Laravel.
Renaming the `App` namespace could also make this test to fail.

# How to fix

I think it would be possible to detect the fact that it is a Laravel application using another test but I'm not sure what is the best one in order not to create other issues.

**Comment by bastien-phi** [comment]
Maybe testing that Laravel is installed but Orchestra not could do the trick : 

```php
public static function isALaravelApplication(): bool
{
        return class_exists(\Illuminate\Foundation\Application::class)
            && ! class_exists(\Orchestra\Testbench\TestCase::class);
}
```
or using `composer-runtime-api ^2.0`, it could be possible to change this to 
```php
public static function isALaravelApplication(): bool
{
    return \Composer\InstalledVersions::isInstalled('laravel/framework')
            && ! \Composer\InstalledVersions::isInstalled('orchestra/testbench');
}
```
Again, I'm not sure this won't cause any problem

**Comment by lukeraymonddowning** [comment]
Thanks for your detailed info on this. Do you feel confident enough to open up a PR for it?

**Comment by bastien-phi** [comment]
I can change the implementation (either way) but I just want to be sure I won't broke something I'm not aware of...

**Comment by nunomaduro** [comment]
Please re-open this issue, and the pull request, once the parallel testing plugin is ready for Pest v2.x.
