### ISSUE TITLE
toThrow expectation does not work in higher-order tests

### ISSUE THREAD

**Issue by msvujnovic-becklyn** [pestphp/pest#509]
Given these equivalent test scenarios:

```php
test('exceptions can be tested in a closure test', function() {
    expect(fn() => throw new \InvalidArgumentException())
        ->toThrow(\InvalidArgumentException::class);
});

test('exceptions can be tested in a in a higher order test')
    ->expect(fn() => throw new \InvalidArgumentException())
    ->toThrow(\InvalidArgumentException::class);
```

The first one passes, while the second one fails with the `\InvalidArgumentException` bubbling up. Is it possible to make `toThrow` work in higher-order tests like in the second example?

**Comment by lukeraymonddowning** [comment]
@msvujnovic-becklyn would you be open to submitting a PR to fix this?

**Comment by nunomaduro** [comment]
This issue needs to be fixed on Pest v1, and Pest v2.

**Comment by nunomaduro** [comment]
Cosing due of lack of activity.
