### ISSUE TITLE
Different behavior between phpunit and pest when using depends

### ISSUE THREAD

**Issue by Lukasss93** [pestphp/pest#512]
Hi,
I don't know if this "_bug_" (?) is related to this plugin or to **Pest** itself...

When I run a single test with **PHPStorm**, I noticed that there is different behavior between **PHPUnit** and **Pest** when using `@depends`.

### PHPUnit: correct behavior ✅
![immagine](https://user-images.githubusercontent.com/4071613/161869383-88449789-44df-4f77-bdfa-2a7053bb3954.png)

### Pest: wrong behavior ❌
![immagine](https://user-images.githubusercontent.com/4071613/161869420-8db68ef4-013f-4aed-a3bc-bf8d1a1bd860.png)

It seems the pest plugin doesn't start dependent test.

**Comment by olivernybroe** [comment]
I have moved this bug reported on the IntelliJ plugin to the pest repository as for me it looks like a pest issue. 

If this is in fact something extra I need to do in the plugin, we can move it back 👍

**Comment by pildit** [comment]
I think it's about the naming. 

Can  you try to use : 
 
`->depends('test foo') ` 

It worked for me when i used it like 

`->depends('it foo') `

**Comment by frankroc2022** [comment]
Not working for me.

**Comment by nunomaduro** [comment]
Cosing due of lack of activity.
