### ISSUE TITLE
Pest.php file is called before bootstrap file from phpunit.xml?

### ISSUE THREAD

**Issue by dingo-d** [pestphp/pest#513]
I'm not sure if this is the intended behavior, but it is a bit odd (at least it is to me 😂).

I'm trying to set up WordPress integration tests using Pest. For that to work, I'd have to change the underlying test case from the `PHPUnit\Framework\TestCase` to WordPresses' `WP_UnitTestCase` ([link to class](https://github.com/WordPress/wordpress-develop/blob/trunk/tests/phpunit/includes/testcase.php)). 

After making modifications in the `phpunit.xml` file - changing the `bootstrap` from `vendor/autoload.php` to custom `tests/bootstrap.php` that looks like this:

```php
<?php

// Autoload everything for unit tests.
require_once dirname(__FILE__, 2) . '/vendor/autoload.php';

/**
 * Include core bootstrap for an integration test suite
 *
 * This will only work if you run the tests from the command line.
 * Running the tests from IDE such as PhpStorm will require you to
 * add an additional argument to the test run command if you want to run
 * integration tests.
 */
if (isset($GLOBALS['argv']) && isset($GLOBALS['argv'][1]) && strpos($GLOBALS['argv'][1], 'integration') !== false) {
	// We need to set up core config details and test details
	copy(dirname(__FILE__, 2) . '/wp/wp-tests-config-sample.php', dirname(__FILE__, 2) . '/wp/tests/phpunit/wp-tests-config.php');

	// Change certain constants from the test's config file.
	$testConfigPath = dirname(__FILE__, 2) . '/wp/tests/phpunit/wp-tests-config.php';
	$testConfigContents = file_get_contents($testConfigPath);

	$testConfigContents = str_replace("dirname( __FILE__ ) . '/src/'", "dirname(__FILE__, 3) . '/src/'", $testConfigContents);
	$testConfigContents = str_replace("youremptytestdbnamehere", $_SERVER['DB_NAME'], $testConfigContents);
	$testConfigContents = str_replace("yourusernamehere", $_SERVER['DB_USER'], $testConfigContents);
	$testConfigContents = str_replace("yourpasswordhere", $_SERVER['DB_PASSWORD'], $testConfigContents);
	$testConfigContents = str_replace("localhost", $_SERVER['DB_HOST'], $testConfigContents);

	file_put_contents($testConfigPath, $testConfigContents);

	require_once dirname(__FILE__, 2) . '/wp/tests/phpunit/includes/bootstrap.php';
}
```

I went and in `Pest.php` added:

```php
<?php

uses()->group('integration')->in('Integration');
uses()->group('unit')->in('Unit');

uses(\WP_UnitTestCase::class)->in('Integration');
```

However, running integration tests returns:

```bash
 Pest\Exceptions\TestCaseClassOrTraitNotFound

  The class `WP_UnitTestCase` was not found.
Script @php ./vendor/bin/pest --group=integration handling the test:integration event returned with error code 1
```

Now, what I thought was that the order of execution of tests goes like this:

1. Configuration is set from `phpunit.xml`
2. Additional config is picked up from `Pest.php`
3. Tests are run

But it looks like the `Pest.php` is executed before parsing the `phpunit.xml` and getting the `bootstrap.php` file loaded. And therefore the test fails.

If I comment `uses(\WP_UnitTestCase::class)->in('Integration');` out, I can get the WP integration tests to run (the output looks like the WP integration tests), but they won't work as intended unless the base class for the test is `WP_UnitTestCase` class.

I can just try to manually autoload these files, but I'm not sure if that is the correct way 🤷🏼‍♂️.

Is it intended for `Pest.php` file to be loaded before bootstrap? I cannot add the bootstrapping logic there because I don't have the `$_SERVER` arguments or the `ENV` arguments defined there (which is necessary to setup configuration for the WP part).

What is the best course of action here?

**Comment by lukeraymonddowning** [comment]
Could you try updating your `composer.json` to load in that file? The composer autoloader is booted prior to Pest.php, but if that TestCase isn't registered with PSR-4, it won't be auto-detected.

**Comment by dingo-d** [comment]
I managed to solve this issue, so it shouldn't be a problem anymore, it's just that I kinda thought that Pest.php would be run after the bootstrap file (referenced in phpunit.xml), but I think from the PHPUnit documentation it's actually the correct behavior (bootstrap being run before test cases).
