### ISSUE TITLE
$this context in beforeAll and afterAll

### ISSUE THREAD

**Issue by ZiperRom1** [pestphp/pest#518]
Hello,

Is this possible to access `$this` context in `beforeAll` and `afterAll` Setup and Teardown methods ?

Got a `Using $this when not in object context` when I attempt to and this is frustrating because I need to setup one object in `beforeAll` closure that would be accessible in all testCases.

**Comment by owenvoke** [comment]
It's not possible (in the same way it's not in PHPUnit). 👍🏻 You should use `beforeEach()` and `afterEach()` instead, which are the equivalent of `setUp()` and `tearDown()` in PHPUnit. 🙂
