### ISSUE TITLE
Support for Magento 2

### ISSUE THREAD

**Issue by wpoortman** [pestphp/pest#52]
Would be nice to have support for Magento 2 version 2.3.3 and up.

`composer require pestphp/pest:0.1.5` on minimum-stability "stable"

**Problems**
- Installation request for pestphp/pest ^0.1.5 -> satisfiable by pestphp/pest[v0.1.5].
- pestphp/pest v0.1.5 requires nunomaduro/collision ^5.0 -> satisfiable by nunomaduro/collision[v5.0.0-BETA1] but these conflict with your requirements or minimum-stability.

`composer require pestphp/pest:0.1.5` on minimum-stability "dev"

**Problems**
- Can only install one of: sebastian/environment[5.1.0, 3.1.0].
- Can only install one of: sebastian/environment[5.1.0, 3.1.0].
- Can only install one of: sebastian/environment[5.1.0, 3.1.0].
- pestphp/pest v0.1.5 requires sebastian/environment ^5.1 -> satisfiable by sebastian/environment[5.1.0].
- Installation request for pestphp/pest 0.1.5 -> satisfiable by pestphp/pest[v0.1.5].
- Installation request for sebastian/environment (locked at 3.1.0) -> satisfiable by sebastian/environment[3.1.0].

**Comment by nunomaduro** [comment]
@wpoortman You need to follow exactly this installation process: https://pestphp.com/docs/installation/.

Can you try again and let me know?

**Comment by wpoortman** [comment]
@nunomaduro I've tried at first, but it dragged me into a whole nother dependency struggle.

**Problems**
- magento/magento2-functional-testing-framework 2.4.5 requires codeception/codeception ~2.3.4 || ~2.4.0  -> satisfiable by codeception/codeception[2.4.5, 2.3.4, 2.3.5, 2.3.6, 2.3.7, 2.3...
- codeception/codeception 2.4.0 requires codeception/phpunit-wrapper ^6.0|^7.0 -> satisfiable by codeception/phpunit-wrapper[6.8.1, 6.0.0, 6.0.1, 6.0.10, 6.0.11, 6.0.12, 6.0.13, 6.0...
- codeception/phpunit-wrapper 7.8.0 requires phpunit/phpunit 7.5.* -> satisfiable by phpunit/phpunit[7.5.0, 7.5.1, 7.5.10, 7.5.11, 7.5.12, 7.5.13, 7.5.14, 7.5.15, 7.5.16, 7.5...
- codeception/phpunit-wrapper 7.8.0 requires phpunit/phpunit 7.5.* -> satisfiable by phpunit/phpunit[7.5.0, 7.5.1, 7.5.10, 7.5.11, 7.5.12, 7.5.13, 7.5.14, 7.5.15, 7.5.16, 7.5...

**Comment by nunomaduro** [comment]
Well, you need to support at least phpunit 9.

**Comment by owenvoke** [comment]
By the way, it looks like the next version of the Magento FTF will probably support PHPUnit 9.
https://github.com/magento/magento2-functional-testing-framework/blob/develop/composer.json#L20

**Comment by wpoortman** [comment]
> By the way, it looks like the next version of the Magento FTF will probably support PHPUnit 9.
> https://github.com/magento/magento2-functional-testing-framework/blob/develop/composer.json#L20

I was just about to reply on this topic. Magento 2.4.0 creates a lot of happy faces. I've cloned the develop branch and tried to install Pest on this latest release.

The first few steps looked promising, but have some problems at step 4.

**Problems**
- pestphp/pest v0.1.5 requires nunomaduro/collision ^5.0 -> satisfiable by nunomaduro/collision[v5.0.0-BETA1].
- Installation request for pestphp/pest ^0.1.5 -> satisfiable by pestphp/pest[v0.1.5].
- Conclusion: remove symfony/console v4.4.8
- Conclusion: don't install symfony/console v4.4.8
- nunomaduro/collision v5.0.0-BETA1 requires symfony/console ^5.0 -> satisfiable by symfony/console[5.0.x-dev, 5.1.x-dev, 5.2.x-dev].
- Can only install one of: symfony/console[5.0.x-dev, v4.4.8].
- Can only install one of: symfony/console[5.1.x-dev, v4.4.8].
- Can only install one of: symfony/console[5.2.x-dev, v4.4.8].
- Installation request for symfony/console (locked at v4.4.8, required as ~4.4.0) -> satisfiable by symfony/console[v4.4.8].

**Comment by owenvoke** [comment]
Yeah, looks like Magento 2.4 will still use Symfony 4, however Pest (via Collision) requires Symfony 5.
