### ISSUE TITLE
[feature] Public access method to Dataset

### ISSUE THREAD

**Issue by ZiperRom1** [pestphp/pest#521]
Hello,

In some tests I needed to access a `dataset` into a `test` for some processing before testing.

I used 

```php
foreach (\Pest\Datasets::get('my_dataset') as $data) {
    // ...
}
```

With success but with IDE warning about accessing internal function : `Class Datasets is marked as @internal`.

It could be good to allow users to access `dataset` "legally" with a function.

**Comment by nunomaduro** [comment]
Closing due of lack of activity.
