### ISSUE TITLE
Allow lazy datasets to have a custom description

### ISSUE THREAD

**Issue by IAmRGroot** [pestphp/pest#527]
I'm using pest with Laravel and I would like to have a description to the following lazy dataset, but I can't seem to do that.

```php
dataset('user', function () {
    yield fn () => User::factory()->make();
});


it('should work', function (User $user) {
    expect(true)->toBe(true);
})->with('user');
```

Right now this dataset resolves to `(Closure Object (...))` in the output, but I would like to customize that. It would be ideal if this would work:

```php
dataset('user', function () {
    yield [ 'user' => fn () => User::factory()->make() ];
});
```

The following works, but is not lazy:
```php
dataset('user', [
    'user' => [ fn () => User::factory()->make() ]
]);
```

**Comment by olivernybroe** [comment]
@dr41d45 Could you please confirm that you copy/pasted the right output?

Looking at your result, it says `test for all`, however your test name is `it has emails`.

**Comment by fabio-ivona** [comment]
@dr41d45  could you check the code you pasted? the result's text doesn't match your test description

if I run your code here's what gets printed:

![image](https://user-images.githubusercontent.com/8792274/170667564-a4f3ab0d-c599-42e9-83af-0c066d4b0cc4.png)

**Comment by IAmRGroot** [comment]
Why is this closed? My issue was specific for lazy datasets and the following doesn't work:

```php
dataset('user', function () {
    yield [ 'user' => fn () => User::factory()->make() ];
});
```
Gives 
![image](https://user-images.githubusercontent.com/8398505/170943694-35b139a8-985b-4ac3-9433-3fdeddf7e51e.png)


```php
dataset('user', function () {
    yield fn () => User::factory()->make();
});
```
Gives 
![image](https://user-images.githubusercontent.com/8398505/170943773-ec5330df-d0cc-4056-a0b5-9611783f813f.png)

**Comment by IAmRGroot** [comment]
@fabio-ivona see above comment

**Comment by fabio-ivona** [comment]
@IAmRGroot v1 is on feature freeze, so it is not a planned feature. We are evaluating internally if it's worth to include it in v2
