### ISSUE TITLE
Weird Behavior When using Laravel Factory Within Datasets?

### ISSUE THREAD

**Issue by amrmsccs** [pestphp/pest#528]
I have tried using `UserFactory::class` within a Dataset i.e my Dataset name is 
According to this suggestion I tried but didn't succeed as well [https://laracasts.com/discuss/channels/laravel/factory-cant-be-seen-in-unit-test?page=1&replyId=563688](url)
> Users.php

  `<?php

      use App\Models\User;
      use Illuminate\Foundation\Testing\RefreshDatabase;
      /** 
       * According to different Suggestions I found to 
       * Use Tests\TestCases instead of Laravel PHPUnit\Framework\TestCase
       * **/
      use Tests\TestCase; // In Use
      //use PHPUnit\Framework\TestCase; //Tested As Well and Not working.
      
      
      //This should not be here but I tried to Call uses TestCase::class to overcome the problem. 
      // Did not Succeed
      uses(RefreshDatabase::class, TestCase::class);
      
      dataset('admin', function () {
          return User::factory(1)->make();
      });
`

Within my UserTest.php calling the Dataset code is : 

      `
        it('redirects to user profile', function ($admin) 
              actingAs($admin)->get('/admin/profile')->assertSee($user->name);
        })->with('admin');
      `
The result is Error 

    

> InvalidArgumentException 

  Unknown format "lastName"

  at vendor/fakerphp/faker/src/Faker/Generator.php:723
    719▕                 return $this->formatters[$format];
    720▕             }
    721▕         }
    722▕ 
  ➜ 723▕         throw new \InvalidArgumentException(sprintf('Unknown format "%s"', $format));
    724▕     }
    725▕ 
    726▕     /**
    727▕      * Replaces tokens ('{{ tokenName }}') with the result from the token method call

      +2 vendor frames 
  3   database/factories/UserFactory.php:24
      Faker\Generator::__call("lastName", [])

      +6 vendor frames 
  10  [internal]:0
      Illuminate\Database\Eloquent\Factories\Factory::Illuminate\Database\Eloquent\Factories\{closure}()

 When I've over come the problem by not using factory within Datasets.

My Composer Json Versions as follow: 
  `
    "php": "^8.0",
    "laravel/dusk": "^6.11",
    "laravel/framework": "^9.0",
Dev-Dep: 
    "fakerphp/faker": "^1.9.2",
    "pestphp/pest-plugin-laravel": "^1.2",
     "pestphp/pest-plugin-parallel": "^1.0",
      "phpunit/phpunit": "^9.3.3",

`

**Comment by wvandeweyer** [comment]
Did you install the pest faker plugin?
https://pestphp.com/docs/plugins/faker

**Comment by fabio-ivona** [comment]
@amrmsccs  when your dataset tries to make a user from factory, the Application is not yet loaded. In order to achieve this you should wrap the factory call in a closure and return the dataset as a generator (using `yield`):

```php
dataset('admin', function () {
    yield fn() => User::factory()->make(); // user 1

    yield fn() => User::factory()->make(); // user 2
});

it('redirects to user profile', function ($admin) {
    actingAs($admin)->get('/')->assertSee($admin->name);
})->with('admin')->only();
```

![image](https://user-images.githubusercontent.com/8792274/171130535-86ef370c-06ff-4b6c-a312-5bc280d97633.png)
