### ISSUE TITLE
Plugin::uses() does not work properly on windows

### ISSUE THREAD

**Issue by dimitrioskarvounaris** [pestphp/pest#53]
I'm trying to write a plugin and I'm using Pest\Plugin::uses() to add a trait.

When I require the plugin, the test suite stops working alltogether with the following message:

    $ vendor/bin/pest
       Pest\Exceptions\InvalidUsesPath
       The path `I:\Code\aurora\vendor\pestphp\pest\src\I:\Code\aurora\tests` is not valid.

I tracked the issue down to `src/PendingObjects/UsesCall.php` lines 63-68, which are adding the extra path to what is already a full path under Windows.

**Comment by dimitrioskarvounaris** [comment]
Fix submitted https://github.com/pestphp/pest/pull/54

**Comment by fetzi** [comment]
@dimitrioskarvounaris is this one fixed now?

**Comment by dimitrioskarvounaris** [comment]
This and other windows issues are fixed by https://github.com/pestphp/pest/pull/61 now
