### ISSUE TITLE
Database Transactions causing locks

### ISSUE THREAD

**Issue by kristoffermodified** [pestphp/pest#533]
When using the laravel trait `DatabaseTransactions` it causes issues in combination with Mockery when running multiple tests at once.
It seems to be caused by locks on the database, and them not being reset with the `DatabaseTransactions` trait.
![image](https://user-images.githubusercontent.com/50329393/175296158-3d13d1d6-8f3c-428d-983a-d3cdf3438c3b.png)

I think the process goes something like this:
1. Begin the transaction
2. Run the test
3. Handle any hooks (Mockery::close)
4. rollback the transaction

On step 3 it throws the Mockery exception (InvalidCountException) which is not caught by Pest, which then causes the transaction to never get rolled back.

I set up a new Laravel installation with Pest and the mockery plugin here: https://github.com/kristoffermodified/pest-php-mockery-error

Run the tests/Unit/ExampleTest.php file, and you will notice the error.

**Comment by nunomaduro** [comment]
This is not a Pest issue.
