### ISSUE TITLE
Calling test() with no parameters gives a "This should not happen..." error message

### ISSUE THREAD

**Issue by ceilidhboy** [pestphp/pest#535]
The following test file is all you need to create the issue

```
<?php

test();
```
Running this test gives the following error message:

```
This should not happen - please create an new issue here: https://github.com/pestphp/pest.

- Issue: Trying to create a test without description.
- PHP version: 8.1.7
- Operating system: Linux
```

Cute :) 

Seems pretty obvious what the problem is but it shouldn't generate a "This should not happen..." message and request a bug report :)

**Comment by nunomaduro** [comment]
Can you make a pull request that addresses this issue please?

**Comment by nunomaduro** [comment]
Fixed in `2.x`.
