### ISSUE TITLE
RefreshDatabase recreates database on every test

### ISSUE THREAD

**Issue by boobooking** [pestphp/pest#539]
If I understand correctly how **RefreshDatabase** should work - it should keep database up to date with migrations, and run all tests in database transactions.

What I see now is that RefreshDatabase recreates database with every test - it works the same as **DatabaseMigrations** does.

What am I missing or cooking wrong?

**Comment by fabio-ivona** [comment]
Is your database "in-memory"? Laravel migrates in memory databases before each tests

Source code for reference https://github.com/guiwoda/laravel-framework/blob/master/src/Illuminate/Foundation/Testing/RefreshDatabase.php

**Comment by boobooking** [comment]
No, not in-memory database in my case. I run tests using MySQL database.

And here is the configuration of traits I use:
uses(TestCase::class, CreatesApplication::class, RefreshDatabase::class)
    ->in('Feature', 'Unit');

**Comment by sambenne** [comment]
I have tested this on MySQL using the latest version and can not replicate your issue.

**Comment by nunomaduro** [comment]
This is not a Pest issue.

**Comment by ed-vieira** [comment]
This happened to me today using Postgres. I agree it's not a problem related to Pest, but this code shouldn't come by default in a fresh Laravel installation.

``
pest()->extend(TestCase::class)
``
``
       ->use(Illuminate\Foundation\Testing\RefreshDatabase::class)
``
``
       ->in('Feature');
``

 I hadn't even noticed it was configured to run this way, and honestly, I don't see much sense in it. I'd really have to want it to happen to keep recreating data all the time. Today, the AI ​​agent ran the tests and deleted data I didn't want deleted.

Now I'll have to do work I didn't need to do, and remember to remove this line of code from every new application.
