### ISSUE TITLE
Target class [request] does not exist.

### ISSUE THREAD

**Issue by PH7-Jack** [pestphp/pest#541]
### Description
When I'm testing a blade component that has many usages of the request class, the test fails. If I run the same code in the PHPUnit test it works. 
PS: if the test is moved to the feature namespace the request class can be used

### Versions
```
php 8.1
laravel 9.19
pest 1.21
pestphp/pest-plugin-laravel 1.2
```

### test
/tests/Unit/ExampleTest.php
```
it('should create the app routes', function () {
    dd(request());
});
```

### Error
![image](https://user-images.githubusercontent.com/38913462/178126508-9bff56fd-a74e-4bcd-a155-38a73c844e0b.png)

**Comment by owenvoke** [comment]
The request class is pulled from the container, and therefore requires using a TestCase with app access. You'll probably need to do this as a feature test, or add a `uses()` call with your TestCase class.
