### ISSUE TITLE
./vendor/bin/pest throws error

### ISSUE THREAD

**Issue by wilpat** [pestphp/pest#547]
I just installed the version 1.21 of pestphp/pest for a small php library.

Installations works until I try running `./vendor/bin/pest`

I keep getting this error: `Exclusive locks are not supported for this stream`

Research on this error has proven unsuccessful as I could not find a similar case.

Please let me know if you've experienced this before and how you fixed it.

Thanks!

**Comment by fabio-ivona** [comment]
Hi, could you past here the full console output?

**Comment by wilpat** [comment]
Hi @fabio-ivona the full error was `file_put_contents(): Exclusive locks are not supported for this stream`

I have figured out the issue.
I was running this from the htdocs of the vm version of xampp running on my laptop.

Taking the project out of here solved this issue.

Thanks!
