### ISSUE TITLE
Calling `toMatchArray()` with an empty array performs no assertions.

### ISSUE THREAD

**Issue by juanpferreira** [pestphp/pest#548]
Basically
```
test('matching empty arrays', function () {
    expect([])->toMatchArray([]);
});
```
results in a risked test because it performs no assertions. I know that `toBeEmpty()` exists, but when receiving the expected result from a dataset, it would be simpler to just pass the expected array and have it succeed if both are empty. I suppose that simply comparing the length inside `toMatchArray()` (additionally to the current assertions) would be enough to prevent this.

**Comment by fabio-ivona** [comment]
toMatchArray check against a subset, iterating its elements

You should use `expect([])->toBe([])`
