### ISSUE TITLE
PHP Storm Pest plugin readme update

### ISSUE THREAD

**Issue by lasseeee** [pestphp/pest#549]
The path in the PHP Storm Pest plugin readme reads 

> Navigate to Preferences > Languages & Frameworks > PHP > Test Frameworks 

it should be updated to 

> Navigate to Preferences > PHP > Test Frameworks

**Comment by olivernybroe** [comment]
@lasseeee thanks. Yes PHP Storm made this change in the last year, however the old path is still valid when using IntelliJ Idea. 

I think the best solution here would be to just have both paths in the readme and state that one of them is for PhpStorm and the other is for other IDE's. 

Feel free to submit a PR 👍
