### ISSUE TITLE
Question : Orchestra annotation

### ISSUE THREAD

**Issue by ElRochito** [pestphp/pest#553]
Hi,

How we can use `@environment-setup` annotation from `orchestral/testbench` on a Pest test ?

Thanks

**Comment by nunomaduro** [comment]
No.

**Comment by nunomaduro** [comment]
In fact, you can. Create a regular class, that extends the base test case from `testbench`, and add that annotation. After, use the `uses` in your own test case.

**Comment by ElRochito** [comment]
Ok thanks, but I don't see where to add the annotation :(

**Comment by AyoobMH** [comment]
@ElRochito , there is a workaround but it isn't the best.
1. Define a trait that you want to include your environment setup in
```php
trait Configure {
   public function disableConfig($app) {
      // ... your code here
   }
}
```

2. Use the trait in your test file using `uses`
```php
uses(Configure::class);

// your tests here
test('my test')
```

3. In your TestCase.php, check if the the disableConfig exists during environment setup
```php
protected function getEnvironmentSetUp($app) {
  // ... define your env configuration here
  
  if (method_exists($this, 'disableConfig')) {
     $this-> disableConfig($app);
  }
}
```
