### ISSUE TITLE
[PHP 8.2] Handling dynamic properties?

### ISSUE THREAD

**Issue by dingo-d** [pestphp/pest#555]
I'm wondering what is the correct way of handling dynamic properties defined in the `beforeEach` method?

In the documentation there is the following example:

```php
beforeEach(function () {
    $this->hey = 'artisan';
});
 
it('has artisan', function () {
    echo $this->hey;
});
```

But in PHP 8.2, dynamic properties are deprecated, and this will throw a notice that will fail the tests:

> Whoops\Exception\ErrorException: Creation of dynamic property P\Tests\Unit\Example\ExampleTest::$hey is deprecated

**Comment by nunomaduro** [comment]
@fabio-ivona Can you take this one? We need to fix this on Pest v1.x, and Pest v2.x.

**Comment by fabio-ivona** [comment]
Sure, but I'm out on vacation, will be back on 22nd of August

If it is not too late, I'll handle it
