### ISSUE TITLE
throws() needs to check the thrown exception

### ISSUE THREAD

**Issue by jefhar** [pestphp/pest#573]
As a part-time practitioner of TDD, I write a test expecting a new exception, then write the code to throw the new exception, and at some point I expect my test suite to say that the new exception does not exist. Pest does not report that the exception does not exist.

Minimal example:
```php
function throwARandomException()
{
    throw new \This\Namespace\Does\Not\Exist();
}

it('catches an exception that does not exist', function () {
    throwARandomException();
})->throws(\This\Namespace\Does\Not\Exist::class);
```

This incorrectly passes.

I believe the `throws()` checks that if the class does not exist, it expects to find the string in the message, so the `new RuntimeException("\This\Namespace\Does\Not\Exist::class does not exist")` passes the secondary check, but it is not the exception that I'm looking for.

**Comment by fabio-ivona** [comment]
Hi @jefhar! Thanks for pointing this out. We'll have a look at it soon

**Comment by nunomaduro** [comment]
It does not look like a bug to me.
