### ISSUE TITLE
RFC: Pest Plugin registration

### ISSUE THREAD

**Issue by fetzi** [pestphp/pest#59]
So atm we have 3 different ways how pest is extensible:

* a file with helper functions loaded with PSR-4 autoloading
* Traits or classes with `Plugin::uses` and also PSR-4 autoloading
* Composer plugin with interfaces (`HandlesArguments` & `AddsOutput`) with auto registration on install

I think we should make it easier for plugin developers to get started. I would suggest to have only the helper functions and the other way through the auto registration.

Otherwise I'm afraid that the plugin docs will get hard to understand.

**Comment by AlexMartinFR** [comment]
_Disclaimer: I haven't written any plugin nor studied them, so this opinion is general and rhetorical, take it as is._

If there is no drawback and the three options offer the same extensibility, it makes sense to me to enforce one.

Too many choices can lead to decision fatigue and prevent good future contributions.

**Comment by dimitrioskarvounaris** [comment]
It was easy to understand the `Plugin::uses()` while I started working on it... easier, than the composer plugin interfaces, which I haven't yet fully understood how it's done. 

So, I'm for keeping all of these. I don't see it, that it will make it more hard for people, rather the opposite. The uses() is extremely simple to handle and something people may be already used to it from writing tests.
