### ISSUE TITLE
Property access via dot notation

### ISSUE THREAD

**Issue by ntnp** [pestphp/pest#594]
Currently, when working with int-keyed arrays, `HigherOrderExpectation` allows this syntax:

``` PHP
expect(...)
    ->data->books->{0}->name->toBe('A Dream of Spring');
````

Personally, using `->books->{0}` looks a bit hacky. As a workaround we could easily allow the following syntax, which would still be backwards compatible with the one above:

``` PHP
expect(...)
    ->data
    ->{'books.0.name'}->toBe('A Feast for Crows')
    ->{'books.1.name'}->toBe('A Dream of Spring');
```

Is there a reason this would be bad looking?

**Comment by nunomaduro** [comment]
Can you create a pull request for this for the `2.x` branch?
