### ISSUE TITLE
How to access TestCase before parent setUp calls?

### ISSUE THREAD

**Issue by zolotov88** [pestphp/pest#60]
I need to set some parameters parameters in test class before Laravel application creates. How can I do that?

**Comment by zolotov88** [comment]
No. Laravel application creates in TestCase setUp. Funtion beforeAll starts after parnt setUp.
```php
...
abstract class TestCase extends BaseTestCase
{
    use ...

    protected function setUp(): void
    {
        parent::setUp(); // <-- createApplication() runs here

        $uses = array_flip(class_uses_recursive(static::class));

        if (isset($uses[MyMigrateDatabase::class])) {
            $this->refreshDatabase();
        }
        if (isset($uses[MySeedDatabase::class])) {
            $this->seedDatabase(); // <-- I need pass data here
        }
        if (isset($uses[MyUseDatabaseTransaction::class])) {
            $this->beginDatabaseTransaction();
        }
    } // <-- beforeAll() runs here 
}
```

**Comment by fetzi** [comment]
So you need to create a custom class extending `TestCase` and inside of the class you can override the `setUp` function and set your data before the `parent::setUp()` call.

**Comment by zolotov88** [comment]
You see that custom class below. How can I pass data from pest test file? Maybe I can make function like beforeAll() and call it myself? How can I do?

**Comment by nunomaduro** [comment]
@zolotov88 Did you find your answer? If yes, can you close this issue?

**Comment by zolotov88** [comment]
@nunomaduro I still do not know how to make beforeAll() analog that will starts before setUp method of TestCase class.

**Comment by nunomaduro** [comment]
No plans to have this.
