### ISSUE TITLE
Cannot access to config('...') or env('...') from test function

### ISSUE THREAD

**Issue by dewelooper** [pestphp/pest#606]
Hello,
Im pretty new in Pest (and PHP UNIT also).

Im facing with strange situation.

I have two PHP projects on my laptop handled by the same enviroment (no docker containers) where I want to start dealing with Pest.

One project is running on laravel 8 and second on laravel 9. Im using PHP 8.1 and newest phpunit (9.5.25).

I installed PEST by default from official site without any problems.

Finally on newest project everything working properly but on old one when i want to get for example value from config file or env file I got error:

```
   Illuminate\Contracts\Container\BindingResolutionException 

  Target class [config] does not exist.

  at vendor/laravel/framework/src/Illuminate/Container/Container.php:879
    875▕ 
    876▕         try {
    877▕             $reflector = new ReflectionClass($concrete);
    878▕         } catch (ReflectionException $e) {
  ➜ 879▕             throw new BindingResolutionException("Target class [$concrete] does not exist.", 0, $e);
    880▕         }
    881▕ 
    882▕         // If the type is not instantiable, the developer is attempting to resolve
    883▕         // an abstract type such as an Interface or Abstract Class and there is

      +6 vendor frames 
  7   tests/Unit/Services/AutoLoginLinkServiceTest.php:81
      config("app.url")
```

When I write test in raw PHPUNIT I can get data from conf(..) or  env(...)

Project has standard configuration without any additional manipulations.

(I tried composer du and clearing cache without any results)

Somebody know why this dont work? Can I check something more?

Thank you
K

**Comment by alexmanase** [comment]
Hi there! Can you check if the test case is included in your test files, in `Pest.php`?

**Comment by dewelooper** [comment]
Hello,
yes, this was the reason.

I dont know what on old project Pest installed file with commented this one line and on new one without.

Anyway thank you for your help!
