### ISSUE TITLE
Running tests with coverage mode on PHP8.1 returns error

### ISSUE THREAD

**Issue by dingo-d** [pestphp/pest#607]
I'm using Laravel Valet with PHP 8.1:

```bash
PHP 8.1.10 (cli) (built: Sep  3 2022 12:09:27) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.10, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.10, Copyright (c), by Zend Technologies
    with Xdebug v3.1.4, Copyright (c) 2002-2022, by Derick Rethans
```

The version of pest and plugin is

```bash
pestphp/pest                        v1.22.0 An elegant PHP Testing Framework.
pestphp/pest-plugin                 v1.0.0  The Pest plugin manager
phpunit/phpunit                     9.5.5   The PHP Unit Testing framework.
```

When I set the xdebug mode to be `coverage`, and run my tests using `vendor/bin/pest --coverage` I get

> Undefined array key 403

as error.

I tried debugging what could be wrong, and managed to go to `vendor/phpunit/phpunit/src/TextUI/TestRunner.php` on line 666 (😈 )

```php
$suite->run($result);
```

After this line the thing dies with the above error.

I'll try to see if I can debug this further using Xdebug, but not sure why this happens.

My guess is that it happens because of PHPUnit version, because when I run it with:

```bash
pestphp/pest                        v1.22.1 An elegant PHP Testing Framework.
pestphp/pest-plugin                 v1.1.0  The Pest plugin manager
phpunit/phpunit                     9.5.26  The PHP Unit Testing framework.
```

The tests pass.

Also, tests are passing on all other versions (PHP 7.4, 8, 8.2).

<img width="359" alt="image" src="https://user-images.githubusercontent.com/8638515/200831315-9bff584f-6705-4682-a388-0ffee903ba52.png">

**Comment by nunomaduro** [comment]
I am unable to reproduce this issue. Sorry!

**Comment by dingo-d** [comment]
Also, this happens when I set the `xdebug.mode=coverage` in the `xdebug.ini` settings, but when I have it set to `debug,develop` and try to trigger the coverage using `XDEBUG_MODE=coverage vendor/bin/pest --coverage` I get a notification 

> Unable to get coverage using Xdebug. Did you set Xdebug's coverage mode?

I'll try to create a minimum reproducible example.

**Comment by dingo-d** [comment]
Indeed I cannot reproduce with an MRE, but with it, I get the above error about Xdebug coverage (which is odd, as it should work fine).

I did manage to get the stack trace and from the looks of it, it seems that parsing the code coverage fails in the Lexer.php from the PhpParser.

On further inspection, the 'lowest' dependency which is loaded when I run `composer update --prefer-lowest --prefer-stable` will load the `nikic/php-parser` lib version 4.10.2, which throws the error about missing token, when parsing the following part of the code:

```php
$parser = function (
			\SimpleXMLElement $element,
			?Node $parentNode = null,
			?array $children = []
		) use (&$parser) { // The & part trips the lexer out, as it doesn't have this token in the token map list and it errors out.
			$attributes = $element->attributes();
```

I reproduced this when I installed that version and let it parse the same code

```bash
PHP Warning:  Undefined array key 403 in /home/dzoljom/Projects/Personal/pest-issue607/vendor/nikic/php-parser/lib/PhpParser/Lexer.php on line 324
PHP Fatal error:  Uncaught TypeError: PhpParser\Lexer::getNextToken(): Return value must be of type int, null returned in /home/dzoljom/Projects/Personal/pest-issue607/vendor/nikic/php-parser/lib/PhpParser/Lexer.php:364
Stack trace:
#0 /home/dzoljom/Projects/Personal/pest-issue607/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php(208): PhpParser\Lexer->getNextToken()
#1 /home/dzoljom/Projects/Personal/pest-issue607/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php(158): PhpParser\ParserAbstract->doParse()
#2 /home/dzoljom/Projects/Personal/pest-issue607/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php(51): PhpParser\ParserAbstract->parse()
#3 /home/dzoljom/Projects/Personal/pest-issue607/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php(32): PhpParser\Parser\Multiple->tryParse()
#4 /home/dzoljom/Projects/Personal/pest-issue607/parsertest.php(62): PhpParser\Parser\Multiple->parse()
#5 {main}
  thrown in /home/dzoljom/Projects/Personal/pest-issue607/vendor/nikic/php-parser/lib/PhpParser/Lexer.php on line 364
```

So it's not the Pest's fault, but the code coverage coupled with code parsing on a specific lib version 🤷🏼‍♂️
