### ISSUE TITLE
Lazy datasets ignore description keys

### ISSUE THREAD

**Issue by ragulka** [pestphp/pest#608]
Given the following test:

```php
it('has emails', function ($email) {
    expect($email)->not->toBeEmpty();
})->with(function() {
    yield 'james' => 'james@laravel.com';
    yield 'taylor' => 'taylor@laravel.com';
});
```

I would expect the test description to be `it has emails with data set "james"`.

Instead, the test description is `it has emails with (james@laravel.com)`

Would it be possible to support description keys for lazy datasets?

**Comment by nunomaduro** [comment]
Can you check if this PR caused a regression there? https://github.com/pestphp/pest/pull/603.

**Comment by ragulka** [comment]
@nunomaduro I'm not able to verify if it's that exact PR, but the issue does indeed _not_ occur in v `1.22.1`. I also looked at the PR and it does sound like it may be the cause.

**Comment by alexmanase** [comment]
@nunomaduro I will try to create a PR with the fix.

**Comment by nunomaduro** [comment]
@alexmanase Fixed on `v1.x`. Can you pull request this fix to `v2.x` please?

**Comment by alexmanase** [comment]
@nunomaduro done. https://github.com/pestphp/pest/pull/620
