### ISSUE TITLE
Code coverage not working php 8.1.8 & xdebug 3

### ISSUE THREAD

**Issue by marcLeeroy** [pestphp/pest#611]
First off, great tool!

My issue is this:

Using php 8.1.8 with xdebug loaded and in coverage mode. running Pest 1.21.3

i get

![image](https://user-images.githubusercontent.com/59919105/202191695-6559e168-4721-48da-947b-af49cab5b90a.png)

![image](https://user-images.githubusercontent.com/59919105/202191558-24dbabd2-875e-43e9-a4f2-7e65ba186e91.png)

is there something i'm missing here?

thanks

**Comment by nunomaduro** [comment]
I am not facing that issue locally. It must be something related to your environment configuration. As a workaround, you can try to use a different coverage driver.
