### ISSUE TITLE
📝 Docs - POST `application/x-www-form-urlencoded`

### ISSUE THREAD

**Issue by Rikj000** [pestphp/pest#615]
How can one correctly pass parameters as `application/x-www-form-urlencoded` data to POST endpoints?

I've been struggling to get this working as following:
```php
it('asserts response code + result', function () {
    // Initialize data
    $request = ['parameter' => 'foo'];
    $response = ['code' => 200, 'result' => 'bar'];
    $headers = ['Content-Type' => 'application/x-www-form-urlencoded'];
    
    // Test case
    $test_response = $this->post('api/endpoint', $request, $headers);
    $test_response->assertStatus(200)->assertJson($response);
});
```

The API I'm working within my example,   
expects request data as `application/x-www-form-urlencoded` and responds with `application/json`.

**Comment by nunomaduro** [comment]
Please only use this issue tracker for reporting bugs with the library itself.

**Comment by Rikj000** [comment]
Excuses,   
moved to discussions #617 as it seems a more appropriate place + my issue is not resolved yet.
