### ISSUE TITLE
Assert in afterEach

### ISSUE THREAD

**Issue by HugoHeneault** [pestphp/pest#622]
Hi there 👋 

First, love Pest. Thanks for your great work!

I'my trying to detect duplicated queries using https://github.com/beyondcode/laravel-query-detector
So I created a beforeEach and afterEach method which check it for each test.

```php 
// Pest.php

use BeyondCode\QueryDetector\Events\QueryDetected;
use Illuminate\Foundation\Testing\LazilyRefreshDatabase;
use Illuminate\Foundation\Testing\RefreshDatabaseState;
use Illuminate\Foundation\Testing\TestCase;
use Illuminate\Support\Facades\Event;
use Tests\CreatesApplication;
$beforeEach = function (): void {
    Event::fake([
        QueryDetected::class,
    ]);
};

$afterEach = function (): void {
    $duplicatedQueries = Event::dispatched(QueryDetected::class);
    if ($duplicatedQueries->isNotEmpty()) {
        // ray so we can debug n+1 queries
        ray($duplicatedQueries->all());

        // allow DB refresh on next test becase throwing here will stop pest DB refresh process
        RefreshDatabaseState::$lazilyRefreshed = false;
    }

    Event::assertNotDispatched(QueryDetected::class);
};

uses(TestCase::class, CreatesApplication::class, LazilyRefreshDatabase::class)
    ->beforeEach($beforeEach)
    ->afterEach($afterEach)
    ->in('Feature', 'Unit')
;
```
It works great!

But after a few hundred tests, it gets stuck. 
I suspect that asserting/throwing `Event::assertNotDispatched(QueryDetected::class);` in an afterEach test stops the ` tearDown` / cleaning process after each test and that lead to oom?

If I remove `Event::assertNotDispatched(QueryDetected::class);` everything runs as usual
 
Is there a way to assert in afterEach ?

Thanks :)

**Comment by nunomaduro** [comment]
I don't think is possible.

**Comment by HugoHeneault** [comment]
Well FYI it is possible. It seems I had some sail bug and now it works fine. 

So we can still throw in `afterEach` and it'll make test fail.
