### ISSUE TITLE
Is it possible to define the base test class, after the bootstrap is loaded?

### ISSUE THREAD

**Issue by dingo-d** [pestphp/pest#623]
In the [documentation](https://pestphp.com/docs/underlying-test-case) about the underlying test case, it's mentioned how we can change the default test class from `PHPUnit\Framework\TestCase` to any other that we may want.

Is there a way, to change the test class **after** the `bootstrap.php` file is loaded, besides defining the `uses()` in every test file?

I have a situation where the test class only becomes available after `bootstrap.php` file has been processed (I blame WordPress). So I cannot use that class in the `Pest.php` file (I get an error about it not existing).

The only workaround is adding the `uses()` function on the top of every test that depends on it, which is kinda tedious, and makes code like

```php
uses(TestCase::class)->in('Integration');
uses(OtherTestCase::class)->in('Unit');
```
impossible to use.

Is there some sort of 'middleware' that I could use to set the base test class in one place, but after the bootstrapping process?

I'm using Pest v1.22.3.

**Comment by nunomaduro** [comment]
I don't think is possible.

**Comment by dingo-d** [comment]
Yeah, suspected as such. Thanks 👍🏼
