### ISSUE TITLE
Unable to create test case for test file

### ISSUE THREAD

**Issue by devxarif** [pestphp/pest#624]
I encountered the following error after installing the pest package. I'm not sure why I keep getting this error. Help me, please

## After pressing "php artisan test or./vendor/bin/pest" the error appears as shown in the following screenshot.
![Screenshot from 2022-12-13 20-43-05](https://user-images.githubusercontent.com/39763885/207365003-c112c19f-3c99-4772-92e4-2e80f22b8572.png)

## This is how my AuthenticationTest.php file looks:
![Screenshot from 2022-12-13 20-43-46](https://user-images.githubusercontent.com/39763885/207365189-f24a390f-e76b-43b0-b1d6-23a3409f8e0e.png)

## This is how my web.php file looks:
![Screenshot from 2022-12-13 20-44-30](https://user-images.githubusercontent.com/39763885/207365392-b9cfe65b-f476-4f56-b4f2-3dbc45bb4f40.png)

**Thank you**

**Comment by fabio-ivona** [comment]
Hi, could you try to move your project to a folder tree without a `'` character in directory names?

**Comment by devxarif** [comment]
@fabio-ivona Sorry i did'nt get it. Please be more specific in order for me to understand.

**Comment by fabio-ivona** [comment]
I see that one of your project path folders has a `'` in it (Arif's Important)

I was wondering if the character led to the error

**Comment by devxarif** [comment]
@fabio-ivona Thank you so much. It was fixed
