### ISSUE TITLE
Test is duplicated in the CLI when an error occurs in `tearDownAfterClass` method

### ISSUE THREAD

**Issue by stein-j** [pestphp/pest#627]
### The issue

As I was trying to setup my environnement, I ended up creating an error in the `tearDownAfterClass` and the last test from the file/class ended up being displayed twice in the CLI: Once that is has succeeded and a second time that is has failed, but it didn't actually run the test a second it.
 
```
   FAIL  Tests\Feature\ExampleTest
  ✓ it can say Hello to the World
  ⨯ it can say Hello to the World

  Exception in P\Tests\Feature\ExampleTest::tearDownAfterClass
  Call to undefined method P\Tests\Feature\ExampleTest::randomError()

  Tests:  1 failed, 1 passed, -1 pending
  Time:   0.11s
```

I have tried this on a fresh project, and the test doesn't run any code:
```php
expect(true)->toBeTrue();
```

> Note: Make sure to notice at the end of the CLI output, it says "1 failed, 1 passed, -1 pending" so this could be a lead.

> Note 2 : I noticed as I was writing this issue that the documentation says to call [afterAll()](https://pestphp.com/docs/setup-and-teardown#afterall), so maybe I shouldn't even call `::tearDownAfterClass()` in the first place ?

### How to reproduce:

1. Add the `tearDownAfterClass` static function in your TestCase. Make sure you generate an error inside of that method :
```php
<?php

namespace Tests;

use Illuminate\Foundation\Testing\TestCase as BaseTestCase;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;


    public static function tearDownAfterClass(): void
    {
        static::randomError();
        
        parent::tearDownAfterClass();
    }
}
```

2. Call your test and check the console output.

**Comment by nunomaduro** [comment]
Are you able to reproduce this issue with Pest `v2.x`?

**Comment by stein-j** [comment]
No I cannot reproduce this issue with Pest `v2.x` as I need access to the `TestCase` class to call `tearDownAfterClass` to test this issue. I do not know how to have this class outside of a Laravel environnement.

It would seem `v2.x` may be installed only on Laravel 10, but there are conflicts as L10 needs [PhpUnit ^9.5](https://github.com/laravel/laravel/blob/9fb954fb909d1f742978efb3a08207ff45e37e91/composer.json#L20) but Pest 2.x needs [PhpUnit  10.x](https://github.com/pestphp/pest/blob/0e98c5c5c49589bd3f983f9057a8fa1403817b5e/composer.json#L24).

**Comment by nunomaduro** [comment]
Pest `v1.x` is only open for critical bug fixes at this point. Feel free to try to reproduce this issue with Pest `v2.x`. For that, you need Laravel 10 (laravel new foo --dev), and use the framework branch (dev-feat/phpunit10). In addition, you will need to use PHPUnit 10 and Collision v7.
