### ISSUE TITLE
How to undo uses()

### ISSUE THREAD

**Issue by riabiy-denis** [pestphp/pest#628]
**(this sentence is just a "thank you")** First and foremost, great job, amazing framework. Will migrate and go on with it. Since I'm writing +1k tests per project, will save a lot of boilerplate and mind power : ) 

**(now the issue/question)**

Is is possible to undo some "uses()"? 
The scenario. I have `uses(RefreshDatabase::class)` in my main `Pest.php`. 

But in my local test I notice, that I need to run `DatabaseMigrations::class` for some test files to reset sequences (ids on my snapshot should be the same always). Would be nice to nave

```
notUses(RefreshDatabase::class)
uses(DatabaseMigrations::class)

//or

use(DatabaseMigrations::class)->insteadOf(RefreshDatabase::class)
use()->insteadOf(RefreshDatabase::class) //just unset
```

**Comment by nunomaduro** [comment]
No plans for this at this time.

**Comment by plakhin** [comment]
@nunomaduro so what's the best way to use `DatabaseMigrations` only for one file in the `Unit` tests directory and `RefreshDatabase` for all other in the same dir?
