### ISSUE TITLE
Using helpers in High Order Tests

### ISSUE THREAD

**Issue by beliolfa** [pestphp/pest#63]
I'm trying to understand how Helpers work. I'm doing a set of helpers for Api call assertions and the first test is passing but the second one is saying that the method doesn't exists in TestCase. How could we use those helpers using High Order tests?

```php
// It works
test('all fields can be null updating user info', fn () => assertApiCallOk('PUT', '/api/user'));

// It throws Call to undefined method Tests\TestCase::assertApiCallOk()
test('all fields can be null updating user info 2')->assertApiCallOk('PUT', '/api/user');
```

And this is the declaration inside `Helpers.php`
```php
/**
 * Asserts that the api call returns an ok response.
 */
function assertApiCallOk(string $verb, string $url = '', array $payload = []): TestResponse
{
    return test()->json($verb, $url, $payload)->assertOk();
}
```

Thanks!

**Comment by owenvoke** [comment]
The helpers allow shorthand functions inside your test closures (or short functions). However, higher order tests need to be added using a trait via `uses(TraitName::class)`.

So for this, you could create a trait such as:
```php
trait InteractsWithApi
{
    protected function assertApiCallOk(string $verb, string $url = '', array $payload = []): TestResponse
    {
        return test()->json($verb, $url, $payload)->assertOk();
    }
}

// In your test (or "tests/Pest.php")
uses(InteractsWithApi::class);
```

**Comment by nunomaduro** [comment]
In this case may be:

```
uses(InteractsWithApi::class)->in(__DIR__);
```

**Comment by beliolfa** [comment]
Thanks guys. Working on it!
