### ISSUE TITLE
No code coverage driver is available.

### ISSUE THREAD

**Issue by sicaboy** [pestphp/pest#632]
`./vendor/bin/pest --coverage` comes with error `ERROR  No code coverage driver is available.`
I have phpdbg installed.
Is there a detailed process for configuring?

**Comment by owenvoke** [comment]
Are you using v1 or v2? 🤔 I'm assuming v1, could you try dumping the `PHP_SAPI` constant, it should be `phpdbg`, that's how we discover whether PHPDBG is active.

If you're using v2, PHPDBG is no longer supported by the Environment package, so I'd assume PHPUnit 10 (and therefore Pest v2) will stop supporting it.

**Comment by jhdxr** [comment]
I ran into same issue. v2 with phpdbg. 

Understand phpdbg is no longer supported, which is fine with me, but the document should be updated to indicate this change. https://pestphp.com/docs/test-coverage doesn't mention it at all.

**Comment by owenvoke** [comment]
Opened https://github.com/pestphp/docs/pull/188 to cover this update.
