### ISSUE TITLE
Proposal to add or to expectation api.

### ISSUE THREAD

**Issue by mohammedzeglam-pg** [pestphp/pest#634]
Testing with expectation api it is to easy and minimal to write but somtimes you need multiple expectation based on some different dataset or factories and or when you need to test relation when model have relation or not.
becuase i am lazy person and i want just one test with for these scenarios.
So i want to introduce an or implementation
```php
public function or(...$callbacks){
    try {
        $callback = array_shift($callbacks);
        if (is_callable($callback)) {
            $callback(new self($this->value));
        }
    } catch (\Throwable $th) {
        if (count($callbacks)) {
            $this->or($callbacks);
        } else {
            throw $th;
        }
    }

}
```

i could submit it as pr.

**Comment by nunomaduro** [comment]
Can you give me some real world examples of where would you use that new feature?

**Comment by mohammedzeglam-pg** [comment]
> 

I Have model that have relation with one to one relation with another model and the relation nullable so it is up to client to add this relation or not so in the response it will be null but when we have relation it will not be null.
so you could give dataset with both scenarios in mind instead of doing the same code again.

**Comment by nunomaduro** [comment]
Can you display the exact code that you would write with Pest with your proposed feature?

**Comment by mohammedzeglam-pg** [comment]
> Can you display the exact code that you would write with Pest with your proposed feature?

i am sorry about delay
```php
expect($json)
->data->
relation->or(
                    fn ($relation) => $relation->toBeNull(),
                    fn ($relation) => $relation
                        ->toBeArray()
                        ->id->toBeInt()
                        ->name->toBeString()
                );
```

**Comment by nunomaduro** [comment]
No plans for this.
