### ISSUE TITLE
[2.x ] Windows tests failing due TeamCity printer

### ISSUE THREAD

**Issue by fabio-ivona** [pestphp/pest#641]
Seems that the integration tests fail in `Tests\Visual\TeamCity > visual snapshot of team city with ('Failure.php') ` because of directory separators and the paths being absolute instead of relative to the project root:

eg:

expected

`##teamcity[testSuiteStarted name='Tests\tests\Failure' locationHint='file://tests/.tests/Failure.php' flowId='1234']`

actual

`##teamcity[testSuiteStarted name='Tests\tests\Failure' locationHint='file://D:\a\pest\pest\tests\.tests\Failure.php' flowId='1234']`

ref. to this workflow result for more info:

https://github.com/fabio-ivona/pest/actions/runs/3922822285/jobs/6706024482

**Comment by olivernybroe** [comment]
Closed by #642
