### ISSUE TITLE
`filter` argument not working with `=` sign in the filter

### ISSUE THREAD

**Issue by olivernybroe** [pestphp/pest#643]
When having a test which contains a `=` sign, it is impossible to get it with the filter argument, when the filter is a regex. 
```
vendor/bin/pest tests/Unit/test.php --filter="/description=description/"
```

<img width="619" alt="image" src="https://user-images.githubusercontent.com/5870441/212539749-70d0eea0-3989-49ad-8f9c-66fa653ca6bf.png">

Seems to impact both v1 and v2

**Comment by dansysanalyst** [comment]
I was having a quick look at `SebastianBergmann\CliParser`  in PHPUnit, more specifically in the method `parseLongOption()`, which explodes the argument by '`=`'.

The filter

```php 
string(32) "filter=/description=description/"
```
turns into:

```php 
string(12) "/description"
```

This is probably under the logic that there is no `function test_description_=_description()`.

**Comment by olivernybroe** [comment]
Just for more context for why this is needed. 
The phpstorm plugin relies heavily on the filter regex, and without this, we cannot run tests that uses `=` sign in their name.

**Comment by nunomaduro** [comment]
No plans of fixing this myself, unless someone makes a pull request. It's fine.
