### ISSUE TITLE
Use `toContain` expectation with traversable (Collection)

### ISSUE THREAD

**Issue by calebdw** [pestphp/pest#648]
Hello!

I was trying to use higher order expectations to check if a model relationship contains a given model, however it appears this is not currently possible as I receive this error:

> Failed asserting that a traversable contains Task Object &0000000000000f7a0000000000000000 ...

Here is what I was attempting:

```
    expect($workOrder)
        ->tasks->toContain($task);

    // had to use
    expect($workOrder->tasks->contains($task))->toBeTrue();
```

Would it be possible to support this kind of check with the `toContain` method? I'd rather not break up the method chaining just to check if the model is in the relationship.

Thanks!

**Comment by wayz9** [comment]
Maybe you can try this:

```php
expect($workOrder)
    ->tasks->contains($task)->toBeTrue()
    ->...; # continue with $workOrder
```

What type of relationship is tasks to workOrder?

**Comment by calebdw** [comment]
@wayz9,

Yes that worked, thanks!

Although I still think it would be much cleaner to use `toContain()`---the relationship is a many-to-many.

**Comment by wayz9** [comment]
I might be wrong but if it's many to many, models loaded in tasks relationship contain pivot, while your $task probably dont. This could be a reason why it's failing to assert.

**Comment by calebdw** [comment]
Ah, that could be why...I haven't tested it on a HasMany relationship. However, the Collection method `->contains()` works on Many-To-Many as well so it is not necessarily out of the realm of possibilities.

**Comment by wayz9** [comment]
Yeah but contains() method on Eloquent Collections is performing different kind of "check" 

You can see it here
https://github.com/laravel/framework/blob/9.x/src/Illuminate/Database/Eloquent/Collection.php#L309

While Pest is doing it with PHPUnits Assert::assertContains(). 
https://github.com/pestphp/pest/blob/3911cfec6df111b07c92b15ab825d41d8125cb81/src/Mixins/Expectation.php#L175

Maybe you can make a pull req to extend this or make your own toContainModel expectation helper. 
https://pestphp.com/docs/expectations#custom-expectations

**Comment by nunomaduro** [comment]
Feel free to make a pull request to improve this.
