### ISSUE TITLE
NotThrow expectation doesn't work correctly

### ISSUE THREAD

**Issue by MatanYadaev** [pestphp/pest#657]
This test doesn't run any assertion:
```php
it('expects exception to not be thrown', function () {
    expect(function () {})->not->toThrow(RuntimeException::class);
});
```
![image](https://user-images.githubusercontent.com/13586343/217276585-678a8dc2-76bb-46ab-b1ca-9bb0f3d050ba.png)

The test fails when the closure throws the exception, which is good, but doesn't pass the test on the opposite case.

**Comment by utsavsomaiya** [comment]
I think the `expect` function does not accept the closure.

![image](https://user-images.githubusercontent.com/96036522/218550476-bec7c4d8-d8ea-460a-a6e2-fa6fe3f5de47.png)

But I am not :100: sure.. 

```php
function example(mixed $arg) {
  if (is_callable($arg)) {
    $arg();
  }
}

$closure = function() {
  echo "This is a closure";
};

example($closure); // Output: "This is a closure"
```

**Comment by MatanYadaev** [comment]
@utsavsomaiya I don't think you're correct

**Comment by nunomaduro** [comment]
Fixed on `v2.x`.
