### ISSUE TITLE
Parallel feature

### ISSUE THREAD

**Issue by utsavsomaiya** [pestphp/pest#663]
https://user-images.githubusercontent.com/96036522/218549079-610e2450-a3d5-40ad-891b-d7adead3f86d.mp4

**Comment by utsavsomaiya** [comment]
Please at least mention the comment why you completed this :smiling_face_with_tear:

**Comment by nunomaduro** [comment]
Sorry, i don't know the reason why your parallel testing is slower. Feel free to make a pull request that addresses your issues.

**Comment by utsavsomaiya** [comment]
Okay!! First I am diving deeper in the parallel test after I will make PR. :slightly_smiling_face:
