### ISSUE TITLE
Coverage driver error PCOV

### ISSUE THREAD

**Issue by art0s-dev** [pestphp/pest#671]
Hello there,

i just installed PCOV on ubuntu, and it does not seem to work as a coverage driver.
Ive added Ondreij's Repo to my repo sources and ran the install command and this beauty came along.

```
This should not happen - please create an new issue here: https://github.com/pestphp/pest.

- Issue: Coverage not found in path: /home/till_a77/PhpstormProjects/webpage/vendor/pestphp/pest/.temp/coverage.php.
- PHP version: 8.2.3
- Operating system: Linux

  at vendor/pestphp/pest/src/Exceptions/ShouldNotHappen.php:38
     34▕      * Creates a new instance of should not happen without a specific exception.
     35▕      */
     36▕     public static function fromMessage(string $message): ShouldNotHappen
     37▕     {
  ➜  38▕         return new ShouldNotHappen(new Exception($message));
     39▕     }
     40▕ }
     41▕ 
```

**Comment by nunomaduro** [comment]
Can you try generate coverage using `--coverage-php` and check the message?

**Comment by art0s-dev** [comment]
Oh sure! Maybe i was unclear, that was the output of the coverage flag.

   Pest\Exceptions\ShouldNotHappen 

  
This should not happen - please create an new issue here: https://github.com/pestphp/pest.

- Issue: Coverage not found in path: /home/till_a77/PhpstormProjects/webpage/vendor/pestphp/pest/.temp/coverage.php.
- PHP version: 8.2.3
- Operating system: Linux

  at vendor/pestphp/pest/src/Exceptions/ShouldNotHappen.php:38
     34▕      * Creates a new instance of should not happen without a specific exception.
     35▕      */
     36▕     public static function fromMessage(string $message): ShouldNotHappen
     37▕     {
  ➜  38▕         return new ShouldNotHappen(new Exception($message));
     39▕     }
     40▕ }
     41▕

**Comment by nunomaduro** [comment]
Please use the flag `--coverage-php`, and report back what the terminal displays as error, if anything.
