### ISSUE TITLE
[Feature request] toMatchArrayRecursive

### ISSUE THREAD

**Issue by Floppy012** [pestphp/pest#673]
Currently the `toMatchArray` expectation does not  work on nested arrays. Those nested arrays are still compared using `assertEquals`.

It would be nice to have a `toMatchArrayRecursive` expectation that also handles nested arrays. I initially wanted to submit a PR but I've seen that you are working on a version 2 of pest. Is there such a feature already planned/implemented or shall I just submit a PR for v1?

Thanks in advance.

**Comment by nunomaduro** [comment]
Can you share how Jest solves this issue?

**Comment by Floppy012** [comment]
> Can you share how Jest solves this issue? 

If I've seen this correctly, they're doing it with the `arrayContaining`/`objectContaining` ("nested object partial matching") methods:

```javascript
expect(obj).toEqual(
    expect.objectContaining({
        nestedArray: expect.arrayContaining([1, 2, 3, 4]),
        nestedObject: expect.objectContaining({
            key: 'value',
        })
    })
);
```
I have extended Pest for my personal use-case like this:

```php
expect()->extend('toMatchArrayRecursive', function (array $array) {
    $valueAsArray = (array) $this->value;

    foreach ($array as $key => $value) {
        Assert::assertArrayHasKey($key, $valueAsArray);

        if (is_array($value)) {
            Assert::assertIsArray($valueAsArray[$key]);
            expect($valueAsArray[$key])->toMatchArrayRecursive($value);

            continue;
        }

        Assert::assertEquals(
            $value,
            $valueAsArray[$key],
            sprintf(
                'Failed asserting that an array has a key %s with the value %s.',
                $this->export($key),
                $this->export($valueAsArray[$key]),
            ),
        );
    }

    return $this;
});
```
Its the code from `toMatchArray` but when the value is another array it recurses.

**Comment by nunomaduro** [comment]
I like the general idea, however no fan of the method name.
