### ISSUE TITLE
unable to use `$this` in beforeAll()

### ISSUE THREAD

**Issue by syehan** [pestphp/pest#674]
hi all, has anyone do the same like me is when to create a factory from model is just doing creating one record for all assertions and expectations, recently i created like this :

```php
beforeAll(fn () => $this->event = Event::factory()->create());
 
it('has event created', function(){
    $this->assertDatabaseHas('core_day_events', [
        'id' => $this->event->id,
    ]);
});

test('event dates is jsonable or array', function(){
    $this->assertTrue(is_array($this->event->dates) and !is_string($this->event->dates));
});
```

but when I run the test, the output alert like this : 

```bash
• Tests\Unit\EventTest > it has event created
   Error 

  Using $this when not in object context
```
the `beforeEach()` normally worked, but it create each record in each `test()` / `it()` functions

any suggestions to do this? can we doing the same thing like `beforeEach()` does?

**Comment by nunomaduro** [comment]
Using `$this` on beforeAll and afterAll is not possible.

**Comment by surgiie** [comment]
> Using `$this` on beforeAll and afterAll is not possible.

Any plans to add this support or offer another hook that has the bounded test suite available? 

Running code before all tests is pretty common so seems like something worth adding in a future release.
