### ISSUE TITLE
How to test commands in laravel extension package

### ISSUE THREAD

**Issue by huangdijia** [pestphp/pest#677]
Can give an example?

**Comment by dansysanalyst** [comment]
You may check the example at Spatie Event Sourcing: https://github.com/spatie/laravel-event-sourcing/blob/main/tests/Console/ReplayCommandTest.php.

You may also read the [Orchestra Testbench](https://packages.tools/testbench/getting-started/introduction.html) documentation.

**Comment by huangdijia** [comment]
Thank you!
