### ISSUE TITLE
Additional flags are not removed when using parallel

### ISSUE THREAD

**Issue by owenvoke** [pestphp/pest#682]
When running Pest in parallel, and passing additional flags such as for our [GraphQL Coverage package](https://github.com/worksome/pest-graphql-coverage), the flags are not stripped as the parallel plugin doesn't seem to run plugin code.

This does not happen in standard execution (e.g. `pest --gql-coverage`).

```shell
> php vendor/bin/pest -p --gql-coverage

  The "--gql-coverage" option does not exist.
```

Blaming Luke 🤷🏻

**Comment by nunomaduro** [comment]
You need to pass the flags before the --parallel flag.

**Comment by owenvoke** [comment]
Hmm, weird. This worked before. Will try it on Monday. 👍🏻

**Comment by owenvoke** [comment]
@nunomaduro, this doesn't work either way round. 🤔

![image](https://user-images.githubusercontent.com/1899334/226300511-665b860a-ebe3-43b1-a731-aef3896d53c2.png)
