### ISSUE TITLE
This should not happen

### ISSUE THREAD

**Issue by YouMixx** [pestphp/pest#683]
This should not happen - please create an new issue here: https://github.com/pestphp/pest. - Issue: Test file not found. - PHP version: 8.0.22 - Operating system: WINNT

![image](https://user-images.githubusercontent.com/89249508/224492492-82bf287e-9ba6-4c0d-a38a-bbe6a9873b7a.png)

**Comment by nunomaduro** [comment]
We will need to re-create this issue, sharing more detail about what's happening.

**Comment by YouMixx** [comment]
I created mutation with name "test".
function getTestAttribute()
