### ISSUE TITLE
Pest with faker: Call to undefined function Pest\Faker\fake()

### ISSUE THREAD

**Issue by Bjornar97** [pestphp/pest#687]
I installed the pest faker plugin like this:
```composer require pestphp/pest-plugin-faker --dev```

And then tried to use it like so, as per documentation:
```php
use function Pest\Faker\fake;

it('generates a name using faker', function () {
    $name = fake()->name;

    // Same as:
    $name = $this->fake()->name;

    assertIsString($name);
});
```

I get the following error:
```Call to undefined function Pest\Faker\fake()```

If i use ```$this->fake()->name``` instead I also get an error:
```Call to undefined method Tests\Feature\TestTest::fake()```

**Comment by owenvoke** [comment]
In v1, [the function is called `faker()`](https://github.com/pestphp/pest-plugin-faker/blob/1.x/src/Faker.php#L11). I'm not entirely sure why it was renamed to `fake()` in v2. 🤔 @nunomaduro, do you know? I guess the docs should reflect v1 ATM? 👀

**Comment by Bjornar97** [comment]
faker() worked. Thank you :)

**Comment by jansgescheit** [comment]
A change of the version in the documentation would be very helpful. Not everyone is migrated to v2 right away, especially if you are still using Laravel 9
