### ISSUE TITLE
Unknown option "--init"

### ISSUE THREAD

**Issue by bubba-h57** [pestphp/pest#688]
Fresh install following [the documentation](https://pestphp.com/docs/installation).

When I get to `Step 2: Continue the installation according to your project specification:` I drop down to the instructions for **Other PHP Projects** and run `./vendor/bin/pest --init`

In response, I receive the following:

```
❯ cd /home/bubba/project_root
❯ ./utilities/vendor/bin/pest init
PHPUnit 9.6.5 by Sebastian Bergmann and contributors.

Unknown option "--init"
```

If I move into the `/home/bubba/project_root/utilities/` directory and run `./vendor/bin/pest --init`, then it works as advertised. Of course, that is not where my tests need to go.

The tests should reside in `/home/bubba/project_root/tests`, and that is the result I expected.

For no I can move `pest` to my `project_root` composer file. I considered just copying the files created to the project root, but am concerned that pest may have other things it expects to be in a fixed directory layout.

Thanks for all the work, I appreciate it.

**Comment by nunomaduro** [comment]
Sorry, no idea what's happening there. We are going to release Pest 2 soon, so you can try again with this release.

**Comment by Rozkalns** [comment]
Today had the same issue with Pest 2.34.

running `./vendor/bin/pest` I see phpunit output. trying to check version with `./vendor/bin/pest --version` I get nothing but `.`
