### ISSUE TITLE
When using the vendor-dir option in composer.json pest can't find composer.json

### ISSUE THREAD

**Issue by thattomperson** [pestphp/pest#693]
Hey, 

So I've got some legacy project that install the composer dependancies into `lib/vendor` using the [vendor-dir](https://getcomposer.org/doc/06-config.md#vendor-dir) option, When Pest starts it finds the autoload.php and navigates 2 folders up to find the composer.json 
as per https://github.com/pestphp/pest/blob/d71af91360c38bc0846b490754c7e9008cdf0f9d/bin/pest#L71

but that leaves it looking in the `lib` directory in my project

Can I propose we add a --root flag that would let us define the root when it is not detectable?

**Comment by nunomaduro** [comment]
You can make a pull request, that targets Pest 2, and we can discuss from there.
