### ISSUE TITLE
Nested bound dataset fails

### ISSUE THREAD

**Issue by sinnbeck** [pestphp/pest#706]
In pest v1 I was able to use nested bound datasets. 

Example
```php
it('can fail validation', function($invalidData, $errors) {
    $response = $this->post('/posts'), $invalidData);

    $response->assertSessionHasErrors($errors)
        ->assertRedirect();
})->with([
    'only user id'                => [ //only user id
         fn() => ['owner_id' => User::factory()->create()->id], //this fails in V2
         [
              'post_id',
              'start_date',
              'end_date',
        ],
    ],
]);
```
In version 1 the closure was automatically resolved in the `->with()` but now I get

>post(): Argument 2 ($data) must be of type array, Closure given

**Comment by fabio-ivona** [comment]
@sinnbeck in v2 bound dataset parameters must be typed in order to be resolved:

```php
it('can fail validation', function(array $invalidData, array $errors) {
```

**Comment by sinnbeck** [comment]
@fabio-ivona Ah briliant! Didnt catch that from the docs. I assumed it was only if it expected a class instance :+1:
