### ISSUE TITLE
Custom helpers functions don't work

### ISSUE THREAD

**Issue by MirasMustimov** [pestphp/pest#707]
Hello! 

Thank you for your work on this nice testing framework.

I tried upgrading to pest 2, but my custom helper function dont seem to work anymore, the error I see is `Call to undefined function something() `.

Then I tried to create a fresh laravel app and installed pest and tried it there but I still see the error.

Here is a my fresh laravel app with this error https://github.com/MirasMustimov/try-pest-2/blob/main/tests/Feature/ExampleTest.php#L4

Thanks!

Env: Laravel 10, Windows 11

**Comment by nunomaduro** [comment]
Pest v2.0.2 released, and it fixes this issue. Please update and let me know how it goes.

**Comment by MirasMustimov** [comment]
> Pest v2.0.2 released, and it fixes this issue. Please update and let me know how it goes.

Thank you, it works now!
