### ISSUE TITLE
Pest 2.0 significantly slower than 1.22

### ISSUE THREAD

**Issue by MichaelRushton** [pestphp/pest#712]
Not sure if an actual bug, but 2.0 is significantly slower than 1.22. Using this as an example:

```php
<?php

for ($i = 1; $i <= 1000; ++$i)
{
  test("test $i", fn () => expect(1)->toBe(1));
}
```
This takes 0.12s with v1.22 and 0.5s with v2.0

**Comment by alexmanase** [comment]
I ran this test on my computer. I have the following configuration:
 - MBA 2020
 - 8 GB
 - Apple M1

I ran 5 tests for each version.

| Pest Version | Run 1 | Run 2 | Run 3 | Run 4 | Run 5 |
|--------|--------|--------|--------|--------|--------|
| 1 | 19.43 | 17.55 | 17.53 | 17.66 | 16.82 |
| 2 | 18.98 | 18.78 | 17.06 | 16.89 | 15.96 |

Average time Pest 1.22: 17.798s
Average time Pest 2: 17.534s

I think my computer is significantly slower than yours, but I believe it's fine for version comparison. It doesn't appear that Pest 2 is slower than Pest 1.22.

**Comment by MichaelRushton** [comment]
A couple of screenshots of my test. I made a fresh install of v2.0, replaced the example unit test with the test above, ran the test, then downgraded to v1.22, then reran the test. You can see the difference. Just to note, the v2.0 test doesn't create the `.phpunit.result.cache` file (it's created after the first v1.22 test) so that doesn't explain it.

<img width="1095" alt="Screenshot 2023-03-21 094242" src="https://user-images.githubusercontent.com/49325097/226569994-ac74b4d8-c052-4eeb-b312-825eb1b89a85.png">

<img width="1105" alt="Screenshot 2023-03-21 094326" src="https://user-images.githubusercontent.com/49325097/226570019-0b45ef23-87c8-4db4-8013-b042e7d358b6.png">

This is Windows 11, WSL2 (Ubuntu 22.04.1 LTS), 16GB.

**Comment by alexmanase** [comment]
I also created a blank project like yours and the stats are almost the same:
 - Pest 1.22: 0.11s
 - Pest 2: 0.54s

In my first response I tested using a Laravel Project.

**Comment by MichaelRushton** [comment]
> I also created a blank project like yours and the stats are almost the same:
> 
> * Pest 1.22: 0.54s
> * Pest 2: 0.11s
> 
> In my first response I tested using a Laravel Project.

Did you mix up the times there?

**Comment by alexmanase** [comment]
Yeah, by mistake. Sorry.

I updated it.

**Comment by nunomaduro** [comment]
It's not slower.
