### ISSUE TITLE
Possibly input type mismatch in v2

### ISSUE THREAD

**Issue by jtomek** [pestphp/pest#713]
I would like to submit something for your review without knowing if it is expected behaviour or possibly a logical bug. 

Let me use the example of `expect()->toBeGreaterThan()`.

I noticed that `toBeGreaterThan()` newly types the input to `int|float`. 

But that is not in line with the end class GreaterThan in PHPUnit, which types it to `mixed`.

In my case, it throws an error when comparing dates.

**V1 code:** 

https://github.com/pestphp/pest/blob/9f6a88232733f9d1e33f49531340f447bd255c9e/src/Expectation.php#L336

**V2 code:**

https://github.com/pestphp/pest/blob/f309e06292204394ad7e9c943b88bf9d5da39673/src/Mixins/Expectation.php#L127

**PHPUnit GreaterThan:**
 
https://github.com/sebastianbergmann/phpunit/blob/bc0f2fca24d4c216155e36d8ac053649d495093f/src/Framework/Constraint/Cardinality/GreaterThan.php

― 

**You can test it on this example:**

```php
it('compare dates', function () {
    expect(now()->addMinute(2))->toBeGreaterThan(now());
});
```

― 

I am not sure if this is intended. But thought I would share my thoughts with you.

Edit: I have extended my `Pest.php` with a new function `toBeDateGreaterThan()`

```php
expect()->extend('toBeDateGreaterThan', function (Carbon $input) {
    return expect($this->value->unix())->toBeGreaterThan($input->unix());
});
```

**Comment by fabio-ivona** [comment]
solved by #716
