### ISSUE TITLE
Parallel testing option always exits with status code 1 (fail) from script

### ISSUE THREAD

**Issue by ronfuller** [pestphp/pest#722]
File: test.sh
``
#!/bin/bash
./vendor/bin/pest 
``
Exit Code: 0
File: test.sh
``
#!/bin/bash
./vendor/bin/pest --parallel
``
Exit Code: 1

**Comment by ronfuller** [comment]
![image](https://user-images.githubusercontent.com/9759221/226771868-30dc4b10-bf19-4160-9180-8acdc70b6005.png)

**Comment by nunomaduro** [comment]
This should be fixed on 2.2.0.

**Comment by ronfuller** [comment]
Thank you for fixing this so quickly!
