### ISSUE TITLE
Output to stdout (var_dump etc.) not showing 

### ISSUE THREAD

**Issue by nobuf** [pestphp/pest#73]
ref. https://github.com/pestphp/pest/issues/33#issuecomment-640191841

I'd like to see the output to stdout by echo, var_dump etc in console. Current Pest silently hides them either coming from test code or tested code. Expected behavior could be similar to PHPUnit's [`--disallow-test-output`](https://phpunit.readthedocs.io/en/9.0/risky-tests.html). In case the tested code prints something by accident it lets us know by marking the test case risky.

Note that `fwrite(STDERR, ...)` emits output to stderr and we can see it in console.

### Code to reproduce

```php
<?php

test('print debugging', function () {
    $someVariable = 'foo';

    var_dump($someVariable);

    assertTrue(true);
});
```

### Actual

```
   PASS  Tests\AppTest
  ✓ print debugging

  Tests:  1 passed
  Time:   0.06s
```

### Expected

The output contains:
```
string(3) "foo"
```

**Comment by nunomaduro** [comment]
You probably just forgot adding `beStrictAboutOutputDuringTests="true"` in your `phpunit.xml` file.

Let me know if it helps.

**Comment by nobuf** [comment]
I see! `beStrictAboutOutputDuringTests="true"` works. Also, I forgot that we can actually pass `--disallow-test-output` to bin/pest.

So, the default behavior is different from PHPUnit's `beStrictAboutOutputDuringTests="false"` as it has no output at all.

**Comment by nunomaduro** [comment]
Could you try to debug why? Thanks!

**Comment by nobuf** [comment]
Here's what I found.

In Pest, AddsDefaults::to() is called and \NunoMaduro\Collision\Adapters\Phpunit\Printer will be used while PHPUnit uses \PHPUnit\TextUI\DefaultResultPrinter.

The difference is that at the end of endTest() in DefaultResultPrinter, it emits output regardless of `beStrictAboutOutputDuringTests`:

```php
if ($test instanceof TestCase && !$test->hasExpectationOnOutput()) {
    $this->write($test->getActualOutput());
}
```

https://github.com/sebastianbergmann/phpunit/blob/fe9223c9f06e46e17035ee1cfd5d6c2bcd6b77fa/src/TextUI/DefaultResultPrinter.php#L298

**Comment by nunomaduro** [comment]
Can you pull request something on the collision repository?

**Comment by olivernybroe** [comment]
Seems like this has been fixed now, I'll reopen if this is still an issue.

Thanks @nobuf for the PR! 👍

**Comment by DGCarramona** [comment]
Hello, I have same issue, even though I have the enhancement you made on the other lib.
Is there any specific configuration to set to display this output ?

**Comment by Nelwhix** [comment]
Hi I am having this issue on pestphp/pest v2.28. I have added `   beStrictAboutOutputDuringTests="true"` in phpunit.xml but no output is still showing in the console

**Comment by pedromatosonv** [comment]
Same issue here

**Comment by XedinUnknown** [comment]
Same: no debug output in console.

**Comment by antiftw** [comment]
Same issue here.

**Comment by ToshY** [comment]
I also had this issue in a Symfony project. For me it was due to `DebugBundle` in the `bundles.php` had `'test' => true`. Removing this, shows the dumps in the console again.

`config/bundles.php`
```php
    Symfony\Bundle\DebugBundle\DebugBundle::class => ['dev' => true], // removed 'test' => true from here
```
