### ISSUE TITLE
--watch not working

### ISSUE THREAD

**Issue by grafst** [pestphp/pest#732]
❯ vendor/bin/pest --version

  Pest Testing Framework 2.2.1.

❯ vendor/bin/pest --watch

   INFO  Unknown option "--watch".

<img width="473" alt="2023-03-23_18-34-03" src="https://user-images.githubusercontent.com/8471055/227291687-3577e00f-0469-40da-9419-2d9fc0c8771d.png">

**Comment by nunomaduro** [comment]
You need to install the `watch` plugin. https://pestphp.com/docs/plugins#watch
