### ISSUE TITLE
withoutEvents() does't work anymore. 

### ISSUE THREAD

**Issue by RomkaLTU** [pestphp/pest#735]
After the upgrade to Pest2 withoutEvents() it stopped working. 

```
ReflectionException: Call to undefined method Illuminate\Foundation\Testing\TestCase::withoutEvents()
```

**Comment by dansysanalyst** [comment]
Hi @RomkaLTU,

In Laravel 10 it should be replaced with `Event::fake()`. 

Read more in the [Laravel 10 Upgrade Guide](https://laravel.com/docs/10.x/upgrade#service-mocking).

**Comment by RomkaLTU** [comment]
I used Laravel Shift to upgrade Laravel, and I see that withoutEvents() still exists. Not sure how to replace this with fake():

```
->beforeEach(function () {
        withoutEvents();
    })
```
