### ISSUE TITLE
Proposal: Test classes (callable class)

### ISSUE THREAD

**Issue by matiechaza** [pestphp/pest#74]
I was thinking it would be great if we could pass a callable class as the second argument. 
In this way the entire test would be encapsulated within classes.

![image](https://user-images.githubusercontent.com/50587234/83987558-061b0f00-a917-11ea-95fd-511a34f3bf5c.png)

I think it would be great feature! Since the tests would be very clean and we could apply design patterns for the different test classes.

For example. Given the next test:
![image](https://user-images.githubusercontent.com/50587234/83987680-72960e00-a917-11ea-9310-b3e1f86d4309.png)

The following test class can be written:
![image](https://user-images.githubusercontent.com/50587234/83987783-c86ab600-a917-11ea-86db-6fa2ac9cc55e.png)

You could even force these "test classes" to have the given-when-then methods to be printed on the report and not need a description in the `test()` and `it()` functions 😍.

**Comment by nunomaduro** [comment]
Sounds good to me. Can you make a pull request on this?

**Comment by owenvoke** [comment]
I guess this would involve changing the `it()` and `test()` signatures to use `callable` instead of `Closure`? 🤔 And then in turn the `TestCall`, `TestCaseFactory`, and a few other places. Not sure how much work would be needed, but this would be a really neat feature to have. 👍

**Comment by nunomaduro** [comment]
@owenvoke Exactly. Same goes for `beforeEach`, etc.

I think it may be interesting to have something like:

```php
beforeAll(Browser::start());
```

**Comment by matiechaza** [comment]
I don't have much time to dedicate to it. But I'm going to try 😃

**Comment by matiechaza** [comment]
I didn't think about changing the signatures of it() and test(). 
I think it would be better to create a new function for this feature. This way I wouldn't add one more use case to the it() and test() functions.

Perhaps this new function will organize the data to use the test() function (as the it() currently does). 

What do you think?

**Comment by nunomaduro** [comment]
Why a new functions? I think is fine to it and test to support callables.

**Comment by matiechaza** [comment]
Because in this new function I could modify the receive class by a class of callable type and send it to the test () function. This way I would not break the signature.

It was my first quick thought I had.

**Comment by nunomaduro** [comment]
Yeah - I think its fine.

**Comment by nunomaduro** [comment]
Fell free to make a pull request on this.
