### ISSUE TITLE
The [--process-isolation] option is not supported.

### ISSUE THREAD

**Issue by devajmeireles** [pestphp/pest#742]
# Environment

OS: MacOS 13.X
Laravel Framework: 10.4.1
PHP: 8.1.17
**Pest: 2 (Latest)**

# What

When I try to run the Pest using `--process-isolation` I get an error:
![image](https://user-images.githubusercontent.com/60591772/227815042-cf6075c6-7f45-45b2-b9ff-2409a6f10be1.png)

This options exists on [the documentation](https://pestphp.com/docs/cli-api-reference#content-execution) and also on `--help` output, but there are not detailed explanations about this behavior or how it needs to be used correctly.

**Comment by nunomaduro** [comment]
We don't support `--process-isolation`. And the next patch version of Pest, will remove that option.

**Comment by devajmeireles** [comment]
> We don't support `--process-isolation`. And the next patch version of Pest, will remove that option.

Thank you! Please, remember to remove in the documentation as well.

**Comment by nunomaduro** [comment]
Can you make a contribution on that?
