### ISSUE TITLE
Pest won't show errors or any runtime output

### ISSUE THREAD

**Issue by rafark** [pestphp/pest#744]
This is extremely annoying. 

Pest won't show fatal errors. If there's a fatal error, there's no way to know where's the problem.

![Screen Shot 2023-03-27 at 8 58 47 PM](https://user-images.githubusercontent.com/37381922/228116310-1f9a0b66-6bb0-4ead-bb0b-65eaa434f207.png)

It ONLY shows the generated output when MANUALLY manipulating the buffers:

![Screen Shot 2023-03-27 at 9 00 16 PM](https://user-images.githubusercontent.com/37381922/228116470-6f2dd154-371e-43c6-8a71-dfb0b6f5f636.png)
![Screen Shot 2023-03-27 at 9 00 37 PM](https://user-images.githubusercontent.com/37381922/228116529-7499e46d-d675-41c2-90eb-17ca062d81f9.png)

Is there a way I can have PEST not save the output buffer?

Imagine if I get a fatal error in one of my 1000+ tests, with absolutely NO feedback, how am I supposed to know where is the error coming from?

Pest 2.2.3, PHP 8.1.16

**Comment by rafark** [comment]
@nunomaduro  May I ask how is this completed?

**Comment by owenvoke** [comment]
Are you using any plugins that are modifying the output (or a custom printer)? 🤔 I'm not entirely sure why there isn't any normal Pest output in your screenshot.

Do you have an example repository, or a minimum reproducible example?

**Comment by rafark** [comment]
Hi @owenvoke  

Thank you for taking the time to review my issue.

I do happen to be using WordPress with PHPUnit. 

After some frustrating debugging of both PEST and WordPress, I found out the error was WordPress, it was exiting the script early with no feedback.

Thanks again for your time.

**Comment by rafark** [comment]
Still, the fatal errors are not shown unless I manually call:

`ob_end_flush();
    ob_end_clean();
    ob_implicit_flush(true);`

Any ideas of what could be causing the errors to not show?

**Comment by rafark** [comment]
Fatal errors are stil not being displayed. I just registered a shutdown function and am manullay showing it using error_get_last(). Error reporting is E_ALL. Any ideas what could be silencing the error?

**Comment by owenvoke** [comment]
I know WordPress has some functionality that hides/manipulates error output, perhaps it could be that or a plugin there.

Although, I'm surprised this hasn't come up more often for WordPress users.

However, as you've mentioned you've made changes to these, I'm surprised the issue is still happening. If I get some time today, I might have a look into this.
