### ISSUE TITLE
PCOV integration is not working

### ISSUE THREAD

**Issue by MaurizioMoreo** [pestphp/pest#746]
Even if this test is green:
```
    public function testPcovEnabled(): void
    {
        $this->assertSame('1', ini_get('pcov.enabled'));
        $this->assertTrue(extension_loaded('pcov'));
    }
```
if I run the tests with the `--coverage` option, I've got this error:
```
 ERROR  Unable to get coverage using Xdebug. Did you set Xdebug's coverage mode?
 ```
 It seems related to `\Pest\Support\Coverage::isAvailable`. Am I missing something?

**Comment by owenvoke** [comment]
PCov seems to work fine for me on PHP 8.2 🤔 That kind of sounds like both Xdebug and PCov are running at the same time, and Xdebug is taking precedence.

**Comment by MaurizioMoreo** [comment]
In this case we could maybe consider to check if Xdebug is enabled: should we consider whether it is the enabling of a component that determines precedence? @nunomaduro make sense?

**Comment by MaurizioMoreo** [comment]
We need another approval to merge the #772 PR.

**Comment by MaurizioMoreo** [comment]
The problem is solved in [_v2.5.1_](https://github.com/pestphp/pest/commits/v2.5.1), but I see that the `cacheDirectory` XML attribute for the `coverage` element is ignored. Should we open a new issue @owenvoke?

**Comment by nunomaduro** [comment]
Yes plz.
