### ISSUE TITLE
arch-testing issue

### ISSUE THREAD

**Issue by abmmhasan** [pestphp/pest#749]
```
test('Not debugging statements are left in our code.')
 ->expect(['dd', 'dump', 'ray'])
 ->not->toBeUsed();
```

resulting in error 

`[PHPUnit\Architecture\Asserts\Dependencies\ObjectDependenciesDescription::getDocBlockTypeWithNamespace(): Argument #1 ($type) must be of type phpDocumentor\Reflection\Type, null given](url)`

**Comment by fabio-ivona** [comment]
@abmmhasan could you share here your error stacktrace?

**Comment by abmmhasan** [comment]
Sorry to say, I no longer able to create the scenario. Interestingly it is not even working, and not even giving any feedback. I tried with keeping dd, dump, die but it not able to detect but passing the test.

tried with:
```php
test('No debugging statements are left in code', function () {
    expect(['dd', 'dump', 'ray', 'die', 'd'])->not()->toBeUsed();
});
```

**Comment by fabio-ivona** [comment]
Could you share a simple example repository that reproduces the issue?

I mean the last scenario, where dd is not detected

**Comment by abmmhasan** [comment]
both happened in this repo:
https://github.com/abmmhasan/InterMix

**Comment by fabio-ivona** [comment]
just a couple of notes:

you should fix this

```diff
test('No debugging statements are left in code', function () {
+    expect(['dd', 'dump', 'ray', 'die', 'd'])->each->not()->toBeUsed();
-    expect(['dd', 'dump', 'ray', 'die', 'd'])->not()->toBeUsed();
});
```

`dd`, `dump`, `ray`, `d` are not available in your project, that's why they are not detected. I tried installing spatie/ray and this is what you get

![image](https://user-images.githubusercontent.com/8792274/229296554-ab683a3c-1371-45ca-8812-d74c86d58ef1.png)

**finally**

`die` is a built-in function and it is not detected by arch, @nunomaduro is this intended?

**Comment by abmmhasan** [comment]
I was trying with `die()` in this case & seems we are on same page. Big thanks for the `each`, I missed that.

**Comment by abmmhasan** [comment]
I believe, `die`, `var_dump`, `print_r`,... should be detectable if stated. Common debug functions in use.
