### ISSUE TITLE
Digits-only dataset descriptions are ignored

### ISSUE THREAD

**Issue by magnetas** [pestphp/pest#750]
I have a test with a dataset:

```php
->with([
    '401' => [
        'exception' => new Exception('Some message', 401),
        'message' => 'Invalid  token. Responded with 401 and: Some message',
    ],
    ...
]);
```

Basically listing different API response cases and testing whether it's handled correctly.

And the message I get when running it:

`it deletes access token if response is invalid with (Namespace\Exception Object (...), 'Invalid tok...essage')`

However if I change the key in my dataset to something like `401 response` the message is fine:

`it deletes access token if response is invalid with data set "401 response"`

Didn't yet have a chance to investigate deeper, the assumption is it does not work with digits-only key/description. Maybe it's not treated as associative array anymore? I do set it as digits-only string, other keys are more descriptive (not only digits) and work fine.

**Comment by magnetas** [comment]
My bad. It seems PHP converts digits-only keys to integer ones.

```php
dd(['401' => 'abc']);
```

returns

```
array:1 [
  401 => "abc"
]
```

I guess the descriptions simply should not be integers or integer strings to work

**Comment by owenvoke** [comment]
Hmm, we should still probably handle this and if it's a string, use the string (whether it's a numeric string or not). 🤔

**Comment by magnetas** [comment]
> Hmm, we should still probably handle this and if it's a string, use the string (whether it's a numeric string or not). 🤔

Yeah, but look at my comment. If it's a numeric string PHP converts it to integer (unless it's something like `0401`).

It's possible to check, let's say, if 0 index exists and, if it doesn't, treat the key as description. That would basically mean the array is not indexed automatically (would be zero based).

However this would not work if the dataset does contain `0` as desired description.
