### ISSUE TITLE
Test in "Helpers" directory are not executed

### ISSUE THREAD

**Issue by gehrisandro** [pestphp/pest#752]
After upgrading from v1 to v2 I run into the exact same problem already mentioned here: #734 

It worked perfectly fine with v1 but with v2 all tests in the "Helpers" directory are silently ignored. I only realized it because I tried to execute a specific test in the Helpers directory some days later.

Maybe we could add some information into the upgrade guide.

If you agree I can make a PR.

**Comment by nunomaduro** [comment]
This is a bug.

**Comment by gehrisandro** [comment]
Okay. I thought this is the expected behaviour. 🙃 

I will try to fix this later today.
