### ISSUE TITLE
After upgrading to v2. We receive this error: ERROR  Test case `Tests\TestCase` can not be used. The folder `/var/www/html/tests/Feature/ExampleTwoTest.php` already uses the test case `Tests\TestCase`

### ISSUE THREAD

**Issue by jared-kesler** [pestphp/pest#756]
We recently started a brand new application and we have been using Pest v1 which has been working great. This week we wanted to upgrade to Pest v2 but we have been running into this error that we have not been able to figure out. 

We followed the upgrade guide step by step, however when we attempt to run Pest v2, we get the following error:

/var/www/html # ./vendor/bin/pest

   ERROR  Test case `Tests\TestCase` can not be used. The folder `/var/www/html/tests/Feature/ExampleTwoTest.php` already uses the test case `Tests\TestCase`

Location: /var/www/html/vendor/pestphp/pest/src/Repositories/TestRepository.php:174

Our TestCase file has not changed since v1. We are not sure what this error is saying, as our tests run perfectly fine in v1 but v2 is throwing this error. 

Is there anyone who might have any ideas on what might be causing this? Is there anything that I can provide that might help someone on the team point us in the right direction with trying to solve this error? 

Any help is greatly appreciated, thank you!

**Comment by lvqingan** [comment]
Specifying a path or file to the pest command will not report an error. If you specify a --group, the same error will appear

**Comment by lvqingan** [comment]
Found a solution, which is to remove the previously customized testsuite in phpunit.xml

**Comment by gehrisandro** [comment]
@lvqingan Could you provide the customized phpunit.xml which lead to this problem?

**Comment by lvqingan** [comment]
It seems that there cannot be multiple <testsuite> containing the same <directory>. If one of the <testsuite> contains <directory> of `./tests/Feature`, then no other <testsuite> can contain <directory> of `./tests/Feature/Api`

**Comment by gehrisandro** [comment]
I was not able to reproduce the issue. Maybe you can provide more details or even better a full example how to reproduce?

So far I've tried the following:
```xml
    <testsuites>
        <testsuite name="Unit">
            <directory suffix="Test.php">./tests/Unit</directory>
        </testsuite>
        <testsuite name="Nested">
            <directory suffix="Test.php">./tests/Unit/Nested</directory>
        </testsuite>
    </testsuites>
```

**Comment by lvqingan** [comment]
@gehrisandro I use `TestCase::class` in Pest.php, is it related to this?

```php
uses(
    Tests\TestCase::class,
)->in('Feature', 'Unit');
```

**Comment by gehrisandro** [comment]
No, I am still not able to reproduce.

**Comment by jkesler** [comment]
Thank you for the replies! We were able to find the issue thanks to your responses. 

This is what my phpunit.xml config file was listing for the test suites. 

  <testsuites>
    <testsuite name="Default">
      <directory suffix="Test.php">./tests/</directory>
    </testsuite>
    <testsuite name="Unit">
      <directory suffix="Test.php">./tests/Unit</directory>
    </testsuite>
    <testsuite name="Feature">
      <directory suffix="Test.php">./tests/Feature</directory>
    </testsuite>
  </testsuites>

If I change it to run only the single default test suite, it works with no issues!

  <testsuites>
    <testsuite name="Default">
      <directory suffix="Test.php">./tests/</directory>
    </testsuite>
  </testsuites>

**Comment by jkesler** [comment]
Thank you for the replies! We were able to find the issue thanks to your responses. 

This is what my phpunit.xml config file was listing for the test suites. 

 ` <testsuites>
    <testsuite name="Default">
      <directory suffix="Test.php">./tests/</directory>
    </testsuite>
    <testsuite name="Unit">
      <directory suffix="Test.php">./tests/Unit</directory>
    </testsuite>
    <testsuite name="Feature">
      <directory suffix="Test.php">./tests/Feature</directory>
    </testsuite>
  </testsuites>`

If I change it to run only the single default test suite, it works with no issues!

`  <testsuites>
    <testsuite name="Default">
      <directory suffix="Test.php">./tests/</directory>
    </testsuite>
  </testsuites>`

**Comment by jared-kesler** [comment]
Thank you for the replies! We were able to find the issue thanks to your responses. 

This is what my phpunit.xml config file was listing for the test suites. 

 ```
 <testsuites>
    <testsuite name="Default">
      <directory suffix="Test.php">./tests/</directory>
    </testsuite>
    <testsuite name="Unit">
      <directory suffix="Test.php">./tests/Unit</directory>
    </testsuite>
    <testsuite name="Feature">
      <directory suffix="Test.php">./tests/Feature</directory>
    </testsuite>
  </testsuites>
```

If I change it to run only the single default test suite, all of our tests run with no issues!

``` 
<testsuites>
    <testsuite name="Default">
      <directory suffix="Test.php">./tests/</directory>
    </testsuite>
</testsuites>

**Comment by gehrisandro** [comment]
@jared-kesler Thank you for your update.

I'm able to reproduce now, but I think it's not necessary to fix this issue as your testsuites were not properly configured.

**Comment by hunwalk** [comment]
For those who stepped into this issue.
When you define your testsuites, makes sure you don't define a global route and then a specified route under it. Apparently Pest will recursively check every file under given testsuite directory. Same thing happens when using `pest()->use()`

Some examples

`phpunit.xml` - Bad
```
<testsuite name="Default">
    <directory>tests/</directory>
</testsuite>
<testsuite name="Unit">
    <directory>tests/Unit</directory>
</testsuite>
```

`Pest.php` - Bad

```
pest()->extend(Tests\TestCase::class)
    ->use(RefreshDatabase::class)
    ->in(
        __DIR__,
        __DIR__.'/Integration',
    );
```

In my case, I've duplicated some lines and did not notice that __DIR__ was defined 3 times, because I mistook a comma for a dot

`Pest.php` - My case (still bad)
```
pest()->extend(Tests\TestCase::class)
    ->use(RefreshDatabase::class)
    ->in(
        __DIR__, '../Modules/Auth/tests',
        __DIR__, '../Modules/User/tests',
        __DIR__, '../Modules/Package/tests',
    );
```
