### ISSUE TITLE
Pest 0.2 release

### ISSUE THREAD

**Issue by nunomaduro** [pestphp/pest#76]
Tasks:
- [x] Release Plugin API ( waiting for https://github.com/pestphp/pest/issues/77)
- [x] Release Laravel Plugin
- [x] Adds Docs Laravel Plugin
- [x] Release Livewire Plugin
- [x] Updates Docs Livewire Plugin
- [x] Release Faker Plugin
- [x] Updates Docs Faker Plugin
- [x] Release Init Plugin
- [x] Adds Docs Init Plugin
- [x] Release Snapshots Plugin (waiting for https://github.com/spatie/pest-plugin-snapshots/pull/4)
- [x] Adds Docs Snapshots Plugin (waiting for https://github.com/pestphp/website/pull/56)
- [ ] Update "Writing Plugins" documentation
- [x] Update stubs to namespaced functions

Later ( if possible ):
- [ ] Release **Dust**
- [ ] Updates Docs **Dust**
- [ ] Release **Watch**
- [ ] Updates Docs ** Watch**

Questions:

1. @fetzi The plugin API is closed for the 0.2 correct? Is interfaced based, so we can add things later?
2. @AlexMartinFR Do you think you are able to help us on the missing documention?
3. @caneco Do you think you can provide me a logo/banner for Dest?
4. @owenvoke Can you tackle the missing parts on the init?

**Comment by AlexMartinFR** [comment]
I'll have to dive into some topics first to be really helpful, since I haven't written/used any plugin yet.

If someone can give a summary of the main ideas, even very rough, I can work with that.

**Comment by nunomaduro** [comment]
Let's schedule a call tomorrow, what do you think? 👍

**Comment by AlexMartinFR** [comment]
Yup!

**Comment by owenvoke** [comment]
Some notes about developing the `init` plugin:

- It looks like the main things that cause issues are:
   - The [`ValidatesEnvironment::in()` method](https://github.com/pestphp/pest/blob/e536c28e342d1434ec76e9b8de4f7ab4dfad3abc/src/Actions/ValidatesEnvironment.php#L38), which is called in the binary [`bin/pest`](https://github.com/pestphp/pest/blob/2efed3ef80c4b8390f34490d16538c2dd9ec6b68/bin/pest#L36)
   - The [`UsesCall::in()` method](https://github.com/pestphp/pest/blob/7d7c5f1ab1e9d526492ebb3f1c870d14fda2142d/src/PendingObjects/UsesCall.php#L83), which is called in [`src/Plugin.php`](https://github.com/pestphp/pest/blob/7d7c5f1ab1e9d526492ebb3f1c870d14fda2142d/src/Plugin.php#L25)

- When working locally, it looks like [the Pest binary uses `dirname(__DIR__)`](https://github.com/pestphp/pest/blob/2efed3ef80c4b8390f34490d16538c2dd9ec6b68/bin/pest#L13-L17) which stops the `pest` binary finding the right autoload file so I then get a ``Class `Pest\Init\Plugin` does not exist`` error.

**Comment by AlexMartinFR** [comment]
Since the `--init`option will be provided out of the box, I think we shouldn't treat that as a plugin in the documentation. That is an implementation detail to me.

What do you think about splitting the Installation guide in two sections?
I can do that today, here is a rough summary of what I have in mind:

# Installation

## Blank project

- **Set up your project:** `composer init` with `"minimum-stability": "dev",` and `"prefer-stable": true,`
- **Install Pest:** `composer require pestphp/pest --dev`
- **Initialise Pest:** `pest --init`
- **Happy testing!**

## Use Pest in an existing project

- (Insert existing installation steps here)

**Comment by AlexMartinFR** [comment]
I've lost track of what's missing on the documentation before release.
Are we up to date yet?

**Comment by nunomaduro** [comment]
@AlexMartinFR yes. I will be doing it tonight. 👍

Enjoy your Sunday.

**Comment by AlexMartinFR** [comment]
Thanks, you too!
I'm free tonight also if you need review or anything.

**Comment by fetzi** [comment]
@nunomaduro did you already write something regarding the plugin API?

**Comment by nunomaduro** [comment]
You can check here: https://pestphp.com/docs/guides/plugins/.

It's missing the interfaces thing, and the auto-detection of plugins.
