### ISSUE TITLE
List 3rd party plugins on website

### ISSUE THREAD

**Issue by calebdw** [pestphp/pest#764]
Hello!

The old version of the Pest site listed a bunch of 3rd party plugins for Pest (i.e., some by Spatie) and they seem to be removed from the new site.

I understand separating the officially maintained/endorsed plugins from other plugins, but it still would be nice to have a 3rd party list on the website for a one-stop-shop plugin discovery.

Thanks!

**Comment by nunomaduro** [comment]
No plans for this.
