### ISSUE TITLE
Apply test case to specific groups OR override test case in specific test file

### ISSUE THREAD

**Issue by calebdw** [pestphp/pest#765]
Hello,

I have several types of tests that have their own parent Test Case (e.g., like Validator classes). However, we follow a DDD layout and don't want to place all of the validators in a single directory.

Ideally, I'd like to be able to specify a parent test case for a group of tests like so:

```php
// Pest.php
uses(ValidatorTestCase::class)->group('validators');
uses(TestCase::class)->in('Feature');


// test file in `Feature/some/path/to/Validators/`
uses()->group('validators')
```

Another solution would be to just override the test case used in that particular file:
```php
// test file in `Feature/some/path/to/Validators/`
uses(ValidatorTestCase::class)->group('validators');
```
however, this yields a `folder already uses the test case 'Tests\TestCase'` exception.

The first solution would be the best and most robust as there wouldn't be a ton of duplicate calls throughout the tests.

Thanks!

**Comment by nunomaduro** [comment]
This seems a feature request - and are free to submit a pull request that adds this feature.
