### ISSUE TITLE
Coverage report using XDEBUG showing error code on separate line

### ISSUE THREAD

**Issue by CHE1RON** [pestphp/pest#766]
Hey there,
following the `--min=90` example [in the docs](https://pestphp.com/docs/test-coverage#content-minimum-threshold-enforcement) the report should look like this when failing:

![image](https://user-images.githubusercontent.com/122524301/229630275-f4f01ccc-de41-4922-b102-ee282ce7dd99.png)

However, using XDEBUG in my setup, there's an extra line (rather ugly one), see here:

![image](https://user-images.githubusercontent.com/122524301/229630160-7673f0ae-dc10-4b07-aee5-317f94475b1f.png)

My setup:

```text
$ ./vendor/bin/pest --version
Pest    1.22.3
PHPUnit 9.6.6 by Sebastian Bergmann and contributors.

$ php --version
PHP 8.0.28 (cli) (built: Feb 14 2023 15:42:52) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.28, Copyright (c) Zend Technologies
    with Xdebug v3.2.1, Copyright (c) 2002-2023, by Derick Rethans
    with Zend OPcache v8.0.28, Copyright (c), by Zend Technologies
```

From the docs, I would expect it not to be there, as it's kind of disrupting the very clean look of `Pest`'s output 😅

**Comment by owenvoke** [comment]
Is that your terminal that's causing that? 🤔 (You could try running `exit 1` to see whether that shows without Pest.

I'm not able to replicate this on my terminal.

**Comment by CHE1RON** [comment]
I'm using [`iTerm2`](https://iterm2.com) as terminal emulator, and you might be right about this .. I just checked with [`kitty`](https://github.com/kovidgoyal/kitty) and got this:

![image](https://user-images.githubusercontent.com/122524301/229748302-d0701fb3-200d-4aa1-a6bf-5bee89c4317b.png)

too bad ☹️

**Comment by CHE1RON** [comment]
Sadly, I cannot seem to prevent iTerm2 from doing this, but clearly this does not have anything to do with `pest`, so I closed this. If by chance anyone knows how to do this, feel free to ping me and let me know!

**Comment by owenvoke** [comment]
Hmm, weird. I'm also using iTerm2. 🤔 Not sure how I disabled that.

**Comment by CHE1RON** [comment]
@owenvoke If you come across this, let me know :wink: it's not exactly obvious to me if there's a setting, but not a big deal right now .. thanks for your effort and time!
