### ISSUE TITLE
Not all arguments are passed to plugins

### ISSUE THREAD

**Issue by michaelw85** [pestphp/pest#773]
I'm using Pest with the `--test-directory` argument, which works as intended.
But when you start using the pest watch plugin this argument will never be passed to the plugin.

The argument is removed here: https://github.com/pestphp/pest/blob/2.x/bin/pest#L33
```
        if (str_contains($value, '--test-directory')) {
            unset($args[$key]);
        }
```
And the filtered list is passed to the rest of the application here: https://github.com/pestphp/pest/blob/2.x/bin/pest#L91
```
        $result = $kernel->handle($args);
```

In my opinion, all arguments should be passed to plugins.
Currently, this creates an error because Pest does not support the argument internally.

For now, I've created a PR to re-add the argument in the watch plugin but as I said I think this issue should be resolved in the Pest setup. For reference: https://github.com/pestphp/pest-plugin-watch/pull/20

**Comment by lukeraymonddowning** [comment]
@michaelw85 could you not check ARGV for this? I know it's a bit of a workaround

**Comment by nunomaduro** [comment]
Duplicated of : https://github.com/pestphp/pest/issues/738.
