### ISSUE TITLE
Expectation::dd not output

### ISSUE THREAD

**Issue by cxlblm** [pestphp/pest#775]
PHP version: 8.2.4
pest version: 2.4.0

```
it('testcase', function () {

    expect(111)->dd('xxx');
});
```
Not running in laravel environment。Modify the internal implementation of the dd method to replace var_dump with the following code is possible to have output.

```
public function dd(mixed ...$arguments): void
{
  if (function_exists('dd')) {
      dd($this->value, ...$arguments);
  }

  // var_dump($this->value);
  fwrite(STDOUT, var_export($this->value, true));


  exit(1);
}
```

**Comment by nunomaduro** [comment]
No plans on changing this.

**Comment by cxlblm** [comment]
I want to express whether this is an ongoing issue or a bug, and if it's a bug, whether there is a fix in progress.

**Comment by julien-boudry** [comment]
I have exactly the same problem.
