### ISSUE TITLE
--parallel argument passed to paratest

### ISSUE THREAD

**Issue by moranda** [pestphp/pest#781]
When running in the gitlab CI, the `--parallel` option seems to be passed to paratest:

```
$ php artisan test --parallel
                                           
  The "--parallel" option does not exist.  
                                           
paratest [--bootstrap BOOTSTRAP] [--colors [COLORS]] [-c|--configuration CONFIGURATION] [--coverage-clover COVERAGE-CLOVER] [--coverage-cobertura COVERAGE-COBERTURA] [--coverage-crap4j COVERAGE-CRAP4J] [--coverage-html COVERAGE-HTML] [--coverage-php COVERAGE-PHP] [--coverage-test-limit COVERAGE-TEST-LIMIT] [--coverage-text [COVERAGE-TEXT]] [--coverage-xml COVERAGE-XML] [--debug] [--exclude-group EXCLUDE-GROUP] [--filter FILTER] [-f|--functional] [-g|--group GROUP] [-h|--help] [--log-junit LOG-JUNIT] [--log-teamcity LOG-TEAMCITY] [-m|--max-batch-size MAX-BATCH-SIZE] [--no-coverage] [--no-test-tokens] [--order-by ORDER-BY] [--parallel-suite] [--passthru PASSTHRU] [--passthru-php PASSTHRU-PHP] [--path PATH] [-p|--processes PROCESSES] [--random-order-seed RANDOM-ORDER-SEED] [--repeat REPEAT] [--runner RUNNER] [--stop-on-failure] [--teamcity] [--testdox] [--testsuite TESTSUITE] [--tmp-dir TMP-DIR] [-v|--verbose] [--whitelist WHITELIST] [--] [<path>]
```

**Comment by julien-boudry** [comment]
The same problem inside Github Codespace (in the browser)

_(a composer show then a --parallel)_
![image](https://github.com/pestphp/pest/assets/4020317/3c6fc0ac-99b0-4a3f-8a59-995aa9576bd3)

**Comment by devajmeireles** [comment]
Hey, @moranda ! Thanks for your report.

According to the date range from the opening of the issue until now, does this issue still occur?

**Comment by devajmeireles** [comment]
> Hey, @moranda ! Thanks for your report.
> 
> According to the date range from the opening of the issue until now, does this issue still occur?

@moranda ,

As twenty-four hours have passed without a response from you, I will be closing this issue. If you still have the same problem, feel free to open a new issue at any time. This action is part of an attempt to organize the issues.

**Comment by LukeTowers** [comment]
Duplicate of #751. 

The error message

> Unknown option "--parallel"

is most likely caused by the `pestphp/pest-plugin` not being enabled, either by running composer with `--no-plugins` or by not allowing it in your `composer.json` configuration.

Ran into this issue just now myself because someone had explicitly disabled the `pestphp/pest-plugin` in the project's `composer.json`.
