### ISSUE TITLE
A never-returning function must not return

### ISSUE THREAD

**Issue by michaelw85** [pestphp/pest#785]
I'm using PHP 8.1 with:

phpunit/phpunit 10.1.1
pestphp/pest v2.5.2

Here's a repo with more detailed info and reproduction steps: https://github.com/michaelw85/never-issue#readme

TLDR; When the first test uses Mockery, Pest stops working. When there is another test with output it works fine.

**Comment by michaelw85** [comment]
@nunomaduro you closed this issue but I wonder has it been resolved? I did not manage to find and resolve the root cause and I don't see commit referencing this issue.

**Comment by nunomaduro** [comment]
It's an issue with the package/setup of that project. It's not an Pest specific issue.

**Comment by michaelw85** [comment]
@nunomaduro is it? I've contacted the other tooling and they validated its not coming from those packages. When I tested it's source points to either a layer in pest or php unit. Did you have time to look at the [Stack trace](https://github.com/michaelw85/never-issue/blob/main/stack-trace.txt)  I provided?

**Comment by nunomaduro** [comment]
I've cloned your repository - and indeed verified that Pest does not run when using the functions you provided. However, I am unable to spend time debugging why. Feel free to perform a pull request that addresses this issue.

**Comment by michaelw85** [comment]
@nunomaduro thank you for testing. If I find the issue I will surely provide a PR. I've spent multiple hours debugging so far and haven't been able to find the root cause yet.

**Comment by paulshryock** [comment]
> If I find the issue

Did you ever find the issue? I get this error sometimes. Pest will throw a `Whoops\Exception\ErrorException` that `A never-returning function must not return`, and point to some vendor library function that has a `never` return type and _does not return anything_ but simply `throw`s, which is the correct usage of that return type.

**Comment by michaelw85** [comment]
@paulshryock If I remember correctly I ended up patching code as a work around and stopped searching for a root cause. And I think I dropped the patch after some updates. Not completely sure though it's been a while.
