### ISSUE TITLE
Normalize changelogs

### ISSUE THREAD

**Issue by nunomaduro** [pestphp/pest#79]
Across all the organisation some changelogs are missing dates, links, etc. They should all look like this:  https://github.com/pestphp/pest/blob/master/CHANGELOG.md.

**Comment by HDVinnie** [comment]
I highly suggest looking into https://github.com/symplify/changelog-linker. I have started using it on all my older and new projects and its very clean and easy to you.

Example output: https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/master/CHANGELOG.md

**Comment by rkozlov95** [comment]
@nunomaduro
How do you think?
Is it right to use [changelog-linker](https://github.com/symplify/changelog-linker) in terms of [keep a changelog](https://keepachangelog.com/en/1.1.0/)?
I think manual writing is the best way for users of the package.  
Another option is to use the "changelog-linker" output to make adjustments to the "changelog".

**Comment by nunomaduro** [comment]
For now, I prefer to do it manually.

What we really need is:

1. Go to every repository and make sure all of them have the https://keepachangelog.com/en/1.1.0/ format.
2. Add missing links to pull requests / commits. Or at least most of them when we can't find.

**Comment by owenvoke** [comment]
I'll apply these changes to any of the repos I help maintain tomorrow. 👍

**Comment by nunomaduro** [comment]
They seem to be normalised now.
