### ISSUE TITLE
beforeEach with skip() fails

### ISSUE THREAD

**Issue by getupkid** [pestphp/pest#790]
As per the documentation, it says it is possible to call the skip() method on beforeEach(). However, when I try this, I get `Call to undefined method Tests\TestCase::skip`

My code:
```
beforeEach(function() {
    // blah blah blah...
})->skip();
```

the docs:
```
beforeEach(function () {
    //
})->skip();
```

The error:
![image](https://user-images.githubusercontent.com/4795041/233823399-c16d37a2-ed0e-4ad1-833d-d02eba407209.png)

**Comment by nunomaduro** [comment]
Fixed.
