### ISSUE TITLE
Customize EnvironmentSetUp

### ISSUE THREAD

**Issue by ph7jack** [pestphp/pest#793]
Is it possible to customize the EnvironmentSetUp?
I can do it using the PHPUnit tests, but I can't in pest tests.
I also have tested **beforeEach** and **beforeAll**, but these **callable** are called after the **service provider** is loaded

Pest: 2.0

![image](https://user-images.githubusercontent.com/38913462/234757991-847a9216-eadb-45a0-96b3-46663b0a57ca.png)

**Comment by owenvoke** [comment]
You can do this by just creating an abstract `TestCase`, and then enabling it with `uses()` 👍🏻

**Comment by ph7jack** [comment]
@owenvoke Yes, I know. But I don't want to modify `.env` for all tests, I want it just for specific testing cases.

**Comment by titantwentyone** [comment]
I think what @owenvoke is meaning is that for every environment change you want to make, you'd have to create a base test case which does or does not extend from the main test case. This could be very cumbersome for package developers as you'd need a test case for every combination of config change needed to be tested. It would be great if there was something like:

```php
setApplicationEnvironment(function($app) {
   $app['config']->set('my.config.value', 'something');
})
->name('my_test_environment');

//then in the test itself

it('does something', function() {
    //test with defined environment
})->environment('my_test_environment');

```
or even better IMO  and perhaps in addition as an optional syntax:
```php
it('does something', function() {
    //test with defined environment
})->environment(function($app) {
    $app['config']->set('my.config.value', 'something');
});
```

This is how I imagine porting the syntax from Testbench across to Pest would look like. I'm really not up to speed on the internals of Pest so I'm not sure how feasible this is.

**Comment by devajmeireles** [comment]
Hey, @PH7-Jack ! Thanks for your report.

As per @titantwentyone answer, I'm going to mark this issue as a suggestion so the Pest team can handle it if it's an interesting addition to make to Pest.

**Comment by titantwentyone** [comment]
Just an FYI for anyone coming across this. There was a tentative PR to provide this functionality which led me down the path to suggesting opening up the internal annotations API and provide the ability to add test class methods. https://github.com/pestphp/pest/pull/805

**Comment by joaopalopes24** [comment]
@devajmeireles Any expectations of implementing this?
