### ISSUE TITLE
Test crash when using a static closure

### ISSUE THREAD

**Issue by julien-boudry** [pestphp/pest#794]
Hi,

The bug:

```php
it('can be static closure', static fn() => expect(true)->toBeTrue());
```

<img width="1362" alt="Screenshot 2023-04-27 at 15 55 19" src="https://user-images.githubusercontent.com/4020317/234884330-ec8dcf59-6f09-4b4c-8056-fa42f3a0a77e.png">

It works without static closure:
```php
it('can be closure', fn() => expect(true)->toBeTrue());
```

It's boring because my Laravel Pint configuration uses the `"static_lambda"` directive.

**Comment by nunomaduro** [comment]
Don't use static lambdas in your tests.

**Comment by julien-boudry** [comment]
The bug is much more the error message "Should not happen" and the related documentation. @nunomaduro

**Comment by nunomaduro** [comment]
@julien-boudry Got it! Can you make a pull request to address that issue?

**Comment by julien-boudry** [comment]
I will try, but not sure to know how to do it well.
