### ISSUE TITLE
Call to undefined method  $this::get()

### ISSUE THREAD

**Issue by hfuccillo** [pestphp/pest#796]
I'm running Pest for the first time and trying to make a basic test works. 
I've installed Pest and then added a new test:
```sh
php artisan make:test RoutesTest --pest`
```
And then adding this code to the test:
```php

<?php

test('works', function () {
    $this->get('/')
    ->assertStatus(200);
    
});
```
I'm getting this as result:
![image](https://user-images.githubusercontent.com/738877/235386666-cfc08976-8be3-46c2-90d3-7216df8a2a17.png)

What am I doing wrong?

**Comment by alexmanase** [comment]
Did you make sure that you use Laravel's `TestCase` inside the Feature folder? Something like this:

```php
uses(Tests\TestCase::class)->in('Feature');
```

**Comment by wagnerfnds** [comment]
Hi guys, i have a similar issue. 

When i run this same test inside the default Feature folder, it runs ok.

But i've changed my phpunit.xml to point to my controllers folder.
```
<testsuites>
    <testsuite name="Unit">
        <directory suffix="Test.php">./app/Http/Controllers</directory>
    </testsuite>
    <testsuite name="Feature">
        <directory suffix="Test.php">./app/Http/Controllers</directory>
    </testsuite>
</testsuites>
```

When i make this change, and move my tests to controllers folder i loose access to $this->get() function.

Already tried to change the Pest.php file to: 
`uses(Tests\TestCase::class)->in('./app/Http/Controllers');`

And also tried to put the uses() on top of my test file. 

Things like
`$this->assertTrue(true);`
Works fine...
