### ISSUE TITLE
Loose access to $this->get() when change defaults Feature folder

### ISSUE THREAD

**Issue by wagnerfnds** [pestphp/pest#802]
Hi guys,

When i run this sample test inside the default Feature folder, it runs ok.

```
it('Should return 200', function () {
    $this->get('/')->assertStatus(401);
});
```

But i've changed my phpunit.xml to point to my controllers folder.
```
<testsuites>
    <testsuite name="Unit">
        <directory suffix="Test.php">./app/Http/Controllers</directory>
    </testsuite>
    <testsuite name="Feature">
        <directory suffix="Test.php">./app/Http/Controllers</directory>
    </testsuite>
</testsuites>
```

When i make this change, and move my tests to controllers folder i loose access to $this->get() function.

Already tried to change the Pest.php file to: 
`uses(Tests\TestCase::class)->in('./app/Http/Controllers');`

And also tried to put the uses() on top of my test file. 

Things like
`$this->assertTrue(true);`
Works fine...

**Comment by nunomaduro** [comment]
Please use: https://github.com/pestphp/pest/discussions.
