### ISSUE TITLE
--dirty flag runs a lot more tests than only the dirty tests

### ISSUE THREAD

**Issue by edwinheij** [pestphp/pest#806]
Debugged the 'loadChangedFiles' method and that result is ok. Only the files that are dirty.

Why are there more tests running?

Read something with the '--retry' option, is this somehow the same:
_Note: Keep in mind that if your phpunit.xml file has two test suites (usually Unit and Feature), this option will sort each suite by running the failed tests first. This means that sometimes, you may see the entire Unit test suite run before Pest runs the Feature test suite, where previously failed tests take priority._

**Comment by nunomaduro** [comment]
Are you using PHPUnit test classes? Or only Pest tests?

**Comment by edwinheij** [comment]
I'm using a combination. Is that the issue?

**Comment by nunomaduro** [comment]
Yes. Dirty flag don't support classes tests. Can you make a pull request that clarifies that on the docs?
