### ISSUE TITLE
Add duration of tests on output

### ISSUE THREAD

**Issue by marcoT89** [pestphp/pest#81]
Hi! I work with integration tests and one of the things that I'm really woried about is the time a service is responding in my tests. It would be very very very helpfull for me to hav those durations of every test.

I was used to sempro/phpunit-pretty-print that displays the duration of each test. It would be really helpfull for me and maybe for others to check how their tests is performing. And even know how long a performance test would take to execute.

Here's an example:
![image](https://raw.githubusercontent.com/Sempro/phpunit-pretty-print/master/preview.gif)

Thank you very much for your work! It's so cleaner and ease to write tests now.

Cheers

**Comment by nunomaduro** [comment]
Sounds a good idea. Can you contribute with that to this package? https://github.com/nunomaduro/collision
