### ISSUE TITLE
Passing bound dataset to higher-order expect throws undefined array key error

### ISSUE THREAD

**Issue by apphaus-simon** [pestphp/pest#810]
When using a bound dataset with a higher-order expect test, the dataset values are not passed through, and it causes a very cryptic error message.

```php
// Works
dataset('greeting-string', [
    'formal' => 'Evening',
    'informal' => 'yo',
]);

it('uses regular dataset')
    ->with('greeting-string')
    ->expect(fn (string $greeting) => $greeting)
    ->throwsNoExceptions();

// Fails
dataset('greeting-bound', [
    'formal' => fn () => 'Evening',
    'informal' => fn () => 'yo',
]);

it('uses bound dataset')
    ->with('greeting-bound')
    ->expect(fn (string $greeting) => $greeting)
    ->throwsNoExceptions();
```

Running the above with pest v2.6.1 - The first test succeeds but the second causes a cryptic error message:

`ErrorException Undefined array key 0`

![image](https://github.com/pestphp/pest/assets/28444923/62455ed7-a37c-494f-bc18-4504c0d71beb)

---

It is possible to circumvent this issue by running the `expect()` callback in the second param of `it()`. But the inconsistency in how the two approaches work has me a bit stumped:

```php
// Works
dataset('greeting-string', [
    'formal' => 'Evening',
    'informal' => 'yo',
]);

it('uses regular dataset', fn (string $greeting) => $greeting)
    ->throwsNoExceptions()
    ->with('greeting-string');

// Works
dataset('greeting-bound', [
    'formal' => fn () => 'Evening',
    'informal' => fn () => 'yo',
]);

it('uses bound dataset', fn (string $greeting) => $greeting)
    ->with('greeting-bound')
    ->throwsNoExceptions();
```

![image](https://github.com/pestphp/pest/assets/28444923/7bc6bd73-653c-443a-a18a-7afd00278401)

As a side note - this issue is also present in pest v1, but in a different form. There `expect` is passed the dataset's callable instead of the callable's value. That issue made some sense to me, but I haven't been able to figure the v2 bug out.

---

**Edit:** As a follow up, it seems that the minimum amount of code required to replicate this issue is this:

```php
it('uses bound dataset')
    ->with([fn () => null]);
```

It's clear now that bound datasets need type-hinting up-front. But it isn't clear that that's still the case with higher-order expect.

It's also notable that higher-order expect parses it's bound arguments separately from those passed to `it()`, and as such, even if you type-hint up-front with `it('', fn(string $value) => $value)`, expect will still only receive a closure instead of the closure's value.

**Comment by apphaus-simon** [comment]
I've managed to track down the line which throws the error:
https://github.com/pestphp/pest/blob/2.x/src/Concerns/Testable.php#LL258C78-L258C78

With a bound dataset `$testParameterTypes` is an empty array, which causes the `Undefined array key 0` error.

If you bypass that error with something like  `if(!empty($testParameterTypes) && ...` the value is correctly returned from the `__resolveTestArguments` function.

After that point, I can see that the closure is called with the resolved arguments via `__callClosure`, however I haven't been able to work out what happens between there and when we hit `Reflection::bindCallableWithData`, since the data at that point seems to no longer be the value of the bound `$arguments` from the `__resolveTestArguments` step.

In trying to track this issue down, I've definitely gained an even greater respect for the scale of this project, it's such a complex system :joy: . Hopefully this helps, and this behaviour isn't just entirely out of scope for the project.

**Comment by apphaus-simon** [comment]
I've realised it's also possible to provide basic typehints in `it()`'s `$closure` parameter, which prevents the described error.

However, doing so results in the higher-order expect receiving the callable instead:

```php
// Fails
it('uses bound dataset', fn (string $greeting) => $greeting)
    ->with(['formal' => fn () => 'Evening'])
    ->expect(fn ($greeting) => $greeting)
    ->toBe('Evening');
```

![image](https://github.com/pestphp/pest/assets/28444923/420cda8c-0c48-48e8-a2bc-7d847213b09d)

**Comment by fabio-ivona** [comment]
Will take a look at this :+1:

**Comment by devajmeireles** [comment]
> Will take a look at this 👍

Did you check this? Any updates?

**Comment by fabio-ivona** [comment]
sadly not, Higher Order Testing is not my field, maybe @lukeraymonddowning has some insight about this?

**Comment by nunomaduro** [comment]
It will be marked as not supported. Pest 2.30 says that high order testing does not support bound datasets.
