### ISSUE TITLE
Teamcity printer in parallel mode

### ISSUE THREAD

**Issue by ariaieboy** [pestphp/pest#811]
Right now the --parallel does not support teamcity output and because of that the phpstorm plugin can not detect the tests. On parallel runs

**Comment by devajmeireles** [comment]
Hey, @ariaieboy ! Thanks for your report.

I'm checking the Pest team if we have any plans for that.

**Comment by keith-ferney** [comment]
are there any plans to implement this in the near future?

**Comment by smirok** [comment]
@devajmeireles Hi, PhpStorm is here! We are awaiting for updates regarding the plans as well, this feature would really help us to support the parallel running of tests through the Pest plugin.

**Comment by nunomaduro** [comment]
Do you mind of taking this one @devajmeireles? And this one: https://github.com/pestphp/pest/issues/823.

**Comment by austincarpenter** [comment]
Is there an update on this one? 😀 @devajmeireles 
https://youtrack.jetbrains.com/issue/WI-75728

**Comment by pindab0ter** [comment]
Would love to see this fixed as well so we can get support for parallel testing in PHPStorm.

**Comment by pindab0ter** [comment]
Any news on this? I would love to have native support for parallel testing in my IDE, which this depends on.

**Comment by nunomaduro** [comment]
I've very few knowledge on teamcity output at the moment. So, unless someone is able to contribute with this, i can't really help here.

**Comment by squatto** [comment]
@nunomaduro does closing this issue (and #823) mean that there's no plans to support parallel testing in PhpStorm?

The latest comment on [the relevant PhpStorm issue](https://youtrack.jetbrains.com/issue/WI-75728/Pest-Support-parallel-testing#focus=Comments-27-9550938.0-0) says:
> We will support parallel testing on the Pest plugin side as soon as the issue https://github.com/pestphp/pest/issues/811 regarding teamcity-style output in parallel mode is resolved.

Thanks! 🙏🏻

**Comment by pindab0ter** [comment]
I also don't understand why not resolving this issue immediately would warrant closing it. The issue is still relevant, no?
