### ISSUE TITLE
feat: Disable parallel testing on certain tests.

### ISSUE THREAD

**Issue by sbrow** [pestphp/pest#819]
AFAIK dusk tests can be run with Pest, but they won't work if you try to run them in parallel. it'd be great if we could selectively prevent tests from running in parallel so that you can run most of your test suite in parallel, but run all your dusk tests sequentially. Perhaps this could be done with a `->lock()` or `->inSeries()` setter method?

It'd also be useful as a temporary solution on tests that should run fine in parallel, but don't always in practice.

**Comment by nunomaduro** [comment]
Feel free to make a pull request that adds this feature.

**Comment by flap152** [comment]
Considering a PR for this, I'd like opinion/confirmation on proposed approach. Basically, we would filter sequential tests and run them on a single worker, when other workers are not running (at start or end of run):
- tests to be run sequentially are identified similar to groups or skips with `->markAsSequential()`
- in addition to `$pending = []` in BaseRunner, we create `$pendingSequentials = [];` to store those sequential tests. This filtering can be done in sortPending()
- in `fillRunQueue(array $availableTokens)` we only use and fill a single token/queue until the `$pendingSequentials[]` list of tests is empty and executed. 
- This sequential test processing would be done before or after the `$pending` list is processed, maybe determined with a `--sequential-first` option
Any reason this would not work or be unacceptable? Thx.
Edit: realizing this comment does not reopen issue, which makes sense. Maybe tagging @nunomaduro for consideration?

**Comment by sbrow** [comment]
I am in favor of @flap152's  solution :)
