### ISSUE TITLE
OutputInterface cannot be resolved

### ISSUE THREAD

**Issue by uglydawg** [pestphp/pest#821]
This issue happens when trying to start phpunit using xdebug.

Issue: A dependency with the name `Symfony\Component\Console\Output\OutputInterface` cannot be resolved.
  PHP version: 8.2.6
  Operating system: Linux

**Comment by uglydawg** [comment]
![image](https://github.com/pestphp/pest/assets/7563223/f7eaa56a-eebb-4c2b-ab89-f422ca6720a1)

**Comment by nunomaduro** [comment]
Can't replicate.
