### ISSUE TITLE
Imperfect description on tests with data set when using `--teamcity` flag

### ISSUE THREAD

**Issue by hafezdivandari** [pestphp/pest#823]
Running tests with dataset in PhpStorm (using `--teamcity`) causes imperfect test descriptions:

![image](https://github.com/pestphp/pest/assets/56585913/3c974edd-592b-43cc-83b0-d0668f5dd31d)

Same tests are fine in CLI without `--teamcity` flag:

![image](https://github.com/pestphp/pest/assets/56585913/139a48e7-4238-4a84-80b1-2f365a6e58da)

**Comment by olivernybroe** [comment]
@nunomaduro team city output does not touch the name generation. 
https://github.com/pestphp/pest/blob/2.x/src/Logging/TeamCity/Converter.php#L45

**Comment by devajmeireles** [comment]
Hey, @hafezdivandari ! Thanks for your report.

I'm checking with Pest team if we have plans to do something related with that.

**Comment by nunomaduro** [comment]
Do you mind of taking this one @devajmeireles? And this one: https://github.com/pestphp/pest/issues/811.
