### ISSUE TITLE
Documentation / Guide: Handling private methods

### ISSUE THREAD

**Issue by AlexMartinFR** [pestphp/pest#83]
Extracted from [#33](https://github.com/pestphp/pest/issues/33#issuecomment-634567880):

**1. Handling private methods**

« I traditionally used private/protected methods in my test classes, where code is shared between tests, or even just to make a test more concise and readable.
The roadblock here was deciding where to they belong? 
 
- in a trait and register it in the `tests/Pest.php`
- create a parent test case and put them there

I decided at the moment to put them in the parent test case - not sure if the docs should recommend an approach for this? »

This is a recurring question and will deserve its own guide / mention on the documentation.

**Comment by nunomaduro** [comment]
This has been documented.
