### ISSUE TITLE
Access current dataset key inside test

### ISSUE THREAD

**Issue by calebdw** [pestphp/pest#830]
Hello!

Given the following pseudo-test:
```php
it('...', function (...) {
    // ...
})->with([
    'foo' => [...],
    'bar' => [...],
]);
```

It would be helpful to be able to access the current dataset key (`foo` or `baz`) inside the test, is this currently possible, and if not, can it implemented?

Otherwise, if I need to use it inside the test I need to repeat information which isn't desired:

```php
->with([
    'foo' => ['foo', ...],
    'bar' => ['bar', ...],
]);
```

Thanks!

**Comment by fabio-ivona** [comment]
Hi, currently not supported

Don't think it's possible to achieve it in an easy way, but feel free to open a PR if you wish 😉
