### ISSUE TITLE
Mock function breaks in latest version of Mockery

### ISSUE THREAD

**Issue by ghost** [pestphp/pest#831]
When using version `1.6.1` or above of mockery/mockery the default `mock` function no longer returns a `Pest\Mock\Mock` but instead the default mockery class. This causes calls to `expect` to fail.

When I downgraded to version `1.5.1` everything worked as expected. This is the error received:  
`Mockery\Exception\BadMethodCallException: Method Mockery_0_Shopify_Clients_Graphql::expect() does not exist on this mock object`

**Comment by owenvoke** [comment]
I don't see why this new version would be causing issues 🤔 Mockery has had a global `mock()` function for years that would have always conflicted with Pest's `mock()`.
https://github.com/mockery/mockery/blob/main/library/helpers.php#L25-L30

I wonder if something has changed in the order of `pestphp/pest-plugin-mock` and `mockery/mockery` when being autoloaded, this would mean that Mockery's `mock()` would be included before Pest's one. 🤔

**Comment by fabio-ivona** [comment]
I confirm this, it seems that autoload order has changed, this broke my pipelines too

@kristoffermodified a temporary workaround is to call `new Pest\Mock\Mock(<class>)` instead of `mock(<class>)` while we investigate on the issue

**Comment by kyryl-bogach** [comment]
+1 on this issue!

**Comment by igorsgm** [comment]
+1 on this issue!

**Comment by williamtrevisan** [comment]
+1 on this issue!

**Comment by grEvenX** [comment]
Any workaround possible?

**Comment by williamtrevisan** [comment]
> Any workaround possible?

I did what @fabio-ivona said. It worked for me.

**Comment by la-roberto** [comment]
> Any workaround possible?

In my case, I ended up installing Mockery per the documentation: https://pestphp.com/docs/mocking

**Comment by ghostwriter** [comment]
If https://github.com/pestphp/pest-plugin-mock/pull/7 is accepted, adding `use function Pest\Mock\mock;` at the top of your test will resolve this issue.

**Comment by ghostwriter** [comment]
Disregard my last comment the pull request is now closed, The owner has archived the repository.

> This repository has been archived by the owner on Aug 24, 2023. It is now read-only. 
https://github.com/pestphp/pest-plugin-mock

**Comment by ghost** [comment]
As the package seems to have been archived, this issue is no longer relevant
