### ISSUE TITLE
🐞 Bug - Open - `DatabaseTruncation` and `DatabaseMigrations` not working for `Dusk` tests under `--parallel`

### ISSUE THREAD

**Issue by Rikj000** [pestphp/pest#832]
Description:
Currently the [`DatabaseTruncation` and `DatabaseMigrations`](https://laravel.com/docs/10.x/dusk#resetting-the-database-after-each-test) traits are not correctly resetting the database in between tests of the same group when running with `--parallel`.

When not using `--parallel`, the DB resets correctly.

- **Linked issue:** https://github.com/pestphp/pest/issues/819
- **Issue status:** `Open` *(Not resolved, will likely be closed by issue-closing-OCD by maintainer...)*

**Comment by devajmeireles** [comment]
Hey, @Rikj000 . Thanks for your report.

Could you help us by opening a PR for that, please?

**Comment by nunomaduro** [comment]
This is an Laravel issue. I don't think Laravel Dusk supports parallel testing.

**Comment by Rikj000** [comment]
I've got Dusk working fine under parallel with Pest in my project by now,   
however it required a fair amount of custom work.

Due to the way my issues have been handled thus far,   
I don't feel motivated to help on this issue.
