### ISSUE TITLE
Undefined method error when trying to access model attributes on HigherOrderTest

### ISSUE THREAD

**Issue by calebdw** [pestphp/pest#835]
Hello!

The following tests fail with the message: `Call to undefined method App\User::username()`

```php
<?php

use App\User;

it('works')
    ->expect(fn () => User::all())
    ->not->toBeEmpty()
    ->each->username->not->toBeNull();

it('works2', function () {
    expect(User::all())
        ->not->toBeEmpty()
        ->each->username->not->toBeNull();
});
```

Thanks!

**Comment by devajmeireles** [comment]
Hey, @CalebDW ! Thanks for your report.

According to my review, behind the scenes the proxy using `each` expects to find a method. Alternatively, you can do this:

```php
it('works')
    ->expect(fn () => User::all())
    ->not->toBeEmpty()
    ->each(fn ($user) => expect($user->name)->not->toBeNull());
```

Anyway, I will tag your report with a suggestion tag, so the Pest team can review if there are any plans to improve this.
