### ISSUE TITLE
If array 1 is equal to array 2, toContain returns false

### ISSUE THREAD

**Issue by GlennBags** [pestphp/pest#836]
Running Laravel 9 on Mac, using pest to test.
Came across this during testing, originally trying to test using contains, as some of the response being tested was variable. Therefore, ended up targeting part of the payload and ended up with two pieces that should be the same, yet the `toContain` test was returning false. Ran the following (results to follow):

```
it('arrays are equal', function () {
    $a1 = ['this' => 'that', 'something' => 'else',];
    $a2 = $a1;

    expect($a1)->toBe($a2);
});

it('arrays are equal, should belong/contain as well', function () {
    $a1 = ['this' => 'that', 'something' => 'else',];
    $a2 = $a1;

    expect($a1)->toContain($a2);
});
```
   FAIL  Tests\Feature\BuyFlow\ManageBuyFlowTest
  ✓ it arrays are equal
  ⨯ it arrays are equal, should belong/contain as well

  ---

  • Tests\Feature\BuyFlow\ManageBuyFlowTest > it arrays are equal, should belong/contain as well
  Failed asserting that an array contains Array &0 (
      'this' => 'that'
      'something' => 'else'
  ).

  at tests/Feature/BuyFlow/ManageBuyFlowTest.php:132
    128▕ it('arrays are equal, should belong/contain as well', function () {
    129▕     $a1 = ['this' => 'that', 'something' => 'else',];
    130▕     $a2 = $a1;
    131▕
  ➜ 132▕     expect($a1)->toContain($a2);
    133▕ });
    134▕
    135▕ // it('can send to checkout--no previous opportunity', function () {
    136▕ //     $this->captureLogs();

  Tests:  1 failed, 1 passed
  Time:   6.72s

Been a while since set theory, to double check I asked chatGpt: 
in set theory if set A and set B are equal, does set A "contain" set B?
ChatGPT
Yes, in set theory, if set A and set B are equal, it means that they contain exactly the same elements. In this case, you can say that set A contains set B and set B contains set A. The concept of containment is often used to describe the relationship between sets, and when two sets are equal, they are considered to contain each other.

**Comment by fabio-ivona** [comment]
Is is a right behavior, in my opinion

[1,2,3] *is* [1,2,3]

But

[1,2,3] does not contain [1,2,3]

It contains 1, 2 and 3, but not an array with those three values

**Comment by GlennBags** [comment]
I respectfully disagree.

The one contains the other. Yes, it contains the Full set, but still contains it.

**Comment by fabio-ivona** [comment]
What you are looking for is `toMatchArray()`

https://pestphp.com/docs/expectations#content-tomatcharrayarray

**Comment by ceilidhboy** [comment]
@GlennBags the issue is the semantics of the parameter passed to `toContain()`. It treats this as a single entity and checks if that entity is contained in the array. In the case of calling `toContain([1, 2, 3])`, it checks if the whole array as an entity is present in the initial array. It doesn't check if each of the items present in the passed array are present in the initial array.

Consider this:
```php
expect([1, 2, 3])->toContain(2); // true
expect([1, 2, 3])->toContain([2]); // false, because there's no array [2] in array [1, 2, 3], since 2 !== [2]
expect([1, [2], 3])->toContain([2]); // true, because there IS an array [2] in array [1, [2], 3]
```

Your confusion is caused by assuming that `toContain()` takes a set of entities when it takes a single entity, which may itself be a set.

A solution would be to create your own custom expectation, say `toContainSet()`, which checks if each element passed in an array or Iterable is contained in the initial array or Iterable.

**Comment by owenvoke** [comment]
Just to flag up as well, the [`->toContain()` expectation](https://pestphp.com/docs/expectations#content-tocontainneedles) is [a variadic method](https://github.com/pestphp/pest/blob/cd823193cc8a68b77146387b8f5dd65ef0470d62/src/Mixins/Expectation.php#L176), so can be called with multiple parameters if you want to check it contains them.
```php
expect([1, 2, 3])->toContain(1, 2, 3); // true
```

However, this won't really work for your initial example as the array is using keys. Perhaps we could have something similar to [Jests `expect.arrayContaining()` method](https://jestjs.io/docs/expect#expectarraycontainingarray). 🤔
