### ISSUE TITLE
Skipped installation of bin

### ISSUE THREAD

**Issue by abmmhasan** [pestphp/pest#840]
![image](https://github.com/pestphp/pest/assets/7711128/b2c090a9-8a21-460c-a4b4-3deb96e9de67)

```bash
9/17 [==============>-------------]  52%    Skipped installation of bin bin/paratest.bat for package brianium/paratest: name conflicts with an existing file
```

Happens every time it installed/updated! Though didn't found any issue yet. But should it get attention?

**Comment by devajmeireles** [comment]
> ![image](https://user-images.githubusercontent.com/7711128/246727740-b2c090a9-8a21-460c-a4b4-3deb96e9de67.png)
> 
> ```shell
> 9/17 [==============>-------------]  52%    Skipped installation of bin bin/paratest.bat for package brianium/paratest: name conflicts with an existing file
> ```
> 
> Happens every time it installed/updated! Though didn't found any issue yet. But should it get attention?

Hey! @abmmhasan,

Could you tell us if the problem keeps happening? Can you reproduce the problem with a fresh install? I couldn't get the issue in my tests. I also noticed that you didn't offer details of the problem, this makes it impossible for us to analyze it to help you. I will close this issue, but feel free to open a new one if the problem persists.

**Comment by alf4712** [comment]
Same issue here.
```
 66/78 [=======================>----]  84%    Skipped installation of bin bin/paratest.bat for package brianium/paratest: name conflicts with an existing file
```
 
<img width="818" alt="image" src="https://github.com/pestphp/pest/assets/91665360/df941b46-c84e-4d79-adfe-33e0a30f1a6e">

composer.json:
```
"require": {
        "php": "^8.2",
        "ext-bcmath": "*",
        "ext-iconv": "*",
        "ext-mbstring": "*"
    },
    "require-dev": {
        "friendsofphp/php-cs-fixer": "^3.22.0",
        "pestphp/pest": "^2.16",
        "phpstan/extension-installer": "^1.3.1",
        "phpstan/phpstan": "^1.10.29",
        "phpstan/phpstan-deprecation-rules": "^1.1.4",
        "phpstan/phpstan-phpunit": "^1.3.13",
        "phpstan/phpstan-strict-rules": "^1.5.1",
        "spatie/ray": "^1.37.2",
        "roave/security-advisories": "dev-latest"
    },
    "config": {
        "sort-packages": true,
        "allow-plugins": {
            "phpstan/extension-installer": true,
            "pestphp/pest-plugin": true
        },
        "optimize-autoloader": true,
        "preferred-install": "dist"
    },
    "extra": {
        "phpstan": {
            "includes": [
                "extension.neon"
            ]
        }
    },
    "minimum-stability": "stable",
    "prefer-stable": true
```

Run:
```
composer update
```

**Comment by alf4712** [comment]
I created a new issue:
https://github.com/pestphp/pest/issues/928
