### ISSUE TITLE
Uncaught Error: Call to undefined function it()

### ISSUE THREAD

**Issue by bhaidar** [pestphp/pest#845]
Hello, community,

This is the first time I have tried configuring PHPStorm to run my PEST tests. I generally run tests via the terminal, and all works well.

I've installed all requirements to run PEST tests via PHPStorm.

However, when I try to run a single test, I get the following error:

```
[docker://sail-8.2/app:latest/]:php /opt/project/tests/Unit/ExampleTest.php
PHP Fatal error:  Uncaught Error: Call to undefined function it() in /opt/project/tests/Unit/ExampleTest.php:3
Stack trace:
#0 {main}
  thrown in /opt/project/tests/Unit/ExampleTest.php on line 3
```
If I run the tests using `sail test` all works well.

Also, in the Pest.php file, I've included the following:

```
uses(
    Tests\TestCase::class,
    //Illuminate\Foundation\Testing\RefreshDatabase::class,
)->in('Feature', 'Unit');
```

Inside PHPStorm, if I run with Debug, it works fine. Only when I use "Run .." it fails with the error above.

<img width="372" alt="image" src="https://github.com/pestphp/pest/assets/1163421/c17ba1ae-8ef1-4ee3-a739-04911f0289c8">

What might still be missing?

I appreciate your feedback.

Regards
Bilal

**Comment by bhaidar** [comment]
After running Debug, then I run Run, and it works fine.

Could it be a cache issue? If so, what cache could be affected in this case?

**Comment by nunomaduro** [comment]
Not really sure - sorry!
