### ISSUE TITLE
Could not bind closure

### ISSUE THREAD

**Issue by alf4712** [pestphp/pest#847]
FAILED  Tests\PestTest > pest                                                                      
  ShouldNotHappen
  This should not happen - please create an new issue here: https://github.com/pestphp/pest.

  Issue: Could not bind closure.
  PHP version: 8.2.6
  Operating system: Linux
  str_replace(): Argument #3 ($subject) must be of type array|string, null given

  at vendor/filp/whoops/src/Whoops/Exception/FrameCollection.php:43
     39▕      * @return FrameCollection
     40▕      */
     41▕     public function filter($callable)
     42▕     {
  ➜  43▕         $this->frames = array_values(array_filter($this->frames, $callable));
     44▕         return $this;
     45▕     }
     46▕
     47▕     /**

Script vendor/bin/pest handling the test event returned with error code 1
Script composer test handling the check-all event returned with error code 1

-- Version: 2.8.1

```php
<?php

declare(strict_types=1);

use PHPUnit\Framework\TestCase;

/**
 * @var TestCase $this
 */
test('pest', static function() : void {
    expect(date('d'))->toBe(date('d', time()));
});
```

**Comment by owenvoke** [comment]
You should remove the `static` keyword from the test closure. 👍🏻

```php
<?php

declare(strict_types=1);

use PHPUnit\Framework\TestCase;

/**
 * @var TestCase $this
 */
test('pest', function(): void {
    expect(date('d'))->toBe(date('d', time()));
});
```

**Comment by alf4712** [comment]
Yes, of course. Thank you.
