### ISSUE TITLE
PHP Warning:  file_put_contents(): Exclusive locks are not supported for this stream in DefaultResultCache.php on line 181

### ISSUE THREAD

**Issue by alf4712** [pestphp/pest#848]
pestphp/pest: v2.8.1
Windows 11

---
> php -v
PHP 8.2.5 (cli) (built: Apr 12 2023 08:42:33) (NTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.2.5, Copyright (c) Zend Technologies
    with Xdebug v3.2.1, Copyright (c) 2002-2023, by Derick Rethans

---
> vendor/bin/pest --bail

   PASS  Tests\Exceptions\ExceptionsTest
  ✓ it .......

  Tests:    17 passed (28 assertions)
  Duration: 1.28s

PHP Warning:  file_put_contents(): Exclusive locks are not supported for this stream in ........\vendor\pestphp\pest\overrides\Runner\ResultCache\DefaultResultCache.php on line 181

---
<?xml version="1.0" encoding="UTF-8"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/10.2/phpunit.xsd"
         colors="true" beStrictAboutOutputDuringTests="true">
    <testsuites>
        <testsuite name="Test Suite">
            <directory>./tests</directory>
        </testsuite>
    </testsuites>
    <coverage>
        <report>
            <html outputDirectory="build/coverage"/>
            <text outputFile="build/coverage.txt"/>
            <clover outputFile="build/logs/clover.xml"/>
        </report>
    </coverage>
    <logging>
        <junit outputFile="build/report.junit.xml"/>
    </logging>
    <source>
        <include>
            <directory suffix=".php">./src</directory>
        </include>
    </source>
</phpunit>

<img width="648" alt="image" src="https://github.com/pestphp/pest/assets/91665360/7d48d5b6-8d4a-4122-9b06-5f7a44ed75dc">

**Comment by alf4712** [comment]
Sorry for the whitespaces. I copy&paste my phpunit.xml
this is the file as a image.
<img width="552" alt="image" src="https://github.com/pestphp/pest/assets/91665360/4f73e012-3460-4beb-bfbd-6c86a323ff78">

**Comment by devajmeireles** [comment]
Hey, @alf4712 !

Thanks for your report. Unfortunately it seems to me that details are missing. I also noticed that you are on an outdated version of Pest, due to the date you opened this issue.

**Try to update your Pest and check if the error will occur. If so**, open a new issue now with as much detail as possible and even with an example repository. This makes it easier to work on a fix if it's a bug.
