### ISSUE TITLE
Documentation / Guide: Troubleshooting Pest

### ISSUE THREAD

**Issue by AlexMartinFR** [pestphp/pest#85]
We'll be collecting here the most common issues met by users, which doesn't (yet) belongs to a specific guide.

- testing API: [https://github.com/pestphp/pest/issues/33#issuecomment-634673474](https://github.com/pestphp/pest/issues/33#issuecomment-634673474)
- confusion between old & new Laravel methods, eg `visit()` is now `get()`: [https://github.com/pestphp/pest/issues/38#event-3382547293](https://github.com/pestphp/pest/issues/38#event-3382547293)
- Check if Pest is working on the latest Magento 2 version? composer dependencies issues?

(Feel free to add more when you encounter them)

**Comment by AlexMartinFR** [comment]
Move 1st installation step to the Troubleshooting guide (the note about phpunit.xml)

**Comment by nunomaduro** [comment]
I'm closing this issue because it has been inactive for a few months.
