### ISSUE TITLE
Some tests randomly fail with `stat(): stat failed for /path-to-project/.laravel`

### ISSUE THREAD

**Issue by innocenzi** [pestphp/pest#851]
## What happens

When running `./vendor/bin/pest --order-by random --stop-on-failure --stop-on-error`, some tests randomly fail with `stat(): stat failed for /path-to-project/.laravel`. I haven't find the cause.

![image](https://github.com/pestphp/pest/assets/16060559/0ac5d829-e46d-459c-9186-9c7b0e76479b)

## Additional details

This is the first time I ever encounter this. I'm using the latest version of Pest (`^2.8.2`) and Laravel (`^10.14.1`).

I'm also using an unconventional architecture for this project. Tests are located in `src/Feature/<SomeModule>/tests/<SomeTest.php>`. I'm using the following in `Pest.php`:

```php
uses(LazilyRefreshDatabase::class, Tests\TestCase::class)->in(
    '../src/Feature/*/tests/*Test.php',
);
```

I've tried running the test suite a few times and there always seem to be two failing tests. Running a test individually with `--filter` also triggers the error:

![image](https://github.com/pestphp/pest/assets/16060559/d5b3b689-43d4-43aa-b0a8-15117e347e63)

**Comment by innocenzi** [comment]
So the issue comes from [`Application#bindPathsInContainer`](https://github.com/laravel/framework/blob/10.x/src/Illuminate/Foundation/Application.php#L345), the questions now are:
- Why does `is_dir` fails instead of returning `false`
- Why does the error happen only for the two first tests

**Comment by innocenzi** [comment]
Found the culprit, this is unrelated to Pest. Sorry about that!

![image](https://github.com/pestphp/pest/assets/16060559/330a5d47-e6ed-40ab-9dd3-650c3a7c14b9)

**Comment by davideprevosto** [comment]
@innocenzi I am running the same problem. Can you suggest me how to identify the culprit? Thank you.

EDIT
found: https://github.com/dg/bypass-finals/pull/54
