### ISSUE TITLE
`toHaveProperties` does not handle nested array

### ISSUE THREAD

**Issue by abdul-alhasany** [pestphp/pest#852]
Hi
I am adding tests for my [WordPress plugin](https://wordpress.org/plugins/nashaat-activity-log/) and using `toHaveProperties` to check database value.

Since the database value is an array, I am using this test code:
```php
expect($edit_comment) ->toHaveProperties(array(
				'event'    => 'edited',
				'context'  => 'comment',
				'log_info' => array(
					'post_id'   => '1',
					'post_type' => 'post',
				),
			));
```
But it fails with an error stating that `log_info` is missing an item. 

I checked the source code for Pest and it seems that `toHaveProperties` only check for top-level properties.

I am happy to submit a PR if you consider updating this method or creating a new one.

**Comment by fabio-ivona** [comment]
Hi! Feel free to open a PR for it 😉

**Comment by abdul-alhasany** [comment]
Thanks. I forked the repo and ran the tests (without changing anything) but 2 gave failed. 

Tests\Visual\TeamCity > visual snapshot of team city with ('SuccessOnly.php'…   
  Failed asserting that two strings are equal.
Tests:    2 failed, 11 skipped, 2 passed (4 assertions)

Also, when I tried to run `composer update:snapshots` I received this error:
```bash
'REBUILD_SNAPSHOTS' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by fabio-ivona** [comment]
You can ignore integration tests, just run test:unit and test:parallel

**Comment by abdul-alhasany** [comment]
@fabio-ivona Sorry I did not read your message earlier. That is what I ended up doing anyway. I already submitted a PR.

**Comment by nunomaduro** [comment]
No plans for this.
