### ISSUE TITLE
Unable to test exceptions in higher order testing

### ISSUE THREAD

**Issue by ramsey** [pestphp/pest#853]
I encountered an unexpected issue while trying to test exceptions using higher order testing. It seems Pest does not properly catch the exceptions when using higher order testing.

For example:

```php
$tests = ['foo', 'bar', 'baz'];

it('throws exception using higher order testing')
    ->with($tests)
    ->expect(fn () => throw new Exception())
    ->toThrow(Exception::class);
```

I expect to see 3 tests pass. However, each test fails with a message like:

```
  FAILED  Tests\path\to\test > it throws exception…   Exception 
```

If I change the test to use the "standard" test structure, it passes, as expected:

```php
$tests = ['foo', 'bar', 'baz'];

it('throws exception using standard test structure', function () {
    expect(fn () => throw new Exception())
        ->toThrow(Exception::class);
})->with($tests);
```

**Comment by nunomaduro** [comment]
@lukeraymonddowning I know why it's failing, however do you have any recommendation here?

**Comment by nunomaduro** [comment]
```
it('throws exception using higher order testing')
    ->with($tests)
    ->expect(fn () => throw new Exception())
    ->throws(Exception::class);
```

It's `throws`.
