### ISSUE TITLE
Is it possible or viable to create an UI for pest like vitest UI?

### ISSUE THREAD

**Issue by roger-rocha** [pestphp/pest#856]
First of all im starting to use pest and im loving it, but however i come from vitest which is the testing framework im most familiar with.
I think it would be an amazing feature for pest to develop a UI like Vitest UI, i really think it could bring a lot of people to use it instead of phpUnit, it would be another great advantage, pest would have on top of phpUnit, for others  and for me also it would be a game changer.

**Comment by nunomaduro** [comment]
Not sure. However, no plans on my side for it.
