### ISSUE TITLE
Documentation / Guide: PHPStorm

### ISSUE THREAD

**Issue by AlexMartinFR** [pestphp/pest#86]
PHPStorm is a commonly used IDE and Pest integration is not ideal:

### **Feel free to add other user experiences on the same topic in the comments!**

This is for compiling users stories, try to reproduce their issue and see what we can do about that. The Pest ecosystem is moving quickly, perhaps a guide will not be needed at some point in the future. For now, I think this is going to be a big friction point preventing people to adopt Pest.

------------------------------------------------------------------------------------------------ 

### First feedback:

**Issue 1** - Forcing PHPStorm to use the Pest executable instead of the PHPUnit one was challenging. But solvable:

Just select `./vendor/bin/pest` as the `.phar` option:

![image](https://user-images.githubusercontent.com/19224681/83339338-2d495f00-a2cd-11ea-8ffb-77f7e345cb5a.png)

**Issue 2** - The working directory MUST be set to the folder that contains `composer.json` otherwise Pest throws a _file not found_ exception.

**Issue 3** - Because tests written with Pest do not need a class extending TestCase , PHPStorm marks these test files as "normal php scripts" and not "PHPUnit files". This means when clicking the RUN/DEBUG icon (which would normally launch PHPUnit for testing), instead it tries to run the file with regular PHP causing errors / exit immediately.

**Issue 4** - When using the most simple test on the Pest website **I could not get any of the `assertSomething()` methods via autocomplete** after the `test()` method:

```php
test('true is true')->assertTrue(true);
```

![image](https://user-images.githubusercontent.com/19224681/83339377-81544380-a2cd-11ea-8dde-e5baebab4ef3.png)

**Issue 5** - When we run a test suite having both PHPUnit tests and Pest tests from PHPStorm, only the PHPUnit tests will run and be reported upon:

![image](https://user-images.githubusercontent.com/19224681/83339423-ec9e1580-a2cd-11ea-8283-be22af209f9c.png)

When the same test suite is run from Pest CLI, the 8th Pest test is ran:

![image](https://user-images.githubusercontent.com/19224681/83339418-e27c1700-a2cd-11ea-958c-fc265170d7b8.png)

**Comment by AlexMartinFR** [comment]
Finally extracted/edited the main issues from this user feedback.

This issue would be fixed by [#5 Missing PHPStorm Plugin](https://github.com/pestphp/pest/issues/5)

**Comment by jonnywilliamson** [comment]
Thank you for extracting that.

**Comment by AlexMartinFR** [comment]
Continuing on: https://github.com/pestphp/pest/issues/86
