### ISSUE TITLE
 Call to undefined method Tests\Feature\ExampleTest::get()

### ISSUE THREAD

**Issue by rasasak** [pestphp/pest#862]
After update 2.8. to 2.9.  I get error 
" Call to undefined method Tests\Feature\ExampleTest::get()"

is there some upgrade guide from 2.8. to 2.9. ? 
or some dependency to upgrade too ? 
![Bez názvu](https://github.com/pestphp/pest/assets/28921659/bc14f479-03a5-4c73-be79-9a517e45ee2d)

![Bez názvu](https://github.com/pestphp/pest/assets/28921659/b084d03a-b508-47c6-8bad-934e21b3bcd3)

**Comment by ghost** [comment]
Looking for solution also.
After upgrading to 2.9, My test is failing on ` Model::factory()->create() ` and produce error below.
_Call to a member function connection() on null._

It was perfectly working on  v2.8.

**Comment by rasasak** [comment]
OK,  i Fixed it 

In PEST.php 

I replaced 

`uses(
    Tests\TestCase::class,
    Illuminate\Foundation\Testing\RefreshDatabase::class,
)->in('Feature');`

with

`uses(
    Tests\TestCase::class,
    Illuminate\Foundation\Testing\RefreshDatabase::class,
)->in(__DIR__.'\Feature');`

now it workds ... weird problem

**Comment by ghost** [comment]
Thanks, Thats worked for me also.

**Comment by nunomaduro** [comment]
You both use Windows?

**Comment by ghost** [comment]
Yes, I am on Windows.

**Comment by rasasak** [comment]
yes, windows

**Comment by nunomaduro** [comment]
Please download the latest version of Pest, and close the issue if the latest version fixes the issue.

**Comment by rasasak** [comment]
Yup.. it works .. Thanks :)
