### ISSUE TITLE
[Feature Request / Suggestion] Probably Test Failures (False Positives)

### ISSUE THREAD

**Issue by devajmeireles** [pestphp/pest#863]
Hey, @nunomaduro, 

I decided to suggest this feature based on a reality that I live today and that may also be the reality for other people.

# Problem

Currently one of my applications with Laravel 10 has about 1200 tests, and among these tests there are some that fail without necessarily being a failure - a false positive. The tests that fail are linked to files that may or may not be created as the tests run.

# Suggestion

For cases similar to this one, we could count on some differential in Pest. At first I thought of in some conditionals:

```php
->skipOnFailure()
```
👆🏻 expresses the idea that the test was ignored because it failed - but i found it confusing.

```php
->falsePositive()
```
👆🏻 expresses the idea that the test contains probably false positive failures.

```php
// preparing...
test()->probablyFailures($reasons);

// then...
->acceptProbablyFailuresOf($reasons)
```
👆🏻 expresses the idea that the test contains probably false positive failures that was registered to provide a better controller of the failures - **most acceptable.**

Hope this help,

Thanks.

**Comment by nunomaduro** [comment]
Thanks for the suggestion.
