### ISSUE TITLE
beforeEach not called in Pest ^2.9.0 on Windows

### ISSUE THREAD

**Issue by Lukasss93** [pestphp/pest#865]
The beforeEach function is not called in Pest ^2.9.0 on Windows (php 8.2)

## Code
```php
beforeEach(function () {
    $this->foo = 'bar';
});

test('foo is bar', function () {
    expect($this->foo)->toBe('bar');
});
``` 

### Pest v2.8.3
Tests:    1 passed (1 assertions)
Duration: 0.29s

### Pest v2.9.0 - v2.9.1
Failed asserting that null is identical to 'bar'.

**Comment by nunomaduro** [comment]
You using Windows?

**Comment by Lukasss93** [comment]
> You using Windows?

Yes, it doesn't work only on Windows (using php 8.2)

**Comment by nunomaduro** [comment]
Please download the latest version of Pest, and close the issue if the latest version fixes the issue.

**Comment by Lukasss93** [comment]
Fixed. Thanks
