### ISSUE TITLE
Psalm UndefinedDocblockClass for Expectable in functions.php

### ISSUE THREAD

**Issue by ndench** [pestphp/pest#867]
After upgrading to 2.9.x we get psalm reporting a lot of `UndefinedDockblockClass` issues on our pest tests.
It appears to be caused by https://github.com/pestphp/pest/commit/4f3796ed2e0158773889a143ab430d4e0cdae209.

This has been raised in psalm a while back (https://github.com/vimeo/psalm/issues/3695) and the response was
> Traits are not types so you shouldn't use them as types.

Maybe we should define an `ExpectableInterface` and use that type instead?

**Comment by nunomaduro** [comment]
That's an issue with psalm. Not Pest.

**Comment by kielabokkie** [comment]
@nunomaduro Would you reconsider this if PHPStan agrees with Psalm that Traits should not be used as types?

https://phpstan.org/writing-php-code/phpdoc-types#classes-and-interfaces


<img width="1008" alt="Screen Shot 2023-07-24 at 12 19 26 PM" src="https://github.com/pestphp/pest/assets/1221750/1e483eaf-2373-4dfb-b399-608b325934dc">
