### ISSUE TITLE
Documentation / Guide: Resources to learn testing

### ISSUE THREAD

**Issue by AlexMartinFR** [pestphp/pest#87]
I'm convinced Pest's simplicity will bring new users to the testing world.

Pointing newcomers to learning resources would be interesting.
Until @nunomaduro comes up with learning material of his own, at least!

Just some of the many who jump on the occasion to get onboard the testing train:

> Heya!
> Never wrote tests, Pest makes me want to start this ..

> I never ever wrote any test. I want to, but since code works as expected, i never tried to learn. Can someone advice me, or perhaps there is good that takes you step by step using Pest to write test?

> Hey nunomaduro  I have always wanted to test but this has inspired me to actually learn to really do it well.

> Nice! I think Pest will be a great way to begin/learn testing with its clean syntax. (me 😋)

> Maybe it’s not the best place... Does anyone recommend me a tutorial for learning to make tests? Thks. :sweat_smile:

**Comment by nunomaduro** [comment]
The community have done some material, and indeed I've some planned too.
