### ISSUE TITLE
error: call to undefined method todo()

### ISSUE THREAD

**Issue by aagjalpankaj** [pestphp/pest#873]
I just installed pestphp. Creating todo tests according to https://pestphp.com/docs/skipping-tests#content-creating-todos but getting below error: 
<img width="765" alt="image" src="https://github.com/pestphp/pest/assets/15609300/464af406-6e14-49a3-bae1-30e33b33577d">

`FeatureTestCase` extends `Illuminate\Foundation\Testing\TestCase`.

**Comment by nunomaduro** [comment]
Are you using the latest version of Pest PHP?
