### ISSUE TITLE
Using Pest expect() inside PHPUnit is a good idea?

### ISSUE THREAD

**Issue by julien-boudry** [pestphp/pest#874]
If we want to use PHPUnit and want to keep it (at least for some time or forever).
And if Pest is required in `composer.json`.

Then we can use the Pest Expectation API `expect()` inside PHPUnit style tests (with class, method, attributes, and all options). And run the test suite with PHPUnit (or also with Pest).

And everything seems to work perfectly!

I love this Pest Expectation API, but I'm not ready or perfectly convinced to migrate to a full Pest for now.
Do you think it's a good idea, and will this practice be maintained for long?

**Comment by nunomaduro** [comment]
Typically the regular Pest user just use the new API, however you are free to use the `expect` inside a regular PHPUnit test.
