### ISSUE TITLE
question: Globs in architecture tests

### ISSUE THREAD

**Issue by alejandrovelez7** [pestphp/pest#875]
Hi Pest maintainers!

First of all, love the architecture tests! 

I created this [small repo](https://github.com/alejandrovelez7/modular-laravel) to showcase how to use architecture tests to enforce domain driven design boundaries, but it gets a little wordy in some cases. 

Are globs allowed? Or can I specify broader namespaces in some other way? 

It would be really cool if I could write -> 

```php
    test('only uses contracts of other domains')
        ->expect('App\Domains\Support')
        ->toOnlyUse('App\Domains\Support')
        ->ignoring('App\Domains\**\Contracts') // allow using other domains' contracts
        ->ignoring('Spatie\LaravelData\**')
        ->ignoring('Illuminate\**\*')
```

Instead of:
```php
  test('only uses contracts of other domains')
      ->expect('App\Domains\Support')
      ->toOnlyUse('App\Domains\Support')
      ->ignoring('App\Domains\Sales\Contracts')
      ->ignoring('Spatie\LaravelData\Data')
      ->ignoring('Spatie\LaravelData\Attributes\DataCollectionOf')
      ->ignoring('Illuminate\Support\ServiceProvider')
      ->ignoring('Illuminate\Database\Eloquent\Model');
```

Thanks in advance, and keep up the great work! ❤️

**Comment by devajmeireles** [comment]
Hey, @alejandrovelez7 . Thank you for your feedback.

Feel free to send us a PR with this addition. If not, we'll need to wait for PR from someone else or the Pest team.

**Comment by jaimesares** [comment]
Hi @alejandrovelez7 

You can use datasets. It would be something like this:

```php
$namespaces = [
    'Animals',
    'Users',
];

test('enums', function ($namespace) {
    expect("SukyCMS\\Domain\\$namespace\\Enums")->toBeEnums();
})->with($namespaces);
```

In this way, you can reuse the namespaces until glob becomes compatible with arch plugin.

**Comment by devajmeireles** [comment]
According to the @jaimesares reply, I'm closing this issue and tagging this as a suggestion for the next Pest releases.

**Comment by pindab0ter** [comment]
> Hi @alejandrovelez7
> 
> You can use datasets. It would be something like this:
> 
> ```
> $namespaces = [
>     'Animals',
>     'Users',
> ];
> 
> test('enums', function ($namespace) {
>     expect("SukyCMS\\Domain\\$namespace\\Enums")->toBeEnums();
> })->with($namespaces);
> ```
> 
> In this way, you can reuse the namespaces until glob becomes compatible with arch plugin.

I'm currently looking for a way to dynamically load in all known namespaces and filter then down to the ones I want to have the test apply to. I haven't found a way to do this that isn't manuall scanning every folder and opening every file to check the declared namespace. Is there a way to do this that I haven't found yet?

**Comment by jaimesares** [comment]
> > Hi @alejandrovelez7
> > You can use datasets. It would be something like this:
> > ```
> > $namespaces = [
> >     'Animals',
> >     'Users',
> > ];
> > 
> > test('enums', function ($namespace) {
> >     expect("SukyCMS\\Domain\\$namespace\\Enums")->toBeEnums();
> > })->with($namespaces);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In this way, you can reuse the namespaces until glob becomes compatible with arch plugin.
> 
> I'm currently looking for a way to dynamically load in all known namespaces and filter then down to the ones I want to have the test apply to. I haven't found a way to do this that isn't manuall scanning every folder and opening every file to check the declared namespace. Is there a way to do this that I haven't found yet?

I'm doing this:

```
use App\Core\Enums\Module;

arch('arch action tests', function ($module) {
    expect("App\Domain\{$module}\Actions")
        ->toBeReadonly()
        ->toHaveMethod('handle');
})->with(Module::toNamespaces());

arch('arch controller tests', function ($module) {
    expect("App\Domain\{$module}\Models")
        ->not->toBeUsedIn("App\Admin\{$module}\Controllers");
})->with(Module::toNamespaces());
```

with a Module enum:

```
<?php

namespace App\Core\Enums;

use Illuminate\Support\Str;

enum Module: string
{
    case USERS = 'users';
    
    ... rest

    public static function toNamespaces(): array
    {
        return array_map(
            fn (Module $module) => Str::title($module->value),
            self::cases(),
        );
    }
}
```

You can custom `toNamespaces` method to adapt it to your case. There is no way to use a wildcard at this moment. See https://github.com/pestphp/pest/discussions/1072

**Comment by marvinschroeder** [comment]
Would be great to have a glob integration into architectural tests, especially when using DDD (domain driven design). So if you have this structure including the namespace Domain:

- Domain
- - Finance
- - - Models
- - - - Account.php
- - - - Scopes
- - - - - SomeScope.php
- - Users
- - - Models
- - - - User.php

It would be great to define this (based on the Laravel preset):
```
expect('Domain\*\Models')
            ->classes()
            ->toExtend('Illuminate\Database\Eloquent\Model')
            ->ignoring('Domain\*\Models\Scopes');

expect('Domain\*\Models')
            ->classes()
            ->not->toHaveSuffix('Model')
```
