### ISSUE TITLE
Allow adding skip/todo at the beginning rather than the end

### ISSUE THREAD

**Issue by swissspidy** [pestphp/pest#876]
Let's say you have a very long test (or describe block):

```php
it('has home', function () {
    //
    // ... more lines
    //
})->skip();
```

When you're skimming over a test file or doing a code review, it is difficult to see at a glance which test the `skip()` actually belongs to.

In Jest that's not a problem because you use `it.skip` and `it.todo`. And if you ever unskip the test, it is much easier to review.

It would be interesting to support something like `it()->skip( 'has home', function () { ... });` or `it_skip( 'has home', function () { ... });` (`it_skipOnWindows( 'has home', function () { ... });`)

**Comment by swissspidy** [comment]
Alternative suggestion from https://twitter.com/lillerik/status/1684118662892879872: xit, xdescribe like in Jasmine

**Comment by slowmove** [comment]
> Alternative suggestion from https://twitter.com/lillerik/status/1684118662892879872: xit, xdescribe like in Jasmine

This is as well supported in Jest (biggest JavaScript testing framework) but also Kahlan (php) ![image](https://github.com/pestphp/pest/assets/624182/b0a2b1b7-44ab-48ae-8af4-0b95f65b9757)

**Comment by nunomaduro** [comment]
No plans for this.
