### ISSUE TITLE
toUse() is not providing feedback on where the test failed

### ISSUE THREAD

**Issue by haheap** [pestphp/pest#878]
When I use ->toExtend() I get a nice error message showing me exactly where the test failed.
But when using ->toUse() there doesn't seem to be any information except that the test failed.

The first test here is using toUse(), where the second is testing ->toExtend():
![image](https://github.com/pestphp/pest/assets/48035047/ff7e5542-7ee5-4dcb-a048-5fabf4242010)

I am trying to make sure, that any deprecated classes are not being called by my application.

These are my two tests (second one of course just to force an error ;-) ):
 
```
test('project is not using deprecated legacy classes')
    ->expect('App\Console\Commands')
    ->not()
    ->toUse(['App\Models\Legacy\Photo', 'App\Models\Legacy\Event', 'App\Models\Legacy\User']);

test('models')
    ->expect('App\Models')
    ->not()
    ->toExtend('Illuminate\Database\Eloquent\Model');
```

**Comment by fabio-ivona** [comment]
@haheap thanks for pointing this out, will have a check on this one :+1:

**Comment by haheap** [comment]
Thanks @fabio-ivona - This is of course only a problem when making the expectation for an entire namespace instead of a single class.

**Comment by devajmeireles** [comment]
> Thanks @fabio-ivona - This is of course only a problem when making the expectation for an entire namespace instead of a single class.

Could you open a PR with this improvement, please?

**Comment by nunomaduro** [comment]
@haheap Feel free to open a pull request on this.
