### ISSUE TITLE
Inconsistent xsi:noNamespaceSchemaLocation in phpunit.xml between --init and --migrate-configuration

### ISSUE THREAD

**Issue by MichaelRushton** [pestphp/pest#879]
When initialising using `./vendor/bin/pest --init` the `phpunit.xml` uses `xsi:noNamespaceSchemaLocation="./vendor/phpunit/phpunit/phpunit.xsd"` but when migrating an existing `phpunit.xml` using `./vendor/bin/pest --migrate-configuration` it uses `xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/10.2/phpunit.xsd"`.

Wouldn't it be better for them to use the same (whichever is chosen)?

**Comment by devajmeireles** [comment]
> When initialising using `./vendor/bin/pest --init` the `phpunit.xml` uses `xsi:noNamespaceSchemaLocation="./vendor/phpunit/phpunit/phpunit.xsd"` but when migrating an existing `phpunit.xml` using `./vendor/bin/pest --migrate-configuration` it uses `xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/10.2/phpunit.xsd"`.
> 
> Wouldn't it be better for them to use the same (whichever is chosen)?

Hey @MichaelRushton. Thanks for your report.

As the alert happens by PhpUnit, I created a PR (https://github.com/pestphp/pest/pull/915) to adapt the Pest stubs to the expected format. Let's wait for @nunomaduro review to check if we're right about this procedure.
