### ISSUE TITLE
Documentation / Guide: Common assertions

### ISSUE THREAD

**Issue by AlexMartinFR** [pestphp/pest#88]
**Purpose:**
List the most commonly used PHPUnit assertions with small description for newcomers.

For more edge-cases, the user would then find the link to the full [assertions list](https://phpunit.readthedocs.io/en/latest/assertions.html) at the end of the document.

**Benefits:**
- Don't make the user have to go through 2 different sites for the basic needs. They can find everything in one place (Pest)
- Search assertions directly from the [Pest Docs Alfred Workflow](https://github.com/AlexMartinFR/alfred-pestphp-docs) (same reasoning as before)

**Hanging decisions:**
- Should this be merged with [#40 Resources to learn testing](https://github.com/pestphp/website/issues/40) ?
- Should this be a PHPUnit - part 2 Guide?
- Should we list Laravel's custom assertions in the _Laravel_ Guide, or in a Laravel section of the _Common Assertions_ Guide ?
- What are the common assertions we want to list?

**Comment by nunomaduro** [comment]
We already have this.
