### ISSUE TITLE
Running pest test suite with PHPStorm creates a ./--cache-result/test-results file

### ISSUE THREAD

**Issue by Roboroads** [pestphp/pest#882]
Idk if it's important, but running with sail (through docker compose interpreter).

As title sais: Running pest test suite with PHPStorm creates a `./--cache-result/test-results` file

**Comment by keyvangholami** [comment]
If you want to prevent the creation of the ./--cache-result/test-results file when running the pest test suite with PHPStorm, you can use the `--do-not-cache-result` flag. This will disable the caching of results, and the file will not be generated.
