### ISSUE TITLE
Test fails with "Target class [translator] does not exist" if return value is translated

### ISSUE THREAD

**Issue by Bergrebell** [pestphp/pest#883]
I have the following function that I want to test:

```
public static function formatCurrency($value, $currencyCode, int $precision = 0, string $decimalSeparator = '.', string $thousandsSeparator = '\'', bool $removeTrailingZeros = true)
    {
        $number = self::formatNumber($value, $precision, $decimalSeparator, $thousandsSeparator, $removeTrailingZeros);

        return $currencyCode ? __('strings.currencies.'.$currencyCode, ['value' => $number]) : $number;
    }
```

using the following test:

```
it('formats a number as currency with thousands and decimal separator', function () {
    $result = NumberFormatter::formatCurrency(12.34, 'USD');

    expect($result)->toBe('$12');
});
```

which results in a `BindingResolutionException` with `Target class [translator] does not exist.`

What am i missing here? I'm using a standard (default) installation of pest in Laravel 10.

**Comment by haheap** [comment]
Could you be writing the test in the unit test directory? Unit tests don't have access to the translator.

**Comment by Bergrebell** [comment]
@haheap - yes that's been the issue. adding `uses(Tests\TestCase::class)->in('Unit');` in `Pest.php` solved it for me.
