### ISSUE TITLE
Snapshot Test incomplete?

### ISSUE THREAD

**Issue by IgorDePaula** [pestphp/pest#886]
![image](https://github.com/pestphp/pest/assets/2833993/ee883ccc-60ac-44c8-896e-6bce1118d834)

**Comment by fabio-ivona** [comment]
Could you elaborate?

**Comment by IgorDePaula** [comment]
> Could you elaborate?

The script said that my test is incomplete, but why? No reason. Your message isn`t elaborated.

I put a print of message from script and my code.

**Comment by fabio-ivona** [comment]
The test is incomplete because the snapshot was created in that moment, so no check was done yet

On subsequent runs it should do the check and show as green (or red of if something failed)
