### ISSUE TITLE
Documentation / Guide: Pest From Scratch

### ISSUE THREAD

**Issue by AlexMartinFR** [pestphp/pest#89]
Some have troubles apparently when installing Pest on a blank project, this might warrant a guide too.

Extracts from something posted on our Discord help channel*
It's an interesting comment, but needs curation before we extract the relevant part to the docs. I've only pasted the part regarding the current state of Pest:

**Boilerplate architecture and config:**
> The docs say to write a test, create a file in the Unit or Feature directory. I don't have those as I am starting a new project and don't already use PHPUnit. It also says Pest will only run a test file if its name ends with the suffix set in your phpunit.xml. But I don't have one of those yet either. Is there a good guide for getting started with Pest from scratch?

> IDK, maybe I'm overcomplicating it in my mind, but the docs left me with the impression that was a special directory somewhere for Unit and for Feature that should already be configured somehow with/for PHPUnit, as opposed to, just make a directory called Unit and Feature. I'm also imagining I shouldn't just create a phpunit.xml file myself, it is probably supposed to be generated by something with some default settings placed in it first.

> I tried just running pest, it said a tests folder was not found, so I made one. Then it runs without crashing, but just outputs phpunit command line options. I looked through them and found --generate-configuration
> I tried using it with pest instead of phpunit, just to see if it would work, since I'm trying to sort of pretend phpunit doesn't exit. It worked, it asked me about the defaults and generated that phpunit.xml file
> Hmm. It seems to be ignoring the phpunit.xml file. The docs made it sound like it would use it automatically
> It's still looking for a tests directory, even though I specified a different directory
> Okay, so if I create the tests directory again, just to make it happy, and then put the tests where I want it still runs them. Lame I need a random empty tests directory though.

> Well at least I know I don't actually need those Unit and Feature directories the docs talked about. It is running with a test file being right next to the class it is testing, in the same directory. I much prefer that, since if I rename the directory/namespace, I only need to rename it in one place. This also creates less friction when going back and forth between the tests and the code, which makes programmers less likely to ignore the tests, either not adding more when they should or forgetting they exist. It makes it very natural to edit and run the code and tests together.

That's all for now, the rest of the comment was about Psalm compatibility and wishes for the future of Pest.

* _Cf Discord, #help, June 2nd, 2020._

**Comment by AlexMartinFR** [comment]
I think this issue should be addressed with the upcoming release of Pest 0.2.0 and the awesome init plugin 👌

The new **Install Pest on a blank project** section on the **Installation** page should fill this void.

**Comment by owenvoke** [comment]
I guess this can be closed as it seems to be available now in https://pestphp.com/docs/guides/pest-from-scratch/ ? 🤔

One thing to note, the image at the bottom doesn't correspond to how the actual output is.

![Preview of output from pest init](https://user-images.githubusercontent.com/1899334/87043778-80c49c00-c1ed-11ea-8691-babc3d240e5e.png)

**Comment by AlexMartinFR** [comment]
Yes we could close the issue now, but now that you mention it, there is this picture problem to solve.

I wonder though, shouldn't the **pest-plugin-init** create a _Unit_ & _Feature_ folders, with their respective example tests?
(Following Laravel's default structure)

**Comment by owenvoke** [comment]
Not sure, the `init` plugin isn't really only for Laravel. So it sets up a generic structure to get started. However, the Laravel Artisan command will set up a Laravel structure.

**Comment by AlexMartinFR** [comment]
I'm wondering what people usually do in other projects, isn't Feature/Unit folder a common need even beyond Laravel?

**Comment by owenvoke** [comment]
I've seen various structures. Often a unit directory, sometimes all top-level, sometimes feature, integration, functionality, etc. That's why I thought keeping it vague would be best. That way people can just create a directory structure if that's what they want.

The [current `phpunit.xml` provided](https://github.com/pestphp/pest-plugin-init/blob/master/stubs/phpunit.xml) by `--init` just runs any file ending with `Test.php` that's under the entire tests directory. Which I think is a good starting point.

If they want to have a more advanced config, they could use the `pest --generate-configuration` flag, or manually edit it.

**Comment by AlexMartinFR** [comment]
Good point, thanks for your insights 👍 

I've updated the image, let's close this now.
