### ISSUE TITLE
Documentation / UX: Improvements ideas

### ISSUE THREAD

**Issue by AlexMartinFR** [pestphp/pest#90]
Let's list here the changes we would like to make to the docs in a futur overhaul.

**Comment by AlexMartinFR** [comment]
I like how the Laravel documentation has a table of content and anchors to subsections titles.
This could be good for Pest documentation:

<img width="923" alt="Capture d’écran 2020-06-13 à 12 03 54" src="https://user-images.githubusercontent.com/19224681/84566022-0b8cb500-ad6e-11ea-862b-a3a6da5bdf8f.png">

**Comment by AlexMartinFR** [comment]
# Idea 2:

Provide a **Copy to Clipboard** button next to relevant command lines:

<img width="903" alt="Capture d’écran 2020-06-13 à 17 26 07" src="https://user-images.githubusercontent.com/19224681/84572559-20337200-ad9b-11ea-9a58-5a1dbb7e7cb2.png">

**Comment by nunomaduro** [comment]
@octoper Can you work on this one? I would love, but I am afraid on don't have the skills.

**Comment by octoper** [comment]
I'm on it @nunomaduro

**Comment by AlexMartinFR** [comment]
Posting @octoper 's idea before it gets buried since he's busy for now:

Provide a version selector for the docs, if/when we'll have breaking changes in the API.

(I think for the moment it's not urgent, as Pest dev is still moving fast and we are expecting people to update to latest version. This can wait until it smoothes out perhaps?)

**Comment by owenvoke** [comment]
Closing as this has mostly all been implemented on the new site, and the version is planned in future. :+1:
