### ISSUE TITLE
The `describe` does not support dataset

### ISSUE THREAD

**Issue by godruoyi** [pestphp/pest#901]
I am trying to use "describe" with a dataset as shown below, but I am encountering an error:

```php
describe('hello', function ($email) {
    $person = new Person($email);

    it('one', function () use ($person) {...});
    it('two', function () use ($person) {...});
})->with(['enunomaduro@gmail.com', 'other@example.com']);
```

Error: 

```
ERROR  Too few arguments to function PHPUnit\Runner\TestSuiteLoader::{closure}(), 0 passed in vendor/pestphp/pest/src/PendingCalls/DescribeCall.php on line 67 and exactly 1 expected

Location: tests/Feature/BasicIOTest.php:23
```

I want to use dataset to initialize some data, and then the entire describe test will use this initialize data. Are there any other ways to achieve this? 

Also, do we have plans to add dataset support for describe? If there is such a plan, I'd like to contribute my PR.

**Comment by godruoyi** [comment]
https://github.com/apache/incubator-opendal/blob/aebe3170fdd70b15d25461527816bc70311b591d/bindings/php/tests/Feature/BasicIOTest.php#L21

**Comment by fabio-ivona** [comment]
Datasets are meant to be used in a test, they are currently not supported for describe()

**Comment by godruoyi** [comment]
@fabio-ivona I am very sad that this issue was closed directly. Do we have any plans to support datasets for describe? I am also willing to contribute my PR for it.

**Comment by fabio-ivona** [comment]
@godruoyi feel free to open a PR for it 😉
