### ISSUE TITLE
No Pest\Expectation suggestions in Pest 2.13 in Laravel 10

### ISSUE THREAD

**Issue by kevinkoenen** [pestphp/pest#903]
Hi,

First, thank you for the great library!

On a new project, suggestions is not working on the expect function of the library:
<img width="352" alt="image" src="https://github.com/pestphp/pest/assets/30780782/33c6bbd0-5d66-4bc2-bca7-25dba2ab979d">

Laravel 10.10 with PHP 8.1 with the following packages:
"phpunit/phpunit": "10.3.1",
"pestphp/pest": "2.13",

I use PHPStorm 2023.2 with the official Pest plugin 1.10.1.

Steps to reproduce:
1. Download PHPStorm 2023.2
2. Install a fresh Laravel 10 application
3. Install the Pest plugin
4. Go to the existing feature test
5. write `expect()->` and press `control + space` for the suggestions.

Tested with the Pest plugin and without.
Testen with all plugins disabled.

You will see that there are no suggestions.

Seems PHP 8.1 and Laravel 8 with Pest 1.x has no issues with the suggestions. Both running in PHPStorm 2023.2:
<img width="748" alt="image" src="https://github.com/pestphp/pest/assets/30780782/37f166e2-38c2-4e55-9b52-05f66814411d">

Even the `__constructor` from `vendor/pestphp/pest/src/Expectation.php` class doesn't show any suggestions:
<img width="432" alt="image" src="https://github.com/pestphp/pest/assets/30780782/e2b044ea-c479-46af-b04c-dae31dfee862">
No issues when I test other packages.

Many thanks in advance for your reply!

**Comment by devajmeireles** [comment]
> Hi,
> 
> First, thank you for the great library!
> 
> On a new project, suggestions is not working on the expect function of the library: <img alt="image" width="352" src="https://user-images.githubusercontent.com/30780782/259727724-33c6bbd0-5d66-4bc2-bca7-25dba2ab979d.png">
> 
> Laravel 10.10 with PHP 8.1 with the following packages: "phpunit/phpunit": "10.3.1", "pestphp/pest": "2.13",
> 
> I use PHPStorm 2023.2 with the official Pest plugin 1.10.1.
> 
> Steps to reproduce:
> 
> 1. Download PHPStorm 2023.2
> 2. Install a fresh Laravel 10 application
> 3. Install the Pest plugin
> 4. Go to the existing feature test
> 5. write `expect()->` and press `control + space` for the suggestions.
> 
> Tested with the Pest plugin and without. Testen with all plugins disabled.
> 
> You will see that there are no suggestions.
> 
> Seems PHP 8.1 and Laravel 8 with Pest 1.x has no issues with the suggestions. Both running in PHPStorm 2023.2: <img alt="image" width="748" src="https://user-images.githubusercontent.com/30780782/259772147-37f166e2-38c2-4e55-9b52-05f66814411d.png">
> 
> Even the `__constructor` from `vendor/pestphp/pest/src/Expectation.php` class doesn't show any suggestions: <img alt="image" width="432" src="https://user-images.githubusercontent.com/30780782/259778236-e2b044ea-c479-46af-b04c-dae31dfee862.png"> No issues when I test other packages.
> 
> Many thanks in advance for your reply!

Try to turn off your assistente (AI) and check again. I have the same problem when I'm using Github Copilot.

**Comment by kevinkoenen** [comment]
> Try to turn off your assistente (AI) and check again. I have the same problem when I'm using Github Copilot.

Thanks for you reply. Turning of the AI doesn't fix the problem.

**Comment by devajmeireles** [comment]
> > Try to turn off your assistente (AI) and check again. I have the same problem when I'm using Github Copilot.
> 
> Thanks for you reply. Turning of the AI doesn't fix the problem.

As this is not an issue with Pest, I will close this issue. Check your IDE. I and other people are using PhpStorm and these issues usually happen due to AI like Copilot. When disabled, we have access to methods and reference. Also, it might be worth relocating this issue to the Pest plugin repository for PhpStorm: https://github.com/pestphp/pest-intellij
