### ISSUE TITLE
Random Test Failures with Laravel Inertia React Default Testing

### ISSUE THREAD

**Issue by Putnug1122** [pestphp/pest#904]
I'm facing different failed test every time I'm running testing on default Laravel + Inertia + React tests. It's using user factories and faker. I'm not changing anything it's just makes CI/CD difficult 

- Laravel version : 10.10
- PHP : 8.1
- inertiajs/inertia-laravel : 0.6.3,
- Pest : 2.0
- Faker : 1.9.1

1. First Testing
![image](https://github.com/pestphp/pest/assets/62296958/c81ac06e-f758-4c6e-9b89-6f8256568581)

2. Second Testing
![image](https://github.com/pestphp/pest/assets/62296958/4030b6ec-dcd7-4ae7-bcfa-5a77917c5b82)

Anyone having same issue ?

**Comment by devajmeireles** [comment]
> I'm facing different failed test every time I'm running testing on default Laravel + Inertia + React tests. It's using user factories and faker. I'm not changing anything it's just makes CI/CD difficult
> 
> * Laravel version : 10.10
> * PHP : 8.1
> * inertiajs/inertia-laravel : 0.6.3,
> * Pest : 2.0
> * Faker : 1.9.1
> 
> 1. First Testing
>    ![image](https://user-images.githubusercontent.com/62296958/259759678-c81ac06e-f758-4c6e-9b89-6f8256568581.png)
> 2. Second Testing
>    ![image](https://user-images.githubusercontent.com/62296958/259759889-4030b6ec-dcd7-4ae7-bcfa-5a77917c5b82.png)
> 
> Anyone having same issue ?

The fact that you have tests passing and tests failing is evidence that there may be something wrong with the test written or with the code being tested. I have the same behavior when I test some code that deal with text files. If the text file exists, the test will fail, I always need to delete the files before the test.

**Comment by devajmeireles** [comment]
> I'm facing different failed test every time I'm running testing on default Laravel + Inertia + React tests. It's using user factories and faker. I'm not changing anything it's just makes CI/CD difficult
> 
> * Laravel version : 10.10
> * PHP : 8.1
> * inertiajs/inertia-laravel : 0.6.3,
> * Pest : 2.0
> * Faker : 1.9.1
> 
> 1. First Testing
>    ![image](https://user-images.githubusercontent.com/62296958/259759678-c81ac06e-f758-4c6e-9b89-6f8256568581.png)
> 2. Second Testing
>    ![image](https://user-images.githubusercontent.com/62296958/259759889-4030b6ec-dcd7-4ae7-bcfa-5a77917c5b82.png)
> 
> Anyone having same issue ?

I noticed that you didn't answer me. I will close this issue. Please, if the issue persists, feel free to open another issue with more details.
