### ISSUE TITLE
`repeat` method needs some improvements.

### ISSUE THREAD

**Issue by utsavsomaiya** [pestphp/pest#908]
![image](https://github.com/pestphp/pest/assets/96036522/13874a9c-4f1a-47d3-acf4-9e722a852ffb)

**Comment by devajmeireles** [comment]
> ![image](https://user-images.githubusercontent.com/96036522/260444612-13874a9c-4f1a-47d3-acf4-9e722a852ffb.png)

Would be a very good addition, @nunomaduro. I think I'm able to do that 😣 As a workaround, you can do that, @utsavsomaiya :

![CleanShot 2023-08-15 at 6 46 58](https://github.com/pestphp/pest/assets/60591772/793f9280-4008-4340-ac38-0a3193170da8)

**Comment by nunomaduro** [comment]
@devajmeireles Can you do a pull request? Thanks!

**Comment by utsavsomaiya** [comment]
I will try from my side.. If I am not getting into it. Then can you please help me?

**Comment by Katalam** [comment]
@utsavsomaiya I created a PR for it, I wasn't sure how much work you already put into it, but I thought I try it anyway

**Comment by utsavsomaiya** [comment]
> @utsavsomaiya I created a PR for it, I wasn't sure how much work you already put into it, but I thought I try it anyway

Okay.. you can do it.

**Comment by nunomaduro** [comment]
Fixed in Pest `v3.x`.
