### ISSUE TITLE
Output on Windows and parallel testing not correctly formatted

### ISSUE THREAD

**Issue by schonhoff** [pestphp/pest#909]
Hey!

I'm currently trying out pest as my default testing framework. I'm very positively impressed by its output and its working very smooth. But one thing I'm observed is the output on parallel testing under windows looks quite strange:

![image](https://github.com/pestphp/pest/assets/42345405/66611729-44f9-47c3-9835-6bcb2ba728e7)

I would guess, that the percentage should be on the right but it is in between the testing dots.

### Specs
OS: Windows 11
Laravel Version: 10.18.0
Pest Version: v2.12.2
Plugins: `pestphp/pest-plugin-drift`, `pestphp/pest-plugin-faker`, `pestphp/pest-plugin-laravel`, `pestphp/pest-plugin-livewire` and `pestphp/pest-plugin-type-coverage`
CMD: Windows standard cmd and PowerShell 7.3.6
Editor: PHPStorm (but tried out without editor)
Server: WAMP
PHP: 8.1.9
GIT Bash for Windows: 2.39.0.windows.1

If you need more information, I will try to deliver them. If you have more information for me where I can try out something, I will also do this.

Thanks for the great tool and have a nice day :-)

**Comment by devajmeireles** [comment]
> 

Hey, @schonhoff!

1. Does this happen with any other project even if it's smaller?
2. Was there any resizing of the terminal during the test run?

**Comment by devajmeireles** [comment]
@schonhoff ,



> Hey!
> 
> I'm currently trying out pest as my default testing framework. I'm very positively impressed by its output and its working very smooth. But one thing I'm observed is the output on parallel testing under windows looks quite strange:
> 
> ![image](https://user-images.githubusercontent.com/42345405/260447771-66611729-44f9-47c3-9835-6bcb2ba728e7.png)
> 
> I would guess, that the percentage should be on the right but it is in between the testing dots.
> 
> ### Specs
> OS: Windows 11 Laravel Version: 10.18.0 Pest Version: v2.12.2 Plugins: `pestphp/pest-plugin-drift`, `pestphp/pest-plugin-faker`, `pestphp/pest-plugin-laravel`, `pestphp/pest-plugin-livewire` and `pestphp/pest-plugin-type-coverage` CMD: Windows standard cmd and PowerShell 7.3.6 Editor: PHPStorm (but tried out without editor) Server: WAMP PHP: 8.1.9 GIT Bash for Windows: 2.39.0.windows.1
> 
> If you need more information, I will try to deliver them. If you have more information for me where I can try out something, I will also do this.
> 
> Thanks for the great tool and have a nice day :-)

I noticed that you didn't answer me. I will close this issue. Please, if the issue persists, feel free to open another topic here with more details.
