### ISSUE TITLE
Unkown option --process-isolation

### ISSUE THREAD

**Issue by schonhoff** [pestphp/pest#910]
Hey!

On parallel testing for code coverage our test cases needed the option `--process-isolation`. After switching to pest I cannot run the command anymore with the option. Paratest does allow this option after this fix https://github.com/paratestphp/paratest/pull/737

Can this command be past through pest to paratest? I read all the past threads but couldn't find why it isn't support.

**Comment by devajmeireles** [comment]
> Hey!
> 
> On parallel testing for code coverage our test cases needed the option `--process-isolation`. After switching to pest I cannot run the command anymore with the option. Paratest does allow this option after this fix [paratestphp/paratest#737](https://github.com/paratestphp/paratest/pull/737)
> 
> Can this command be past through pest to paratest? I read all the past threads but couldn't find why it isn't support.

According to [this reply](https://github.com/pestphp/pest/issues/742), the `--process-isolation` option is not available on Pest. All available options is documented [here](https://pestphp.com/docs/cli-api-reference#content-execution)
