### ISSUE TITLE
Class "PHPUnit\Metadata\Api\DataProvider" not found when running ./vendor/bin/pest

### ISSUE THREAD

**Issue by Nelwhix** [pestphp/pest#913]
I tried installing pestphp v2.14.1 in Laravel 10 and PHP 8.2.8 on alpine linux. I followed the new docs installation guide. but when I run `./vendor/bin/pest`. I get this error: 

```bash
   ERROR  Class "PHPUnit\Metadata\Api\DataProvider" not found

Location: /var/www/html/vendor/phpunit/phpunit/src/Framework/TestBuilder.php:38

#0 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php(477): PHPUnit\Framework\TestBuilder->build(Object(ReflectionClass), 'test_that_t
rue_...')
#1 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php(125): PHPUnit\Framework\TestSuite->addTestMethod(Object(ReflectionClass), Object
(ReflectionMethod))
#2 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php(215): PHPUnit\Framework\TestSuite::fromClassReflector(Object(ReflectionClass))  
#3 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php(243): PHPUnit\Framework\TestSuite->addTestSuite(Object(ReflectionClass))        
#4 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php(261): PHPUnit\Framework\TestSuite->addTestFile('/var/www/html/t...')
#5 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Configuration/Xml/TestSuiteMapper.php(77): PHPUnit\Framework\TestSuite->addTestFiles(Array)      
#6 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Configuration/TestSuiteBuilder.php(58): PHPUnit\TextUI\XmlConfiguration\TestSuiteMapper->map('/va
r/www/html/p...', Object(PHPUnit\TextUI\Configuration\TestSuiteCollection), '', '')
#7 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Application.php(356): PHPUnit\TextUI\Configuration\TestSuiteBuilder->build(Object(PHPUnit\TextUI\
Configuration\Configuration))
#8 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Application.php(103): PHPUnit\TextUI\Application->buildTestSuite(Object(PHPUnit\TextUI\Configurat
ion\Configuration))
#9 /var/www/html/vendor/pestphp/pest/src/Kernel.php(91): PHPUnit\TextUI\Application->run(Array)
#10 /var/www/html/vendor/pestphp/pest/bin/pest(91): Pest\Kernel->handle(Array)
#11 /var/www/html/vendor/pestphp/pest/bin/pest(99): {closure}()
#12 /var/www/html/vendor/bin/pest(120): include('/var/www/html/v...')
#13 {main}.

```

**Comment by devajmeireles** [comment]
> I tried installing pestphp v2.14.1 in Laravel 10 and PHP 8.2.8 on alpine linux. I followed the new docs installation guide. but when I run `./vendor/bin/pest`. I get this error:
> 
> ```shell
>    ERROR  Class "PHPUnit\Metadata\Api\DataProvider" not found
> 
> Location: /var/www/html/vendor/phpunit/phpunit/src/Framework/TestBuilder.php:38
> 
> #0 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php(477): PHPUnit\Framework\TestBuilder->build(Object(ReflectionClass), 'test_that_t
> rue_...')
> #1 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php(125): PHPUnit\Framework\TestSuite->addTestMethod(Object(ReflectionClass), Object
> (ReflectionMethod))
> #2 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php(215): PHPUnit\Framework\TestSuite::fromClassReflector(Object(ReflectionClass))  
> #3 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php(243): PHPUnit\Framework\TestSuite->addTestSuite(Object(ReflectionClass))        
> #4 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php(261): PHPUnit\Framework\TestSuite->addTestFile('/var/www/html/t...')
> #5 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Configuration/Xml/TestSuiteMapper.php(77): PHPUnit\Framework\TestSuite->addTestFiles(Array)      
> #6 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Configuration/TestSuiteBuilder.php(58): PHPUnit\TextUI\XmlConfiguration\TestSuiteMapper->map('/va
> r/www/html/p...', Object(PHPUnit\TextUI\Configuration\TestSuiteCollection), '', '')
> #7 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Application.php(356): PHPUnit\TextUI\Configuration\TestSuiteBuilder->build(Object(PHPUnit\TextUI\
> Configuration\Configuration))
> #8 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Application.php(103): PHPUnit\TextUI\Application->buildTestSuite(Object(PHPUnit\TextUI\Configurat
> ion\Configuration))
> #9 /var/www/html/vendor/pestphp/pest/src/Kernel.php(91): PHPUnit\TextUI\Application->run(Array)
> #10 /var/www/html/vendor/pestphp/pest/bin/pest(91): Pest\Kernel->handle(Array)
> #11 /var/www/html/vendor/pestphp/pest/bin/pest(99): {closure}()
> #12 /var/www/html/vendor/bin/pest(120): include('/var/www/html/v...')
> #13 {main}.
> ```

Hey, @Nelwhix ! Could you provide more details, please?

- What version of PHP were you using when the issue occurred?
- Did you have this problem when trying to run through Docker?
- Has the `composer install` worked successfully?

We now have an issue template in the repository, feel free to close the issue and reopen it with the appropriate details. The details help us to understand the issue and verify if it is a bug.

**Comment by Nelwhix** [comment]
@devajmeireles  Okay closing now, link to the issue: https://github.com/pestphp/pest/issues/914
