### ISSUE TITLE
[Bug]: When I run ./vendor/bin/pest I get some errors

### ISSUE THREAD

**Issue by Nelwhix** [pestphp/pest#914]
### What Happened

I tried running my tests with `./vendor/bin/pest` and I got  Class "PHPUnit\Metadata\Annotation\Parser\Registry" not found. I have tried installing and reinstalling pestphp, `composer dump-autoload` but no changes.

### How to Reproduce

- Install a fresh laravel 10 app
- Install pestphp following the docs steps
- when you get to `./vendor/bin/pest` the error starts

### Sample Repository

https://github.com/Nelwhix/buckhill-test

### Pest Version

2.15.0

### PHP Version

8.2.8

### Operation System

Linux

**Comment by nunomaduro** [comment]
Can't reproduce...

**Comment by devajmeireles** [comment]
> ### What Happened
> I tried running my tests with `./vendor/bin/pest` and I got Class "PHPUnit\Metadata\Annotation\Parser\Registry" not found. I have tried installing and reinstalling pestphp, `composer dump-autoload` but no changes.
> 
> ### How to Reproduce
> * Install a fresh laravel 10 app
> * Install pestphp following the docs steps
> * when you get to `./vendor/bin/pest` the error starts
> 
> ### Sample Repository
> https://github.com/Nelwhix/buckhill-test
> 
> ### Pest Version
> 2.15.0
> 
> ### PHP Version
> 8.2.8
> 
> ### Operation System
> Linux
> 
> ### Notes
> _No response_

Hey, @Nelwhix !

I also was not able to reproduce the bug:

![CleanShot 2023-08-17 at 2 15 58](https://github.com/pestphp/pest/assets/60591772/1258c4a1-b173-4748-92a4-30719c73d64e)

The only change I made was to delete the composer container and compile composer inside the app so I could easily run `composer install` inside the app container. 

Try the same as I did. I will close the topic to improve our organization. Feel free to open a new issue whenever you like.

**Comment by Nelwhix** [comment]
@devajmeireles Thanks, what I did was downgrade my pestphp to v1.23.1 and it is working. Probably not the best solution but I will manage.

**Comment by aagjalpankaj** [comment]
I'm getting below error when I run `vendor/bin/pest`:
```
Error: Class "PHPUnit\TextUI\Configuration\Registry" not found in Standard input code on line 107
```

**Comment by Nelwhix** [comment]
@aagjalpankaj paste a link to the project let's see if the maintainers can reproduce the bug.
