### ISSUE TITLE
Mark Pending Tests as Incomplete

### ISSUE THREAD

**Issue by AlexMartinFR** [pestphp/pest#92]
## Problem:
When we write a pending test by omitting the closure, PHPUnit marks the test as **Risky**.

## Suggestion:
Use the PHPUnit `markTestIncomplete()` method on pending test to mark them as **Incomplete** instead.

**Comment by nunomaduro** [comment]
Sounds a good idea.

**Comment by AlexMartinFR** [comment]
Closing, as it's a duplicate of #11
