### ISSUE TITLE
Symfony - Liip FixturesTrait causes issues with TestCaseFactory

### ISSUE THREAD

**Issue by dingo-d** [pestphp/pest#93]
I'm trying to update my tests in a sample Symfony project I'm playing with, and I need to use fixtures to load dummy DB data.

I'm using the [LiipTestFixturesBundle](https://github.com/liip/LiipTestFixturesBundle), and in the [docs](https://github.com/liip/LiipTestFixturesBundle/blob/master/doc/database.md) it says I need to use the `FixturesTrait`, so I've added to my `Pest.php`

```php
<?php

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;
use Liip\TestFixturesBundle\Test\FixturesTrait;

uses(WebTestCase::class)->in('Controller');
uses(FixturesTrait::class)->in('Controller');

```

And in the test I'm trying to use it like this:

```php
<?php

beforeEach(function () {
    $this->client = static::createClient();

    $this->loadFixtures([
        UserFixture::class,
        QuestionFixture::class,
        ArticleFixture::class,
        AnswerFixture::class,
    ]);
});

test('question controller returns correct view for the homepage', function () {
    $this->client->request('GET', '/');

    $this->assertResponseIsSuccessful();
    $this->assertSelectorTextContains('h1', 'Your Questions Answered');
});

test('question controller returns correct view for the question', function () {
    $this->client->request('GET', '/questions/cool-question');

    $this->assertResponseIsSuccessful();
    $this->assertSelectorTextContains('.q-title-show', 'Cool Question');

});
```

But it thows the following error when I try to run the test

```bash
PHP Fatal error:  Trait method tearDown has not been applied, because there are collisions with other trait methods on \Tests\Controller\QuestionControllerTest in /vendor/pestphp/pest/src/Factories/TestCaseFactory.php(185) : eval()'d code on line 4

Fatal error: Trait method tearDown has not been applied, because there are collisions with other trait methods on \Tests\Controller\QuestionControllerTest in /vendor/pestphp/pest/src/Factories/TestCaseFactory.php(185) : eval()'d code on line 4

   Whoops\Exception\ErrorException

  Trait method tearDown has not been applied, because there are collisions with other trait methods on \Tests\Controller\QuestionControllerTest

  at vendor/pestphp/pest/src/Factories/TestCaseFactory.php:185
    181▕
    182▕             final class $className extends $baseClass implements $hasPrintableTestCaseClassFQN {
    183▕                 $traitsCode
    184▕
  ➜ 185▕                 private static \$__filename = '$filename';
    186▕             }
    187▕         ");
    188▕
    189▕         return $classFQN;

      +1 vendor frames
  2   [internal]:0
      Whoops\Run::handleShutdown()
Script @php ./vendor/bin/pest handling the test:run event returned with error code 255
``` 

From the docs it looks like I am loading the trait correctly. Any ideas what could be the issue?

**Comment by nunomaduro** [comment]
What version of pest are you using?

**Comment by dingo-d** [comment]
I have v0.1.5 installed.

**Comment by SimoTod** [comment]
this is the standard behaviour in php when 2 traits have a method with the same name: https://www.php.net/manual/en/language.oop5.traits.php#language.oop5.traits.conflict (tearDown in this case)

**Comment by dingo-d** [comment]
Yeah, I'm wondering if there is a way to avoid this collision.

**Comment by nunomaduro** [comment]
@SimoTod @SimoTod Maybe we can avoid the trait on the internals of Pest? Somehow having the code we have on `Concern\TestCase.php` on the eval string itself?

**Comment by SimoTod** [comment]
> Yeah, I'm wondering if there is a way to avoid this collision.

@dingo-d 
As a workaround,I think you can create your own trait extending both, use aliases for the teardown methods and define a new teardown which calls both of them (or if you don't need one of them just define an alias for the wrong one)

**Comment by SimoTod** [comment]
> @SimoTod @SimoTod Maybe we can avoid the trait on the internals of Pest? Somehow having the code we have on `Concern\TestCase.php` on the eval string itself?

@nunomaduro I don't have much knowledge about the internals but I assume pest creates classes at runtime composing methods, traits, etc. The main challenge is that, if a user decide to use 2 traits with the same method, you don't know. which one of the 2 methods they want to use (probably both).
Maybe you can create a trait at runtime (like you do with classes) which composes all those traits; you can use reflection to get a list of methods, create aliases for conflicting ones and create methods with the. same name calling all those aliases sequentially, Not sure if it's over killing thought.

**Comment by nunomaduro** [comment]
I've no plans on working on this. Feel free to submit a pull request on this.
