### ISSUE TITLE
[Bug]: Test Dependency not working on `describe` blocks

### ISSUE THREAD

**Issue by lidani** [pestphp/pest#936]
### What Happened

when I made an dependency test inside a describe block it fails

### How to Reproduce

```php
// MercadoLivreAnnouncesTest.php
 
describe('mercado livre announces service', function () {

  it('should serialize an announce', function () {
    expect(true)->toBeTrue();
    return 'example-value';
  });

 it('should create an announce', function ($serialized) {
    var_dump($serialized); // should dump 'example-value'
    expect(true)->toBeTrue();
  })->depends('it should serialize an announce');

});

```

<img width="1503" alt="image" src="https://github.com/pestphp/pest/assets/29063458/885b4fb7-d9d5-4b5c-bc05-964dae81a352">

apparently, pest gets lost in the second test, even printing the wrong name.
the line 
`⨯ mercado livre announces service → it should serialize an announce`
should be something like 
`✓ mercado livre announces service → it should create an announce`

and when I remove the describe block

```php
it('should serialize an announce', function () {
  expect(true)->toBeTrue();
  return 'example-value';
});

it('should create an announce', function ($serialized) {
  var_dump($serialized); // should dump 'example-value'
  expect(true)->toBeTrue();
})->depends('it should serialize an announce');
```

it works as expected

<img width="500" alt="image" src="https://github.com/pestphp/pest/assets/29063458/cf0521c2-c6a2-45f6-9759-a5bdfddcf4e0">

### Pest Version

2.16

### PHP Version

8.2.9

### Operation System

macOS, Linux

### Notes

the error occurs both in my Mac and my alpine linux docker container

**Comment by devajmeireles** [comment]
Hey, @lidani . Thanks for your report.

I was able to reproduce that. I will report this to the Pest team.

**Comment by lidani** [comment]
perfect, thank you so much

**Comment by devajmeireles** [comment]
Hey, @lidani ! This PR: https://github.com/pestphp/pest/pull/949 was created to fix this issue.
