### ISSUE TITLE
Datasets not working if use a real data from databases.

### ISSUE THREAD

**Issue by developerabdan** [pestphp/pest#940]
following to the issues that has been closed #938 , i already read the documentation on the pest well
https://pestphp.com/docs/datasets
heres to reproduce.

**tests/Datasets/Employee.php**
```
dataset('employee',function(){
    $employee = \App\Models\Employee::get();
    $map = $employee->mapWithKeys(function($item){
        return [$item->name => $item];
    });
    return $map->toArray();
});
```
**test/Feature/ExampleTest.php**
```
it('employee can access the page', function ($employee) {
    $response = $this->get('/');
    $response->assertStatus(200);
})->with('employee');
```
**Pest.php**
`uses(Tests\TestCase::class)->in('Feature','Unit');`

when running the tests, it shows that `Call to a member function connection() on null`. Is there a way to use a real data from database for datasets instead manually configure datasets or using factory?

**Comment by devajmeireles** [comment]
Hey, @developerabdan . Thanks for your report.

Per my review, the datasets do not accept closures. I don't think we have plans for that. Instead, you need to return an array, which inside can contain any number of closures you want:

```php
dataset('unacceptable', fn () => User::factory()->create()); // ❌ 

dataset('unacceptable', function () {  // ❌ 
    return User::factory()->create();
});

dataset('acceptable', [ // ✅ 
    function () {
        $users = User::factory(5)->create();

        return [...$users->map(fn ($user) => $user->id)->toArray()];
    }
]);

dataset('acceptable too', [ // ✅ 
    fn () => User::factory()->create(),
    fn () => User::factory()->create(),
    fn () => User::factory()->create(),
    fn () => User::factory()->create(),
    fn () => User::factory()->create(),
]);
```

Also, you can't do that because the database connection will only be set when the test starts running:

```php
$users = User::factory(5)->create();

dataset('unacceptable', function () use ($users) {
    return [...$users->map(fn ($user) => $user->id)->toArray()];
});
```

According to our organization, I'll close this issue. Feel free to open a new issue whenever necessary.
