### ISSUE TITLE
[Bug]: toMatchArray - Field informed in the error message is the incorrect.

### ISSUE THREAD

**Issue by HENRIQUELOBO** [pestphp/pest#945]
### What Happened

The “NAME” field informed in the error message is not incorrect, what is incorrect is the “AGE”.

test('check if value array matches the given subset', function () {
    expect(['name' => 'lobo', 'age' => 10])->toMatchArray(['name' => 'lobo', 'age' => 0]);
});

Failed asserting that an array has a key 'name' with the value 'lobo'.
Failed asserting that 10 matches expected 0.
Expected :0
Actual   :10

### How to Reproduce

test('check if value array matches the given subset', function () {
    expect(['name' => 'lobo', 'age' => 10])->toMatchArray(['name' => 'lobo', 'age' => 0]);
});

### Pest Version

2.16.1

### PHP Version

8.1

### Operation System

Linux

**Comment by devajmeireles** [comment]
Hey, @HENRIQUELOBO . Thanks for your report.

I was able to reproduce the behavior reported for you, but I don't think this is a bug or something related to that, I mean something that requires special attention. **I will tag this as an enhancement to future Pest releases. Feel free to send us a PR with the enhancement in this part.**

**Comment by drsdre** [comment]
Why is reporting the wrong field not an error? Just spend 2 hours trying to figure out on a large array what is not matching.

Getting a headache from the logic when $message from Assert::assertArrayHasKey($key, $valueAsArray, $message); is empty, it is considered as an error and $message is updated. It looks very hacky and wrong.

https://github.com/pestphp/pest/pull/1357 to fix this issue
