### ISSUE TITLE
[Bug]: `->toMatchSnapshot()` will not work with `@csrf`

### ISSUE THREAD

**Issue by alexmanase** [pestphp/pest#946]
### What Happened

When I use `expect($response)->toMatchSnapshot()` and I use the `@csrf` directory the test will fail because the csrf is changed on every request.`

I think there should be a way to ignore the `@csrf` directive on snapshot testing.

### How to Reproduce

1. Create a Laravel Project with Pest
2. Create a view that contains `@csrf`
3. Use the Pest API for testing the snapshot: `expect($response)->toMatchSnapshot()`.
4. Run tests.

### Sample Repository

https://github.com/alexmanase/pest-snapshost-csrf-issue

### Pest Version

2.16.1

### PHP Version

8.2.8

### Operation System

macOS

**Comment by nunomaduro** [comment]
cc @freekmurze

**Comment by freekmurze** [comment]
In our projects we add a function to strip out the token of a value before snapshotting that value.

It would be nice if there were some helper methods on the Pest snapshot methods for this. Or maybe let the `toMatchSnapshot()` method accept a canonicalising callable.

```
expect($response)->toMatchSnapshot($callableThatWillCanonicaliseResponse)
```

**Comment by gehrisandro** [comment]
There is a similar problem with `wire:id="<random-string>"` when trying to take a snapshot of a Livewire component.

I think it would be nice if the most common "problems" would be handled automatically by Pest. But the idea with the callable sounds nice for custom use cases. 👍

**Comment by owenvoke** [comment]
I think the callable makes the most sense. Perhaps for Livewire, it could be a hook or something via the Pest Livewire plugin, and `@csrf` output could be part of the Pest Laravel plugin. I think it seems a bit weird maybe to handle a bunch of Laravel-specific cases in Pest core. As people might ask us to add (and maintain) a bunch of other common cases, such as for Symfony and other frameworks. 🤷🏻

For example, we could have a method like `Snapshot::macro('laravel.csrf', function () { ... });`, and then in plugins they can register bits to strip out in snapshots. 🤷🏻 And then have like `Snapshot::disableMacro('laravel.csrf');` if you don't want to include a plugins macro.

**Comment by gehrisandro** [comment]
@owenvoke Sounds amazing 🎉

**Comment by nunomaduro** [comment]
@gehrisandro I like the idea of `nice if the most common "problems" would be handled automatically by Pest`.

**Comment by gehrisandro** [comment]
Here my current quick and dirty fix for Livewire:

```php
expect(str($component->html(stripInitialData: true))->replaceMatches('/wire:id="[0-9a-zA-Z]*"/', ''))
        ->toMatchSnapshot();
```

If we all agree on the suggestion by @owenvoke I can help here. I should find some time by the end of this week.

**Comment by alexmanase** [comment]
And here is my fix for the `@csrf` issue:

```php
$response = get($url);
$content = $response->content();

$newContent = collect(
    str($content)->explode("\n")
)
    ->reject(fn (string $line) => str($line)->contains('_token'))
    ->reject(fn (string $line) => str($line)->contains('link rel="preload" as="style"'))
    ->implode("\n");

$response->setContent($newContent);

expect($response)->toMatchSnapshot();
```

**Comment by gehrisandro** [comment]
Here my [PR](https://github.com/pestphp/pest/pull/954)

**Comment by jellisii** [comment]
CSRF tokens can possibly be more easily stripped by using 
`$response->setContent(preg_replace('/' . csrf_token() . '/', '', $response->getContent()));`

**Comment by nunomaduro** [comment]
Fixed: https://pestphp.com/docs/snapshot-testing#content-handling-dynamic-data.
