### ISSUE TITLE
[Bug]: `toHaveMethod` Arch Expectation is Overwriting `toHaveMethod` of Common Expectations

### ISSUE THREAD

**Issue by devajmeireles** [pestphp/pest#951]
### What Happened

The `toHaveMethod` in the Arch plugin, which was added on this PR: https://github.com/pestphp/pest/pull/947, is overwriting the `toHaveMethod` from [common expectations.](https://pestphp.com/docs/expectations#content-tohavemethodstring-name) The same doesn't happen to the `toHaveMethods` because the Arch plugin doesn't contain this expectation.

### How to Reproduce

The test:

```php
test('pass', function () {
    $object = new class
    {
        public function foo(): void
        {
            //
        }
    };

    expect($object)->toHaveMethod('foo');
});
```

... Will fail:

![CleanShot 2023-09-06 at 12 44 25](https://github.com/pestphp/pest/assets/60591772/1a1f3b5b-da7f-4b8b-adec-f798e21103ca)

### Pest Version

Latest

### PHP Version

8.2.9

### Operation System

macOS

### Notes

It was not noticed on the PR that adds the `toHaveMethod` in the Arch plugin, because the `toHaveMethod` from common expectations is not tested, only the `toHaveMethods` from common expectations are tested [here](https://github.com/pestphp/pest/blob/2.x/tests/Features/Expect/toHaveMethods.php)

**Comment by vegabsm** [comment]
+1, note that `toHaveMethods` works in the meantime with a singular item array, ie `expect($object)->toHaveMethods(['foo']);`.

Not ideal 🤦🏻‍♂️ , but will prevent the suite from failing until this is fixed.

**Comment by KeithBush** [comment]
We're coming up on about a year now and this still appears to be an issue in v2.35.1.  

The test listed at pest/tests/Features/Expect/toHaveMethod.php does not seem to align with what is listed in the common/standard expectations https://pestphp.com/docs/expectations#content-tohavemethodstring-name

It looks like it was written to only test the architecture version and no consideration is given for the standard usage?

**Comment by nunomaduro** [comment]
The original `toHaveMethod` will be removed in Pest 3.
