### ISSUE TITLE
[Bug]: Error: Class "PHPUnit\TextUI\Configuration\Registry" not found in Standard input

### ISSUE THREAD

**Issue by aagjalpankaj** [pestphp/pest#953]
### What Happened

I am switching from phpunit to pest. Using Laravel v10 & pest v2.17.
When I run `vendor/bin/phpunit` tests executes properly but when I run `vendor/bin/pest` I get below error:
```
PHPUnit\TextUI\Configuration\Registry
```
Let me know if any additional information required.

### How to Reproduce

- Use Laravel v10 & pest v2.17
- Write a phpunit test using annotation `runInSeparateProcess`
- Run `vendor/bin/phpunit` & `vendor/bin/pest`
- You may get the error when you run `vendor/bin/pest`

### Pest Version

2.17

### PHP Version

8.1

### Operation System

macOS

**Comment by aagjalpankaj** [comment]
@nunomaduro fyi, after debugging further found it is due to annotation `* @runInSeparateProcess`

**Comment by nunomaduro** [comment]
We don't support `runInSeparateProcess`.

**Comment by aagjalpankaj** [comment]
Any chance to support it in upcoming version?
