### ISSUE TITLE
[Bug]: vendor/bin/pest --init will return a deprecated schema for phpunit.xml

### ISSUE THREAD

**Issue by mho22** [pestphp/pest#955]
### What Happened

The XML configuration is already deprecated when `pest --init`.

### How to Reproduce

Created a very empty project. Only with this composer.json file : 

```
{
    "name": "test/test",
    "description": "Test Pest",
    "require-dev": {
        "pestphp/pest": "*"
    },
    "config": {
        "allow-plugins": {
            "pestphp/pest-plugin": true
        }
    }
}
```

ran command : `composer install`

ran command : `vendor/bin/pest --init`

ran command : `vendor/bin/pest`

got Warning : 

```
Your XML configuration validates against a deprecated schema. Migrate your XML configuration using "--migrate-configuration"!
```

### Pest Version

2.18.0

### PHP Version

8.1.23

### Operation System

macOS

### Notes

It seems like when running `vendor/bin/pest --migrate-configuration`, the slight change is the `<coverage>` tag previously is `<include>` parent. It the new `phpunit.xml` file, the `<coverage>` tag is a self-closing and the `<source> tag has taken the place of `<coverage>`.

I could quickly make a PR if you wish. I don't want to make it directly without asking.

**Comment by owenvoke** [comment]
That would be great, if you don't mind PRing it 👍🏻

**Comment by mho22** [comment]
@owenvoke done. 👌

**Comment by devajmeireles** [comment]
Hey, @Itemshopp ! Thanks for you report.

I'm reopening this issue til the PR #956 is merged.

**Comment by mho22** [comment]
@devajmeireles I suppose we can close this issue now that the PR is merged?
