### ISSUE TITLE
[Bug]: PHP Fatal error

### ISSUE THREAD

**Issue by opusaha** [pestphp/pest#959]
### What Happened

I have an existing project, and now I install pest in it, when I run 
./vendor/bin/pest it says 
![Screenshot from 2023-09-13 17-24-07](https://github.com/pestphp/pest/assets/47876003/6fae1e8b-4753-4622-bc6e-d93bad42f079)

My Laravel version is "^9.19",
My php unit version is 10.3.3

### How to Reproduce

opu@Oxyzen:~/Office/adlisting$ ./vendor/bin/pest
PHP Fatal error:  Declaration of Illuminate\Foundation\Testing\TestCase::onNotSuccessfulTest(Throwable $exception): void must be compatible with PHPUnit\Framework\TestCase::onNotSuccessfulTest(Throwable $t): never in /home/opu/Office/adlisting/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestCase.php on line 301

### Pest Version

2.18

### PHP Version

8.1.12

### Operation System

Linux

**Comment by owenvoke** [comment]
Laravel 9.x doesn't support Pest 2.x / PHPUnit 10.x afaik. 👀

**Comment by opusaha** [comment]
> Laravel 9.x doesn't support Pest 2.x / PHPUnit 10.x afaik. 👀

Thanks, @owenvoke.
