### ISSUE TITLE
Pest Livewire Plugin not working

### ISSUE THREAD

**Issue by fkraefft** [pestphp/pest#96]
### Problem 

Livewire plugin not working as expected.

PestPhp: v0.2.0
PestLivewire: v0.2.0

<img width="883" alt="Screen_Shot_2020-06-15_at_8 55 43_AM" src="https://user-images.githubusercontent.com/25204406/84843886-7ca6c380-b01f-11ea-8440-153cc03fdb7a.png">
<img width="913" alt="Screen_Shot_2020-06-15_at_8 55 58_AM" src="https://user-images.githubusercontent.com/25204406/84843888-7dd7f080-b01f-11ea-950d-7df34472fe27.png">

After some debugging I found that the InteractsWithLivewire trait is not being loaded in the test instance.

Trying the following in Livewire.php did the trick, but I can't chain livewire method in the it() or test().
```
// This
return test()->livewire(...func_get_args());
// For this 
return Livewire::test(...func_get_args());
```

**Comment by owenvoke** [comment]
This should be fixed in the next patch release of the Livewire plugin, hopefully that will be released soon. 👍 Let us know if you still experience this issue after it releases. 🙂

**Comment by owenvoke** [comment]
Reopening as it looks like this isn't fixed, might be an issue with the [core `Plugin` class](https://github.com/pestphp/pest/blob/a3fd60ce4d892b80504359a3c1b8ff815d5541ee/src/Plugin.php#L22) as adding the trait manually with `uses()` appears to work as per https://github.com/pestphp/pest-plugin-livewire/pull/4#issuecomment-645341512.

**Comment by fkraefft** [comment]
Found it & PR submitted. The TestRepository was overriding the previous class, traits & groups for the given path. 

https://github.com/pestphp/pest/pull/97

**Comment by nunomaduro** [comment]
Version 0.2.1 is out with this fix. Thanks!
