### ISSUE TITLE
test dependency doesn't work in different file

### ISSUE THREAD

**Issue by aaykacc** [pestphp/pest#969]
I can set test dependencies within the same file when using PEST, but it doesn't work when the tests are in different files.

**Comment by devajmeireles** [comment]
Hey, @aaykacc ! Thanks for your report.

As mentioned by you, dependencies only work for tests on the same file. We have no plans to improve this by adding the ability to use test dependencies in another file. PR is welcome to suggest this to Pest.

According to our organization, I'll close this issue. Feel free to open a new issue whenever necessary.
