### ISSUE TITLE
[Bug]: toHavePropery and Properties are not working as documented in the Pest Docs

### ISSUE THREAD

**Issue by roni-estein** [pestphp/pest#970]
### What Happened

When I used either the toHaveProperty or toHaveProperties examples even directly copied from the docs, they both report false in true scenarios.

### How to Reproduce

1. Install a fresh laravel app with pest
2. Make sure phpunit.xml has in memory options uncommented
3. Uncomment `Illuminate\Foundation\Testing\RefreshDatabase::class` so that it runs in feature
4. replace the text in Feature ExampleTest with the following basically clipped from the docs

```php
<?php
use App\Models\User;


it('pass: user created properly', function () {
    $user = User::factory(['name' => 'Nuno'])->create();
    expect($user)->name->toBe('Nuno');
});

it('fail: can detect a property', function () {
 $user = User::factory(['name' => 'Nuno'])->create();
 expect($user)->toHaveProperty('name');
});

it('fail: can detect a property with a value', function () {
 $user = User::factory(['name' => 'Nuno'])->create();
 expect($user)->toHaveProperty('name', 'Nuno');
});

it('fail: can detect properties', function () {
    $user = User::factory([
        'name' => 'Nuno',
        'email' => 'enunomaduro@gmail.com',
    ])->create();
    expect($user)->toHaveProperties(['name', 'email']);
});

it('fail: can detect a properties with values', function () {
    $user = User::factory([
        'name' => 'Nuno',
        'email' => 'enunomaduro@gmail.com',
    ])->create();
    expect($user)->toHaveProperties([
        'name' => 'Nuno',
        'email' => 'enunomaduro@gmail.com'
    ]);
});
```

### Pest Version

2.19.2

### PHP Version

8.2.10

### Operation System

macOS

### Notes

`php artisan about`
 Environment ......................................................................................................................................
  Application Name ......................................................................................................................... Laravel
  Laravel Version .......................................................................................................................... 10.24.0
  PHP Version ............................................................................................................................... 8.2.10
  Composer Version ........................................................................................................................... 2.5.5
  Environment ................................................................................................................................ local
  Debug Mode ............................................................................................................................... ENABLED
  URL .............................................................................................................................. pest-error.test
  Maintenance Mode ............................................................................................................................. OFF

  Cache ............................................................................................................................................
  Config ................................................................................................................................ NOT CACHED
  Events ................................................................................................................................ NOT CACHED
  Routes ................................................................................................................................ NOT CACHED
  Views ..................................................................................................................................... CACHED

  Drivers ..........................................................................................................................................
  Broadcasting ................................................................................................................................. log
  Cache ....................................................................................................................................... file
  Database ................................................................................................................................... mysql
  Logs .............................................................................................................................. stack / single
  Mail ........................................................................................................................................ smtp
  Queue ....................................................................................................................................... sync
  Session ..................................................................................................................................... file

**Comment by Katalam** [comment]
That is because these attributes are not real properties, but get returned as they are accessible via a magic method.

A fix would be easy
```php
// @phpstan-ignore-next-line
if ($this->value instanceof Illuminate\Database\Eloquent\Model) {
    // @phpstan-ignore-next-line
    Assert::assertNotNull($this->value->getAttribute($name), $message);

    if (! $value instanceof Any) {
        // @phpstan-ignore-next-line
        Assert::assertEquals($value, $this->value->getAttribute($name), $message);
    }

    return $this;
}
```

Inside the `toHaveProperty` Expectation, but tbh that is a false claim, you can extend the expectation pretty easy as shown here: https://pestphp.com/docs/custom-expectations maybe put it locally in your project, I'm not sure where I would put it

**Comment by roni-estein** [comment]
That makes sense! I was too focused on the laravel model idea especially looking at the example. Yet really we are testing PHP. Thanks for clarifying. I should have source dove it earlier. 👍

**Comment by kauhat** [comment]
Hi, I found this issue when also trying to use `toHaveProperty()` to test a Laravel model. 

Using `toHaveKey()` instead seems to be working for me. My best guess is that accessing the attribute as a key on the model will retrieve it via the [`__get($key)` magic method](https://www.php.net/manual/en/language.oop5.overloading.php#object.get).
