### ISSUE TITLE
[Bug]: Fatal error: Cannot redeclare

### ISSUE THREAD

**Issue by ZebTheWizard** [pestphp/pest#976]
### What Happened

When I create test cases using unconventional characters like `&` or `|` in a test name, it seems the test runner is creating an internal method name where the characters are replaced with `_`

### How to Reproduce

```
test('x <= 2 || y >= 6', ...)
test('x <= 2 && y >= 6', ...)
```

Produces internal method name like:
```
__pest_evaluable______x____2____y____6__
```

These have different names, but are being interpreted as having the same name?   Can the internal method names be built on something like base64 so these test cases don't conflict?

### Pest Version

2.20

### PHP Version

8.2.9

### Operation System

macOS

**Comment by devajmeireles** [comment]
Hey, @ZebTheWizard . Thanks for your report.

I was able to reproduce the issue when having two test methods in the same file, as you did. With just one method, there is no problem. I'll mark this PR as a suggestion anyway. For now, avoid using this name and everything will work out fine.

According to our organization, I'll close this issue. Feel free to open a new issue whenever necessary.
