### ISSUE TITLE
[Improvement]: Customize EnvironmentSetUp

### ISSUE THREAD

**Issue by joaopalopes24** [pestphp/pest#985]
Is it possible to customize the EnvironmentSetUp?

I can do it using the PHPUnit tests, but I can't in pest tests. I also have tested **beforeEach** and **beforeAll**, but these **callable** are called after the **service provider** is loaded

Pest: 2.24

![image](https://user-images.githubusercontent.com/38913462/234757991-847a9216-eadb-45a0-96b3-46663b0a57ca.png)

**Comment by owenvoke** [comment]
Hi @joaopalopes24, I think this is probably more of [a discussion](https://github.com/pestphp/pest/discussions) than an issue. However, please check out https://github.com/pestphp/pest/issues/793 for some further information where this topic has been previously discussed. 👍🏻

**Comment by joaopalopes24** [comment]
@owenvoke There was no solution to the problem. Any chance of this being implemented?

**Comment by owenvoke** [comment]
Nuno has mentioned that there were no plans to implement the solution in https://github.com/pestphp/pest/pull/805.

I think the current solution is to continue using traits or base classes defining the `getEnvironmentSetup()` with the values required. 🤷🏻

**Comment by joaopalopes24** [comment]
Thank you.
