### ISSUE TITLE
[Question] Vscode plugin similar to Better Phpunit

### ISSUE THREAD

**Issue by Naoray** [pestphp/pest#99]
Is anyone already working on a plugin for vscode similar to Caleb's [Better Phpunit](https://github.com/calebporzio/better-phpunit) or does such a plugin already exist?

**Comment by owenvoke** [comment]
I know that @m1guelpf created a fork for Pest around when Pest originally released.
https://github.com/m1guelpf/better-pest

Not sure if it still works, but it should. 👍

**Comment by Naoray** [comment]
Thanks @owenvoke, that is exactly what I was looking for!
