### ISSUE TITLE
[Bug]: Test fails on a PHPStan test

### ISSUE THREAD

**Issue by calebdw** [pestphp/pest#992]
### What Happened

Hello!

I'm trying to write a test for a [custom PHPStan Rule](https://phpstan.org/developing-extensions/testing) and the test keeps yielding a warning when using `artisan test` / `pest`. However, the test passes just fine when using the `phpunit` test runner which makes me think this is an issue with pest.

Any ideas what might be causing this?

![image](https://github.com/pestphp/pest/assets/4176520/4535cd13-5492-4bea-8107-4b074faba814)

CC: @ondrejmirtes 

Thanks!

### How to Reproduce

- Install new laravel app
- Install PHPStan
- Create a custom PHPStan rule and test
- Try to run test with pest

### Pest Version

2.24

### PHP Version

8.2.10

### Operation System

Linux

**Comment by calebdw** [comment]
Apparently I can run the test the first time but then repeated runs fail:

![image](https://github.com/pestphp/pest/assets/4176520/30bcbe66-0cfc-423a-ae65-b786a7e96151)

**Comment by calebdw** [comment]
Perhaps it has to do with this?

https://github.com/phpstan/phpstan/issues/5204#issuecomment-865916757

**Comment by nunomaduro** [comment]
This is not seem a Pest issue.

**Comment by calebdw** [comment]
This is/was a Pest issue because of how it reports silenced errors (`@mkdir`) as warnings instead of ignoring them. 

However, PHPStan may have been updated to check for the directory before attempting to create it so not that big a deal now. 

However, the warning report system should probably be updated to ignore silenced errors, which is how PHPUnit works
